### PR TITLE
Vulkan Improvements

### PR DESCRIPTION
**Pull request by 0cc4m**
Here's a batch of Vulkan improvements:
* Shader optimizations, especially for legacy quants to get them up to speed
  * I also optimized them for AMD GCN GPUs
* Allow simple ops (add, mul, etc) to work on non-continuous tensors
* Simplify and standardize matrix matrix multiplication shader selection
* Add dequant matrix matrix multiplication shaders for legacy quants
  * k-quants will come later, they are not as simple to implement
* Add environment variable GGML_VK_FORCE_MAX_ALLOCATION_SIZE to limit max buffer size as workaround for #5441
* Update soft_max to support ALIBI

I'll add some benchmarks of my GPUs later. Let me know what you think.

### CODE REVIEW

**Comment by Artefact2** [comment]
<details>
<summary>Q4_0 benchmarks on gfx1030/radv</summary>

| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | Vulkan pr     |  99 | pp 512     |    203.97 ± 1.45 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | Vulkan pr     |  99 | tg 128     |     23.97 ± 0.09 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | Vulkan master     |  99 | pp 512     |    160.00 ± 1.69 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | Vulkan master     |  99 | tg 128     |     13.62 ± 0.03 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | pp 512     |    499.00 ± 0.15 |
| llama 13B Q4_0                 |   6.88 GiB |    13.02 B | ROCm       |  99 | tg 128     |     40.98 ± 0.01 |

</details>

**Comment by sorasoras** [comment]
@0cc4m what about IQ quants?
I think  IQ4XS is a upgrade of Q4KM in most case.
Thanks.

**Comment by 0cc4m** [comment]
> @0cc4m what about IQ quants? I think IQ4XS is a upgrade of Q4KM in most case. Thanks.

Sure, but they're quite a bit of work to implement. I'll get to them eventually, but especially MoE takes precedence.

**Comment by 0cc4m** [comment]
Here are some benchmarks:

Vulkan0: AMD Radeon Pro VII (RADV VEGA20) | uma: 0 | fp16: 1 | warp size: 64
| model                          |       size |     params | backend    | ngl | test       |              t/s | 
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)    |  99 | pp 512     |    168.31 ± 0.78 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)    |  99 | tg 128     |     10.03 ± 0.35 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | pp 512     |    181.23 ± 0.82 | 
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | tg 128     |     19.24 ± 0.81 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | ROCm       |  99 | pp 512     |    271.75 ± 0.78 | 
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | ROCm       |  99 | tg 128     |     45.41 ± 0.05 |

Vulkan0: AMD Radeon RX 6800 XT (RADV NAVI21) | uma: 0 | fp16: 1 | warp size: 64
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | pp 512     |    276.86 ± 5.49 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | tg 128     |     20.15 ± 0.33 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | pp 512     |    374.73 ± 8.15 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | tg 128     |     34.21 ± 1.14 |

(ROCm failed to run on that PC for whatever reason)

Vulkan0: Intel(R) Arc(tm) A770 Graphics (DG2) | uma: 0 | fp16: 1 | warp size: 32
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | pp 512     |    109.11 ± 2.30 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | tg 128     |      2.82 ± 0.03 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | pp 512     |    100.91 ± 2.09 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | tg 128     |     16.18 ± 1.17 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | SYCL       |  99 | pp 512     |   453.10 ± 46.87 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | SYCL       |  99 | tg 128     |     18.64 ± 0.01 |

Vulkan0: NVIDIA GeForce RTX 3090 | uma: 0 | fp16: 1 | warp size: 32
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | pp 512     |   317.80 ± 14.31 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (Master)     |  99 | tg 128     |     27.32 ± 1.17 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | pp 512     |   492.58 ± 32.60 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | Vulkan (PR)     |  99 | tg 128     |     26.20 ± 0.18 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | CUDA       |  99 | pp 512     |  2452.13 ± 38.87 |
| llama 13B Q4_0                 |   6.86 GiB |    13.02 B | CUDA       |  99 | tg 128     |     82.22 ± 0.02 |

**Comment by Nindaleth** [comment]
Here are my numbers:
Radeon RX 6700 XT, Ryzen 5700X ECO, model mistral-7b-instruct-v0.2 fully oflloaded to the GPU. ROCm 6.0.

I've only tested the known-to-be-much-slower quants + the single one known to be already faster than ROCm. Very nice speed improvements all across the board.

| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |    309.00 ± 7.35 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     23.68 ± 0.34 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |   425.07 ± 12.91 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     41.81 ± 1.27 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | pp 512     |   1017.28 ± 5.60 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | ROCm       |  99 | tg 128     |     58.97 ± 0.21 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |    306.82 ± 7.91 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     23.39 ± 0.39 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    358.06 ± 9.70 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     41.32 ± 1.40 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | ROCm       |  99 | pp 512     |    974.39 ± 0.82 |
| llama 7B Q4_1                  |   4.24 GiB |     7.24 B | ROCm       |  99 | tg 128     |     54.88 ± 0.57 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |    309.18 ± 8.64 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     17.65 ± 0.25 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    357.03 ± 8.72 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     29.65 ± 0.38 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | ROCm       |  99 | pp 512     |    875.97 ± 0.45 |
| llama 7B Q5_0                  |   4.65 GiB |     7.24 B | ROCm       |  99 | tg 128     |     52.33 ± 0.04 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |    301.61 ± 7.63 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     17.85 ± 0.38 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    356.00 ± 9.50 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     28.87 ± 0.47 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | ROCm       |  99 | pp 512     |   864.23 ± 16.58 |
| llama 7B Q5_1                  |   5.07 GiB |     7.24 B | ROCm       |  99 | tg 128     |     48.27 ± 0.19 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |   356.89 ± 10.47 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     50.49 ± 1.41 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    352.91 ± 9.94 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     54.58 ± 2.35 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | ROCm       |  99 | pp 512     |    838.06 ± 0.35 |
| llama 7B Q4_K - Small          |   3.86 GiB |     7.24 B | ROCm       |  99 | tg 128     |     49.70 ± 0.06 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |    336.32 ± 9.85 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     41.38 ± 1.12 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    333.10 ± 7.90 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     44.35 ± 1.45 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | ROCm       |  99 | pp 512     |    772.27 ± 5.53 |
| llama 7B Q6_K                  |   5.53 GiB |     7.24 B | ROCm       |  99 | tg 128     |     45.06 ± 0.16 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | Vulkan (master)    |  99 | pp 512     |   306.12 ± 10.09 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | Vulkan (master)    |  99 | tg 128     |     22.52 ± 0.27 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | Vulkan (PR)    |  99 | pp 512     |    352.81 ± 9.02 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | Vulkan (PR)    |  99 | tg 128     |     33.43 ± 1.15 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | ROCm       |  99 | pp 512     |   1030.44 ± 4.23 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | ROCm       |  99 | tg 128     |     37.21 ± 0.22 |

**Comment by Nindaleth** [comment]
Couldn't resist testing the commonly recommended Q4_K_M and Q5_K_M, edited my table. Q4_K_* tg is epic, Q5_K_M tg is excellent.

**Comment by DaniAndTheWeb** [comment]
Here are some benchmarks on an AMD Radeon RX 5700 XT, the results are quite impressive, since the prompt processing is now faster than ROCm.

Vulkan0: AMD Radeon RX 5700 XT (RADV NAVI10) | uma: 0 | fp16: 1 | warp size: 64

| model | size | params | backend | ngl | test | t/s |
|--------|--------|--------|--------|--------|--------|--------|
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | Vulkan (master) | 99 | pp 512 | 177.59 ± 0.75 |
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | Vulkan (master) | 99 | tg 128 | 22.76 ± 0.09 |
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | Vulkan (PR) | 99 | pp 512 | 323.04 ± 3.48 |
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | Vulkan (PR) | 99 | tg 128 | 37.80 ± 0.14 |
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | ROCm | 99 | pp 512 | 318.71 ± 0.70 |
| llama 7B Q4_0 | 3.56 GiB | 6.74 B | ROCm | 99 | tg 128 | 60.44 ± 0.06 |

I'll update the comment with further benchmarks on other quants.

**Comment by 0cc4m** [comment]
@ggerganov @slaren Can one of you approve the minimal change to llama.cpp?

The flake8 linting issue isn't coming from my changes.

**Review by ggerganov — APPROVED** [review]

**Comment by akingoverlook** [comment]
This probably wasn't the focus, but FYI, things are still pretty broken with Adreno. Finding a compute queue is fixed, but dequant_q4k and dequant_q5k will still choke Adreno (unknown error) on creating the pipeline, and aside from that, this backend will still die with DeviceLost on submit() if more than a few layers are offloaded to GPU.

That will still happen if the new envar is restricting the max allocation too.

**Pull request merged**
