### PR TITLE
server : parallel decoding and multimodal

### PR DESCRIPTION
**Pull request by FSSRepo**
Based on the server I've already created, I'm working on this PR. There are commented-out sections to save myself from unnecessary headaches. I haven't even tested the results of this PR yet.

Here's the plan for a complete implementation:

- [x] To make `completion` work in streaming mode.
- [x] Correct the mode without streaming. In progress ...
- [x] Fix `embedding` endpoint. Inherent issue with CUDA backend #3625
- [x] Test the grammars and some options of `completion`.
- [x] To correct the `infill` function and perform the tests, it would make my life easier if someone could provide a way to test that endpoint.
- [x] Conduct completion and chat tests, with and without the UI.
- [x] To correct the context reset mode, I need to understand the approach to this, as slots share the entire assigned context, so one slot could consume most of the context, leaving others with no context.
- [x] Refactor the code by removing duplications, unnecessary comments, and prepare it for merging into the `master` branch.
- [x] Beam Search fixed but no tested, if there are some issue about that I will take care of that.

### CODE REVIEW

**Comment by FSSRepo** [comment]
```c++
LOG_TEE("before\n");
        llama.updateSlots();
        LOG_TEE("after\n");
        std::thread t([&llama]()
             {
            bool running = true;
            while (running)
            {
                LOG_TEE("running\n");
                running = llama.updateSlots();
            } });
```
Screenshot 2023-10-11 191044

I have no idea

**Comment by ggerganov** [comment]
You should rebase and adopt the latest sampling changes from: #3543

**Comment by FSSRepo** [comment]
@KerfuffleV2 In the new way of working with samplers, if each slot has different llama_sampling_params, then I should create a llama_sampling_context every time I want to perform a completion.

**Comment by FSSRepo** [comment]
The `completion` function is working fine; however, for some reason, the server crashes when it finishes. I haven't been able to identify the cause.

**Comment by KerfuffleV2** [comment]
> mmmmmmm

Yes, I agree with that. Looks like there are also likely more changes coming: #3601 

> for some reason, the server crashes when it finishes. I haven't been able to identify the cause.

Maybe try compiling with address sanitizing turned on? (Support recently got added to normal `Makefile` builds also.)

**Comment by FSSRepo** [comment]
> > mmmmmmm
> 
> Yes, I agree with that. Looks like there are also likely more changes coming: #3601
> 
> > for some reason, the server crashes when it finishes. I haven't been able to identify the cause.
> 
> Maybe try compiling with address sanitizing turned on? (Support recently got added to normal `Makefile` builds also.)

It was a null pointer; I was accessing an object outside of a lambda function, which always confuses me because the compiler never throws any error in that case.

**Comment by FSSRepo** [comment]
@ggerganov I need to know what to do in case the context gets crowded, given that the server is being used by multiple clients who share the entire context window. I assume that the context swap should only occur when a single slot is fully utilizing the context.

**Comment by FSSRepo** [comment]
Content:

```json
{
  "content": "Which is your dog?"
}
```

PR server:

```json
"embedding": [
    0.0013885498046875,
    0.02568817138671875,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
    0.0013885498046875,
    -0.02291107177734375,
    -0.02291107177734375,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
]
}

master server:

```json
{
  "embedding": [
    0.0013885498046875,
    0.02568817138671875,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
    0.0013885498046875,
    -0.02291107177734375,
    -0.02291107177734375,
    -0.02291107177734375,
    0.0013885498046875,
    0.0013885498046875,
]
}
```

Embedding example:

```bash
2.071708 0.094213 -0.879323 -0.868794 -1.877190 0.149166 0.456107 -1.180170 -1.899972 0.324895 0.137798 1.375898 -0.929520 -0.724631 -3.895488 0.835485 2.534587 -1.334827 -1.068944 -1.522295 -2.574473 -1.089735 0.195261 0.207192 0.607332 -0.160022 -2.255088 0.348395 -0.843356 0.270982 -1.236908 -0.836289 -1.600230 -0.213995 -0.724451 1.241112 0.571537 -1.612993 -0.924750 -1.141107 0.301533 0.476756 0.925662 -0.778871 0.644059 -2.298353 -1.250245 0.888944 1.218905 1.417424 -1.571156 0.380106 1.282110 1.155357 0.254458 -0.391138 4.462999 -2.220449 -0.675895 2.643535 -0.059323 -0.518516 -1.783109 1.390705 1.135090 2.257272 ....
```

**Comment by FSSRepo** [comment]
@ggerganov @monatis Server example now support LlaVA model

test

Response:

Screenshot 2023-10-13 184159

**Comment by FSSRepo** [comment]
274014591-d2aa99eb-5dac-4963-98cd-05d10b7763a5

Params
```json
{
  "stream": false,
  "n_predict": -1,
  "temperature": 0.1,
  "prompt": "A chat between a curious human and an artificial intelligence assistant.  The assistant gives helpful, detailed, and polite answers to the human's questions.\nUSER: [(img)]describe the image in detail.\nASSISTANT:",
  "image_data": "image data in base64",
  "stop": ["</s>"]
}
```

```json
 The image features a desk with two computer monitors on it. One of the monitors has an unusual decoration: a small toy lamb figurine is sitting on top of it, adding a playful touch to the workspace. A keyboard and mouse are also present on the desk, indicating that this is likely a computer setup.\n\nIn addition to the main desk area, there's another smaller desk visible in the background. The room appears to be well-equipped for work or study purposes, with various items such as books and a TV placed around the space.
```

**Comment by monatis** [comment]
> ```
> {
>   "stream": false,
>   "n_predict": -1,
>   "temperature": 0.1,
>   "prompt": "A chat between a curious human and an artificial intelligence assistant.  The assistant gives helpful, detailed, and polite answers to the human's questions.\nUSER: [(img)]describe the image in detail.\nASSISTANT:",
>   "image_data": "image data in base64",
>   "stop": ["</s>"]
> }
> ```

Awesome work! Thanks @FSSRepo for taking this

**Comment by FSSRepo** [comment]
@monatis This change was outside the scope of this PR, but I still wanted to implement it when I saw that it was something straightforward. 🤣🤣

**Comment by monatis** [comment]
I can make a full review if you think this is ready to merge.

**Comment by josephilome** [comment]
Would you consider a list for image_data, to allow multiple image inputs?

**Comment by FSSRepo** [comment]
> Would you consider a list for image_data, to allow multiple image inputs?

I'm not sure if this supports multiple images. @monatis any answer?

**Comment by josephilome** [comment]
It should work with a clear prompt of numbered multiple images, and I think future versions of VL models would finetune on that.

**Comment by monatis** [comment]
Although it's technically possible, the quality is not good because the model was not trained with multi-image input. See [this](https://github.com/haotian-liu/LLaVA/issues/197). So believe implementing an unsupported feature brings no benefit other than numerous complaining issues rraised about the quality.

**Comment by FSSRepo** [comment]
> Although it's technically possible, the quality is not good because the model was not trained with multi-image input. See [this](https://github.com/haotian-liu/LLaVA/issues/197). So I believe implementing an unsupported feature brings no benefit other than numerous complaining issues rraised about the quality.

Exactly, Better to see this in the future.

**Comment by FSSRepo** [comment]
@monatis 
https://github.com/ggerganov/llama.cpp/assets/57494570/827a1d98-c6f2-4b08-8ae4-010e2aa17617

**Comment by FSSRepo** [comment]
Another example:

https://github.com/ggerganov/llama.cpp/assets/57494570/539bc7f6-496a-4d6f-9802-fbafee39721d

**Comment by FSSRepo** [comment]
@ggerganov please make a review of this PR, answer my questions:

I need to know what to do in case the context gets crowded, given that the server is being used by multiple clients who share the entire context window. I assume that the context swap should only occur when a single slot is fully utilizing the context, or put a context limit per slot.

When I use the embeddings, it doesn't return the same values for some reason. I've already checked the embedding pipeline to compare it with the server implementation, but I'm not getting good results.

Do I leave the multi-modal support to the server enabled by default or do I make it an option in CMake?

**Comment by Seikho** [comment]
I'm noticing a significant drop in performance (~50%) and vastly different responses between using this branch and the current `master` branch.
Both servers are being launched with exactly the same parameters. This also occurs when `parallel` and `cont-batching` are not passed as well.

**Comment by FSSRepo** [comment]
> I'm noticing a significant drop in performance (~50%) and vastly different responses between using this branch and the current `master` branch.
> Both servers are being launched with exactly the same parameters. This also occurs when `parallel` and `cont-batching` are not passed as well.
> 
> Very much looking forward to this though! Great work and thanks for doing this!

I will do some performance test, obviusly for equal the expected scenario with the master server with a single client.

**Comment by FSSRepo** [comment]
Tested in:
Intel Core i5 11400H 12T / 6C
RTX 3050 Laptop 4GB
16 GB RAM DDR4 3200MHz
Windows 11 x64 latest version

master:

```bash
server -m ..\models\vicuna-7b.gguf --ctx_size 2048 -t 6 -ngl 33
```

| model | size       | params | ngl | Threads | test | t/s    | backend |
| ------- | -------- | -------- | ---- | ---- | ---- | ----- | ----- |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | PP 95  | 14.31  |  CPU  |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | TG 1016  | 9.5 |  CPU  |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | PP 95  |  40.99 |  CUDA  |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | TG  | 18.75 |  CUDA |
* CUDA: partial offloading kv cache

PR:

```bash
server -m ..\models\vicuna-7b.gguf --ctx_size 2048 -t 6 -ngl 33
```

| model | size       | params | ngl | Threads | test | t/s    | backend |
| ------- | -------- | -------- | ---- | ---- | ---- | ----- | ----- |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | PP 105  | 14.04 |  CPU  |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | TG 675  |  9.90  |  CPU  |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | PP 105  |  37.50 |  CUDA |
| vicuna 7B | 2.67 GB | 6.74 B| 33 | 6 | TG 658  |  19.07  |  CUDA |
* CUDA: no partial offloading kv cache

**Comment by Seikho** [comment]
For clarity these are my parameters: GGUF Q5_K_M 13B model, 43 (all) layers on GPU, RTX 4090, 4090 context.
After a bit more digging, it's actually the same tokens per second, but the "time to first token" is where the difference is. I think that can be safely ignored.

However I still do seem to experience different responses. `master` is providing long responses, but this branch is terminating the response prematurely. E.g. I'm asking the model to write code samples for generating a random number in different languages (~3.5K input prompt length, Alpaca-formatted prompt, 500 tokens requested). `master` completes this fine, but this branch terminates the response just before the code block each time (It is attempting to respond using markdown and triple back ticks). Could be related to stopping strings maybe?

**Comment by FSSRepo** [comment]
> For clarity these are my parameters: GGUF Q5_K_M 13B model, 43 (all) layers on GPU, RTX 4090, 4090 context.
> After a bit more digging, it's actually the same tokens per second, but the "time to first token" is where the difference is. I think that can be safely ignored.
> 
> However I still do seem to experience different responses. `master` is providing long responses, but this branch is terminating the response prematurely. E.g. I'm asking the model to write code samples for generating a random number in different languages (~3.5K input prompt length, Alpaca-formatted prompt, 500 tokens requested). `master` completes this fine, but this branch terminates the response just before the code block each time (It is attempting to respond using markdown and triple back ticks). Could be related to stopping strings maybe? It appears to always occur after receiving a colon `:`.
> 
> 

Can you share the command line params and the prompt that you test, I can't reproduce your issue because missing these specific information.

**Comment by FSSRepo** [comment]
> After a bit more digging, it's actually the same tokens per second, but the "time to first token" is where the difference is. I think that can be safely ignored.

I think that you refer to prompt processing?

**Comment by Seikho** [comment]
If I include any stopping string that begins with a line break `\n` then the response stops at the first instance of any line break.
It doesn't appear to be checking for the entire stopping string.
E.g. If I pass `stop: ['\nAnythingHere']` then the response will stop at the first instance of any line break rather than the full stopping string.

**Comment by FSSRepo** [comment]
> E.g. If I pass `stop: ['\nAnythingHere']` then the response will stop at the first instance of any line break rather than the full stopping string.
> 
> I think the `if (type == STOP_FULL) { ... }` check has been removed in your refactor of `findStoppingStrings` ?
> 

 I will see how the behavior of  `findStoppingString` differs between the implementations to see if I can resolve this.

**Comment by FSSRepo** [comment]
> > E.g. If I pass `stop: ['\nAnythingHere']` then the response will stop at the first instance of any line break rather than the full stopping string.
> > 
> > I think the `if (type == STOP_FULL) { ... }` check has been removed in your refactor of `findStoppingStrings` ?
> > 
> 
>  I will see how the behavior of  `findStoppingString` differs between the implementations to see if I can resolve this.

Thank you anyway for your insight. 😃😃😃

**Comment by FSSRepo** [comment]
@Seikho Can you test now?

**Comment by Seikho** [comment]
The stopping string issue is all good in commit d7eca25, however I can't start the server on commit 4d18043 (your most recent commit).

**Comment by FSSRepo** [comment]
> The stopping string issue is all good in commit d7eca25, however I can't start the server on commit 4d18043 (your most recent commit).

Some visible error or just slient stop? Send the output and parameters that you giving to the server

**Comment by Seikho** [comment]
At the time it was a silent error, although I didn't run with `-v`.
Now that I've switched back to that commit, recompiled and tried again it's running fine. Sorry for the wild goose chase.

**Comment by FSSRepo** [comment]
> Based on the server I've already created, I'm working on this PR. There are commented-out sections to save myself from unnecessary headaches. I haven't even tested the results of this PR yet.
> 
> Here's the plan for a complete implementation:
> 
> - [x] To make `completion` work in streaming mode.
> - [x] Correct the mode without streaming. In progress ...
> - [x] Fix `embedding` endpoint. Inherent issue with CUDA backend (bad embeddings)
> - [x] Test the grammars and some options of `completion`.
> - [x] To correct the `infill` function and perform the tests, it would make my life easier if someone could provide a way to test that endpoint.
> - [x] Conduct completion and chat tests, with and without the UI.
> - [x] To correct the context reset mode, I need to understand the approach to this, as slots share the entire assigned context, so one slot could consume most of the context, leaving others with no context.
> - [x] Refactor the code by removing duplications, unnecessary comments, and prepare it for merging into the `master` branch.
> - [x] Beam Search fixed but no tested, if there are some issue about that I will take care of that.
>

**Comment by ggerganov** [comment]
I'll make a review tomorrow. First will merge #3624 and then will push changes to this PR to adapt to the new sampling API.

> I need to know what to do in case the context gets crowded, given that the server is being used by multiple clients who share the entire context window. I assume that the context swap should only occur when a single slot is fully utilizing the context, or put a context limit per slot.

There should be a max context per-client (`n_ctx_per_slot`) and should perform the swap per client.
The total context should be `n_system + n_ctx_per_slot*n_slot` where `n_system` is the number of tokens in the common system prompt.

> When I use the embeddings, it doesn't return the same values for some reason. I've already checked the embedding pipeline to compare it with the server implementation, but I'm not getting good results.

Might be fixed via #3657 

> Do I leave the multi-modal support to the server enabled by default or do I make it an option in CMake?

Enable by default

**Comment by FSSRepo** [comment]
@ggerganov Are you reviewing this, now?

**Comment by ggerganov** [comment]
I didn't find the time today, but tomorrow this will be first thing. Until then, you can make changes if you want to. I'll mark the PR when I start reviewing.

**Comment by ggerganov** [comment]
@FSSRepo  I can't push into your branch:

```bash
$ ▶ git push FSSRepo HEAD:master
error: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/FSSRepo/llama.cpp'
```

Let's continue in #3677 - sent you a collaborator invite

**Pull request closed without merging**
