### PR TITLE
Improvements to VIM plugin

### PR DESCRIPTION
**Pull request by AustinMroz**
I had also started a [VIM plugin for interfacing with the example server](https://gitlab.com/AustinMroz/llama.vim) a couple weeks back, but figured it would be too niche to try and submit a pull request for.
Mine is a bit further along and adds a number of extra features including
- Asynchronous execution
- Response streaming
- Support for autoloading
- In buffer magic strings for modifying generation settings

While I remain unsure if all these features would be desired and don't want to overshadow the work of @whoreson, I do wish to share a couple specific improvements I found while working on mine.
This pull request
- Greatly simplifies the problem of escaping by using the builtin json_ecode and json_decode functions
- Removes the need for temporary files.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
Demonstration of all kinds of features is welcome. I don't have experience in writing VIM plugins, so these examples are very welcome.

Btw, if there interest in adding voice control to VIM, checkout the [whisper.nvim](https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.nvim) example. It's very rudimentary, but I think it can be used for starting point for making a more polished plugin.

**Comment by whoreson** [comment]
Oh, so newer vim has built-in JSON functionality. Neat, thanks for the upgrade. For some reason, newline characters get turned into 0x00, so I added a replacement line for that in https://github.com/whoreson/llama.cpp/blob/master/examples/llm.vim

Also, I'm originally Gabucino, but someone took my crappy nick on github, so here we are.

**Comment by whoreson** [comment]
BTW I'm now using your plugin instead of mine, works so much better.

I think you should make a pull request and replace this one.

**Comment by AustinMroz** [comment]
I appreciate the vote of confidence. I'll open a pull request once I've sufficiently tested the recent improvements I've made.

In hindsight, I should have remembered running into the newline issue when I was first working on my plugin, but it escaped my mind when creating/testing the fix here.

**Pull request merged**
