### PR TITLE
No need to copy tokens

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by slaren** [comment]
Ironically with N=1, doing this will move more data than the memcpy (a 64-bit pointer instead of just a 32-bit value).

**Comment by howard0su** [comment]
If we can expose api to create tensor with data, then this will save additional cycles to allocate data of tensor.

**Comment by howard0su** [comment]
> If we can expose api to create tensor with data, then this will save additional cycles to allocate data of tensor.



> Ironically with N=1, doing this will move more data than the memcpy (a 64-bit pointer instead of just a 32-bit value).

Overhead is more than the data but also memcpy? I think the intention is not perf, but we should not do the copy here.

**Comment by ggerganov** [comment]
Redirecting `ggml_tensor.data` is not a good thing to do. `mmap` changes set a precedent, but we should avoid it in general

**Pull request closed without merging**
