### PR TITLE
common : refactor cli arg parsing

### PR DESCRIPTION
**Pull request by ggerganov**
## TODO

- [x] remove `params.instruct`
- [x] remove `params.chatml`
- [x] `params.escape = true` by default
- [x] `params.n_ctx = 0` by default
- [x] merge `server` params in `gpt_params`
- [x] merge `retrieval` params in `gpt_params`
- [x] merge `passkey` params in `gpt_params`

### CODE REVIEW

**Comment by bartowski1182** [comment]
seems this broke some imatrix options, trying to run imatrix with -o or --output-file for an output file yields:

error: unknown argument: -o
usage: ./imatrix [options]

error: unknown argument: --output-file
usage: ./imatrix [options]

**Comment by ericcurtin** [comment]
@ggerganov will --instruct be introduced in future again? That was the feature I found most useful in the main cli binary. Or are there other options that can achieve the same result?

**Comment by Green-Sky** [comment]
@ericcurtin look at `-i` and `-if` with `-r`

**Comment by ericcurtin** [comment]
@Green-Sky -i -if -r don't seem to work if looking to create a basic CLI Ollama/ChatGPT-like assistant... --instruct works great for this...

**Comment by wtarreau** [comment]
I too am quite bothered by the removal of "-ins". Previously it used to be *really* interactive because you had a shell-like prompt ">" inviting you to type. You could distinguish user inputs from outputs in copy-pastes of the output. Now I cannot find an equivalent. I've tried --interactive-first (which is really much less convenient to type than -ins BTW) but there's no invite anymore. For me this is a significant functional regression which will force me to stick to tag b3086 for a while.

I really don't understand why features are *removed*. I can understand that it's unintended breakage of course, it always happens to any of us, but if the breakage is intentional I don't understand.

**Comment by wtarreau** [comment]
In addition the commit is huge (3800 lines of patch), it's impossible to analyze, too bad it was merged as a huge one and not in small pieces :-(

**Comment by ericcurtin** [comment]
I do kinda have the feature forked here:

https://github.com/ericcurtin/podman-llm

You can run like:

podman-llm run granite

But preferably the feature would be upstream in llama.cpp here...

**Comment by Green-Sky** [comment]
@ericcurtin and conversation mode does not meet your needs? (personally not using it)
```
  -cnv,  --conversation           run in conversation mode, does not print special tokens and suffix/prefix
                                  if suffix/prefix are not specified, default chat template will be used
                                  (default: false)
```

**Comment by wtarreau** [comment]
Thank you @Green-Sky it does the job like before indeed. So in the end it's a breaking change caused by a command line argument name change. At least -ins and -cml should be supported transparently (even emit a deprecation warning saying "no longer supported, use -cnv"). The help is so long now that you have little chance of stumbling over the new syntax when looking for the old one (which I did before coming here).

**Comment by ericcurtin** [comment]
@Green-Sky  it seems to work sort of:

$ podman --root /home/curtine/.local/share/podman-llm/storage run --rm -it --security-opt=label=disable -v/home/curtine:/home/curtine -v/tmp:/tmp -v/home/curtine/.cache/huggingface/:/root/.cache/huggingface/ granite llama-main -m /root/granite-3b-code-instruct.Q4_K_M.gguf --log-disable -cnv
> Tell me about podman
![][1]

[1]: http://i.imgur.com/68hI9.png
>
$ podman --root /home/curtine/.local/share/podman-llm/storage run --rm -it --security-opt=label=disable -v/home/curtine:/home/curtine -v/tmp:/tmp -v/home/curtine/.cache/huggingface/:/root/.cache/huggingface/ granite llama-main -m /root/granite-3b-code-instruct.Q4_K_M.gguf --log-disable --instruct
> Tell me about podman
 Podman is a free, open-source container engine that uses cgroups to control group of Linux containers. It is similar to Docker, but it offers more security features and is designed to be more user-friendly. It also has a simpler command-line interface than Docker.
>

**Comment by Green-Sky** [comment]
`instruct` was hardcoded to use the alpaca prompt template, while `conversation` loads it from the model (by default), experiment with different prompt templates or explicitly set
```
         --in-prefix STRING       string to prefix user inputs with (default: empty)
         --in-suffix STRING       string to suffix after user inputs with (default: empty)
         --chat-template JINJA_TEMPLATE
                                  set custom jinja chat template (default: template taken from model's metadata)
                                  if suffix/prefix are specified, template will be disabled
                                  only commonly used templates are accepted:
                                  https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_templat
```

you can always use:
```
--verbose-prompt         print a verbose prompt before generation (default: false)
```
to debug what you get.

**Comment by ericcurtin** [comment]
@Green-Sky in commit d94c6e0ccbd29ee1ba4f44e9caa8682ad94df9fa --conversation seems to be completely broken:

llama_new_context_with_model: graph splits = 1
main: chat template example: <|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant


system_info: n_threads = 6 / 12 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 0 |
error: input is empty

**Pull request merged**
