### PR TITLE
Added new memory efficient conversion script for hf to ggml format, tested on bloomz 176B + Added token conversion script to convert from tokenizer.json format to tokenizer.model

### PR DESCRIPTION
**Pull request by akumaburn**
Converts **tokenizer.json** to **tokenizer.model** format, tested with bigscience model (eg https://huggingface.co/bigscience/bloomz), usage like:

`
python3 tokenconvert.py ./ad033898-d849-41a1-9ecd-ad24e016bc4f/bloomz
`

### CODE REVIEW

**Comment by akumaburn** [comment]
I've added a helper script as well in https://github.com/ggerganov/llama.cpp/pull/867/commits/74b92ff6b834a3e8d854e4e4986bdb845e382864 

This script is more memory efficient than the existing **convert-hf-to-ggml.py** ; I was able to use to convert bloomz-176b to float16 ggml format with under 64GB of ram utilization.

**Comment by bil-ash** [comment]
What is the runtime memory usage of the converted bloomz-176b model?

**Comment by akumaburn** [comment]
> What is the runtime memory usage of the converted bloomz-176b model?

I believe its around 340GB of ram, you'd need to run it with bloomz.cpp (this particular fork: https://github.com/NouamaneTazi/bloomz.cpp/pull/21) which doesn't have mmap at the moment.

I only have around ~96GB of ram, so I've not been able to run the model yet, I've been working on a quantizer as well to quantize it to int4 / q4_0 which is going well, but I suspect it may still not be enough.

**Comment by akumaburn** [comment]
@TheBloke Thanks for linking me to @comex's script ; my script uses the HuggingFace library to handle the tokenization : ( https://github.com/huggingface/tokenizers ) , and assumes Byte-Pair Encoding by default- see: https://huggingface.co/docs/transformers/tokenizer_summary

Comex's script seems to be using SentencePiece (https://arxiv.org/pdf/1808.06226.pdf) which is a different tokenizer. 

I had created it with the hope of using bloom models (which currently llama.cpp doesn't support) see: https://github.com/ggerganov/llama.cpp/issues/452 and it works for that purpose.

In reality the conversion script would probably have to support all common tokenizers in order to work for each common scenario.

**Comment by akumaburn** [comment]
I just updated the token conversion script to add support for "SentencePiece" and "WordPiece" tokenizers, Usage has been updated to:

`python3 tokenconvert.py [TokenizerType] InDIR [OutDir]` where TokenizerType can be one of ["BPE","WordPiece","SentencePiece"]

@TheBloke I'm not sure if this will help with your quest of converting your OPT model into a GGML model, but I thought I'd tag you anyways.

**Comment by aidaho** [comment]
I've tried this on Bloomz mt0-xl:

```
(v:llama.cpp) aidaho@lin:~/bin/llama.cpp$ python3 tokenconvert.py BPE /media/aidaho/blue/llm-files/mt0-xl/
Traceback (most recent call last):
  File "/home/aidaho/bin/llama.cpp/tokenconvert.py", line 87, in <module>
    tokenizer = load_tokenizer_from_json(input_json_path, special_tokens_map_path, tokenizer_config_path, tokenizer_type)
  File "/home/aidaho/bin/llama.cpp/tokenconvert.py", line 34, in load_tokenizer_from_json
    merges = model_data["merges"]
KeyError: 'merges'
Code: 1

```
Am I doing anything wrong?

**Comment by akumaburn** [comment]
@aidaho It looks like that model is using T5Tokenizer(https://huggingface.co/bigscience/mt0-xl/blob/main/tokenizer_config.json) which is not supported by this script, which only supports BPE and WordPiece at the moment..

**Pull request closed without merging**
