### PR TITLE
Add .clang-format file

### PR DESCRIPTION
**Pull request by ericcurtin**
So people can use things like clang-format and git clang-format to
style their code. Copied from ggml-cann, with PointerAlignment
changed to Middle.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by slaren** [comment]
I believe that having a `.clang-format` would be beneficial even if it is not applied by default on every source file, but at least we should make an effort to replicate the current style used in the core of the library. A big one would be `PointerAlignment`, it should be set to `Middle`.

**Comment by ericcurtin** [comment]
> I believe that having a `.clang-format` would be beneficial even if it is not applied by default on every source file, but at least we should make an effort to replicate the current style used in the core of the library. A big one would be `PointerAlignment`, it should be set to `Middle`.

I agree. I find it particularly handy I can bounce around multiple codebases throughout any given year and it's very hard to remember the style nuances and quickly write code.

git clang-format is very good at just styling sections, so we don't have to apply globally.

@slaren if I copy paste this one:

ggml/src/ggml-cann/.clang-format

and change PointerAlignment to middle we should be good?

**Comment by slaren** [comment]
> @slaren if I copy paste this one:
> 
> ggml/src/ggml-cann/.clang-format
> 
> and change PointerAlignment to middle we should be good?

I don't know, but I wouldn't expect so. The CANN backend has its own style that is not likely to be based on the core ggml/llama.cpp style. We tend to use lots of vertical alignment as well.

**Comment by ggerganov** [comment]
For me the vertical alignment is really important. If we find a way to make it compatible with `.clang-format`, or at least not affect it, we can consider it.

**Comment by slaren** [comment]
I don't expect that we will be able to replicate exactly the same style (we don't even have a well-defined style in the first place), but it has a quite a few options for alignment. https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by ericcurtin** [comment]
Not opinionated on what it looks like but I do want a .clang-format file so I can worry about manually modifying style less. Would it be easier for you guys to open a PR or will I keep iterating?

**Comment by ggerganov** [comment]
> I don't expect that we will be able to replicate exactly the same style (we don't even have a well-defined style in the first place), but it has a quite a few options for alignment. [clang.llvm.org/docs/ClangFormatStyleOptions.html](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

Yes, these look like what we need.

@ericcurtin Start by copying the `.clang-format` from the CANN backend in the root and we'll iterate for some time to make it match the existing styles as much as we can. For now, don't auto-apply it on the full source files - just on the changed lines.

**Comment by ericcurtin** [comment]
Sorry I closed this PR by mistake and it became unreopenable, new one here:

https://github.com/ggerganov/llama.cpp/pull/10308

**Pull request closed without merging**
