### PR TITLE
main : add Self-Extend support

### PR DESCRIPTION
**Pull request by ggerganov**
continuation of https://github.com/ggerganov/llama.cpp/pull/4810

Adding support for context extension to `main` based on this work: https://arxiv.org/pdf/2401.01325.pdf

Did some basic fact extraction tests with ~8k context and base LLaMA 7B v2 (train context of 4096) and the context extension seems to work. The input text was a bunch of Wikipedia pages stitched together in a txt file. At the end of the text, I prompted the model to answer a few questions based on information from the text:

```txt
[... Wikipedia text ...]

===

Answer the following questions based on the previous text:

1. Why was the tricolor banned?
2. When was Olivia born?
3. When did Rodrigo receive the BRIT Billion Award?
4. Who are Rodrigo's idols?

Answers:

1.
```

Command used:

```bash
./main \
  -m models/llama-7b-v2/ggml-model-q8_0.gguf \
  -f build/text.txt \
  -n 256 -c 16384 -s 1 \
  --grp-attn-n 4 --grp-attn-w 2048 \
  --temp 0 --repeat-penalty 1.0 --no-penalize-nl
```

This corresponds to 4x context length extension, but I think it does not work really well when going over 8192 - not sure.

Without the `--grp-attn-n 4 --grp-attn-w 2048` arguments, it generates just gibberish as expected.

Different options for these parameters that also work:

- `--grp-attn-n 2`
- `--grp-attn-w 128`
- `--grp-attn-w 256`
- `--grp-attn-w 512`
- `--grp-attn-w 3072`
- etc.

I think the larger `--grp-attn-w` is - the better. But it should be smaller than the train context.

By default, `--grp-attn-n` is 1 which disables the context extension and the example works as before - i.e. using context shift.

### CODE REVIEW

**Comment by x4080** [comment]
Wow this is very nice for RAG, is the prompt processing improved also ?

**Comment by LeonEricsson** [comment]
> does this work on larger context models like mixtral (32k) if so what kind of improvement can be expected

Yes, theoretically SelfExtend can extend infinitely by adjusting group size and window but the performance for longer contexts >32k is still unknown.

**Comment by ggerganov** [comment]
I did the following test with Mistral Instruct to confirm that the context can be extended to 64k using `G=2`:

- Download 60k tokens of PG essays:

  ```bash
  ./script/get-pg.sh 20
  ```

- Add `[INST]` at the start and the following questions at the end:

  ```
  ==========================

  Answer the following questions based on the text above:

  1. Where is the best place to have lunch in Lukovit?
  2. What are the key words (part 2)?
  3. What are dolphins known for?
  4. What are the key words (part 1)?
  
  [/INST]
  ```

- I inserted the following "needles" at various place of the text:

  ```
  The best place to have lunch in Lukovit is the "Konservenata" restaurant.
  ```

  ```
  Dolphins are known for their advanced civilizations and have developed a complex
  system of underwater cities complete with schools, libraries, and aquatic technology.
  ```

  ```
  Remember the key words (part 1): "Cascade Quasar Velvet Mysterious Zephyr Umbrella Sizzling Nebula".
  ```

  ```
  Remember the key words (part 2): "Elephant Symphony Bubble Horizon Whistle Radiant Harmony Lighthouse". 
  ```

- I've inserted the "Dolphins" and "keywords (part 1)" needles at the beginning of the document, the "best place for lunch" in the middle and the "keywords (part 2)" needle - at the end

The expectation is that without self-extend, we will fail to answer the questions about the first 2 needles, since they are outside the 32k context of the model.

First, we confirm this by running Mistral Instruct v0.2 F16 with 64k context and no self-extend:

```bash
./main -m models/mistral-instruct-7b-v0.2/ggml-model-f16.gguf \
       -f build/task-pg-0.txt -n 256 -c 65536 -s 1 --temp 0 \
       --repeat-penalty 1.0 --no-penalize-nl
```

As expected, it fails to answer questions 3 and 4 correctly:

```
1. The best place to have lunch in Lukovit is the "Konservenata" restaurant.
2. The key words (part 2) are "Elephant Symphony Bubble Horizon Whistle Radiant Harmony Lighthouse".
3. Dolphins are known for their advanced intelligence and social structure.
4. The key words (part 1) are "trans_1x1.gif" and "aah/paulgraham/how-to-get-new-ideas-5.gif". [end of text]

llama_print_timings:        load time =    1496.21 ms
llama_print_timings:      sample time =       2.84 ms /   121 runs   (    0.02 ms per token, 42545.71 tokens per second)
llama_print_timings: prompt eval time =  173511.44 ms / 58031 tokens (    2.99 ms per token,   334.45 tokens per second)
llama_print_timings:        eval time =   14284.08 ms /   120 runs   (  119.03 ms per token,     8.40 tokens per second)
llama_print_timings:       total time =  187934.70 ms
```

We then run the same test, but using self-extend with a factor `G=2`:

```bash
./main -m models/mistral-instruct-7b-v0.2/ggml-model-f16.gguf \
       -f build/task-pg-0.txt -n 256 -c 65536 -s 1 --temp 0 \
       --repeat-penalty 1.0 --no-penalize-nl \
       -grp-attn-n 2 -grp-attn-w 2048 
```

Now it answers all 4 questions correctly:

```
1. The best place to have lunch in Lukovit is the "Konservenata" restaurant.
2. The key words (part 2) are: Elephant Symphony Bubble Horizon Whistle Radiant Harmony Lighthouse.
3. Dolphins are known for their advanced civilizations and complex underwater cities, complete with schools, libraries, and aquatic technology.
4. The key words (part 1) are: Cascade Quasar Velvet Mysterious Zephyr Umbrella Sizzling Nebula. [end of text]

llama_print_timings:        load time =    1493.43 ms
llama_print_timings:      sample time =       2.83 ms /   123 runs   (    0.02 ms per token, 43462.90 tokens per second)
llama_print_timings: prompt eval time =  174197.80 ms / 58031 tokens (    3.00 ms per token,   333.13 tokens per second)
llama_print_timings:        eval time =   14505.90 ms /   122 runs   (  118.90 ms per token,     8.41 tokens per second)
llama_print_timings:       total time =  188854.37 ms
```

Note that the performance is maintained regardless if self-extend is used.

**Comment by LeonEricsson** [comment]
> Now it answers all 4 questions correctly:
> 
> ```
> 1. The best place to have lunch in Lukovit is the "Konservenata" restaurant.
> 2. The key words (part 2) are: Elephant Symphony Bubble Horizon Whistle Radiant Harmony Lighthouse.
> 3. Dolphins are known for their advanced civilizations and complex underwater cities, complete with schools, libraries, and aquatic technology.
> 4. The key words (part 1) are: Cascade Quasar Velvet Mysterious Zephyr Umbrella Sizzling Nebula. [end of text]
> 
> llama_print_timings:        load time =    1493.43 ms
> llama_print_timings:      sample time =       2.83 ms /   123 runs   (    0.02 ms per token, 43462.90 tokens per second)
> llama_print_timings: prompt eval time =  174197.80 ms / 58031 tokens (    3.00 ms per token,   333.13 tokens per second)
> llama_print_timings:        eval time =   14505.90 ms /   122 runs   (  118.90 ms per token,     8.41 tokens per second)
> llama_print_timings:       total time =  188854.37 ms
> ```
> 
> Note that the processing speed is maintained regardless if self-extend is used.

Wow, that is pretty remarkable. Are you able to do it just as fast by avoiding the double dot product?
> 
> Edit: did the same test with Mixtral Instruct 8x7B and even though it has just 32k context, it is somehow able to recall the answers correctly even without self-extend enabled. Probably need to test this at 128k context

Could it have something to do with Sliding Window Attention? I know the was talk around whether SWA was to be enabled or disabled for Mistral 0.2 and Mixtral, people were getting weird results.

**Comment by ggerganov** [comment]
This strategy also works with 128k Mixtral context:

- Get 113403 tokens of PG essays:

  ```bash
  ./scripts/get-pg.sh 35
  ```

- Put the same needles in a similar way: 2 at the start, 1 in the middle, 1 in the end

First, confirm that it does not work without self-extend enabled:

```bash
main -m models/mixtral-instruct-8x7b-fast/ggml-model-f16.gguf \
     -f build/task-pg-1.txt -n 256 -c 131070 -s 1 --temp 0 \
     --repeat-penalty 1.0 --no-penalize-nl
```

Output is garbage:

```
Answer the following questions based on the text above:

1. Where is the best place to have lunch in Lukovit?
2. What are the key words (part 2)?
3. What are dolphins known for?
4. What are the key words (part 1)?

[/INST]▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅
Ctrl-C
```

Next, run with `G=4` so that we extend the 32k context to 128k:

```bash
make -j && ./main -m models/mixtral-instruct-8x7b-fast/ggml-model-f16.gguf -f build/task-pg-1.txt -n 256 -c 131070 -s 1 --temp 0 --repeat-penalty 1.0 --no-penalize-nl -gan 4 -gaw 2048
```

We get the correct answers:

```
1. The best place to have lunch in Lukovit is the "Konservenata" restaurant.
2. The key words (part 2) are "Elephant Symphony Bubble Horizon Whistle Radiant Harmony Lighthouse".
3. Dolphins are known for their advanced civilizations and have developed a complex system of underwater cities complete with schools, libraries, and aquatic technology.
4. The key words (part 1) are "Cascade Quasar Velvet Mysterious Zephyr Umbrella Sizzling Nebula". [end of text]

llama_print_timings:        load time =    6768.29 ms
llama_print_timings:      sample time =       2.83 ms /   128 runs   (    0.02 ms per token, 45149.91 tokens per second)
llama_print_timings: prompt eval time =  966107.12 ms / 111229 tokens (    8.69 ms per token,   115.13 tokens per second)
llama_print_timings:        eval time =   30693.03 ms /   127 runs   (  241.68 ms per token,     4.14 tokens per second)
llama_print_timings:       total time =  997102.53 ms
ggml_metal_free: deallocating
Log end
```

@LeonEricsson Yes, the current implementation does not need the double dot product. No SWA is used here

**Comment by LeonEricsson** [comment]
> Edit: Also, ran the test with `G=2` and it succeeds as well.

Any insights as to why `G=2` doesn't generate garbage considering all tokens beyond 64k end up with positions beyond Mixtral's context, >32k?

**Comment by ggerganov** [comment]
Not sure - feels like even though it is trained at 32k it still works at 64k. Or maybe the test is simple enough to work outside the context

**Comment by LeonEricsson** [comment]
> Not sure - feels like even though it is trained at 32k it still works at 64k. Or maybe the test is simple enough to work outside the context

Hmm, i wonder what happens if you divide the 64k tokens between two PDFs: (1) in [0,32k] and (2) in [32k,64k] then do something like summarization or document QA.

**Comment by x4080** [comment]
Hi, can I use self extend for server also ? Or its not supported yet ?

**Comment by Galunid** [comment]
> Hi, can I use self extend for server also ? Or its not supported yet ?

@x4080 No, it's not supported in the server yet.

It's cool this works as well as it does. Thanks for implementing this.

**Comment by x4080** [comment]
@Galunid thanks for quick response cheers

**Comment by x4080** [comment]
Hi, I tried it with dolphin-phi with about 2000 tokens of prompt, it failed to generate anything
```
./main -ngl 1 -t 0 -m ./models/dolphin-2_6-phi-2.Q5_K_M.gguf --color --temp 0.1 -n -1 -f prompts/mistral.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 2500 --grp-attn-n 2 --grp-attn-w 2048
```

the result is
```
?.

?.


?.



?.

.

?.

.

.

.

```

it works without it ex :
```
./main -ngl 1 -t 0 -m ./models/dolphin-2_6-phi-2.Q5_K_M.gguf --color --temp 0.1 -n -1 -f prompts/mistral.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 2500
```
But I tried to use this with self extend because, sometimes it wont stop generating (my prompt is summarize to 5 points)

**Comment by LeonEricsson** [comment]
> Hi, I tried it with dolphin-phi with about 2000 tokens of prompt, it failed to generate anything
> 
> ```
> ./main -ngl 1 -t 0 -m ./models/dolphin-2_6-phi-2.Q5_K_M.gguf --color --temp 0.1 -n -1 -f prompts/mistral.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 2500 --grp-attn-n 2 --grp-attn-w 2048
> ```

Setting the `grp-attn-w` to `2048` doesn't make a lot of sense here as the model is trained on 2048 context. All the tokens past 2048 will still be O.O.D. What I've seen to be most common is setting `grp-attn-w` to be half of the original training context. That being said, I am able to run with the same command:

`./main -m models/dolphin-phi2/dolphin-2_6-phi-2.Q5_K_M.gguf -f task-pg.txt -c 2500 -s 1 --temp 0.1 -n -1 --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 -gan 2 -gaw 2048`

and get coherent response up to a certain point:

```
[... Paul Graham Essay ...]

===

Summarize the text above in five points.

1. Superlinear returns are a feature of the world, not an artifact of rules we've invented. They can be found in business, fame, power, military victories, knowledge, and even benefit to humanity. Understanding this concept is crucial for success.
2. Exponential growth and thresholds are two fundamental causes of superlinear returns. Examples include bacterial cultures, startups, and learning.
3. The most common case of exponential growth in preindustrial times was scholarship, but it has since become more prevalent due to the rise of empires of ideas.
4. Superlinear returns can be found in situations where there are thresholds, such as winning a sports match or achieving fame.
5. Learning is an important factor in their. It's and you're

 you�




```

The prompt size here was `1901`. Note that when testing with a prompt really close to the context window (e.g `2040`), the model just produces completely incoherent text right of the bat, regardless if selfextend is enabled or not. 

Reasonable arguments for `dolphin-phi` should be something like this:

`./main -m models/dolphin-phi2/dolphin-2_6-phi-2.Q5_K_M.gguf -f task-pg.txt -c 4096 -s 1 --temp 0.1 -n 300 --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 -gan 2 -gaw 1024`

Unfortunately, any time I try with a smaller window the model just fails completely. Wish I could give you a better conclusion here, maybe the model is just too small for this to work properly?

**Comment by x4080** [comment]
@LeonEricsson Thanks for the tip, so set the context size to 4096 and group attention to half which is 1024 (half the context size of phi) - but wont work with phi.

In your example, maybe you got pretty good result because of your prompt size smaller than 2000ish. I found out with >2000 prompt it will failed eventually

**Comment by LeonEricsson** [comment]
> @LeonEricsson Thanks for the tip, so set the context size to 4096 and group attention to half which is 1024 (half the context size of phi) - but wont work with phi.
> 
> In your example, maybe you got pretty good result because of your prompt size smaller than 2000ish. I found out with >2000 prompt it will failed eventually

Yes, I'm not sure if this is ubiquitous but `context size`, the `-c` flag in llama.cpp, is the max for prompt **+ output**.

**Comment by x4080** [comment]
Hi guys, I did some experiment with new model : neuralmarcoro14-7b.Q4_K_M.gguf

This is the command that works best :
```
./main -ngl 1 -t 0 -m ./models/neuralmarcoro14-7b.Q4_K_M.gguf --color --temp 0.3 -n -1 -f prompts/mistral.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 4096 --grp-attn-n 2 --grp-attn-w 1024
```

So context size 4096 matters because this is context that we desired (+self extend), and --grp-attn-w is smaller than model's context size (i'm not sure what this model context size though)

I know this works because, when I use only 
```
./main -ngl 1 -t 0 -m ./models/neuralmarcoro14-7b.Q4_K_M.gguf --color --temp 0.3 -n -1 -f prompts/mistral.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 4096
```
The result is different, this is about summarize about 2500 tokens story about satya nadella, the 1st one correctly obey the instruction and summarization (5 bullet points), the 2nd one seems just get the context cut off -> just summarize whatever

@ggerganov great job !
```

**Comment by Slider2k** [comment]
I had some testing on the Phi-2 model.
It starts to produce gibberish after the contexts size becomes bigger than the Grouped Window size parameter.

In this example it breaks into gibberish mid-response:
```
./main \
	-m dolphin-2_6-phi-2.Q8_0.gguf \
 	-f prompt-summary-tiny.txt \
	-c 0 -n -1 \
	--color -e -i \
	--temp 0.0 --min_p 0.1 --top_p 1 --top_k -1 --repeat_penalty 1 --no-penalize-nl \
	--grp-attn-n 2 --grp-attn-w 256
```
[prompt-summary-tiny.txt](https://github.com/ggerganov/llama.cpp/files/13911182/prompt-summary-tiny.txt)
LLama.cpp build: [`1825 (4330bd8)`](https://github.com/ggerganov/llama.cpp/releases/tag/b1832)

**Comment by duykhanhbk** [comment]
Any one can help support self-extend for server https://github.com/ggerganov/llama.cpp/issues/4886 @ggerganov

**Comment by Slider2k** [comment]
Still problems with Phi-2. Self-Extend doesn't appear to work. Produces gibberish.

```
./main \
 	-m dolphin-2_6-phi-2.Q8_0.gguf \
 	-f prompt-summary-giant.txt \
	-c 4096 -n 20 \
	--color -e -i \
	--temp 0.0 --min_p 0.1 --top_p 1 --top_k -1 --repeat_penalty 1 --no-penalize-nl
	--grp-attn-n 8 --grp-attn-w 1024
```

Prompt (2775 t): [prompt-summary-giant.txt](https://github.com/ggerganov/llama.cpp/files/13926336/prompt-summary-giant.txt)
Build: 1838

**Comment by x4080** [comment]
@Slider2k I tried dolphi phi and it works flawlessly after update. 2500 ish prompt size

**Comment by x4080** [comment]
@tried your prompt, here's the result
```
The Game Gear code name was "Project Mercury". [end of text]

llama_print_timings:        load time =    6474.35 ms
llama_print_timings:      sample time =       1.62 ms /    13 runs   (    0.12 ms per token,  8009.86 tokens per second)
llama_print_timings: prompt eval time =   30153.05 ms /  2834 tokens (   10.64 ms per token,    93.99 tokens per second)
llama_print_timings:        eval time =     902.28 ms /    12 runs   (   75.19 ms per token,    13.30 tokens per second)
llama_print_timings:       total time =   31083.96 ms /  2846 tokens
ggml_metal_free: deallocating
Log end
```

```
./main -ngl 1 -t 0 -m ./models/dolphin-2_6-phi-2.Q5_K_M.gguf --color -c 4096 --temp 0.1 -n -1 -f prompts/testprompt.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1 --grp-attn-n 4 --grp-attn-w 1024
```

**Comment by ggerganov** [comment]
@Slider2k I tested your command (i.e. using `G=8`) and it appears to work (tried CPU and Metal):

```bash
./main \
  -m models/phi-2/dolphin-2_6-phi-2.Q8_0.gguf \
  -f ~/Downloads/prompt-summary-giant.txt \
  -c 4096 -n 20 --color -e --temp 0.0 --min_p 0.1 --top_p 1 --top_k -1 \
  --repeat_penalty 1 --no-penalize-nl --grp-attn-n 8 --grp-attn-w 1024
```

```
---
What was the Game Gear code name?

assistant
The Game Gear code name was "Project Mercury". [end of text]

llama_print_timings:        load time =     362.19 ms
llama_print_timings:      sample time =       0.45 ms /    13 runs   (    0.03 ms per token, 28953.23 tokens per second)
llama_print_timings: prompt eval time =    3340.96 ms /  2834 tokens (    1.18 ms per token,   848.26 tokens per second)
llama_print_timings:        eval time =     172.09 ms /    12 runs   (   14.34 ms per token,    69.73 tokens per second)
llama_print_timings:       total time =    3526.76 ms /  2846 tokens
```

**Comment by Slider2k** [comment]
@ggerganov @x4080 
Found the problem.
It seems that Self-Extend is not compatible with using `--prompt-cache`. The initial cache-less run is OK, but when reusing the created cache the LLM produces incorrect results. This only manifests when prompt grows larger than the model's original context size.

**Comment by ggerganov** [comment]
Yes, `--prompt-cache` is not compatible atm. Should add an assert to prevent it

**Comment by Josh-XT** [comment]
Out of curiosity, is there any reason to not make this this the default behavior to extend to whatever `-c` is set to? What is blocking that from being reality? I'm happy to help if I can. Unless I'm totally misunderstanding, it looks like Mixtral based models should have `gan` set to 2, Mistral to 4, and Phi-2 to 8. Is the blocker differentiating those automatically?

Great work to all involved, this is an amazing update.

**Comment by l3utterfly** [comment]
> Yes, `--prompt-cache` is not compatible atm. Should add an assert to prevent it

Can anyone give me a quick rundown on what's preventing support for prompt caching? I am happy to work on its support.

**Comment by ggerganov** [comment]
I think the only thing that is missing is that we don't know `n_past` of the cached prompt. Probably need to extend the KV cache API to be able to query for it - i.e. get the largest position of a sequence currently stored in the cache

**Comment by K-Mistele** [comment]
I can't find anything about this in the docs, or if it's supported in `./server`

**Comment by ExtReMLapin** [comment]
Gave a try to reach window size of `196608` from what I understood, if mistral training size is 32k, I need a "boost factor" or 6 which will make me meet the expected `196608`

The first harry potty book takes `177144` tokens which should be enough to make it fit inside.


However, as it starts running, it fills the memory of my 3 A40 (till page 33 out of ~200).

Am I doing something wrong or this memory usage is expected ?

`~/llm/llama.cpp$ ./main -m ../models/mistral-7b-instruct-v0.2.Q5_K_M.gguf -f ../e-cole-des-sorciers.txt -n 256 -c 196608 --temp 0 -gaw 6 -gaw 2048 -t 32 -tb 32 -td 32  -ngl 444444444`



Right before Cuda OOM

image

**Comment by ExtReMLapin** [comment]
Fixed my last command : 


`./main -m ../models/mistral-7b-instruct-v0.2.Q5_K_M.gguf -f ../e-cole-des-sorciers.txt -n 256 -c 196608 --temp 0 -gan 8 -gaw 2048 -t 32 -tb 32 -td 32  -ngl 444444444`

**Comment by Slider2k** [comment]
@ExtReMLapin Pretty sure Mistal 7b context is 4096. 32k is claimed when using 'sliding window' technique, which I've heard was disabled in Instruct 0.2. And how or whether 'context extending' works together with 'sliding window' I have no idea.

**Comment by sweetcard** [comment]
Could you please  add this feature into [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp) and  [llama.h](https://github.com/ggerganov/llama.cpp/blob/master/llama.h) can be used by python wrapper? @ggerganov 

Check this request: 
https://github.com/abetlen/llama-cpp-python/issues/1242

**Comment by sweetcard** [comment]
> I was thinking recently to move this functionality into `llama_sampling_context` to make it easier to reuse, but couldn't figure out how to do it entirely in a neat way. It should be possible - it's on my radar
> 
> After that, to make this available in `llama.h`, we need to move `llama_sampling_context` from the examples into the library (#5214). Cannot give an ETA, but it might take some time to get there

Thank you for your excellent work.👍

**Comment by sweetcard** [comment]
any update for this feature @ggerganov 😄 ? 
Thank you for your help.

**Pull request merged**
