### PR TITLE
make : fix embdinput library and server examples building on MSYS2

### PR DESCRIPTION
**Pull request by przemoc**

### CODE REVIEW

**Comment by przemoc** [comment]
BTW I'm not familiar with GitHub Actions, but maybe MSYS2 could be relatively easily added to CI? I mean UCRT64 (default since 2022-10-29, previously it was MINGW64 relying on old msvcrt.dll) and CLANG64 (it's good to not rely on gcc only) [environments](https://www.msys2.org/docs/environments/) specifically.

https://github.com/msys2/setup-msys2 may be potentially helpful to achieve that.

**Comment by przemoc** [comment]
`( rm -rf build && mkdir build && cd build && cmake .. && cmake --build . --config Release )` atm fails in MSYS2. It looks like lack of linking ws2_32 that has been fixed for Makefile in this PR.

**Comment by przemoc** [comment]
Seems to be building without errors now.
```
$ time ( rm -rf build && mkdir build && cd build && cmake .. && cmake --build . --config Release )
-- Building for: Ninja
-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/ucrt64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/ucrt64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/msys64/usr/bin/git.exe (found version "2.41.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (1.8s)
-- Generating done (0.1s)
-- Build files have been written to: C:/msys64/home/przemoc/git/github.com/ggerganov/llama.cpp/build
[1/47] Generating build details from Git
-- Found Git: C:/msys64/usr/bin/git.exe (found version "2.41.0")
...
[45/47] Linking CXX executable bin\embd-input-test.exe
[46/47] Building CXX object examples/server/CMakeFiles/server.dir/server.cpp.obj
[47/47] Linking CXX executable bin\server.exe

real    0m26.451s
user    0m0.000s
sys     0m0.015s
```

**Review by ggerganov — APPROVED** [review]
> BTW I'm not familiar with GitHub Actions, but maybe MSYS2 could be relatively easily added to CI? 

You, I believe it is relatively easy to add

**Pull request merged**
