### PR TITLE
un-ignore `build-info.cmake` and `build-info.sh`

### PR DESCRIPTION
**Pull request by mdegans**
If they are ignored it can break some build tools that consider if a file is ignored, even if it's committed, it should not exist at all. I am assuming ignoring it was a mistake.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by slaren** [comment]
There are a few more files affected, although they are not directly used in the build:

```bash
$ git ls-files -ci --exclude-standard                                                                                                                          
.clang-tidy
.github/workflows/build.yml
common/build-info.cpp.in
examples/chat-13B.bat
examples/llama.android/app/build.gradle.kts
examples/llama.android/build.gradle.kts
examples/llama.android/llama/build.gradle.kts
examples/llama.swiftui/llama.swiftui.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
examples/llava/android/build_64.sh
examples/sycl/build.sh
examples/sycl/win-build-sycl.bat
examples/sycl/win-run-llama2.bat
models/.editorconfig
models/ggml-vocab-aquila.gguf
models/ggml-vocab-baichuan.gguf
models/ggml-vocab-bert-bge.gguf
models/ggml-vocab-bert-bge.gguf.inp
models/ggml-vocab-bert-bge.gguf.out
models/ggml-vocab-command-r.gguf
models/ggml-vocab-command-r.gguf.inp
models/ggml-vocab-command-r.gguf.out
models/ggml-vocab-deepseek-coder.gguf
models/ggml-vocab-deepseek-coder.gguf.inp
models/ggml-vocab-deepseek-coder.gguf.out
models/ggml-vocab-deepseek-llm.gguf
models/ggml-vocab-deepseek-llm.gguf.inp
models/ggml-vocab-deepseek-llm.gguf.out
models/ggml-vocab-falcon.gguf
models/ggml-vocab-falcon.gguf.inp
models/ggml-vocab-falcon.gguf.out
models/ggml-vocab-gpt-2.gguf
models/ggml-vocab-gpt-2.gguf.inp
models/ggml-vocab-gpt-2.gguf.out
models/ggml-vocab-gpt-neox.gguf
models/ggml-vocab-gpt2.gguf
models/ggml-vocab-llama-bpe.gguf
models/ggml-vocab-llama-bpe.gguf.inp
models/ggml-vocab-llama-bpe.gguf.out
models/ggml-vocab-llama-spm.gguf
models/ggml-vocab-llama-spm.gguf.inp
models/ggml-vocab-llama-spm.gguf.out
models/ggml-vocab-mpt.gguf
models/ggml-vocab-mpt.gguf.inp
models/ggml-vocab-mpt.gguf.out
models/ggml-vocab-phi-3.gguf
models/ggml-vocab-phi-3.gguf.inp
models/ggml-vocab-phi-3.gguf.out
models/ggml-vocab-qwen2.gguf
models/ggml-vocab-qwen2.gguf.inp
models/ggml-vocab-qwen2.gguf.out
models/ggml-vocab-refact.gguf
models/ggml-vocab-refact.gguf.inp
models/ggml-vocab-refact.gguf.out
models/ggml-vocab-stablelm.gguf
models/ggml-vocab-starcoder.gguf
models/ggml-vocab-starcoder.gguf.inp
models/ggml-vocab-starcoder.gguf.out
scripts/build-info.cmake
scripts/build-info.sh
scripts/install-oneapi.bat
```

**Comment by mdegans** [comment]
I don't know if it was intentional to ignore `models/.editorconfig` given `.clang-tidy` was explicitly ignored. I'm assuming so, but I'll wait for feedback before committing again.

**Comment by slaren** [comment]
I don't think that `.clang-tidy` should be in `.gitignore`. It looks like it was added by @ggerganov in https://github.com/ggerganov/llama.cpp/commit/7ad7750c5c9f6bcea73a1895ffc57e7d21f2ab95.

@ggerganov Do you remember why?

**Comment by ggerganov** [comment]
I used to disable some of the warnings locally, but not anymore. It's fine to unignore

**Comment by mdegans** [comment]
> I used to disable some of the warnings locally, but not anymore. It's fine to unignore

'tis done.

Although on my mac this is still ignored
```
% git ls-files -ci --exclude-standard
examples/llama.swiftui/llama.swiftui.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
```

Despite this line in `.gitignore`

```
!IDEWorkspaceChecks.plist
```

Not sure what's going on there. I'm on macOS so there may be something Apple-specific going on. There's nothing in my `~/gitignore_global`.

**Comment by slaren** [comment]
It's because it is being overridden by `examples/llama.swiftui/.gitignore`. My guess is that it should be deleted.

**Comment by slaren** [comment]
What I meant is that `xcshareddata` and `IDEWorkspaceChecks.plist` should be removed from the repository. I don't know what this file does, but that `.gitignore` was probably automatically generated by some tool and should be respected.

**Comment by mdegans** [comment]
> It's because it is being overridden by `examples/llama.swiftui/.gitignore`. My guess is that it should be deleted.

I have used XCode like twice in my life, and only to build something. I've no idea other than what I found on SO pertaining to `xcsharedata`.

**Comment by mdegans** [comment]
> What I meant is that `xcshareddata` and `IDEWorkspaceChecks.plist` should be removed from the repository. I don't know what this file does, but that `.gitignore` was probably automatically generated by some tool and should be respected.

Sounds good. I'll add it back.

**Review by slaren — APPROVED** [review]

**Pull request merged**
