### PR TITLE
ggml : remove bit shuffling

### PR DESCRIPTION
**Pull request by ggerganov**
Implementation of #1241

Avoid unnecessary bit shuffling by packing the quants in a better way.
Requires model re-quantization

- `Q4_0`
  - [x] quantize
  - [x] dequantize
  - [x] dot ARM NEON
  - [x] dot AVX

- `Q4_1`
  - [x] quantize
  - [x] dequantize
  - [x] dot ARM NEON
  - [x] dot AVX

- `Q5_0`
  - [x] quantize
  - [x] dequantize
  - [x] dot ARM NEON
  - [x] dot AVX
  - [x] dot WASM SIMD

- `Q5_1`
  - [x] quantize
  - [x] dequantize
  - [x] dot ARM NEON
  - [x] dot AVX
  - [x] dot WASM SIMD

---

New timings:

| Model | Measure      | F16    | Q4_0   | Q4_1   | Q5_0   | Q5_1   | Q8_0   |
|------:|--------------|-------:|-------:|-------:|-------:|-------:|-------:|
|    7B | ms/tok @ 4th |    127 |     49 |     56 |     89 |     92 |     74 |
|    7B | ms/tok @ 8th |    120 |     44 |     52 |     49 |     52 |     70 |
|   13B | ms/tok @ 4th |    261* |    91 |    103 |    173 |    177 |    139 |
|   13B | ms/tok @ 8th |    316* |     81 |     95 |    103 |    113 |    134 |

* *these numbers vary a lot since the model is on the 32GB limit of my MacBook*

Old timings:

| Model | Measure      | F16    | Q4_0   | Q4_1   | Q5_0   | Q5_1   | Q8_0   |
|------:|--------------|-------:|-------:|-------:|-------:|-------:|-------:|
|    7B | ms/tok @ 4th |    128 |     56 |     61 |     91 |     95 |     75 |
|    7B | ms/tok @ 8th |    128 |     47 |     55 |     53 |     59 |     75 |
|   13B | ms/tok @ 4th |    239 |    104 |    113 |    176 |    185 |    141 |
|   13B | ms/tok @ 8th |    240 |     85 |     99 |    108 |    117 |    147 |

*overall, all these numbers seem to have about +/- 10% variablility from run to run. not ideal benchmark, but not sure what else to do*

### CODE REVIEW

**Comment by ggerganov** [comment]
@sw 

> I still think this could be done in a non-breaking manner for Q4, by simply changing the order of Q8

Yes, I'm still hesitating. But I think `Q8` quantization will be sub-optimal this way.
Not much, but still.

**Comment by ggerganov** [comment]
> Q5 interleaves the nibbles but not the single MSBs, that could be confusing. The scalar implementation seems to be broken, maybe it's because of that?

Somehow perplexity computation with `Q5_0` + cuBLAS is currently broken and I don't see the error.
It works on M1.

**Comment by ggerganov** [comment]
Surprising that `Q5_0` and `Q5_1` with 4 threads is slower than `Q8_0`

**Comment by eiery** [comment]
To lessen the breaking impact of this change (I got sent here by the big banner on the front page!) a conversion script could be provided for existing models. Since the weights themselves remain unchanged it should be possible for a script to repack them in the correct format.

**Comment by digiwombat** [comment]
I was somewhat waiting to see if anyone would raise this idea.

Is there enough bloat caused by supporting the old models that a header change to allow loading of both the new and old versions would be an imposition? That would keep old model compatibility and allow new quants to benefit from the speedup without any impact on end users.

Alternatively, if @eiery's proposal is feasible, detecting the old versions and giving an error with a copy/paste-able command would be very valuable. Or just a flag allowing it to do an in-place swap. This would definitely help front-end users for things like ooba's webui and koboldcpp.

**Comment by LostRuins** [comment]
Yes, if this is going to be a complete non-backwards compatible change, might I humbly suggest changing the magic in the file header at least, or utilizing the version field?

**Comment by LostRuins** [comment]
@hmih With all due respect, I know this project is all about optimization and experimentation. I am just suggesting that since this is such a major change, helping others identify older and newer models elsewhere would be very useful, since there is already a thriving ggml ecosystem beyond this repo. 

I understand that reconverting the models for those familiar with this project is easy enough - but I just think a 1 line change for the file magic, or simply incrementing the existing version header by 1, something that requires minimal effort, would make future maintenance and identifying these new formats easier.

**Comment by digiwombat** [comment]
> "End users" here are not state bureaucrats with IE8

Firstly, I agree very much in spirit with your statement and the speedup the new version will bring. I also would offer that it is fairly early in the lifecycle for this project and that is an argument in favor of just putting through the breaking change and letting it be.

On the other side, ggml (especially via llama.cpp) is being used pretty widely and I would ask that spare a bit of a thought for the maintainers of supporting projects like @LostRuins with Koboldcpp or the fine folks doing llama-cpp-python (and downstream of it, oobabooga's webui), among others who will likely bear the brunt of user confusion on these issues. It will cause a burden in a wider radius that the user-facing software people don't have a lot of control over since they are generally not in control of the model repos to make the updates themselves.

That's all. Just wanted to toss out a bit of an explanation since the nature of the users was raised. I think the repos for front-end projects may see the target userbase for their projects much differently than core llama.cpp, generally speaking.

**Comment by Green-Sky** [comment]
https://github.com/ggerganov/llama.cpp/blob/0e48eb6f6b3588d78656267b3b8029b7711f6cdf/ggml.h#L191

can we increment this value by 1 ?

**Comment by LostRuins** [comment]
@sw doesn't have to be though, during loading exceptions can be added in llama.cpp to treat old f16 and q8 format with either file versions 1 or 2 as forwards compatible.

**Comment by ggerganov** [comment]
Close in favor of https://github.com/ggerganov/llama.cpp/pull/1405

**Comment by ProfessorSparrs** [comment]
great, I finally compiled it on my pc(no avx2 support) AND with cuda support. And this change makes none of my models load :(. I dont know how to quantize things, Ive read a lot about it and I doubt I even have the PC-resources to do it.

**Comment by Green-Sky** [comment]
@ProfessorSparrs if you have the f16 files, qnantizing is very easy and WAY less recource intensive than running the model. :) (check the `quantize` executable)

**Pull request closed without merging**
