### PR TITLE
Added support for _POSIX_MAPPED_FILES if defined in source

### PR DESCRIPTION
**Pull request by CoderRC**
I have created my own library for mingw32 that includes the POSIX functions that the source needs to compile. That is how I will support llama.cpp for windows using mingw32 compilation in mys2. Compiled successfully using:
make LDFLAGS='-D_POSIX_MAPPED_FILES -lmingw32_extended'

### CODE REVIEW

**Comment by anzz1** [comment]
Since you're one of the few using mingw32 , could you please look into this first ? #551

**Comment by jart** [comment]
I'd be reluctant to merge this because mmap() is a mandatory feature.

```
   _POSIX_MAPPED_FILES
           Support for memory mapped files is mandatory in POSIX.1-2017.

           This facility provides for the mapping of regular files into the
           process address space.

           Both this facility and the Shared Memory Objects option provide
           shared access to memory objects in the process address space. The
           mmap() and munmap() functions provide the functionality of
           existing practice for mapping regular files. This functionality
           was deemed unnecessary, if not inappropriate, for embedded systems
           applications and is expected to be optional in subprofiles.
```

I have a working mmap() implementation now for MSVC which I intend to push soon. Would it be sufficient for your purposes if we just got rid of the MINGW `#ifdef` and assumed that Mingw users will supply their own mmap()?

**Comment by CoderRC** [comment]
Yes, mmap() is a mandatory feature in POSIX.1-2017, but not in older POSIX versions, and MSVC does not fully support POSIX.1-2017 and _POSIX_MAPPED_FILES is not defined in MSVC.

**Comment by jart** [comment]
Would you be interested in sharing your feedback on the mmap() polyfill I've just added to the master branch? https://github.com/ggerganov/llama.cpp/blob/mmap/mmap.c

**Comment by CoderRC** [comment]
My real goal of this pull request is if a user defined their own implementation of mmap they will define _POSIX_MAPPED_FILES to indicate full support of mmap.

**Review by jart — APPROVED** [review]
OK let's do it. Thank you for this change.

**Comment by CoderRC** [comment]
Thank you, I use https://github.com/CoderRC/libmingw32_extended to compile this, thanks.

**Pull request merged**
