### PR TITLE
Zig build-system: add CI/CD and fix build

### PR DESCRIPTION
**Pull request by kassane**

### CODE REVIEW

**Comment by alonfaraj** [comment]
Good idea to add every build system mentioned in llama.cpp Readme!

I'm wondering if zig worth a separate workflow or it better to integrate it with the existing build workflow.

**Comment by kassane** [comment]
> Good idea to add every build system mentioned in llama.cpp Readme!

The readme has a brief introduction on how to use zig build.

> I'm wondering if zig worth a separate workflow or it better to integrate it with the existing build workflow. 

I chose to separate the CI/CD from the zig, in case the @ggerganov author wants to discontinue it for any reason. And it would also be easier to detect the problem individually.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by ggerganov** [comment]
We can update to latest `master` and merge this if it is still of interest

**Comment by kassane** [comment]
> We can update to latest `master` and merge this if it is still of interest

Done! (rebased)

**Pull request merged**
