### PR TITLE
Example/gguf-split Windows build command in README.md

### PR DESCRIPTION
**Pull request by 4cecoder**
Update readme with a windows build command

### CODE REVIEW

**Comment by phymbert** [comment]
I think it is better to fix the toolchain

**Comment by cebtenzzre** [comment]
We are not going to tell users to run g++ directly.

**Comment by 4cecoder** [comment]
> I think it is better to fix the toolchain 

Any idea on how to fix the tool chain? 

Can we just rewrite?

**Comment by phymbert** [comment]
I will check

**Pull request closed without merging**
