### PR TITLE
Overhaul ci/run.sh and enable tests with openllama model files

### PR DESCRIPTION
**Pull request by crasm**
The existing `ci/run.sh` script is currently inconvenient to use locally, has lots of repetitive logic (that does not otherwise improve clarity), compiles llama.cpp more times than strictly necessary, and requires manual cleanup between runs.

This PR aims to address the above, improve readability and maintainability, and make it possible to run ctests against the downloaded openllama model.

- [x] ~~Standardize bash helper lib (logging, etc.)~~
- [ ] ~~Rewrite ci/run.sh~~
- [ ] ~~Write GH actions workflow for shell tests (lib_test.sh, etc.)~~
- [x] Add ci/run.sh wrapper for local use
- [x] Redo cmake config for model tests
- [x] Add ctest_model #4462
- [x] Add ctest_model #4970

### CODE REVIEW

**Comment by crasm** [comment]
@ggerganov Can you take a look at the [stub ci-run.sh script?](https://github.com/ggerganov/llama.cpp/blob/04fee216d31acb073f486c2055ab1806c714cdc3/scripts/ci-run.sh) Just want to make sure this approach is OK with you before I continue in earnest.

I think directly specifying *what* gets run will ultimately end up being easier to reason about than using flags for VRAM_GB, LOW_PERFORMANCE, etc.

**Comment by crasm** [comment]
[(previous branch)](https://github.com/ggerganov/llama.cpp/tree/cr/revamp-ci-run-sh-bak)

**Comment by ggerganov** [comment]
Hm, not sure about the last 2 commits - I can see the intent, but we already have some Bash code that I don't plan to change. Use the style in https://github.com/ggml-org/ci as a reference. It can be improved with small steps when necessary

Will continue to look at the other changes

**Comment by crasm** [comment]
@ggerganov this is ready. Unfortunately, I'm adding to the copy-paste structure in `ci/run.sh` rather than reducing it. However, it does work.

My biggest issues were high IO usage (SSD wear) and the need for manual cleanup after running it. I addressed this by wrapping it with a convenience script that isolates it to a separate directory, ideally on a ramdisk, and stores the persistent model/wikitext/etc files in `~/.cache/llama.cpp`.

**Review by ggerganov — APPROVED** [review]
It seems that that running `ctest` without a label would fail. I guess it's fine, but would be nice to workaround somehow

**Comment by crasm** [comment]
> It seems that that running `ctest` without a label would fail. I guess it's fine, but would be nice to workaround somehow

If you just mean for the ergonomics of running ctest in terminal, exporting GG_RUN_CTEST_MODELFILE in e.g. ~/.bashrc would suffice.

(This actually makes me realize that we don't need to check if we're running in make. We just need to check of the env variable is set or not. Then the model tests will work in make!)

**Comment by crasm** [comment]
@ggerganov I've changed it so that the test outputs a warning if the `LLAMACPP_TEST_MODELFILE` variable is not set, rather than failing. Make and ctest will output warnings if run without that variable, and setting that variable in your local environment will allow those tests to run.

This shouldn't pose an issue for usage in `ci/run.sh` ...unless some bug is introduced later where the environment variable isn't set properly and nobody pays attention to the warning.

**Comment by crasm** [comment]
If there are no objections or concerns, I will merge this tomorrow

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
