### PR TITLE
IQ1_S: attempt to fix SYCL

### PR DESCRIPTION
**Pull request by ikawrakow**
@ggerganov I see you have a WIP to do this, but as far as I can tell this is for the previous `IQ1_S` version, so decided to try to fix it myself.

### CODE REVIEW

**Comment by ggerganov** [comment]
Thanks for looking into this

Assigning the Intel team for review. AFAICT they are currently focused on resolving some additional problems with the SYCL backend (https://github.com/ggerganov/llama.cpp/pull/6006) and might take them some time to review this, and I don't want to interfere in their work with more PRs (as long as the CI on `master` is green). Will let them merge this when they think it is appropriate

**Comment by NeoZhangJianyu** [comment]
@ikawrakow @ggerganov 
Due to the CI always be broken from yesterday, it's hard to make new PR be passed by CI.

The code of IQ1_S are fixed by several PRs with different solution. It will make this part be complex and easy be with error.
I suggest:
1. pending the new PRs (which not fix CI) until the CI is restored.
2. after the CI is restored, please rebased code and test with unit-test locally to make sure IQ1_S work well.

Thank you!

**Comment by ikawrakow** [comment]
So, I'm not sure what those PR's that fix `IQ1_S` are, but what we currently have does not work, and to me it does not look like it ever did (not even before I made the changes to `IQ1_S`, which this PR is addressing).

No, I don't have a local environment to test the SYCL implementation.  But the CI is definitely not failing because of this PR.

**Comment by abhilash1910** [comment]
@ikawrakow We will review this shortly as we close aome major fixes. Thanks for your contribution.

**Comment by NeoZhangJianyu** [comment]
@ikawrakow 

@AidanBeltonS 
Based on your previews work, the IQ types in this PR are supported by https://github.com/ggerganov/llama.cpp/pull/6521.
I think it could be closed.

Thank your support!

**Pull request closed without merging**
