### PR TITLE
Update convert-hf-to-gguf.py

### PR DESCRIPTION
**Pull request by 0xspringtime**
Replacing with a less risky alternative to the 'assert' statement

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by 0xspringtime — COMMENTED** [review]
syntax correction

**Review by Galunid — APPROVED** [review]

**Comment by HanClinto** [comment]
Too many blank lines were added on line 977-ish, so it's [now breaking CI](https://github.com/ggerganov/llama.cpp/actions/runs/9586913085/job/26435841222#step:4:82). Not a huge deal, but wanted to let you know. I will fix in another PR.

Make sure to double-check failing CI steps before merging. Sometimes build failures are fine (like the finicky Docker builds), but things like the Lint check should always pass. Always double-check failures to ensure that they're not caused by the PR prior to merging.

**Comment by HanClinto** [comment]
I'm also not sure how the CI treats Python-only changes, and it's possible that CI didn't run until merge, so it might not have been easy to see this one.

**Comment by Galunid** [comment]
My bad, sorry about that and thanks for fixing!

**Comment by HanClinto** [comment]
> My bad, sorry about that and thanks for fixing!

No worries! Looking at it now, I'm really not sure if the CI ran prior to the merge or not, so I don't know if there was a way you reasonably could have caught it. 

We may need to modify the CI triggers on Python-only changes -- I'm really not sure.

Either way, not a big deal. I've made my share of merge hiccups, and it's just something to take in stride. :)

Thanks for being pro-active with reviews and merges!

**Pull request merged**
