### PR TITLE
common : disable repeat penalties by default

### PR DESCRIPTION
**Pull request by ggerganov**
ref https://github.com/ggerganov/llama.cpp/issues/6095#issuecomment-2002406208

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
Isn't that a little dangerous to change it for all others models ?

**Review by phymbert — APPROVED** [review]

**Comment by phymbert** [comment]
FYI [it breaks the server](https://github.com/ggerganov/llama.cpp/actions/runs/8339731367) tests as new tokens sequences are now generated. Strange it is only on windows.

**Comment by ggerganov** [comment]
> FYI [it breaks the server](https://github.com/ggerganov/llama.cpp/actions/runs/8339731367) tests as new tokens sequences are now generated. Strange it is only on windows. Fixed in:
> 
> * [server tests : more pythonic process management; fix bare `except:` #6146](https://github.com/ggerganov/llama.cpp/pull/6146)

Thanks and apologies for breaking that

**Comment by phymbert** [comment]
> Thanks and apologies for breaking that

No worries at all, I think this is good that tests fail for this kind of changes

**Pull request merged**
