### PR TITLE
metal : build metallib + fix embed path

### LINKED ISSUE #5977: 'ggml-common.h' file not found when running as shared library and using metal
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

System: M2 Pro Sonoma v14.3.1
Building on master branch

Steps to reproduce:
- Build llama as shared library
- Copy ggml-metal.metal and ggml-common.h into same dir as bin
- Run executable

Error message:
```
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:4:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:4:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #5977 

This should improve the build process following the changes in #5940:

- CMake now always builds `default.metallib`
- Fix `LLAMA_METAL_EMBED_LIBRARY` (Makefile + CMake) to work with the new `ggml-common.h`

### CODE REVIEW

**Comment by giladgd** [comment]
This PR seems to have solved the issue on my end.
I suggest deleting `ggml-metal.air`, `ggml-common.h` and `ggml-metal.metal` from the output directory after building `default.metallib` since it seems that those files aren't necessary at runtime now.

**Comment by giladgd** [comment]
Compiling with `LLAMA_METAL_EMBED_LIBRARY` now relies on `default.metallib` to exist at runtime

**Comment by ggerganov** [comment]
I believe I fixed it - would appreciate another test if you have the opportunity

**Comment by giladgd** [comment]
I've tested your recent commit and now compiling with `LLAMA_METAL_EMBED_LIBRARY` fails at runtime with the original error:
```
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
```

**Pull request merged**
