### PR TITLE
llama-bench : add support for the RPC backend

### PR DESCRIPTION
**Pull request by rgerganov**

### CODE REVIEW

**Comment by rgerganov** [comment]
The `--rpc` command line arg is treated a bit differently from other args of `llama-bench`. When you do:
```bash
$ bin/llama-bench -m ../../models/tinyllama-1b/ggml-model-f16.gguf --rpc localhost:50052 -rpc localhost:50053
```
it won't run two separate tests with `localhost:50052` and `localhost:50053` but a single one with `localhost:50052,localhost:50053`. So it is equivalent to:
```bash
$ bin/llama-bench -m ../../models/tinyllama-1b/ggml-model-f16.gguf --rpc localhost:50052,localhost:50053
```

Another thing that should be noted is that we re-load the model on every single run when using RPC. This is because we cannot free the RPC backend if we still have allocated RPC buffers.

**Comment by slaren** [comment]
> The `--rpc` command line arg is treated a bit differently from other args of `llama-bench`. 

I don't think this is ok, it is preferable to take each `--rpc` parameter as full string and simply don't allow passing multiple values separated with commas. So `--rpc a:123,b:456` is parsed as a full string. There is also no reason to not support using different sets of rpc servers, like with any other parameter, so `--rpc a:123,b:456 --rpc a:123,c:789` would test the two different combinations of servers.

> Another thing that should be noted is that we re-load the model on every single run when using RPC. This is because we cannot free the RPC backend if we still have allocated RPC buffers.

This really should be fixed in the RPC backend rather than requiring specific workarounds in applications that are just using the llama.cpp API.

**Comment by rgerganov** [comment]
> I don't think this is ok, it is preferable to take each `--rpc` parameter as full string and simply don't allow passing multiple values separated with commas. So `--rpc a:123,b:456` is parsed as a full string. There is also no reason to not support using different sets of rpc servers, like with any other parameter, so `--rpc a:123,b:456 --rpc a:123,c:789` would test the two different combinations of servers.
> 

Fair enough, will fix this.

> This really should be fixed in the RPC backend rather than requiring specific workarounds in applications that are just using the llama.cpp API.

Resource management becomes tricky if we allow buffer objects to outlive the backend which created them. One would expect that all resources allocated by the backend (like sockets) should be freed/closed when `ggml_backend_XXX_free()` is called. If buffers outlive their corresponding backend this won't be the case. In this case we need to take special care to deallocate resources when the last RPC buffer is freed or something like this?

**Comment by slaren** [comment]
In ggml-backend, the buffers are not tied to a backend instance. So it cannot be said that a backend created these objects, that's not what is happening. My suggestion would be to keep an internal pool of connections in `shared_ptr`, and reference them on each object tied to that connection, ie. buffers and backend instances. Once they are all freed, the connection can be closed.

**Comment by rgerganov** [comment]
> My suggestion would be to keep an internal pool of connections in `shared_ptr`, and reference them on each object tied to that connection, ie. buffers and backend instances. Once they are all freed, the connection can be closed.

Ok, I will implement this in a separate PR and update this one when ready

**Comment by rgerganov** [comment]
this one is ready for review

**Review by slaren — APPROVED** [review]

**Pull request merged**
