### PR TITLE
prevent markdownish from modifying text inside code block

### PR DESCRIPTION
**Pull request by nathan-sixnines**
was trying to pull out blocks of python code but the markdownish replacements were breaking stuff in the code blocks.

Added some logic to skip the replacements inside code blocks.

### CODE REVIEW

**Comment by tobi** [comment]
Nice

**Comment by mofosyne** [comment]
Looks interesting. Is this a PR you still intend to get in? Just checking for obsolete PRs

**Comment by nathan-sixnines** [comment]
Yeah, if the change is still meaningful after rebasing I intent to commit it.

Will rebase and check

**Comment by nathan-sixnines** [comment]
borked the rebase.

I'm going to open a new PR

**Pull request closed without merging**
