### PR TITLE
llava : use logger in llava-cli

### PR DESCRIPTION
**Pull request by jart**
This change removes printf() logging so llava-cli is shell scriptable.

### CODE REVIEW

**Comment by dagelf** [comment]
How is that different? What's wrong with `2> llama.log`?

**Review by ggerganov — APPROVED** [review]

**Comment by jart** [comment]
@dagelf in most cases llava was actually logging to stdout.

**Comment by sorasoras** [comment]
@jart this break rocm compile on windows
[debugbuild.txt](https://github.com/ggerganov/llama.cpp/files/15078816/debugbuild.txt)
Can you take a look?

**Comment by dagelf** [comment]
W:/git/llama.cpp/common/.\log.h:300:48: warning: token pasting of ',' and
__VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
    #define LOG(str, ...) LOG_IMPL("%s" str, "", ##__VA_ARGS__, "")

clang issues.

**Pull request merged**
