### PR TITLE
do not force the prompt file to end with a new line

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Review by j-f1 — DISMISSED** [review]

**Comment by slaren** [comment]
The changes to `.editorconfig` look good, but I am not sure that it is a good idea to add a space to these prompts, since it can mess with the tokenization of the next word. Instead, we have `--in-prefix " "` for that purpose. `reason-act.sh` already has `--in-prefix " "`, and probably this should be added to `chat.sh` as well.

**Comment by prusnak** [comment]
Okay, so the space should be removed. What about newline at the end of prompt files? Should it be kept or removed too?

**Comment by slaren** [comment]
Yes, adding a new line at the end of a prompt should be a deliberate choice and not something forced by the editor.

**Comment by prusnak** [comment]
> It depends on the prompt but in these cases it should be removed, adding a new line at the end of a prompt should be a deliberate choice and not something forced by the editor.

I am asking about the two particular prompt files I touched in this PR.

**Comment by slaren** [comment]
I don't think these prompts should end in a new line.

**Comment by prusnak** [comment]
Updated the PR to reflect review comments - see 9b52fc3aa65db3c8d2963f8583427bfd3f6a5917

**Review by slaren — APPROVED** [review]

**Pull request merged**
