### PR TITLE
metal : try to utilize more of the shared memory using smaller views

### PR DESCRIPTION
**Pull request by ggerganov**
Not sure if this helps

cc @CyborgArmy83 please give it a try and see if you can load more models with this patch

### CODE REVIEW

**Comment by gianpaj** [comment]
Not sure if this helps. I tested on M1 Pro 16GB for ram

```
./main -m ./models/ggml-model-q4_0.bin -t 8 -n 128 -ngl 1 -p 'The first man on the moon was '
```

3 runs
```
llama_print_timings:        eval time =  4564.88 ms /   103 runs   (   44.32 ms per token,    22.56 tokens per second)
llama_print_timings:        eval time =  5690.39 ms /   127 runs   (   44.81 ms per token,    22.32 tokens per second)
llama_print_timings:        eval time =  5680.82 ms /   127 runs   (   44.73 ms per token,    22.36 tokens per second)
```

**Comment by EliasOenal** [comment]
@ggerganov This sadly does not seem to allow using more than recommendedMaxWorkingSetSize. Tested on M1 Max with 32GB RAM. I set the ctx size to 2700 to trigger the limit, 2600 was still below and worked fine.

```
ggml_metal_init: recommendedMaxWorkingSetSize = 21845.34 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =   166.63 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =            0
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =   4120215552
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =   8240431104
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3204.09 MB, offs =  12360646656, (15492.48 / 21845.34)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =  1280.00 MB, (16772.48 / 21845.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  4096.00 MB, offs =            0
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =    19.30 MB, offs =   4294950912, (20887.78 / 21845.34)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   512.00 MB, (21399.78 / 21845.34)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB, (21911.78 / 21845.34), warning: current allocated size is greater than the recommended max working set size

system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 2700, n_batch = 512, n_predict = -1, n_keep = 0


ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
ggml_metal_get_buffer: error: buffer is nil
```

**Comment by linghunjiushu** [comment]
> @ggerganov This sadly does not seem to allow using more than recommendedMaxWorkingSetSize. Tested on M1 Max with 32GB RAM. I set the ctx size to 2700 to trigger the limit, 2600 was still below and worked fine.
> 
> ```
> ggml_metal_init: recommendedMaxWorkingSetSize = 21845.34 MB
> ggml_metal_init: hasUnifiedMemory             = true
> ggml_metal_init: maxTransferRate              = built-in GPU
> llama_new_context_with_model: max tensor size =   166.63 MB
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =   4120215552
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4096.00 MB, offs =   8240431104
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3204.09 MB, offs =  12360646656, (15492.48 / 21845.34)
> ggml_metal_add_buffer: allocated 'eval            ' buffer, size =  1280.00 MB, (16772.48 / 21845.34)
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  4096.00 MB, offs =            0
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =    19.30 MB, offs =   4294950912, (20887.78 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   512.00 MB, (21399.78 / 21845.34)
> ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB, (21911.78 / 21845.34), warning: current allocated size is greater than the recommended max working set size
> 
> system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> generate: n_ctx = 2700, n_batch = 512, n_predict = -1, n_keep = 0
> 
> 
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ggml_metal_get_buffer: error: buffer is nil
> ```

Thanks for your method.

I met same problem " failed with status 5", and I change n_ctx from 4096 to 2000, then it works fine.

my env : apple m2 pro 16gb
model : llama-2-13b-chat.ggmlv3.q4_0.bin

**Comment by RDearnaley** [comment]
What would be nice was if reducing --gpulayers fixed the problem, so that only the layers that Metal was actually running counted towards the recommendedMaxWorkingSetSize. I have an M2 MacBook Pro with 64GB, recommendedMaxWorkingSetSize = 49152.00 MB, so I can run LLama2 70B 6-bit quantized on CPU (rather slow), but not on GPU — I guess I'll need to redownload one of the 5-bit quantized versions, rather than just shifting a few layers to CPU threads.

Also, it would be nice if hitting this situation gave a more comprehensible error message than:

> GGML_ASSERT: ggml-metal.m:1221: false

without the end user having to first fritz with the code to get GGML Metal debug logging turned back on and then decypher the meaning of the rather opaque:

> ggml_metal_graph_compute: command buffer 4 failed with status 5

perhaps something like "Current allocated size is greater than the recommended max working set size: Metal ran out of memory for running your model on GPU (try a smaller context length or smaller model)"

**Comment by RDearnaley** [comment]
According to https://developer.apple.com/documentation/metal/mtlcommandbufferstatus/error status 5 is a generic 'an error occurred during your command' status, and application code should be checking the error property for more details. So we should probably do that before emitting a diagnosis message like I suggested above.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
