### PR TITLE
cuda : tweak mm stride to double perf on P40 + GTX 970

### PR DESCRIPTION
**Pull request by cebtenzzre**
This simple change more than doubles the prompt processing speed when I am using both of my GPUs. All results are with `-DLLAMA_CUDA_FORCE_MMQ=ON` because I do not have tensor cores.

| GPU      |Model     | Test | t/s master | t/s PR | Speedup |
|----------|-----------|------|------------|--------|---------|
| GTX 970 + P40  |7b q4_0   | pp512   |   217.28 ± 0.004     | 458.18 ± 0.050   |  2.11    |
| GTX 970 + P40  |13b q4_k_s  | pp512   |    111.45 ± 0.001     |  246.14 ± 0.040  |  2.21   |

Can someone with more than one GPU that supports DP4A (compute capability >= 6.1) test with `-DLLAMA_CUDA_FORCE_MMQ=ON` and `-DLLAMA_CUDA_FORCE_MMQ=OFF` (assuming tensor cores are available), in case I need to make this change conditional? Unfortunately, I have only one multi-GPU configuration available to test.

Setting MUL_MAT_SRC1_COL_STRIDE to 1024 is sufficient, if anyone experiences a performance regression with this change, could they test that value too?

cc @Ph0rk0z since you have access to dual P40s.

ref #3814

### CODE REVIEW

**Comment by ziedbha** [comment]
Just curious, do you happen to know how many cuda streams end up being used in either model config? Or maybe an Nsight systems report you'd be willing to share? Would be nice to look at the perf gain from the difference in the stream usage.

**Comment by slaren** [comment]
Since @JohannesGaessler wrote that code and he uses P40s, I am surprised that the value of `MUL_MAT_SRC1_COL_STRIDE` is not already tuned for the P40. Maybe this is only an improvement with the GTX 970?

**Comment by slaren** [comment]
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   yes
ggml_init_cublas: CUDA_USE_TENSOR_CORES: no
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | pp 512     | 2316.59 ± 203.46 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | tg 128     |    123.07 ± 1.78 |

build: 12fb1c58 (1570)

ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | pp 512     | 3644.91 ± 155.33 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | tg 128     |    121.13 ± 3.64 |

build: 12fb1c58 (1570)







Master:

ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   yes
ggml_init_cublas: CUDA_USE_TENSOR_CORES: no
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | pp 512     | 2365.14 ± 138.48 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | tg 128     |    127.23 ± 1.78 |

build: f3b26981 (1570)

ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | pp 512     |  3760.56 ± 80.43 |
| llama 7B mostly Q4_0           |   3.56 GiB |     6.74 B | CUDA       |  99 | tg 128     |    119.70 ± 0.92 |

build: f3b26981 (1570)

**Comment by cebtenzzre** [comment]
The current version shouldn't have an effect unless you use `-DLLAMA_CUDA_FORCE_MMQ=ON` with a card that doesn't support DP4A. I see no siginficant performance different with just my GTX 970, only when I am using both cards.

**Comment by JohannesGaessler** [comment]
MMQ needs compute capability 6.1 or higher, otherwise the `__dp4a` instruction is not present. I did not consider the case of one of the GPUs having a compute capability < 6.1 when optimizing the performance via the stride. Such GPUs cannot use MMQ and should fall back to dequantizing the weight matrix and running cuBLAS. Looking at the code it seems that the dequantized weight matrix is not being cached. So for a stride of 128 this would then imply that the weight matrix is being dequantized four times for a batch size of 512 leading to poor performance. That would also explain why for FP16 on Volta or higher the high stride value yields better performance.

**Comment by cebtenzzre** [comment]
This PR doesn't seem to be relevant anymore - on master with pp512 I'm getting about 654 t/s with my GTX 970 and Tesla P40, with or without this change.

**Pull request closed without merging**
