### PR TITLE
server : (web UI) add copy button for code block, fix api key

### PR DESCRIPTION
**Pull request by ngxson**
Added Copy button for code blocks:

image

It also follow the window as user scroll up (position sticky):

image

This PR also fixes a problem with API key set, as reported via this comment: https://github.com/ggerganov/llama.cpp/pull/10175#issuecomment-2465045744

image

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low

### CODE REVIEW

**Review by jhen0409 — APPROVED** [review]

**Review by ggerganov — APPROVED** [review]
There is a subtle bug with the scrolling:

- Scroll to the bottom of the generated session (or to the top)
- Using a mouse with scroll wheel, first start scrolling down and then up - nothing happens
- If you first scroll up and the down - it works

Edit: please ignore - everything is OK

**Comment by ngxson** [comment]
@ggerganov I'm not sure if I understand it correctly, but I suspect that it may have something to do with the "show-on-hover" that I have on the button.

I removed that in the last commit, so the copy button now always show on code snippet (no need to hover). Please let me know if that fixes the issue. Thanks.

**Comment by ggerganov** [comment]
Ah, apologies for the distraction - this seems to be a browser behaviour that somehow I haven't noticed before. All scrolls on other pages also work like that, so it's not specific to this UI.

**Comment by ngxson** [comment]
No problem. Anw, I think having the copy button being persistent (and not "on hover") feels more consistent overall, so I'll keep it and merge this PR now. Thanks for testing it!

**Pull request merged**
