### PR TITLE
CUDA: Enable K-shift operation for -ctk q8_0 (limited)

### PR DESCRIPTION
**Pull request by ghost**
This is a reworked https://github.com/ggerganov/llama.cpp/pull/5653
Some CUDA code was adapted from: https://github.com/ggerganov/llama.cpp/commit/3d92acfb8d41ca4d924743ffa6f7cfba105c23f5
Original PR had explosive GPU memory requirement. ~~I'm not sure if it's a bug, or intended logic of the allocator.~~
~~I worked around it by reusing the same tensor. It seems to work well for me.~~

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [x] Medium
  - [ ] High

### CODE REVIEW

**Comment by slaren** [comment]
I cannot reproduce the issue that you reported with memory usage, in my tests the allocator correctly reuses the memory of the previous tensors automatically. The `ggml_backend_sched_set_tensor_backend` is necessary, but the other changes should be reverted to keep the code simple.

**Comment by Nekotekina** [comment]
Right, I simplified it. Thanks. But where are dequantize functions you are talking about? You mean `ggml_get_to_fp32_cuda` from convert.cu?

**Comment by Nekotekina** [comment]
I also forgot to ask, is there a reason to use f32 over f16? The performance of q8_0 K-Shift doesn't seem great in this PR, I wonder if using f16 can improve it...

**Comment by slaren** [comment]
Yes, I mean the functions from `convert.cu`, it should be straightforward to use these for `GGML_OP_CPY` when both `src0` and `src1` are contiguous. Using F16 should also work, and at least it would reduce the buffer size, which is always good, but I wouldn't expect a big performance difference. I think the quantization kernels could be optimized to use more threads (one thread per value instead of per block), which should improve performance.

**Review by slaren — APPROVED** [review]

**Comment by neavo** [comment]
> This is a reworked #5653 Some CUDA code was adapted from: [3d92acf](https://github.com/ggerganov/llama.cpp/commit/3d92acfb8d41ca4d924743ffa6f7cfba105c23f5) Original PR had explosive GPU memory requirement. ~I'm not sure if it's a bug, or intended logic of the allocator.~ ~I worked around it by reusing the same tensor. It seems to work well for me.~
> 
> * [x]  I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
> * Self-reported review complexity:
>   
>   * [ ]  Low
>   * [x]  Medium
>   * [ ]  High

Great, it works well in actual use. Is there a plan to support more quantitative specifications, such as q4_0?

**Comment by Nekotekina** [comment]
I'd like to improve it more, as @slaren mentioned, but I'm confused a bit by APIs.
```
ggml_get_to_fp16_cuda(src0->type)(src0_ddc, reinterpret_cast<half*>(src1_ddc), ggml_nelements(src1), main_stream);
```
If I use convert function like this, what should be in `k`? Is the number of f16/f32 elements ok?

**Comment by slaren** [comment]
Yes, that looks right.

**Comment by Nekotekina** [comment]
Hmm, it seems to corrupt KV cache after all. I'll try to create PR later.

**Pull request merged**
