### PR TITLE
Fix CUDA build on Windows

### PR DESCRIPTION
**Pull request by howard0su**
Native doesn't work for Windows with CUDA 12.1.

### CODE REVIEW

**Comment by howard0su** [comment]
We didn't catch this during CI because CI machine doesn't have CUDA card installed.

On CI, it is a bit different: There are CMAKE error and no such gencode option given to nvcc
```
CMake Error in CMakeLists.txt:
  CUDA_ARCHITECTURES is set to "native", but no GPU was detected.

  D:\a\llama.cpp\llama.cpp\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu   -ID:\a\llama.cpp\llama.cpp\. -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart static -arch=native -Xcompiler="/EHsc -Ob2"   -D_WINDOWS -DNDEBUG -DGGML_USE_CUBLAS -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_USE_K_QUANTS -D_CRT_SECURE_NO_WARNINGS -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -DWIN32 -D_WINDOWS -DNDEBUG -DGGML_USE_CUBLAS -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_USE_K_QUANTS -D_CRT_SECURE_NO_WARNINGS -D"CMAKE_INTDIR=\"Release\"" -Xcompiler "/EHsc /W3 /nologo /O2 /FS   /MD /GR" -Xcompiler "/Fdggml.dir\Release\ggml.pdb" -o ggml.dir\Release\ggml-cuda.obj "D:\a\llama.cpp\llama.cpp\ggml-cuda.cu" 
CUDACOMPILE : nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used [D:\a\llama.cpp\llama.cpp\build\ggml.vcxproj]
```

My failed command line:
```
  C:\GPT\llama.cpp\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc.exe" -gencode=arch=compute_native,code=\"compute_native,compute_native\" -gencode=arch=compute_native,code=\"sm_native,compute_native\" --use-local-env -ccbin "C:\Program Files\
  Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu   -IC:\GPT\llama.cpp\. -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include"     --keep-dir x64
  \Debug  -maxrregcount=0   --machine 64 --compile -cudart static -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -DGGML_USE_CUBLAS -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_USE_K_QUANTS -D_CRT_SECURE_NO_WARNINGS -D"CMAKE_INTDIR=\"Debug\""
   -D_MBCS -DWIN32 -D_WINDOWS -DGGML_USE_CUBLAS -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_USE_K_QUANTS -D_CRT_SECURE_NO_WARNINGS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/Fdggml.
  dir\Debug\ggml.pdb" -o ggml.dir\Debug\ggml-cuda.obj "C:\GPT\llama.cpp\ggml-cuda.cu"
  nvcc fatal   : Unsupported gpu architecture 'compute_native'
```

**Comment by slaren** [comment]
Have you tested if using the architecture of your GPU, or just using "all", improves the performance? I wonder if this is the reason why some people have issues with CUDA performance on Windows.

**Comment by howard0su** [comment]
I think I should upgrade my cmake

**Comment by howard0su** [comment]
@slaren let me do some testing with native v.s. OFF on windows perf.

**Comment by Urammar** [comment]
I'm also having an issue building this

image

PATH environmental variables are correct, running nvcc --version verifies that 12.1.105 is installed

**Pull request closed without merging**
