### PR TITLE
llama.swiftui - Updated Models Layout

### PR DESCRIPTION
**Pull request by isaiahbjork**
- Added a models drawer
- Added downloading directly from Hugging Face
- Load custom models from local folder
- Delete models by swiping left

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
- InputButton is not added to the project
- In the model drawer, when a model completes the download, it does not show up in the list of available models. Need to reopen the drawer to see it

**Comment by ggerganov** [comment]
When I build the app for macOS, the main window (on the left) is quite narrow - can we improve this:

image

Also, change the title from "Model Settings" to "Main".

**Comment by azarovalex** [comment]
@isaiahbjork  Haha, I started a similar endeavour of rewriting the SwiftUI sample, you beat me to it 🙂
feel free to merge your PR, there is much left to refactor in the current sample anyway.

My version: 🫠

**Comment by ggerganov** [comment]
@azarovalex Improvements are welcome if you feel like it! I don't have SwiftUI experience, so mostly relying on contributions for this example

**Pull request merged**
