### PR TITLE
server: support reverse proxy setup with custom route

### PR DESCRIPTION
**Pull request by EZForever**
As of b2536, the server's builtin UI uses absolute routes for API and static files, which works fine, but will break if the server is behind a reverse proxy (e.g. nginx) under custom route.

```
# This will work, given that server is running at 127.0.0.1:8080
location / {
    proxy_pass http://127.0.0.1:8080/;
    # ...
}

# This will not work; the interface does not show up
location /llama/ {
    proxy_pass http://127.0.0.1:8080/;
    # ...
}
```

This PR modifies UI code to use relative routes instead. API URL is also made configurable in `chat.js`, allowing it to be used independently.

### CODE REVIEW

**Comment by phymbert** [comment]
Thanks for looking into this. This will work but this is annoying we need to rebuild cpp static files in binary format each time, unable to identify changes you have done there, so I cannot approve alone.

**Review by ngxson — APPROVED** [review]

**Comment by ngxson** [comment]
LGTM, let's wait to see if the CI pass then we can merge.

**Comment by EZForever** [comment]
These failed tests don't make sense; I don't think a UI code change could cause the Metal backend to fail or make a Nix build last for 6 hours.

**Comment by phymbert** [comment]
> These failed tests don't make sense; I don't think a UI code change could cause the Metal backend to fail or make a Nix build last for 6 hours.

Yes, we are facing a lack of resources on the macOS github runners randomly.

**Pull request merged**
