### PR TITLE
[gguf-py] gguf_reader: numpy 2 newbyteorder fix

### LINKED ISSUE #9021: Bug: Couldn't load GGUF file into Transformers
### What happened?

Hi, Im trying to load GGUF model into transformers and I'm doing it like it is in example here https://huggingface.co/docs/transformers/en/gguf

```
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "thirteenbit/madlad400-10b-mt-gguf"
filename = "model-q8_0.gguf"

tokenizer = AutoTokenizer.from_pretrained(model_id, gguf_file=filename)
model = AutoModelForCausalLM.from_pretrained(model_id, gguf_file=filename)

inputs = tokenizer("<2pt> I love pizza!", return_tensors="pt")
outputs = model.generate(**inputs)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))
```

But I'm getting this error 

```
Traceback (most recent call last):
  File "....path.../translate-run-madlad.py", line 14, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_id, gguf_file=filename)
  File "......path....../lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 851, in from_pretrained
    config_dict = load_gguf_checkpoint(gguf_path, return_tensors=False)["config"]
  File "......path....../lib/python3.10/site-packages/transformers/modeling_gguf_pytorch_utils.py", line 83, in load_gguf_checkpoint
    reader = GGUFReader(gguf_checkpoint_path)
  File "......path....../lib/python3.10/site-packages/gguf/gguf_reader.py", line 94, in __init__
    if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
  File "......path....../lib/python3.10/site-packages/gguf/gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
```

It looks like you just need to substitute  `newbyteorder` by `arr.view(arr.dtype.newbyteorder(order))` , thx

### Name and Version

It's i think on all versions https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/gguf_reader.py

### What operating system are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jettjaniak**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

fixes https://github.com/ggerganov/llama.cpp/issues/9021

### CODE REVIEW

**Comment by theo77186** [comment]
also fixes https://github.com/ggerganov/llama.cpp/issues/10127

**Review by danbev — APPROVED** [review]

**Comment by vgel** [comment]
What's the timeline for this getting released to PyPi? Currently blocked on upgrading repeng to numpy 2 by it.

**Comment by ggerganov** [comment]
Should be up after this workflow is done: https://github.com/ggerganov/llama.cpp/actions/runs/12338278342

**Comment by vgel** [comment]
> Should be up after this workflow is done: https://github.com/ggerganov/llama.cpp/actions/runs/12338278342

Awesome, ty both!

**Pull request merged**
