### PR TITLE
simple-chat : only add bos on first prompt

### PR DESCRIPTION
**Pull request by slaren**
Fix bos being added on all calls to `llama_tokenize`.

### CODE REVIEW

**Comment by slaren** [comment]
It seems that the `add_special` flag will also add EOS, which doesn't seem right here. What would be the way to add only BOS?

**Comment by MaggotHATE** [comment]
`main` [adds BOS manually](https://github.com/ggerganov/llama.cpp/blob/a6744e43e80f4be6398fc7733a01642c846dce1d/examples/main/main.cpp#L311) in case of an empty prompt, so I guess the same can be done here - manually putting BOS and EOS whenever needed.

However, maybe it's better to refactor [llama-vocab](https://github.com/ggerganov/llama.cpp/blob/a6744e43e80f4be6398fc7733a01642c846dce1d/src/llama-vocab.cpp#L1437) because `llama_tokenize_internal` doesn't make a distinction between EOS and BOS.

**Comment by ggerganov** [comment]
> What would be the way to add only BOS?

Should check if `llama_add_bos_token(model)` is `true` and add it manually, combined with `llama_tokenize(add_special = false)`.

**Comment by slaren** [comment]
Is there any case where `add_special = true` makes sense? Why would anybody want to add a `EOS` to a prompt?

**Comment by ggerganov** [comment]
> Is there any case where add_special = true makes sense? Why would anybody want to add a EOS to a prompt?

I think it kind of makes sense for embedding models. `add_bos` was changed to `add_special` here: https://github.com/ggerganov/llama.cpp/pull/6498

> I was about to say that server might use it because it processes all messages (so, both prompts and responses, and responses might actually need EOS)

No, if the model needs EOS in responses, it will generate it. So this option is not useful for chat use cases.

**Comment by MaggotHATE** [comment]
> if the model needs EOS in responses, it will generate it

Was there at any point (back in llama2 days or eve earlier) problem with models not generating EOS tokens? There's a [guard](https://github.com/ggerganov/llama.cpp/blob/a6744e43e80f4be6398fc7733a01642c846dce1d/examples/main/main.cpp#L742) for antiprompt generated by the model in main.

**Comment by slaren** [comment]
> I think it kind of makes sense for embedding models.

If this only makes sense for embeddings models, wouldn't this make the way most examples use it wrong? I took a quick look, and almost every case still treats this as an `add_bos`.

**Comment by ggerganov** [comment]
I wouldn't be surprised if there are incorrect usages of the `llama_tokenize()` in the examples. But the general logic that should be followed with the current implementation seems to be:

- If you are tokenizing a full prompt (i.e. starting from the beginning without prior tokens in the context) then use `llama_tokenize(add_special = true)` and hope that the GGUF KV meta data has correctly exported `LLM_KV_TOKENIZER_ADD_BOS` and `LLM_KV_TOKENIZER_ADD_EOS`. For example, both are `true` for embedding models and the latter is `false` for chat models.

- If you are tokenizing a portion of a prompt, always use `llama_tokenize(add_special = false)`

So with this logic in mind, the current implementation in this branch seems OK. Is it failing with a certain model that you tried? If yes, what are the 2 KV values set to?

**Comment by slaren** [comment]
> Is it failing with a certain model that you tried?

No, the responses generated look fine. I missed that it is only added if `LLM_KV_TOKENIZER_ADD_EOS` is true.

**Review by ggerganov — APPROVED** [review]
Yes, I also forgot about this initially and figured it out while looking at the usages. Probably the example can print a warning if the provided model has `llama_add_eos_token(model) == true` as we don't expect to use such models with this example.

**Pull request merged**
