### PR TITLE
llama : return nullptr from llama_grammar_init

### PR DESCRIPTION
**Pull request by danbev**
This commit updates llama_grammar_init to return nullptr instead of throwing an exception.

The motivation for this is that this function is declared inside an extern "C" block and is intended/may be used from C code which will not be able to handle exceptions thrown, and results in undefined behavior.

On Windows and using MSVC the following warning is currently generated:
```console
C:\llama.cpp\llama.cpp(13998,1): warning C4297: 'llama_grammar_init': function assumed not to throw an exception but does
C:\llama.cpp\llama.cpp(13998,1): message :__declspec(nothrow), throw(), noexcept(true), or noexcept was specified on the function
```

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by HanClinto** [comment]
Overall this is a good change, but I'm curious how this changes the stack trace returned with left-recursive grammars. I think we should do an audit for everything that calls `llama_grammar_init()` to ensure that we are checking for null ptrs. Examples include [sampling.cpp:31](https://github.com/ggerganov/llama.cpp/blob/master/common/sampling.cpp#L31) and (less-importantly) [gbnf-validator.cpp:101](https://github.com/ggerganov/llama.cpp/blob/master/examples/gbnf-validator/gbnf-validator.cpp#L101).

**Review by HanClinto — APPROVED** [review]
Overall I think this is a good change, though there may be some cleanup spots to do later.

**Comment by dbevenius** [comment]
> I think we should do an audit for everything that calls `llama_grammar_init()` to ensure that we are checking for null ptrs.

Good point, I'll take a look at this! Thanks

**Comment by danbev** [comment]
> I think we should do an audit for everything that calls `llama_grammar_init()` to ensure that we are checking for null ptrs.

Good point, I'll take a look at this! Thanks

**Comment by HanClinto** [comment]
> > I think we should do an audit for everything that calls `llama_grammar_init()` to ensure that we are checking for null ptrs.
> 
> Good point, I'll take a look at this! Thanks

Did you resolve everything you wanted to in 35d96805f7e504d27b8e8d8d0906b98414f44fb7 or should we wait for more? If you're happy, I think you're good to click "Squash and Merge".

**Comment by danbev** [comment]
> Did you resolve everything you wanted to in [35d9680](https://github.com/ggerganov/llama.cpp/commit/35d96805f7e504d27b8e8d8d0906b98414f44fb7) or should we wait for more? If you're happy, I think you're good to click "Squash and Merge".

All good from my side 👍 I can rebase and squash the commits to make it easier to merge, but I don't I have write access so I don't think I can merge.

**Comment by HanClinto** [comment]
> All good from my side 👍 I can rebase and squash the commits to make it easier to merge, but I don't I have write access so I don't think I can merge.

Aah, right. Thanks for the PR!

**Pull request merged**
