### PR TITLE
Tidy ggml-sycl

### PR DESCRIPTION
**Pull request by AidanBeltonS**
This PR tidies up some aspects of ggml-sycl. 
Specifically focusing on removing unused variables created in the code translation and reducing the number of compiler warnings emitted during compilation.

There should be no behavioural changes from this PR.

### CODE REVIEW

**Comment by AidanBeltonS** [comment]
@abhilash1910  @NeoZhangJianyu @Alcpz, any feedback on this would be welcome.

**Comment by abhilash1910** [comment]
Thanks @AidanBeltonS  for initiating this; I guess there are a couple of places where cleanups are needed (vars + unused codes)

**Comment by NeoZhangJianyu** [comment]
@AidanBeltonS 
Thank your work！
Some unused codes will be used to support multiple GPUs (tensor_split) in the future. We left these codes for next development.
I see your current update have no impact to next job.

I will handle to support multiple GPUs soon.
Please hold remove warning work if you are doing more.

Thank you again!

**Review by abhilash1910 — APPROVED** [review]
Changes does not affect future dev plans; compiler warnings would be removed post @NeoZhangJianyu work.
cc @ggerganov @NeoZhangJianyu for final review

**Review by NeoZhangJianyu — APPROVED** [review]

**Pull request merged**
