### PR TITLE
build : pass all warning flags to nvcc via -Xcompiler

### LINKED ISSUE #5542: CMAKE error nvcc fatal   : Unknown option '-Wall'
On Ubuntu 22.04, using CMAKE and -DLLAMA_CUBLAS=ON I'm getting the following error:

```
Cannot get compiler information:
	Compiler exited with error code 1: /usr/local/cuda/bin/nvcc -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128 -DGGML_USE_CUBLAS -DK_QUANTS_PER_ITERATION=2 -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -isystem=/usr/local/cuda/include -O3 -DNDEBUG -std=c++11 --generate-code=arch=compute_52,code=[compute_52,sm_52] --generate-code=arch=compute_61,code=[compute_61,sm_61] --generate-code=arch=compute_70,code=[compute_70,sm_70] -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -use_fast_math -Wno-pedantic -Xcompiler "-Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native" --dryrun /tmp/compiler-file17262593416218535232.cu
	nvcc fatal   : Unknown option '-Wall'
```

The problem can be solved by replacing the following lines in the CMakeLists.txt:

```
set(CUDA_FLAGS ${CXX_FLAGS} -use_fast_math)
if (NOT MSVC)
    list(APPEND CUDA_FLAGS -Wno-pedantic)
endif()
```

to:

```
set(CUDA_FLAGS -use_fast_math)
if (NOT MSVC)
    list(APPEND CUDA_FLAGS --compiler-options=-Wno-pedantic)
endif()
```

Maybe someone have better idea how to include "${CXX_FLAGS}" for CUDA_FLAGS?

### PR DESCRIPTION
**Pull request by cebtenzzre**
Ref #5543

Fixes #5542

### CODE REVIEW

**Review by slaren — APPROVED** [review]

**Comment by cebtenzzre** [comment]
Looks like PR #3952 broke the Makefile. I promise, this stuff all worked when I wrote it :)

**Review by slaren — APPROVED** [review]
This seems to fix it.

**Comment by slaren** [comment]
I noticed that with `make` builds, `NDEBUG` is no longer defined in CUDA builds, even without `LLAMA_DEBUG`. I think that passing the preprocessor defines to `nvcc` with `-Xcompiler` doesn't work, and should be passed directly to `nvcc` instead. What would be the best way to do? From what I understand, the preprocessor defined are already separately defined in `CPPFLAGS`, so this should be doable without major changes.

**Comment by cebtenzzre** [comment]
> I think that passing the preprocessor defines to `nvcc` with `-Xcompiler` doesn't work, and should be passed directly to `nvcc` instead.

#5598

**Pull request merged**
