### PR TITLE
bug-fix: snprintf prints NULL in place of the last character

### PR DESCRIPTION
**Pull request by kallewoof**
We need to give snprintf enough space to print the last character **and** the `null` character, thus we allocate one extra byte and then ignore it when converting to std::string.

```C++
char buf[5];
snprintf(buf, 5, "hello");
printf("%s", buf); // -> hell\0
```

Because of this, when copying the C string into the `std::string`, we get a `\u0000` at the end of it, [which can cause issues](https://github.com/SillyTavern/SillyTavern/blob/4214c9d8940ac34ee866d87dbb342d39083a8a79/src/endpoints/backends/text-completions.js#L256-L259).

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by ngxson** [comment]
@slaren The return value of `snprintf` excludes the terminating null byte. Should we add one byte before returning from `llama_model_meta_val_str`, or it's up to the user?

In anyway, I think we should leave a comment in `llama.h` to clarify this behavior.

**Comment by kallewoof** [comment]
To be honest, this should be passed a pointed-to `std::string` and write to that. This complexity seems completely unnecessary.

**Comment by kallewoof** [comment]
I pushed an alternative PR in #10424 which simplifies the interface but requires a `free()` call.

**Comment by slaren** [comment]
> Should we add one byte before returning from `llama_model_meta_val_str`, or it's up to the user?

It's up to the user. They do not need to use NUL-termianted strings.

**Review by slaren — APPROVED** [review]

**Comment by kallewoof** [comment]
Unless there are architecture subtleties that I'm not aware of, I think #10430 is a cleaner solution, but keeping both up until a judgement is made.

**Comment by ngxson** [comment]
Should we also apply this patch to every places where `llama_chat_apply_template` is called? (We don't have many of those)

**Comment by kallewoof** [comment]
> Should we also apply this patch to every places where `llama_chat_apply_template` is called? (We don't have many of those)

I looked and it doesn't seem like it is affected since the allocated buffer is basically guaranteed to be bigger than the chat template (including NULL term).

**Comment by ngxson** [comment]
Sorry I mean changing all other places using `llama_model_meta_val_str`

**Comment by kallewoof** [comment]
> Sorry I mean changing all other places using `llama_model_meta_val_str` (there is one inside `llama_chat_apply_template` IIRC)

Right -- the only other place is in [server.cpp](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/server.cpp) specifically in 

https://github.com/ggerganov/llama.cpp/blob/a5e47592b6171ae21f3eaa1aba6fb2b707875063/examples/server/server.cpp#L663-L674

but this code only uses it to check if the key is present, and then uses `llama_chat_apply_template`.

**Comment by kallewoof** [comment]
@slaren Is there something I can do to accelerate this very tiny fix?

**Comment by slaren** [comment]
Sorry, forgot to merge this.

**Pull request merged**
