### PR TITLE
ADD Chatbot UI example

### PR DESCRIPTION
**Pull request by bhubbb**
This example makes use of three projects [llama.cpp](https://github.com/ggerganov/llama.cpp), [gpt-llama.cpp](https://github.com/keldenl/gpt-llama.cpp) and [Chatbot UI](https://github.com/mckaywrigley/chatbot-ui) to provide a ChatGPT UI like experience with llama.cpp.

Let me know if there are some improvements I can make to the Dockerfile and compose.yaml.

### CODE REVIEW

**Comment by slaren** [comment]
This looks like an interesting project, but since there is no code here that shows how to use llama.cpp, I am not sure that it should be in this repository as one of the examples. It would make more sense as an example of gpt-llama.cpp, or even as a standalone project. Maybe we could add a "related projects" section to the README or the wiki and link it there?

**Comment by bhubbb** [comment]
If this is the wrong spot for this, I don't mind. I wanted to share this setup as a simpler alternative to the other UIs. 

Did you want me to close the PR?

**Comment by slaren** [comment]
Don't close it yet, this is just my opinion.

**Comment by ggerganov** [comment]
We now have web UI via the `server` example

**Pull request closed without merging**
