### PR TITLE
grammars : add English-only grammar

### PR DESCRIPTION
**Pull request by ggerganov**
Example:

```bash
# without grammar
./bin/llama-server -m ../models/qwen2.5-32b-instruct/ggml-model-q8_0.gguf

curl --request POST --url http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer no-key" -d "$(jq -n '{ messages: [{ role: "system", content: "You are a helpful assistant." }, { role: "user", content: "How to say \"Good morning\" in Chinese?" }], "top_k": 1 }')" | jq -r .choices[0].message.content

# To say "Good morning" in Chinese, you can say:
# 
# **早晨好** (zǎo chén hǎo)
# 
# or more commonly:
# 
# **早上好** (zǎo shàng hǎo)
# 
# Both phrases are used to greet someone in the morning.
```

```bash
# with English-only grammar
./bin/llama-server -m ../models/qwen2.5-32b-instruct/ggml-model-q8_0.gguf --grammar-file ../grammars/english.gbnf

curl --request POST --url http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer no-key" -d "$(jq -n '{ messages: [{ role: "system", content: "You are a helpful assistant." }, { role: "user", content: "How to say \"Good morning\" in Chinese?" }], "top_k": 1 }')" | jq -r .choices[0].message.content

# To say "Good morning" in Chinese, you can say " mornings" which is pronounced as "zao3 shang4" (the numbers represent the tone).
```

### CODE REVIEW

**Comment by jukofyork** [comment]
I'm on my phone now and the Unicode codepage characters doesn't seem to be showing up:

```
--grammar "root ::= [^一-鿿]*"
```
See: https://old.reddit.com/r/LocalLLaMA/comments/1cdj2uo/qwen15110b_the_first_100b_model_of_the_qwen15/

```
--grammar "root ::= [^一-鿿ぁ-ゟァ-ヿ가-힣]*" 
```
See: https://old.reddit.com/r/LocalLLaMA/comments/1bwjmoo/qwen1532b_released_with_gqa/

But is there a way to block ranges of Unicode characters like these examples? The new `QwQ` model seems to randomly switch to using Cyrillic and Arabic characters too?!

**Comment by ggerganov** [comment]
I'm not sure. This PR is mainly to demonstrate that the grammar works and can be used in such ways. If it does not support the specific case that you need, add a feature request and someone might implement it.

**Comment by jukofyork** [comment]
> I'm not sure. This PR is mainly to demonstrate that the grammar works and can be used in such ways. If it does not support the specific case that you need, add a feature request and someone might implement it.

No problem - I'll do some experiments with the `^` option when I get back.

**Comment by ExtReMLapin** [comment]
People should keep in mind that they need to adjust the prompt when using this kind of restrictive grammar.

Because the LLM might "advance" into a direction now knowing it will not be able to output some tokens and it will lead to sub-optimal outpute.

A solution would also be to use beam search (batched beam search maybe)

**Comment by jukofyork** [comment]
I've found a problem with this as it doesn't allow the output of double newlines (which a lot of models love to use).

This is what I am using now with `QwQ`:

```
root        ::= (en-char | whitespace)*
en-char     ::= letter | digit | punctuation
letter      ::= [a-zA-Z]
digit       ::= [0-9]
punctuation ::= [!"#$%&'()*+,-./:;<=>?@[\\\]^_`{|}~]
whitespace  ::= [ \t\n]
```

and even when asked "to think in Chinese" it works.

**Comment by jukofyork** [comment]
### User

Can you teach me some Chinese characters?

### QwQ

Of course! Learning Chinese characters can be fun and rewarding. Let's start with some basic characters to get you familiar with the structure and principles behind them.

First, it's important to understand that Chinese characters, also known as Hanzi, are logograms, meaning each character represents a word or a morpheme (a meaningful unit of language). They are not purely phonetic, so learning them involves understanding both their meaning and pronunciation.

Let's begin with some fundamental characters that are commonly used in everyday language.

1. **Person ( person )**

   - Pinyin: REN2 (pronounced "ruhn")

   - Meaning: person, people

   - Stroke order: Start with a horizontal stroke, then a vertical stroke, and finally another horizontal stroke.

     - Horizontal (---)

     - Vertical (|)

     - Horizontal (---)

   - Example usage:  people (REN2 MIN2)

2. **Mountain ( mountain )**

   - Pinyin: SHAN1 (pronounced "shahn")

   - Meaning: mountain

   - Stroke order: Three horizontal strokes with vertical strokes in between.

     - Horizontal (---)

     - Vertical then horizontal (| ---)

     - Vertical then horizontal (| ---)

   - Example usage:  mountain (SHAN1)

3. **Tree ( tree )**

   - Pinyin: MU4 (pronounced "muh")

   - Meaning: tree, wood

   - Stroke order: Start with a slanted stroke, then a vertical stroke, and finish with a horizontal stroke on the bottom.

     - Slanted stroke (/)

     - Vertical stroke (|)

     - Horizontal stroke (---)

   - Example usage:  forest (LIN2)

4. **Sun ( sun )**

   - Pinyin: RI4 (pronounced "ree")

   - Meaning: sun, day

   - Stroke order: Start with an outer square, then a horizontal stroke in the middle, and finally a horizontal stroke on the bottom.

     - Start with a horizontal stroke (---), then a vertical stroke (|), then another horizontal stroke (---) to close the top.

     - Horizontal stroke in the middle (---)

     - Horizontal stroke on the bottom (---)

   - Example usage:  today (JIN1TIAN1)

**Pull request merged**
