### PR TITLE
ggml: unify backend logging mechanism

### PR DESCRIPTION
**Pull request by mtmcp**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

This change updates the GGML logging mechanism so all back-ends may share the same logger. Please see issue #9706 and some initial discussion #8830.

Although there is some minor duplication in the llama.cpp (llama_logger_state) and ggml.c (ggml_logger_state), it is required in order to keep these libraries internal details isolated.

### CODE REVIEW

**Comment by bandoti** [comment]
@slaren
In light of #9707 changes to the logging backend, I will need your advice on what needs to change or not in this PR. Should I simply rip out all the logging mechanisms added in #9707?

**Comment by slaren** [comment]
Yes, just remove the `set_log_callback` function ptr from `ggml_backend_reg_i` and all its uses. I wasn't sure when this PR would be complete so I left it there, but it can removed if it is no longer necessary.

**Comment by bandoti** [comment]
Sounds good. I'll brandish my hatchet (emacs) and start chopping away! 😅

**Review by slaren — APPROVED** [review]

**Comment by slaren** [comment]
Let's merge this before adapting more backends to the registry interface to avoid creating more conflicts.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
