### PR TITLE
server tests : more pythonic process management; fix bare `except:`

### PR DESCRIPTION
**Pull request by cebtenzzre**
ref https://github.com/ggerganov/llama.cpp/pull/6098#discussion_r1528946085

This code has been consistently confusing to me. Here I suggest a few simplifications:

- Don't add an extra `\n` to a random selection of `print()`s. A habit from C perhaps? Let me know if any (or all) of these are intentional - it just looked strange to me to have a blank line after so many prints.
- I changed the process management code in the server tests to use built-in subprocess functions instead of os.kill or psutil.
- Before we were sending SIGINT, waiting 50ms, then sending SIGKILL in a loop, and after several tries also sending SIGKILL with both native Python and psutil at the same time. This seems really odd to me, so I changed it to just send SIGKILL if SIGINT didn't kill the process after 500ms. Maybe Popen.terminate() was intended as the second stage of killing, but this will have the same effect as SIGKILL for the server process, even on Unix, as it is not explicitly handled via sigaction.
- I also fixed the neighboring `except:` clause - it's wrong to ignore exceptions like KeyboardInterrupt and SystemExit, so I changed it to `except Exception:`. And `traceback.print_exc` seemed more appropriate here.

### CODE REVIEW

**Review by phymbert — CHANGES_REQUESTED** [review]
Probably better code but the build failed... maybe you must test it before

**Comment by cebtenzzre** [comment]
I was able to run the tests locally after making the connect routine match what the server does - it uses the first address family returned by getaddrinfo, whether it is ipv4 or ipv6. Otherwise, the connection failed because the server was listening on `::1` and the client was trying to connect to `127.0.0.1`.

**Comment by phymbert** [comment]
> Otherwise, the connection failed because the server was listening on `::1` and the client was trying to connect to `127.0.0.1`.

There is a hack on windows server test to force the server to listen 0.0.0.0. But it's probably not the same issue you faced with ipv6

**Review by phymbert — APPROVED** [review]
Thanks for looking into this, your contribution on server tests is highly appreciated :+1: 
If you don't mind I will request your review on changes related to python server tests.

I have included fixes for:
 - #6127

All tests are now working and the python code is clearer, great!

**Pull request merged**
