### PR TITLE
convert : handle tokenizer merges format from transformers 4.45

### PR DESCRIPTION
**Pull request by compilade**
As noted in #9692, `transformers 4.45` introduces a new serialization for merges, which is a list of 2 strings instead of a single string with 2 space-separated parts.

This needs to be handled in `gguf-py/gguf/vocab.py`, because `gguf.SpecialVocab(dir_model, load_merges=True)` otherwise ignores the merges with a warning:

```
WARNING:gguf.vocab:Adding merges requested but no merges found, output may be non-functional.
```

Note that this is only a problem when there is no `merges.txt`, so it *should* be reproducible with <https://huggingface.co/pcuenq/Llama-3.2-1B-Instruct-tokenizer>, but not with <https://huggingface.co/pcuenq/Qwen2.5-0.5B-Instruct-with-new-merges-serialization> unless `merges.txt` is renamed or removed.

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Review by Vaibhavs10 — COMMENTED** [review]
Nice catch! I didn't even think about going down this path to check! 🔥

**Comment by pcuenca** [comment]
What's the reproduction flow? I just pushed the tokenizer to https://huggingface.co/pcuenq/Llama-3.2-1B-Instruct-tokenizer but I have a local copy with the model as well, and it converts successfully using `convert_hf_to_gguf.py` – no `merges.txt` in the directory.

**Comment by pcuenca** [comment]
Is it only failing for sentencepiece-based tokenizers?

**Comment by compilade** [comment]
@pcuenca This isn't about failure, but about warnings and missing `tokenizer.ggml.merges`.

When taking `<https://huggingface.co/pcuenq/Llama-3.2-1B-Instruct-tokenizer>` and converting it with `python3 convert_hf_to_gguf.py --vocab-only /path/to/model_dir` from `master`, I get

```
WARNING:gguf.vocab:Adding merges requested but no merges found, output may be non-functional.
```

And with `gguf-dump`:

```
     23: STRING     |        1 | tokenizer.ggml.model = 'gpt2'
     24: STRING     |        1 | tokenizer.ggml.pre = 'llama-bpe'
     25: [STRING]   |   128256 | tokenizer.ggml.tokens
     26: [INT32]    |   128256 | tokenizer.ggml.token_type
     27: UINT32     |        1 | tokenizer.ggml.bos_token_id = 128000
     28: UINT32     |        1 | tokenizer.ggml.eos_token_id = 128009
```

But when I convert it from this branch, I get

```
INFO:gguf.vocab:Adding 280147 merge(s).
```

And in the dump:

```
     23: STRING     |        1 | tokenizer.ggml.model = 'gpt2'
     24: STRING     |        1 | tokenizer.ggml.pre = 'llama-bpe'
     25: [STRING]   |   128256 | tokenizer.ggml.tokens
     26: [INT32]    |   128256 | tokenizer.ggml.token_type
     27: [STRING]   |   280147 | tokenizer.ggml.merges
     28: UINT32     |        1 | tokenizer.ggml.bos_token_id = 128000
     29: UINT32     |        1 | tokenizer.ggml.eos_token_id = 128009
```

Notice that the `tokenizer.ggml.merges` field is only present when properly handling the new format, at least when it's in use by `tokenizer.json`.

> Is it only failing for sentencepiece-based tokenizers?

No, since those don't have `merges`, only BPE tokenizers do.

**Comment by pcuenca** [comment]
I was considering those warnings failures, as the resulting model could not be used for generation. But I was not seeing them, and thus I was very confused. I have been able to reproduce the issue now with a local copy of Llama 3.1, but both Llama 3.2 and Llama 2 worked fine for me in my tests (with the tokenizer exported using the new format in all three cases).

> No, since those don't have merges, only BPE tokenizers do.

True, but I was reading the code and trying to guess when the code path would trigger.

I'll debug more closely to try to understand why it worked with Llama 3.2 and not with Llama 3.1. Thanks!

**Review by pcuenca — APPROVED** [review]

**Comment by farris** [comment]
Can this be merged... please

**Review by xmaayy — APPROVED** [review]

**Comment by xmaayy** [comment]
@farris I can confirm that just cloning this branch and running the conversion works without any other modifications and the resulting models are immediately usable by llama.cp \ `ollama` or any other GGUF compatible service

**Pull request merged**
