### PR TITLE
tests : add test-tokenizer-0.sh

### PR DESCRIPTION
**Pull request by ggerganov**
Add more extensive tokenizer test that takes a text file, tokenizes it using `transformers` and `llama.cpp` and compares the results.

```bash
# run once
python3 convert-hf-to-gguf-update.py <hf_token>

# tests OK
./tests/test-tokenizer-0.sh llama-spm ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh llama-bpe ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh gpt-2     ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh phi-3     ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh starcoder ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh falcon    ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh refact    ./build/wikitext-2-raw/wiki.train.raw

# tests Fail
./tests/test-tokenizer-0.sh deepseek-llm   ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh deepseek-coder ./build/wikitext-2-raw/wiki.train.raw
./tests/test-tokenizer-0.sh mpt            ./build/wikitext-2-raw/wiki.train.raw
```

Need to find the reason why the tokenization differs in the Fail cases. For example, DeepSeek models fail like this:

```bash
make -j tests/test-tokenizer-0 && ./tests/test-tokenizer-0 ./models/ggml-vocab-deepseek-coder.gguf

src: 'Führer'
res: 'Führer'
tok: 37 2864 71 6247 
main : failed test:    'Führer'
main : detokenized to: 'Führer' instead of 'Führer'
main : expected tokens:     37 'F',  32009 'ü',     71 'h',   6247 'rer', 
main : got tokens:          37 'F',   2864 'ü',     71 'h',   6247 'rer', 
```

Added script for generating the unicode ranges in `unicode-data.cpp`:

```bash
python3 scripts/gen-unicode-data.py
```

### CODE REVIEW

**Comment by ggerganov** [comment]
I think there is a bug in the way we handle added tokens. I'm experimenting with DeepSeek-Coder:

https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base

`llama.cpp` tokenizes `ü` to 2864 which is OK, but there is also the added token 32009 which `transformers` tokenizer selects instead:

```json
    {
      "id": 32009,
      "content": "ü",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": true,
      "special": false
    },
```

If I remove this added token from the `tokenizer.config` then the `transformers` tokenization also outputs 2864. So this means we are not handling the added tokens in the same way.

Any ideas how to fix this?

**Comment by CISC** [comment]
> If I remove this added token from the `tokenizer.config` then the `transformers` tokenization also outputs 2864. So this means we are not handling the added tokens in the same way.

I believe the issue is [this](https://github.com/huggingface/transformers/blob/425e1a0426c8da23a00c456fd69745a1b3e6db5f/src/transformers/tokenization_utils.py#L656), added tokens are always looked up first.

**Comment by ggerganov** [comment]
From what I've found, the problem seem to be that as part of the pre-tokenization, we perform some byte-to-unicode mapping here:

https://github.com/ggerganov/llama.cpp/blob/3275e60f575fb1141e4706da2e9dc810d7d47457/unicode.cpp#L213-L217

https://github.com/ggerganov/llama.cpp/blob/3275e60f575fb1141e4706da2e9dc810d7d47457/unicode.cpp#L151-L173

This converts the string `ü` to the string `Ã¼`. This new string is exactly the token 2864, which detokenizes to `ü` via the `llama_decode_text()` function. The problem is that we don't even consider the token 32009, because `ü` is not present in the pre-tokenized string.

**Comment by teleprint-me** [comment]
Why is the upper limit set to 256? Isn't that the ASCII range? 

The range of valid Unicode code points is from [U+0000 (hexadecimal 0) to U+1FFFFF (hexadecimal FFFF)](https://en.wikipedia.org/wiki/List_of_Unicode_characters), which covers [more than 1 million unique characters](https://en.wikipedia.org/wiki/Unicode).

**Comment by ggerganov** [comment]
> Why is the upper limit set to 256? Isn't that the ASCII range?

This seems to be some strategy to reduce the vocab size:

https://github.com/openai/gpt-2/blob/master/src/encoder.py#L8-L28

**Comment by teleprint-me** [comment]
I find it fascinating how we have a tendency to over-complicate simple ideas. I'm all too guilty of this myself.

```python
# simplified function definition
import string
# >>> string.printable
# '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'
def bytes_to_unicode():
    mapping = {}
    for i in list(range(256)):
        if chr(i) in string.printable:
            mapping[i] = chr(i)
        else:
            mapping[i] = chr(256+i)
    return mapping
```

<details>
<summary>output</summary>

```python
>>> pprint(mapping)
{0: 'Ā',
 1: 'ā',
 2: 'Ă',
 3: 'ă',
 4: 'Ą',
 5: 'ą',
 6: 'Ć',
 7: 'ć',
 8: 'Ĉ',
 9: '\t',
 10: '\n',
 11: '\x0b',
 12: '\x0c',
 13: '\r',
 14: 'Ď',
 15: 'ď',
 16: 'Đ',
 17: 'đ',
 18: 'Ē',
 19: 'ē',
 20: 'Ĕ',
 21: 'ĕ',
 22: 'Ė',
 23: 'ė',
 24: 'Ę',
 25: 'ę',
 26: 'Ě',
 27: 'ě',
 28: 'Ĝ',
 29: 'ĝ',
 30: 'Ğ',
 31: 'ğ',
 32: ' ',
 33: '!',
 34: '"',
 35: '#',
 36: '$',
 37: '%',
 38: '&',
 39: "'",
 40: '(',
 41: ')',
 42: '*',
 43: '+',
 44: ',',
 45: '-',
 46: '.',
 47: '/',
 48: '0',
 49: '1',
 50: '2',
 51: '3',
 52: '4',
 53: '5',
 54: '6',
 55: '7',
 56: '8',
 57: '9',
 58: ':',
 59: ';',
 60: '<',
 61: '=',
 62: '>',
 63: '?',
 64: '@',
 65: 'A',
 66: 'B',
 67: 'C',
 68: 'D',
 69: 'E',
 70: 'F',
 71: 'G',
 72: 'H',
 73: 'I',
 74: 'J',
 75: 'K',
 76: 'L',
 77: 'M',
 78: 'N',
 79: 'O',
 80: 'P',
 81: 'Q',
 82: 'R',
 83: 'S',
 84: 'T',
 85: 'U',
 86: 'V',
 87: 'W',
 88: 'X',
 89: 'Y',
 90: 'Z',
 91: '[',
 92: '\\',
 93: ']',
 94: '^',
 95: '_',
 96: '`',
 97: 'a',
 98: 'b',
 99: 'c',
 100: 'd',
 101: 'e',
 102: 'f',
 103: 'g',
 104: 'h',
 105: 'i',
 106: 'j',
 107: 'k',
 108: 'l',
 109: 'm',
 110: 'n',
 111: 'o',
 112: 'p',
 113: 'q',
 114: 'r',
 115: 's',
 116: 't',
 117: 'u',
 118: 'v',
 119: 'w',
 120: 'x',
 121: 'y',
 122: 'z',
 123: '{',
 124: '|',
 125: '}',
 126: '~',
 127: 'ſ',
 128: 'ƀ',
 129: 'Ɓ',
 130: 'Ƃ',
 131: 'ƃ',
 132: 'Ƅ',
 133: 'ƅ',
 134: 'Ɔ',
 135: 'Ƈ',
 136: 'ƈ',
 137: 'Ɖ',
 138: 'Ɗ',
 139: 'Ƌ',
 140: 'ƌ',
 141: 'ƍ',
 142: 'Ǝ',
 143: 'Ə',
 144: 'Ɛ',
 145: 'Ƒ',
 146: 'ƒ',
 147: 'Ɠ',
 148: 'Ɣ',
 149: 'ƕ',
 150: 'Ɩ',
 151: 'Ɨ',
 152: 'Ƙ',
 153: 'ƙ',
 154: 'ƚ',
 155: 'ƛ',
 156: 'Ɯ',
 157: 'Ɲ',
 158: 'ƞ',
 159: 'Ɵ',
 160: 'Ơ',
 161: 'ơ',
 162: 'Ƣ',
 163: 'ƣ',
 164: 'Ƥ',
 165: 'ƥ',
 166: 'Ʀ',
 167: 'Ƨ',
 168: 'ƨ',
 169: 'Ʃ',
 170: 'ƪ',
 171: 'ƫ',
 172: 'Ƭ',
 173: 'ƭ',
 174: 'Ʈ',
 175: 'Ư',
 176: 'ư',
 177: 'Ʊ',
 178: 'Ʋ',
 179: 'Ƴ',
 180: 'ƴ',
 181: 'Ƶ',
 182: 'ƶ',
 183: 'Ʒ',
 184: 'Ƹ',
 185: 'ƹ',
 186: 'ƺ',
 187: 'ƻ',
 188: 'Ƽ',
 189: 'ƽ',
 190: 'ƾ',
 191: 'ƿ',
 192: 'ǀ',
 193: 'ǁ',
 194: 'ǂ',
 195: 'ǃ',
 196: 'Ǆ',
 197: 'ǅ',
 198: 'ǆ',
 199: 'Ǉ',
 200: 'ǈ',
 201: 'ǉ',
 202: 'Ǌ',
 203: 'ǋ',
 204: 'ǌ',
 205: 'Ǎ',
 206: 'ǎ',
 207: 'Ǐ',
 208: 'ǐ',
 209: 'Ǒ',
 210: 'ǒ',
 211: 'Ǔ',
 212: 'ǔ',
 213: 'Ǖ',
 214: 'ǖ',
 215: 'Ǘ',
 216: 'ǘ',
 217: 'Ǚ',
 218: 'ǚ',
 219: 'Ǜ',
 220: 'ǜ',
 221: 'ǝ',
 222: 'Ǟ',
 223: 'ǟ',
 224: 'Ǡ',
 225: 'ǡ',
 226: 'Ǣ',
 227: 'ǣ',
 228: 'Ǥ',
 229: 'ǥ',
 230: 'Ǧ',
 231: 'ǧ',
 232: 'Ǩ',
 233: 'ǩ',
 234: 'Ǫ',
 235: 'ǫ',
 236: 'Ǭ',
 237: 'ǭ',
 238: 'Ǯ',
 239: 'ǯ',
 240: 'ǰ',
 241: 'Ǳ',
 242: 'ǲ',
 243: 'ǳ',
 244: 'Ǵ',
 245: 'ǵ',
 246: 'Ƕ',
 247: 'Ƿ',
 248: 'Ǹ',
 249: 'ǹ',
 250: 'Ǻ',
 251: 'ǻ',
 252: 'Ǽ',
 253: 'ǽ',
 254: 'Ǿ',
 255: 'ǿ'}
```

</details>

The Extended ASCII Character set displayed here will include a variety of similar looking characters which are _nearly_ visually indistinguishable without referring to their byte-paired counterparts.

```python
 250: 'ú',
 251: 'û',
 252: 'ü',
```

I'm looking into it though.

**Comment by DOGEwbx** [comment]
> I think there is a bug in the way we handle added tokens. I'm experimenting with DeepSeek-Coder:
> 
> https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base
> 
> `llama.cpp` tokenizes `ü` to 2864 which is OK, but there is also the added token 32009 which `transformers` tokenizer selects instead:
> 
> ```json
>     {
>       "id": 32009,
>       "content": "ü",
>       "single_word": false,
>       "lstrip": false,
>       "rstrip": false,
>       "normalized": true,
>       "special": false
>     },
> ```
> 
> If I remove this added token from the `tokenizer.config` then the `transformers` tokenization also outputs 2864. So this means we are not handling the added tokens in the same way.
> 
> Any ideas how to fix this?
@ggerganov 

Hi, I found that current llama.cpp can not pass the unit tests for deepseek models. The problem you mentioned looks like the issue huggingface tokenizers have solved https://github.com/huggingface/tokenizers/issues/1392

for the newly published deepseek v2 and deepseekcoder v1.5, these added tokens are removed.

**Comment by ggerganov** [comment]
@DOGEwbx Thanks - will try deepseek-coder v1.5 then. DS v2 will probably take some time to support #7118

**Pull request merged**
