### PR TITLE
Add `--simple-io option` for subprocesses and separate console to it's own header and cpp

### PR DESCRIPTION
**Pull request by DannyDaemonic**
`--simple-io` uses only basic io functions that work when main is run as a subprocess. This fixes issues with child processes such as those seen in #1547 and #1491. It also happens to be a work around for #1382 by allowing people to switch back to the basic IO for use with Windows Terminal history (that lets you press up and down to scroll through your history).

The number of lines changed is actually not as big as it looks, but the console stuff was half the size of the common.cpp file so I broke it out into its own cpp and header file.

Edit:
[Confirmed fix](https://github.com/ggerganov/llama.cpp/pull/1491#issuecomment-1564798020) for #1491.
[Confirmed fix](https://github.com/ggerganov/llama.cpp/issues/1547#issuecomment-1570241471) for #1547.
[Confirmed fix](https://github.com/ggerganov/llama.cpp/pull/2477#issuecomment-1664006669) for #2477.

### CODE REVIEW

**Review by mirek190 — APPROVED** [review]

**Review by mirek190 — APPROVED** [review]

**Comment by spencekim** [comment]
This would be very useful for my use-case of running in node. Is there an update on this?

**Comment by spencekim** [comment]
Thanks, looking forward to it! I saw this related issue, which is exactly my use case: https://github.com/ggerganov/llama.cpp/pull/1491

**Review by mirek190 — COMMENTED** [review]
Looks legit

**Comment by spencekim** [comment]
Don't mean to be a bother, but is there a path to getting this merged into master?

**Comment by DannyDaemonic** [comment]
Seeing as how people are still hitting the old subprocess issue, I've rebased this patch. I've also got other UI improvements I'd love to put through. I think technically you're supposed to put each group of changes in separate PRs but seeing as how few people like to review this sort of admittedly boring change, perhaps I should just make one larger PR that includes all the stuff at once sort of how the large server rewrite was done?

The only other thing noteworthy in this particular patch is the namespace. I put console in it's own namespace since there are a growing number of global utf and console functions. This also moves the global struct to console.o instead of main.o -- since you only ever have one console, there's no point in making someone declare a status tracking structure. (Other console libraries such as ncurses do the same thing.)

Given it's been a little while, I'd like to briefly restate the goals in the direction of these changes: to simplify `main` by moving the implementation of console interactions out of main.cpp, and make user interactions more intuitive (so we can move away from the sole use of `Ctrl-C` for example). And all while adhering to the no-additional-libraries rule.

**Comment by mirek190** [comment]
Have to wait for this one sooo much time ... Thank you.

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Can’t test this at the moment but I think it is OK to merge

**Comment by DannyDaemonic** [comment]
Thanks. If it helps, I'm pretty good about bug reports related to my code. Even if I'm working on a paid job.

**Comment by mirek190** [comment]
--simple-io - win 11 - powershell console is not responding.
I can't enter any text - only cltl+c works.

**Comment by DannyDaemonic** [comment]
Is this on the official release?

**Comment by DannyDaemonic** [comment]
I vaguely remembered seeing this before, and then I remembered, it was with this project! I was having trouble with powershell before I ever touched the io code. I downloaded an [old version of llama.cpp](https://github.com/ggerganov/llama.cpp/releases/tag/master-f9a6364), from before I changed any console code at all, and it has the same problem with powershell.

I just think no one uses the wide character versions of these functions. Let me see if I can come up with something.

**Comment by DannyDaemonic** [comment]
@mirek190
This was a weird one. I realized if you open a new terminal and the very first thing you do is run `main`, simple io works! The problem is modes are persistent in Windows 11 powershell. This was not the case in the old command prompt. Other programs can set this value and it will affect ours. For now the work around is to make sure it's the first (and only program) you run when you open a windows powershell terminal

**Comment by DannyDaemonic** [comment]
Fixed with #2521. I hope it won't take long to get through. Again, in the meantime, just run main as the first program in your powershell instance. If you run other commands or `--simple-io` stops working for other reasons, you can just start a new powershell instance.

**Comment by mirek190** [comment]
Is working now .
Thanks

**Pull request merged**
