### PR TITLE
Added server example themes support with two sample themes and a favicon.

### PR DESCRIPTION
**Pull request by jboero**
I've always thought the `--path` flag could be used to support basic UI themes and also thought it should have a favicon.  I've added these and tested them out. Have a look.

### CODE REVIEW

**Comment by jboero** [comment]
Fixed whitespace

**Comment by jboero** [comment]
image

**Comment by jboero** [comment]
Ugh an issue with the build environment seems to be killing these Actions.

https://github.com/ggerganov/llama.cpp/actions/runs/8859670654/job/24329697021#step:7:116

**Comment by jboero** [comment]
I think an update to our Actions environment is actually blocking these. Anybody else hitting this error?
https://github.com/ggerganov/llama.cpp/issues/6422

**Comment by jboero** [comment]
@ggerganov did something change in testing automation? This PR is purely additive and shouldn't break anything else but automation keeps tripping on the same error as this python 3.12 support issue.

https://github.com/ggerganov/llama.cpp/issues/6422

**Comment by ggerganov** [comment]
I think you need to rebase on latest `master` - there were some changes to the CI that are missing in this PR as it is

Btw, it seems the themes are copy-pasting the `.js/.html` code. Can this be avoided?
Otherwise, making a change to the frontend would have to be replicated across all themes - does not sound OK

**Comment by jboero** [comment]
> Otherwise, making a change to the frontend would have to be replicated across all themes - does not sound OK

I thought about symlinks for unchanged files but then there is the opposite problem. Changing one theme affects and/or breaks the other themes. I thought these were copied examples. What would you propose?

**Comment by jboero** [comment]
@ggerganov any bump on this? Since the UI is effectively rendered completely using the contents of the public folder it makes sense to me to change copies for themes and just use `--path ./theme_dir`

**Comment by ggerganov** [comment]
Let's give this a try, but first remove the following files from the themes:

- `index.js`
- `completion.js`
- `json-schema-to-grammar.mjs`

Since these are unchanged, they will be served from the static contents embedded in the `server` app:

https://github.com/ggerganov/llama.cpp/blob/947d3ad27d94f1addef76b5d64c314618f063933/examples/server/server.cpp#L3729-L3735

Also rename all files that have underscore to use a dash for consistency

**Comment by jboero** [comment]
Sloppy commits but done.  Thanks @ggerganov

**Comment by scottstirling** [comment]
How are folks gonna customize browser presentation code buried in the C++ binary?  Or is the point to hinder that?

Every tweak to the UI will require a make to compile reload and test, defeating the utility & practicality of externalized user interface code.

**Comment by jboero** [comment]
> Every tweak to the UI will require a make to compile reload and test, defeating the utility & practicality of externalized user interface code.

By separating the UI elements (`--path [UIDIR]`) and having the UI simply map to the API I don't think there is much to worry about. The static strings that become defaults in the C++ can simply be overridden by placing your file in the `--path` directory at runtime. Simple but effective actually or am I misunderstanding your predicament?

**Comment by scottstirling** [comment]
Thanks for the clarification.  I will pull the change and give it a try.

**Pull request merged**
