### PR TITLE
Vulkan Phi Fix for AMD Proprietary Drivers

### LINKED ISSUE #5243: Phi-2 completely broken on Vulkan
I get garbage output when offloading any layer to GPU when running Phi-2 models with the Vulkan backend. The issue seems to be with the first and last layers mostly.

### `.\buildVulkan\bin\Release\main.exe -m .\models\phi\phi-2.Q4_K_M.gguf -t 12 -tb 6 -p "Here is a reciepe for tomato soup:\n" -e -s 0 --temp 0 -n 128 -ngl X`

(main: build = 2035 (7977a2a0))

#### `-ngl 0` (control)

```
Here is a reciepe for tomato soup:

Ingredients:
- 4 cups of chicken broth
- 2 tablespoons of butter
- 1 onion, chopped
- 2 cloves of garlic, minced
- 2 tomatoes, peeled and diced
- Salt and pepper to taste
- Parsley for garnish

Directions:
- In a large pot, melt the butter over medium heat. Add the onion and garlic and cook until soft, about 10 minutes.
- Stir in the chicken broth and bring to a boil. Reduce the heat and simmer for 15 minutes, stirring occasionally.
- Add the tomatoes and season with salt and pepper. Cook for another 10 minutes,
llama_print_timings:        load time =     329.52 ms
llama_print_timings:      sample time =      29.20 ms /   128 runs   (    0.23 ms per token,  4382.96 tokens per second)
llama_print_timings: prompt eval time =     310.37 ms /    11 tokens (   28.22 ms per token,    35.44 tokens per second)
llama_print_timings:        eval time =    8578.80 ms /   127 runs   (   67.55 ms per token,    14.80 tokens per second)
llama_print_timings:       total time =    8949.84 ms /   138 tokens
Log end
```

#### `-ngl 1`

```
Here is a reciepe for tomato soup:

Ingredients:- "
 [end of text]

llama_print_timings:        load time =     641.73 ms
llama_print_timings:      sample time =       1.47 ms /     7 runs   (    0.21 ms per token,  4768.39 tokens per second)
llama_print_timings: prompt eval time =     312.33 ms /    11 tokens (   28.39 ms per token,    35.22 tokens per second)
llama_print_timings:        eval time =     666.72 ms /     6 runs   (  111.12 ms per token,     9.00 tokens per second)
llama_print_timings:       total time =     983.36 ms /    17 tokens
Log end
```
Starts ok, but glitches after a few tokens generated. (in this case it generated an eos token, so it ended the generation early, but with a different prompt/higer temp, the output is just noisy gibberish)
<details>
<summary>  using `-p "Here is a reciepe for tomato soup:\n\n"` </summary>

```
Here is a reciepe for tomato soup:

 - "Tomato SOUP
 Mince 1 onion and 2 cloves of garlic in a large pot over medium heat. Dump in 4 B cans of crushed tomatoes Pinch TThe----------------------------- "-- SOUP
 Mince 1 onion and 2 cloves of garlic in a large pot over medium heat. Dump in 4 B cans of crushed tomatoes Pinch TThe-------------------------
 ```
</details>

#### `-ngl 2`

```
Here is a reciepe for tomato soup:

- " S M D B P TThe-------------------------------------------------------
- " S M D B P TThe-----------------------------------------------------
llama_print_timings:        load time =     562.83 ms
llama_print_timings:      sample time =      27.43 ms /   128 runs   (    0.21 ms per token,  4665.91 tokens per second)
llama_print_timings: prompt eval time =     304.00 ms /    11 tokens (   27.64 ms per token,    36.18 tokens per second)
llama_print_timings:        eval time =    8149.43 ms /   127 runs   (   64.17 ms per token,    15.58 tokens per second)
llama_print_timings:       total time =    8507.07 ms /   138 tokens
Log end
```

(ngl 2 to 32 all produce the same output, only the inference speed changes)

#### `-ngl 32`

```
Here is a reciepe for tomato soup:
- " S M D B P TThe-------------------------------------------------------
- " S M D B P TThe------------------------------------------------------
llama_print_timings:        load time =    1180.39 ms
llama_print_timings:      sample time =      32.76 ms /   128 runs   (    0.26 ms per token,  3906.97 tokens per second)
llama_print_timings: prompt eval time =     184.50 ms /    11 tokens (   16.77 ms per token,    59.62 tokens per second)
llama_print_timings:        eval time =    2464.90 ms /   127 runs   (   19.41 ms per token,    51.52 tokens per second)
llama_print_timings:       total time =    2707.77 ms /   138 tokens
Log end
```

#### `-ngl 33` (all layers)

```
Here is a reciepe for tomato soup:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
llama_print_timings:        load time =    1076.60 ms
llama_print_timings:      sample time =      34.70 ms /   128 runs   (    0.27 ms per token,  3688.97 tokens per second)
llama_print_timings: prompt eval time =     168.66 ms /    11 tokens (   15.33 ms per token,    65.22 tokens per second)
llama_print_timings:        eval time =    1424.31 ms /   127 runs   (   11.21 ms per token,    89.17 tokens per second)
llama_print_timings:       total time =    1652.01 ms /   138 tokens
Log end
```
(always repeating a single token, seems to use mostly '!', 'G' or 'o')

### PR DESCRIPTION
**Pull request by 0cc4m**
Fixes #5243 

I also found a CPY buffer size bug that I fixed alongside this. Let me know if it works @stduhpf

### CODE REVIEW

**Comment by stduhpf** [comment]
Nice, this seems to work pretty well. I don't get nonsense generations anymore, but there are some "issues" with consistency. Testing with fixed seed and 0 temperature give different outputs depending on the amount of layers offloaded. Not a big deal though.

#### `-ngl 0` and `-ngl 1`:
```
Here is a reciepe for tomato soup:

Ingredients:
- 4 cups of chicken broth
- 2 tablespoons of butter
- 1 onion, chopped
- 2 cloves of garlic, minced
- 2 tomatoes, peeled and diced
- Salt and pepper to taste
- Parsley for garnish

Directions:
- In a large pot, melt the butter over medium heat. Add the onion and cook until soft, about 10 minutes.
- Stir in the garlic and cook for another minute.
- Add the tomatoes and chicken broth and bring to a boil. Reduce the heat and simmer for 15 minutes, stirring occasionally.
- Season with salt and pepper
```

#### `-ngl 2` to `-ngl 31` all give different, but always coherent answers

#### `-ngl 32`and `-ngl 33`:
```
Here is a reciepe for tomato soup:

Ingredients:
- 4 cups of chicken broth
- 2 cans of diced tomatoes
- 1 onion, chopped
- 2 cloves of garlic, minced
- Salt and pepper to taste
- Fresh basil leaves for garnish

Directions:
- In a large pot, bring the chicken broth to a boil over high heat.
- Add the diced tomatoes, onion, and garlic and reduce the heat to medium-low. Simmer for about 15 minutes, stirring occasionally.
- Season with salt and pepper to taste.
- Sprinkle some fresh basil leaves on top of the soup and serve hot or cold.
```

**Comment by 0cc4m** [comment]
> Nice, this seems to work pretty well. I don't get nonsense generations anymore, but there are some "issues" with consistency. Testing with fixed seed and 0 temperature give different outputs depending on the amount of layers offloaded. Not a big deal though.

GPU give slightly different results in floating point operations compared to CPU, so even with CUDA or HIP there may be differences. But I also had to build an entire matrix multiplication shader myself since there is no BLAS library for Vulkan, and I suspect there might be some inaccuracies still in there. It's at least mostly correct now and pretty fast.

**Comment by stduhpf** [comment]
> GPU give slightly different results in floating point operations compared to CPU, so even with CUDA or HIP there may be differences. But I also had to build an entire matrix multiplication shader myself since there is no BLAS library for Vulkan, and I suspect there might be some inaccuracies still in there. It's at least mostly correct now and pretty fast.

I'm not observing the same level of discrepency with other models... Anyways, as long as the output is coherenty, that's good enough for me.

**Review by slaren — APPROVED** [review]
Did the GELU op pass `test-backend-ops` before? I think the kompute backend had a similar issue.
https://github.com/ggerganov/llama.cpp/pull/4456/commits/6fc99a6e668d0eaacc3e519ae6d999974adbeb42
https://github.com/ggerganov/llama.cpp/pull/4456/commits/38d1f0c7a0520c53ed9225d3aad8d15d87102d05

**Comment by stduhpf** [comment]
> GPU give slightly different results in floating point operations compared to CPU, so even with CUDA or HIP there may be differences. But I also had to build an entire matrix multiplication shader myself since there is no BLAS library for Vulkan, and I suspect there might be some inaccuracies still in there. It's at least mostly correct now and pretty fast.

Anyways, I just tried with the CLBlast backend, and I get the exact same behaviour as this PR, so it's something about this model specifically that makes him have different outputs between CPU and GPU. 

So everything is good§

**Comment by 0cc4m** [comment]
> Did the GELU op pass `test-backend-ops` before? I think the kompute backend had a similar issue. [6fc99a6](https://github.com/ggerganov/llama.cpp/commit/6fc99a6e668d0eaacc3e519ae6d999974adbeb42) [38d1f0c](https://github.com/ggerganov/llama.cpp/commit/38d1f0c7a0520c53ed9225d3aad8d15d87102d05)

It does pass it, yeah. Since Vulkan can run on a whole bunch of devices, the tests can work one some and fail on other devices or drivers, like in this case on proprietary AMD drivers. On the open source AMD drivers it's fine.

**Comment by cebtenzzre** [comment]
test-backend-ops is failing on the Vulkan backend for me on AMDVLK: [test-backend-ops-amdvlk.txt](https://github.com/ggerganov/llama.cpp/files/14128740/test-backend-ops-amdvlk.txt)
It passes on the Kompute backend.

**Comment by 0cc4m** [comment]
> test-backend-ops is failing on the Vulkan backend for me on AMDVLK (tested on this PR): [test-backend-ops-amdvlk.txt](https://github.com/ggerganov/llama.cpp/files/14128740/test-backend-ops-amdvlk.txt) It passes on the Kompute backend.

Yes, that's expected (and not related to amdvlk), but GELU works. I haven't spent time fixing tests yet cause they came up pretty late and I've had my own testing framework by then, which focuses on getting models to work, not general compliance. But I'll get around to it.

**Pull request merged**
