### PR TITLE
ggml : do not use ARM features not included in the build

### LINKED ISSUE #10435: Bug: Severe Performance Degradation on Q4_0 CPU-only with MacOS / Apple Silicon M2, after PR#9921 / Version 4081
### What happened?

Prior to PR #9921 / Version 4081 the -ngl 0 Q4_0 llama performance was significantly higher (more than 10x) than afterwards.
(hardware: Apple MacBook Air M2 10 GPU 24GB RAM)

before PR:
make clean
git checkout ae8de6d
make -j llama-bench
./llama-bench -p 512 -n 128 -t 4 -ngl 0 -m ...model...
| model                          |       size |     params | backend    | threads |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ------: | ------------: | -------------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |         60.48 ± 0.49 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |         14.89 ± 0.20 |
| llama 7B Q4_0_4_4              |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |         63.50 ± 2.47 |
| llama 7B Q4_0_4_4              |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |         11.93 ± 3.30 |
with ngl 99:
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |        194.94 ± 0.07 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |         11.81 ± 6.53 |

build: ae8de6d5 (4080)

versions after PR (including current):
make clean 
git checkout 1607a5e 
make -j llama-bench
./llama-bench -p 512 -n 128 -t 4 -ngl 0 -m ...model...
| model                          |       size |     params | backend    | threads |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ------: | ------------: | -------------------: |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |          **4.11 ± 0.24** |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |          **1.86 ± 0.01** |
| llama 7B Q4_0_4_4              |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |         62.81 ± 2.55 |
| llama 7B Q4_0_4_4              |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |         14.70 ± 1.97 |
with ngl 99:
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         pp512 |       186.02 ± 13.18 |
| llama 7B Q4_0                  |   3.56 GiB |     6.74 B | Metal,BLAS |       4 |         tg128 |         11.25 ± 3.42 |

build: 1607a5e5 (4081)

The variations except for -ngl 0 / Q4_0 might be due to the MacBook Air's thermals.

### Name and Version

Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
macOS Sequoia 15.1.1

### What operating system are you seeing the problem on?

Mac

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by slaren**
Fixes #10435

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by gustrd** [comment]
Excuse me @slaren , is it possible to do the same for the Android ARM build? I observed the same regression with q4_0_4_4 at the Snapdragon8G1.

**Comment by slaren** [comment]
I am not aware of any issues with Android, this should work in the same way with all the ARM platforms.

**Comment by gustrd** [comment]
I recently built the latest version of llama.cpp on Android and noticed a significant slowdown when using the q4_0_4_4 quantization format. It seems this slowdown occurs because the new version automatically converts q4_0_4_4 to the q4_0_4_8 format.

However, when I use the new IQ4_NL format, performance remains fast. From what I can tell, the automatic conversion in this case transforms it back into into a similar to q4_0_4_4.

**Comment by slaren** [comment]
This is not correct, only Q4_0 is converted to other types.

**Comment by gustrd** [comment]
You're absolutely right! When I run with q4_0, it gets repacked into the correct format, and the token generation speed is consistent.

I'm not sure why q4_0_4_4 has become slower, but it doesn’t seem like a major issue since it’s no longer necessary. Perhaps adding a deprecation warning for q4_0_4_4 could help clarify this for users.

That said, I did notice some performance loss during prompt processing compared to the old version using q4_0_4_4. I plan to benchmark this further and open a separate issue to provide more details. Thanks again for your hard work and patience—it’s greatly appreciated!

**Pull request merged**
