### PR TITLE
[RFC] readme : add feature matrix

### PR DESCRIPTION
**Pull request by Artefact2**
* llama.cpp has lots of features and lots of backends.
* Things are moving fast.
* As a newcomer, it's not always simple to see what is supposed to work, and what isn't.

I suggest adding a feature matrix (see below) to the readme that gives reasonable expectations to newcomers regarding working features across the different backends.

If you can test one of the question mark entries, please help fill the table!

Should we add this as a wiki page instead?

---

|                      | **CPU (AVX2)** | **CPU (ARM NEON)** | **Metal** | **cuBLAS** |    **rocBLAS**   | **SYCL** | **CLBlast** | **Vulkan** | **Kompute** |
|:--------------------:|:--------------:|--------------------|:---------:|:----------:|:----------------:|----------|:-----------:|:----------:|:-----------:|
| **K-quants**         | ✅              | ✅                  | ✅         | ✅          | ✅                | ❓        | ✅           | ✅          | 🚫           |
| **I-quants**         | ✅ (SLOW)       | ✅                  | ✅ (SLOW)  | ✅          | ✅                | 🚫        | 🚫           | 🚫          | 🚫           |
| **Multi-GPU**        | N/A            | N/A                | N/A       | ✅          | ❓                | 🚫        | ❓           | ✅          | ❓           |
|  **K cache quants**  | ✅              | ❓                  | ❓         | ✅          | Only q8_0 (SLOW) | ❓        | ✅           | 🚫          | 🚫           |
| **MoE architecture** | ✅              | ❓                  | ✅         | ✅          | ✅                | ❓        | Only -ngl 0 | 🚫          | 🚫           |

### CODE REVIEW

**Comment by ggerganov** [comment]
There was a similar attempt via a Discussion: https://github.com/ggerganov/llama.cpp/discussions/3471
Not sure if it was really useful

We can give this another try, but it should be either a Discussion or Wiki page, because otherwise we need to make commits to update the Readme

**Comment by Artefact2** [comment]
Thanks for the feedback! The wiki seems quite neglected, is there a policy for changing/updating pages?

**Comment by ggerganov** [comment]
> Thanks for the feedback! The wiki seems quite neglected, is there a policy for changing/updating pages?

Not really. I think you just need to have collaborator access to the repo. Let me know if you are interested in updating it - will send you an invite

**Comment by Artefact2** [comment]
I'd be interested in maintaining such a table in the wiki, but I only have an AMD GPU. We'd ideally need other collaborators to regularly check on the other backends (cuBLAS, Metal, ARM and SYCL).

**Pull request closed without merging**
