### PR TITLE
llama : use cmake for swift build

### PR DESCRIPTION
**Pull request by slaren**
This is intended to show a possible way to use `cmake` to build the llama.cpp dependency for the swift code, without having to duplicate the build in `Package.swift`.

### CODE REVIEW

**Comment by pgorzelany** [comment]
Hi @slaren sorry to bother you but this MR broke the Swift package integration. See more details here: https://github.com/ggerganov/llama.cpp/issues/10747

**Comment by Lancelotbronner** [comment]
Changing this to a system library breaks the SwiftPM integration (basically the only relevant use case) and forces every users to clone the repo.

The build instructions NEED to remain in the `Package.swift`. `systemLibrary` indicates the library is ALREADY installed on EVERY device on which it runs and just links the library instead of actually building and embedding it.

**Comment by ggerganov** [comment]
@Lancelotbronner The Swift builds are being migrated to a XCFramework. Follow https://github.com/ggml-org/llama.cpp/pull/11996 for updates.

**Comment by jaekong** [comment]
I know it's already been merged months ago, but Swift isn't just for Apple platform development. XCFramework won't work on Linux.

**Pull request merged**
