### PR TITLE
sycl : update support conditions 

### PR DESCRIPTION
**Pull request by Alcpz**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

---

Updates SYCL supported OPs checks to be in line with the updates introduced in previous PRs, as test-backend-ops is currently failing due to unsupported datatypes in CONT and IM2COL.

### CODE REVIEW

**Comment by Alcpz** [comment]
@OuadiElfarouki @joeatodd @airMeng @NeoZhangJianyu

**Review by airMeng — APPROVED** [review]

**Comment by NeoZhangJianyu** [comment]
@Alcpz 
UT is used to test the quality and capability.
We need to improve the code to make sure the UT pass rate is 100%, instead of skip the test cases.

Some UT cases are updated for CUDA improvement, so the new/updated cases are not passed with SYCL backend.
SYCL backend should be improved to support more OPs as CUDA, to keep up the llama.cpp capability to support more LLMs.

If skip such UT cases, we won't know what's the gap.

Fault UT cases feedback the issues.
We need to fix the issues as root cause.

In previous months, the UT pass rate is high (96%).
For example:
In commit-id (17e98d4c96a583d420f12046bc92102381dbd28e), 
```
IM2COL(type_input=f32,type_kernel=f16,dst_type=f32,ne_input=[10,10,3,1],ne_kernel=[3,3,3,1],s0=1,s1=1,p0=1,p1=1,d0=1,d1=1,is_2D=1): OK
  IM2COL(type_input=f32,type_kernel=f16,dst_type=f16,ne_input=[10,10,3,1],ne_kernel=[3,3,3,1],s0=1,s1=1,p0=1,p1=1,d0=1,d1=1,is_2D=1): OK
```
In latest commit: 2a358fb0c4b6e917ac852aa17444cc94dd28a2a6
```
IM2COL(type_input=f32,type_kernel=f32,dst_type=f32,ne_input=[10,10,3,1],ne_kernel=[3,3,3,1],s0=1,s1=1,p0=1,p1=1,d0=1,d1=1,is_2D=1): crash....
```

We can see the same case is fault in latest code. But it's passed with old code.
We need to fix the code issues.

So, I suggest to keep the original supports_op() function.

**Comment by Alcpz** [comment]
@NeoZhangJianyu  Thanks for the quick review.
I understand your point, but our internal CI is crashing and hanging because the SYCL backend doesn't currently support these operations, so I must disagree. Our priority is to ensure everything passes, and if we don't fix this now, we risk introducing breaking changes without realizing it. The support_op should reflect this, which is the purpose of this PR.

That said, I don't want to imply that we don't plan to support this in the future, so I will add a TODO to address it at a later time.

**Review by OuadiElfarouki — APPROVED** [review]
LGTM!

**Comment by NeoZhangJianyu** [comment]
> @NeoZhangJianyu Thanks for the quick review. I understand your point, but our internal CI is crashing and hanging because the SYCL backend doesn't currently support these operations, so I must disagree. Our priority is to ensure everything passes, and if we don't fix this now, we risk introducing breaking changes without realizing it. The support_op should reflect this, which is the purpose of this PR.
> 
> That said, I don't want to imply that we don't plan to support this in the future, so I will add a TODO to address it at a later time.

@Alcpz 
OK, I agree.

Thank you!

**Review by NeoZhangJianyu — APPROVED** [review]

**Pull request merged**
