### PR TITLE
llama.swiftui : add bench functionality

### PR DESCRIPTION
**Pull request by ggerganov**
ref #4358 

Some initial runs on iPhone 13 Mini using TinyLlama 1.1B

https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-1195k-token-2.5T

```bash
# clone model
git clone https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-1195k-token-2.5T

# convert to GGUF F16
python3 convert.py ./TinyLlama-1.1B-intermediate-step-1195k-token-2.5T/ --outfile models/tinyllama-1b/ggml-model-f16.gguf --outtype f16

# quantize to Q8_0 and Q4_0
./quantize models/tinyllama-1b/ggml-model-f16.gguf models/tinyllama-1b/ggml-model-q8_0.gguf q8_0
./quantize models/tinyllama-1b/ggml-model-f16.gguf models/tinyllama-1b/ggml-model-q4_0.gguf q4_0

# bench
make clean && make -j llama-bench && ./llama-bench \
  -m ./models/tinyllama-1b/ggml-model-f16.gguf  \
  -m ./models/tinyllama-1b/ggml-model-q8_0.gguf \
  -m ./models/tinyllama-1b/ggml-model-q4_0.gguf \
  -p 512 -n 128 -ngl 99 2> /dev/null
```

| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 1B mostly Q8_0           |  1.09 GiB |     1.10 B | Metal      |  99 | pp 512     |    397.35 |
| llama 1B mostly Q8_0           |  1.09 GiB |     1.10 B | Metal      |  99 | tg 128     |     23.86 |
| llama 1B mostly Q4_0           |  606.53 MiB |    1.10 B | Metal      |  99 | pp 512     |    408.00 |
| llama 1B mostly Q4_0           |  606.53 MiB |    1.10 B | Metal      |  99 | tg 128     |     39.70 |

TODOs:

- [x] Compute result uncertainty in a similar way as `llama-bench`
- [x] Output markdown results that can be copy-pasted
- [x] Download model in-app? not sure how to do that?
- [x] Text generation should terminate after 64 tokens
- [x] Option to stop benchmark
      Sometimes when the model is too big, the phone can get completely bricked while doing the benchmark. Should add "Stop" button + timing to stop benchmarking after more than 1 minute has passed

</img>

### CODE REVIEW

**Comment by jhen0409** [comment]
> [ ] Download model in-app? not sure how to do that?

I can help to do this later if not done yet. Would you expected to download multiple models? It will be help with benchmarking in one run.

**Comment by bachittle** [comment]
I think using this would allow functionality to download from a huggingface URL directly into the app: https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_from_websites

**Comment by ggerganov** [comment]
> Would you expected to download multiple models?

I imagined the most trivial functionality would be to always have a single model stored on the device and have a list of buttons:

- TinyLlama Q4_0 (600 MiB)
- TinyLlama Q8_0 (1.09 GiB)
- Phi-2 Q4_0 (.. GiB)
- etc.

When you click on a button, it erases the currently stored model and downloads the selected model from HF in place of it.

The reason to do it like this is that it can become complicated with managing the storage, free space, what is downloaded and what is not downloaded, etc. But if you think that it is manageable and the code would not become too cumbersome, then we can download and store multiple models. I just don't have enough Swift experience to evaluate how difficult this would be to implement and I'm mostly hacking on this example with the help of Copilot.

**Comment by jhen0409** [comment]
I created a simple download button to do that, it can show progress / abort download and init a llama context. Currently the button does not delete the existing one when performing the download, I added an another clear button.

Currently the models only added [TheBloke/TinyLlama-1.1B-1T-OpenOrca-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-1T-OpenOrca-GGUF) q4_0 and q8_0, we can easily edit it

**Comment by ggerganov** [comment]
Is there a way to write the downloaded model file in chunks so that we reduce memory usage?

Currently, on my device when I download the Q8_0 model, it crashes during writing the file because I think it runs out of memory. The reason seems to be that in order to write the data, we make a copy (I think)

If I add the model manually (i.e. without going though download) it works

**Comment by ggerganov** [comment]
> Is there a way to write the downloaded model file in chunks so that we reduce memory usage?

Well, thank you local Mixtral 8x7B 😄 

```bash
./main -m models/mixtral-instruct-8x7b-fast/ggml-model-q8_0.gguf -e -f task.txt --repeat_penalty 1.0 --color --temp 0.0 -c 4096 -n -1 --no-penalize-nl --verbose-prompt
```

<details>
<summary>Answer via `llama.cpp main`</summary>

sampling: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.000
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 4096, n_batch = 512, n_predict = -1, n_keep = 0


 [INST] How to improve this SwiftUI function to use less memory?

```swift
    private func download() {
        status = "downloading"
        print("Downloading model \(modelName) from \(modelUrl)")
        downloadTask = URLSession.shared.dataTask(with: URL(string: modelUrl)!) { data, response, error in
            if let error = error {
                print("Error: \(error.localizedDescription)")
                return
            }

            guard let response = response as? HTTPURLResponse, (200...299).contains(response.statusCode) else {
                print("Server error!")
                return
            }

            if let data = data {
                do {
                    print("Writing to \(filename)")
                    let fileURL = DownloadButton.getFileURL(filename: filename)
                    try data.write(to: fileURL)

                    llamaState.cacheCleared = false

                    status = "downloaded"
                    try llamaState.loadModel(modelUrl: fileURL)
                } catch let err {
                    print("Error: \(err.localizedDescription)")
                }
            }
        }
        observation = downloadTask?.progress.observe(\.fractionCompleted) { progress, _ in
            self.progress = progress.fractionCompleted
        }
        downloadTask?.resume()
    }
```

Currently, when it downloads a 1GB file, it uses 2GB of memory which is very wasteful. I would like to avoid the copy of the data. [/INST] To avoid copying the data and using less memory while downloading large files in SwiftUI, you can write the data directly to the file as it is being downloaded, instead of loading the entire data into memory before writing it to the file. Here's an updated version of your function that does this:

```swift
private func download() {
    status = "downloading"
    print("Downloading model \(modelName) from \(modelUrl)")
    guard let url = URL(string: modelUrl) else { return }
    let fileURL = DownloadButton.getFileURL(filename: filename)

    downloadTask = URLSession.shared.downloadTask(with: url) { temporaryURL, response, error in
        if let error = error {
            print("Error: \(error.localizedDescription)")
            return
        }

        guard let response = response as? HTTPURLResponse, (200...299).contains(response.statusCode) else {
            print("Server error!")
            return
        }

        do {
            if let temporaryURL = temporaryURL {
                try FileManager.default.copyItem(at: temporaryURL, to: fileURL)
                print("Writing to \(filename) completed")

                llamaState.cacheCleared = false

                status = "downloaded"
                try llamaState.loadModel(modelUrl: fileURL)
            }
        } catch let err {
            print("Error: \(err.localizedDescription)")
        }
    }

    observation = downloadTask?.progress.observe(\.fractionCompleted) { progress, _ in
        self.progress = progress?.fractionCompleted
    }

    downloadTask?.resume()
}
```

This version uses the `downloadTask(with:)` method from `URLSession`, which downloads the file directly to the specified `fileURL`. This way, you avoid loading the entire file into memory, and the memory usage should be much lower. [end of text]

llama_print_timings:        load time =    1615.12 ms
llama_print_timings:      sample time =      13.26 ms /   461 runs   (    0.03 ms per token, 34768.84 tokens per second)
llama_print_timings: prompt eval time =    3456.45 ms /   384 tokens (    9.00 ms per token,   111.10 tokens per second)
llama_print_timings:        eval time =   12839.38 ms /   460 runs   (   27.91 ms per token,    35.83 tokens per second)
llama_print_timings:       total time =   16372.73 ms
</details>

**Comment by ggerganov** [comment]
iPhone 13 Mini

Loading model...
Could not locate model
Loading model...
Loaded model tinyllama-1.1b-1t-openorca.Q4_0.gguf

Running benchmark...
Model info: llama 1B Q4_0
Heat up time: 0.630616959 seconds, please wait...
| model | size | params | backend | test | t/s |
| --- | --- | --- | --- | --- | --- |
| llama 1B Q4_0 | 0.59 GiB | 1.10 B | Metal | pp 512 | 405.30 ± 7.26 |
| llama 1B Q4_0 | 0.59 GiB | 1.10 B | Metal | tg 128 | 39.03 ± 0.08 |
Loading model...
Loaded model tinyllama-1.1b-1t-openorca.Q8_0.gguf

Running benchmark...
Model info: llama 1B Q8_0
Heat up time: 1.659307333 seconds, please wait...
| model | size | params | backend | test | t/s |
| --- | --- | --- | --- | --- | --- |
| llama 1B Q8_0 | 1.09 GiB | 1.10 B | Metal | pp 512 | 411.16 ± 6.22 |
| llama 1B Q8_0 | 1.09 GiB | 1.10 B | Metal | tg 128 | 24.12 ± 0.04 |

image

**Pull request merged**
