### PR TITLE
Add download-release.sh for easy install

### PR DESCRIPTION
**Pull request by NickCrews**
I wanted an easy way to get llama-server on my machine.

I figured this would be useful for other people as well.

Take a look at the docstring and help text, it should be fairly intuitive.

Tested as working on a mac m1. The path handling only works with unixy paths for now, sorry windows people. If you want, this is ripe for improving in this regard.

I tried to keep portability in mind besides that though, though I'm no shell expert.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [x] Medium
  - [ ] High

### CODE REVIEW

**Comment by ggerganov** [comment]
Should be moved to the `scripts` folder

**Comment by NickCrews** [comment]
Will do. Any other top-level comments? Is this even something you want to consider?

I also noticed now scripts/server-llm.sh. This has some duplicate functionality with that, since that also installs llama-server, it just does it by building it instead of downloading a release. Perhaps we want to split this into three scripts?
- download-build.sh
- download-release.sh
- run-server.sh

You can choose whichever download- script you need, and then run-server.sh? Idk this might have to be breaking, but we might be able to keep it non-breaking.

Or other option would be to merge everything into a mega script, adding this functionality to llm-server.sh, toggleable with a flag?

**Comment by ggerganov** [comment]
It's best if the option is merged into the existing `llm-server.sh` script

**Comment by NickCrews** [comment]
I'm just going to close as stale, turns out I didn't need this that badly :) Feel free to push this over the finish line if anyone is interested.

**Pull request closed without merging**
