### PR TITLE
Update special token handling in conversion scripts for gpt2 derived tokenizers

### PR DESCRIPTION
**Pull request by Galunid**
It's not tested yet, I'll test it by updating #3742 later today

Change discussed in #3730

### CODE REVIEW

**Comment by goerch** [comment]
> Baichuan does conversion differently, I'll have to look a bit more into it

Is there immediate need? Tests work for me (with an rather old download) without any change.

**Comment by Galunid** [comment]
Not really, I took a look and I think it's best to leave it as it is, since it seems to be working.

**Comment by Galunid** [comment]
I converted all the other models from this PR and the tokenizer tests pass, so it's probably good to go

**Review by goerch — APPROVED** [review]

**Comment by maddes8cht** [comment]
I am getting this error:
```
python convert-mpt-hf-to-gguf.py e:\hf\mpt-7b-storywriter\
gguf: loading model mpt-7b-storywriter
gguf: found 2 model parts
This gguf file is for Little Endian only
gguf: get model metadata
gguf: get tokenizer metadata
gguf: get gpt2 tokenizer vocab
Traceback (most recent call last):
  File "e:\hf\llama.cpp\convert-mpt-hf-to-gguf.py", line 140, in <module>
    if tokenizer.added_tokens_decoder[i].special:
AttributeError: 'GPTNeoXTokenizerFast' object has no attribute 'added_tokens_decoder'
```
Before this PR the convert-mpt-hf-to-gguf.py script worked for me.

I am running on Windows 10 in a conda env with python 3.10.13

**Pull request merged**
