### PR TITLE
Fix crash of test-tokenizer-0 under Debug build

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by howard0su** [comment]
I don't like the coding style of llama_kv_cache structure. It uses kv_cache_init for initialization, but destructor for cleanup. I didn't change it for now. but may look at cleaning them up later.

**Review by JohannesGaessler — APPROVED** [review]
Seems like I forgot the check. Thanks for fixing it.

**Comment by JohannesGaessler** [comment]
Wait, now that I look at the code there already is a check in `ggml_cuda_free_data` that instantly returns unless the backend is GPU or GPU_SPLIT. Under which circumstances is that not enough?

**Comment by howard0su** [comment]
You are right. the change was not right. please review again.

**Comment by JohannesGaessler** [comment]
So what exactly is the problem that you are trying to fix?
That the k and v tensors can be NULL so there is a segfault when `ggml_cuda_free_data` is called on them?
In that case I think it makes more sense to add this case to the beginning of `ggml_cuda_free_data` so it won't have to be added in user code again in the future.

**Comment by howard0su** [comment]
k & v is not initialized to zero if the client didn't call kv_cache_init like test_tokenizer_0. The garbage will causing crash when dereferencing k & v as tensor pointer.

**Comment by JohannesGaessler** [comment]
Alright, I think I understand the problem. I suggest that you keep initializing k and v as NULL but move the check from the `llama_kv_cache` destructor to `ggml_cuda_free_data`.

**Pull request merged**
