### PR TITLE
Better ccache guide

### PR DESCRIPTION
**Pull request by ibehnam**
Added instructions on how to install ccache and how to disable it (for certain commits, it was necessary).

### CODE REVIEW

**Review by mofosyne — APPROVED** [review]
Looks like it works. The line `I ccache found, compilation results will be cached. Disable with LLAMA_NO_CCACHE: `make clean && time make LLAMA_NO_CCACHE=1` highlights to screen when compiling.

I am a bit iffy about placing RED, GREEN, etc... in this area. Should it be in a common location so we could use it in various locations in the log. Especially to highlight specific warnings or problems? Also is this going to be an issue with terminals without color?

**Comment by slaren** [comment]
I am not sure that this change is necessary, or the color code stuff.

**Comment by ibehnam** [comment]
@mofosyne @slaren 

The instructions would be helpful for users who are new to `ccache`. Currently, the docs don't mention how LLAMA_NO_CCACHE should be used. The only answer to that is deep down in https://github.com/ggerganov/llama.cpp/issues/5389. So I thought it'd be helpful to add that instruction here.

I think the colors could either be part of a common location like @mofosyne said, or be removed as @slaren mentioned. I personally prefer the former because with recent changes especially to `./server`, there's so much additional "noisy" messages generated that the more important ones get buried away and hard to find in server outputs. Maybe using colors could help mitigate that issue as well.

**Comment by mofosyne** [comment]
Does makefile have any method of switching on/off certain logging? E.g. debug/info/warn and per subsystem

Might address what he was thinking here

**Comment by mofosyne** [comment]
Doesn't appear to be enough consensus for this to be included, but thanks for your contribution! Closing for now.

**Pull request closed without merging**
