### PR TITLE
vulkan : reuse parent extra for views

### LINKED ISSUE #7730: Bug: gpu hang after bde7cd3cd949c1a85d3a199498ac98e78039d46f
### What happened?

after bde7cd3cd949c1a85d3a199498ac98e78039d46f . inferring any llama3 q6 model will cause a gpu hang. previous version (a5735e4426b19a3ebd0c653ad8ac01420458ee95) is not affected

### Name and Version

bde7cd3cd949c1a85d3a199498ac98e78039d46f
using vulkan backend

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```
radv/amdgpu: The CS has been cancelled because the context is lost. This context is innocent.
terminate called after throwing an instance of 'vk::DeviceLostError'                   what():  vk::Queue::submit: ErrorDeviceLost
```

dmesg
```
[drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring comp_1.1.0 timeout, signaled seq=898, emitted seq=899
```

### LINKED ISSUE #7769: Bug: server (at least) craches using VULKAN
### What happened?

Hi,
Compiled server using VULKAN backend (as OpenCL was removed :sad:), I can start a server with a model. But, as far as an inference is requested, I've got an error message.

PS: Vulkan is theoretically not intended to replace OpenCL

```
GGML_ASSERT: /home/metal3d/Projects/ML/llama.cpp/ggml-vulkan.cpp:4069: d_D != nullptr
[New LWP 787893]
[New LWP 787894]
[New LWP 787895]
[New LWP 787897]
[New LWP 787900]
[New LWP 787917]
[New LWP 787918]
[New LWP 787919]
[New LWP 787924]
[New LWP 787925]
[New LWP 787926]
[New LWP 787927]
[New LWP 787928]
[New LWP 787929]
[New LWP 787930]
[New LWP 787931]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f5864430e03 in wait4 () from /lib64/libc.so.6
#0  0x00007f5864430e03 in wait4 () from /lib64/libc.so.6
#1  0x00000000005d811b in ggml_print_backtrace ()
#2  0x000000000067dafc in void ggml_vk_op_f32<vk_op_unary_push_constants>(ggml_backend_vk_context*, vk_context*, ggml_tensor const*, ggml_tensor const*, ggml_tensor const*, ggml_tensor*, ggml_op, vk_op_unary_push_constants const&&) [clone .constprop.0] ()
#3  0x00000000006a1507 in ggml_backend_vk_graph_compute(ggml_backend*, ggml_cgraph*) ()
#4  0x000000000062aad4 in ggml_backend_sched_graph_compute_async ()
#5  0x000000000056acb9 in llama_decode_internal(llama_context&, llama_batch) [clone .isra.0] ()
#6  0x000000000056c949 in llama_decode ()
#7  0x00000000004e0171 in server_context::update_slots() ()
#8  0x00000000004b1978 in server_queue::start_loop() ()
#9  0x00000000004552cc in main ()

```

### Name and Version

version adc9ff384121f4d550d28638a646b336d051bf42 

Sorry: 2b3389677a833cee0880226533a1768b1a9508d2

### What operating system are you seeing the problem on?

Linux Fedora 40

### Relevant log output

```shell
GGML_ASSERT: /home/metal3d/Projects/ML/llama.cpp/ggml-vulkan.cpp:4069: d_D != nullptr
[New LWP 787893]
[New LWP 787894]
[New LWP 787895]
[New LWP 787897]
[New LWP 787900]
[New LWP 787917]
[New LWP 787918]
[New LWP 787919]
[New LWP 787924]
[New LWP 787925]
[New LWP 787926]
[New LWP 787927]
[New LWP 787928]
[New LWP 787929]
[New LWP 787930]
[New LWP 787931]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f5864430e03 in wait4 () from /lib64/libc.so.6
#0  0x00007f5864430e03 in wait4 () from /lib64/libc.so.6
#1  0x00000000005d811b in ggml_print_backtrace ()
#2  0x000000000067dafc in void ggml_vk_op_f32<vk_op_unary_push_constants>(ggml_backend_vk_context*, vk_context*, ggml_tensor const*, ggml_tensor const*, ggml_tensor const*, ggml_tensor*, ggml_op, vk_op_unary_push_constants const&&) [clone .constprop.0] ()
#3  0x00000000006a1507 in ggml_backend_vk_graph_compute(ggml_backend*, ggml_cgraph*) ()
#4  0x000000000062aad4 in ggml_backend_sched_graph_compute_async ()
#5  0x000000000056acb9 in llama_decode_internal(llama_context&, llama_batch) [clone .isra.0] ()
#6  0x000000000056c949 in llama_decode ()
#7  0x00000000004e0171 in server_context::update_slots() ()
#8  0x00000000004b1978 in server_queue::start_loop() ()
#9  0x00000000004552cc in main ()
```

### PR DESCRIPTION
**Pull request by slaren**
Should fix #7730 #7769

@rhjdvsgsgks @metal3d @stduhpf Can you check if this fixes the issue?

### CODE REVIEW

**Comment by stduhpf** [comment]
This does fix the issue for me!

**Comment by 0cc4m** [comment]
@slaren Has something changed about how views are handled? Cause `extra->offset` should contain the `view_offs`, they get added during tensor initialization, [here](https://github.com/ggerganov/llama.cpp/blob/ee459f40f65810a810151b24eba5b8bd174ceffe/ggml-vulkan.cpp#L5998).

**Comment by slaren** [comment]
This is what changed (from https://github.com/ggerganov/llama.cpp/issues/7730#issuecomment-2153089435):

@0cc4m this is probably my bad, I made some changes to the way views are initialized in ggml-backend that may have created this issue. Views are now initialized in the buffer of their parent tensor, instead of on the compute buffer. The reason I made this change is because I came to the conclusion that allocating views on the compute buffer cannot work reliably because the compute buffer is not always of the same type as the buffer used to allocate the tensor originally, and backends should be able to use the same extra as their parent anyway. I thought it was safe to make this change because the CUDA backend no longer needs extras for normal buffers, but I didn't realize that the vulkan backend still does.

Looking at the `ggml_tensor_extra_gpu` of the vulkan backend I think it should be possible to do this, the only change is that you would have to calculate the offset as `t->extra->offset + t->view_offs`. Essentially, add the offset of the view to the offset of the extra. Does that sound right?

**Comment by 0cc4m** [comment]
Sounds right, but it should be either an offset addition on using the tensor or initially, not both, so can the part that I linked be removed?

I can't test it today, but I should be able to tomorrow. Thanks for looking into it.

**Comment by slaren** [comment]
I already changed the part that you linked to reuse the extra of the parent tensor instead of allocating a new one. The problem is that without doing this, the extras are allocated in the buffer of the KV cache, since these are views of the KV tensors, and eventually overwrite the extras of the original tensors. To prevent this it is necessary either to allocate the views in the compute buffer (what happened before), or simply avoid allocating extras for views, which is what this change does.

**Comment by metal3d** [comment]
Seems to be ok for me. Thanks!

**Comment by 0cc4m** [comment]
> I already changed the part that you linked to reuse the extra of the parent tensor instead of allocating a new one. The problem is that without doing this, the extras are allocated in the buffer of the KV cache, since these are views of the KV tensors, and eventually overwrite the extras of the original tensors. To prevent this it is necessary either to allocate the views in the compute buffer (what happened before), or simply avoid allocating extras for views, which is what this change does.

Right, sorry. I just glanced over the code and missed that.

**Comment by 0cc4m** [comment]
This causes a validation error when run with `LLAMA_VULKAN_CHECK_RESULTS`, some issue with the fences in `ggml_vk_compute_forward`. I'll debug that this evening.

```
VUID-vkQueueSubmit-fence-00064(ERROR / SPEC): msgNum: -1082734195 - Validation Error: [ VUID-vkQueueSubmit-fence-00064 ] Object 0: handle = 0x5ad034261e90, type = VK_OBJECT_TYPE_QUEUE; Object 1: handle = 0xeae97200000006d2, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0xbf76c98d | vkQueueSubmit():  (VkFence 0xeae97200000006d2[]) is already in use by another submission. The Vulkan spec states: If fence is not VK_NULL_HANDLE, fence must not be associated with any other queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-fence-00064)
    Objects: 2
        [0] 0x5ad034261e90, type: 4, name: NULL
        [1] 0xeae97200000006d2, type: 7, name: NULL
```

**Review by 0cc4m — APPROVED** [review]
Found the issue and fixed it.

**Pull request merged**
