### PR TITLE
server : fix crash when system prompt is bigger than batch size

### PR DESCRIPTION
**Pull request by compilade**
The system prompt is now decoded in batches.

Maybe `llama_decode` should eventually have some kind of built-in auto-batching since forgetting to split a batch seems common in the examples.

I also fixed a problem where `n_past` would skip a `pos` value when the prefix of a prompt is fully matching the tokens in the cache.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
> Maybe llama_decode should eventually have some kind of built-in auto-batching since forgetting to split a batch seems common in the examples.

~It should be added to `common` and eventually the new [llamax](https://github.com/ggerganov/llama.cpp/issues/5215) library will abstract this~ (see below)

**Comment by slaren** [comment]
I plan to extend `llama_decode` to automatically split the batches if they exceed `n_batch` for pipeline parallelism. It is already implemented in the demo PR.

**Comment by phymbert** [comment]
@slaren Hi, thanks for the fix, would it be possible to add a simple test ?

**Comment by slaren** [comment]
After it is implemented sure, but it is not merged yet. It still needs more work, but it should be done soon.

**Pull request merged**
