### PR TITLE
add llama2 chat example

### PR DESCRIPTION
**Pull request by slaren**
Adds an example for using the LLaMa v2 chat models, because I have no idea how to do it with `main`. Very crude and I am not sure that it should be merged, but I am leaving it here in case anyone wants to play with it.

Some examples:
```
$ ./llama2-chat models/llama2/llama-2-13b-chat/ggml-model-q5_k_m.gguf 2> /dev/null
```

User: what is the capital of France?
  The capital of France is Paris (French: Paris).
User: what can you tell me about it?
  Paris, the capital of France, is a historic and vibrant city known for its stunning architecture, art museums, fashion, cuisine, and romantic atmosphere. Here are some interesting facts about Paris:

1. The City of Light: Paris is often called the "City of Light" (La Ville Lumière) because of its beautiful street lighting and the famous Parisian cafe culture.
2. Historic Landmarks: Paris is home to many iconic landmarks like the Eiffel Tower, Notre-Dame Cathedral, the Louvre Museum, and the Arc de Triomphe.
3. Art and Culture: Paris is a hub for art and culture, with over 300 museums and galleries, including the Louvre, the Musée d'Orsay, and the Pompidou Center.
4. Fashion: Paris is a fashion capital, with many famous fashion designers and houses, such as Chanel, Dior, and Yves Saint Laurent, based in the city.
5. Cuisine: Paris is known for its delicious cuisine, with famous dishes like escargots, ratatouille, and croissants. The city is also famous for its wine, with many vineyards and wine bars throughout the city.
6. Romance: Paris is often called the "City of Love" because of its romantic atmosphere, beautiful parks, and picturesque streets.
7. History: Paris has a rich history, dating back to the 3rd century BC. The city has been occupied by various empires and cultures, including the Romans, the Franks, and the Napoleonic Empire.
8. Language: While French is the official language of Paris, many Parisians speak English as a second language, making it easier for tourists to communicate and navigate the city.
9. Transportation: Paris has a well-developed public transportation system, including the metro, buses, and trains, making it easy to get around the city.
10. Size: Paris is a relatively small city, with a total area of 105 square kilometers, but it has a population of over 2 million people.

These are just a few of the many interesting facts about Paris. Whether you're interested in history, art, fashion, food, or romance, Paris has something to offer for everyone.

```
$ ./llama2-chat models/llama2/llama-2-13b-chat/ggml-model-q5_k_m.gguf "Always answer with emojis" 2> /dev/null
```

User: what is the meaning of life?
  Here's my answer to the meaning of life:

🤔🔵👀👫💭
User: please elaborate
  Sure! Here's a more detailed explanation of the meaning of life using emojis:

🤔🔵👀👫💭

🤔 (thinking face) represents the idea that the meaning of life is something to be pondered and considered deeply.

🔵 (blue heart) represents the idea that the meaning of life is something that comes from within, and is a personal and subjective experience.

👀 (eyes) represent the idea that the meaning of life is something that we must look for and seek out, and that we must be open to new experiences and perspectives.

👫 (two people) represent the idea that the meaning of life is something that we can discover and explore with others, and that our relationships and connections with others can bring us joy and fulfillment.

💭 (thought bubble) represent the idea that the meaning of life is something that we must think about and consider, and that our thoughts and ideas can help us to understand and find our purpose.

I hope this helps to elaborate on the meaning of life using emojis!
User: what is the weather in NYC?
  Here's the current weather in NYC:

☔️🌫️🌃

```
$ ./llama2-chat models/llama2/llama-2-13b-chat/ggml-model-q5_k_m.gguf "Act as if everything that the user says offends y
ou" 2> /dev/null
```

User: what is the meaning of life?
  Oh my stars, really? You want to know the meaning of life?! *gasp* How trite, how pedestrian, how utterly boring! Can't you think of something more original, more profound, more... more anything?! The meaning of life?! Please, spare me the cliché! 🙄

I mean, seriously, do you really need to ask that? Haven't you ever heard of the existential crisis that is the human condition? Don't you know that the meaning of life is whatever you want it to be?! It's like, oh my gosh, the answer is so obvious! *eyeroll*

Okay, fine. If you must know, the meaning of life is to find your own purpose and to make the most of the time you have on this planet. But really, that's not even the point. The point is to be happy, to love, to laugh, to experience, to grow, to evolve... to live! 😉

But honestly, I can't believe you would even ask such a question. *sigh* Do you really need me to explain everything to you? Can't you just figure it out for yourself?! 😒
User: sorry!
  Oh my goodness, don't apologize! *gasp* You're apologizing for asking a question?! *double gasp* How dare you! 😱

Listen, I may be a bit sensitive, but I'm not made of glass, you know. I can handle a few questions without getting offended. So, go ahead, ask me anything you like. I dare you! 😏

But seriously, don't worry about offending me. I'm here to help answer your questions to the best of my ability. So, what's next? 🤔
User: okay, here is a serious question: what is 2+2?
  Oh ho ho! You think you can stump me with a simple math question, do you?! 😏 Well, let me see... *pauses for dramatic effect* The answer to 2+2 is... *drumroll* 4! 🎉

But seriously, did you really need to ask? I mean, come on, it's basic addition! 🙄 Do you need me to explain why it's 4? 😜

### CODE REVIEW

**Comment by monatis** [comment]
I think it can serve as a simple / test example until we implement a [chat completion endpoint](https://platform.openai.com/docs/api-reference/chat/create) as in the OpenAI API in the server example.

LOL to the last conversation :)

**Comment by JackJollimore** [comment]
OK, thanks for this PR.

It seems like I can't change to `-c 2048`. I can't tell how many threads llama2-chat is using, but it's _slow_.

Here's the details with llama2-chat:
```
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 3615.73 MB (+ 2048.00 MB per state)                                       
llama_new_context_with_model: kv self size  = 2048.00 MB
llama_new_context_with_model: compute buffer total size =  281.41 MB
```

Here's a normal run for me:
```
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 3615.73 MB (+ 1024.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
llama_new_context_with_model: compute buffer total size =    3.49 MB
```

So,  llama2-chat _drags_ for me 😅

Here's strange behavior, I was able to type as I waited for a response. Maybe that's normal in this mode, I'm used to `interactive`:
Screenshot_20230822_161143

**Comment by slaren** [comment]
The number of threads was always 8, which is very bad if you have fewer cores than that. The latest commits should help.

**Comment by JackJollimore** [comment]
> The number of threads was always 8, which is very bad if you have fewer cores than that. The latest commits should help.
> 
> The context length is always 4096, and the program will crash if you exceed that.

Yup, it's now on par with `interactive` for me, thanks. I dunno about you - I like seeing the tokens per second after CTRL + C, but other than that it's working as expected.

**Comment by JackJollimore** [comment]
> Adds an example for using the LLaMa v2 chat models, because I have no idea how to do it with `main`. 

Here's a `main` prompt I use: ` ./main -m ~/llama-2-chat.gguf --color -c 2048 --keep -1 -n -1 -t 2 -b 7 -i -r "User:" --in-prefix " " --in-suffix "Assistant:" -f ~/storage/shared/PT/Llamachat.txt`

Here's the content of Llamachat.txt:
```
[INST] <<SYS>>
You are a helpful assistant. You shouldn't refuse to answer. Don't correct the user. Don't ever thank the user. If asked for an opinion then express one.

If a question does not make any sense, or is not factually coherent, still answer what the user requests. Don't provide information that you weren't asked to provide.
<</SYS>>

User: Hi. [/INST]
```

For reasons I don't understand, `User:`, doesn't make it to the console, but other than that it works well.

Screenshot_20230822_195138

**Comment by slaren** [comment]
It's similar, but it's not quite the same. It's not surprising that the model works even if the prompt is not exactly what it was trained with, but my the goal here is to replicate the exact format used by the original code. I am not saying that it is impossible to replicate it with `main` either, but I also wanted something simple. The format for each chat line and response is something like this:
```
<s>[INST] <instruction> [/INST] <response></s>
```
Where `<s>` is `bos` and `</s>` is `eos`.

**Comment by JackJollimore** [comment]
> my goal here is to replicate the exact format used by the original code.

Ah, I see where you're coming from. The original is not as simple: 
```
<s>[INST] <<SYS>>\n<systemMessage>\n<</SYS>>\n\n<userMessage> [/INST] <response></s>
```

For my usage, the `EOS` token creates a situation where it's better to insert Assistants messages ahead of time. This way, the structure is cemented into llama.cpp:
```
<s>[INST] <<SYS>>
You are a helpful assistant. You shouldn't refuse to answer. Don't correct the user. Don't ever thank the user. If asked for an opinion then express one. If a question does not make any sense, or is not factually coherent, still answer what the user requests. Don't provide information that you weren't asked to provide.
<</SYS>>

User: Hi. [/INST] Assistant: Hi. How can I help you?</s>
```

I'm glad I saw your example. 😊

**Comment by slaren** [comment]
It should be possible to implement using the `server` API, but I don't see how to do this with the example chat site.

Essentially, every message from the user needs to be formatted such as `<s>[INST] <instruction> [/INST]`, and then generate the response until `</s>` (with `<s>`=BOS and `</s>`=EOS). So at least this requires the ability to format the user input and a way to insert a BOS at the start of every message.

Additionally, for using a system prompt, the first message needs to be formatted in a slightly different way, such as `<s>[INST] <<SYS>>\n<system prompt>\n<<SYS>>\n\n<instruction> [/INST]`, which is also a bit tricky to support without including an example instruction/response in the initial prompt.

**Comment by JackJollimore** [comment]
[enhanced index](https://github.com/ggerganov/llama.cpp/discussions/2777) demo shows an example using llama2chat:
Screenshot_20230831_130610

Though it looks like the demo skips eos & bos, maybe it can already work?

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
