### PR TITLE
CMake: properly find and link to threading library

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by etra0** [comment]
I think this is a duplicate of https://github.com/ggerganov/llama.cpp/pull/114

**Comment by arrowd** [comment]
That change looks incomplete, I had to link both executables with pthreads.

**Comment by ggerganov** [comment]
@arrowd Could you double check - linking just to `ggml` should be enough I think

**Comment by arrowd** [comment]
Ah, right, it is sufficient to add `Threads::Threads` to the library only. I guess, my PR is unnecessary then.

**Pull request closed without merging**
