### PR TITLE
WIP Feature/refl cpp

### PR DESCRIPTION
**Pull request by jmikedupont2**
WIP adding refl cpp
based on my previous cpp work.  https://github.com/veselink1/refl-cpp provides a single header. I am experimenting with it,  first version that compiled. Adding a new base class to everything, not sure if that is needd.

### CODE REVIEW

**Comment by FSSRepo** [comment]
Why did adding that model require changing the way parameters are assigned to structs? Just out of curiosity, I was struck by seeing 39 files changed just to add a model. It amuses me a bit because I sometimes do unnecessary things when I get excited 😂😂.

**Comment by jmikedupont2** [comment]
Well what's happening is that there is an unnamed type information that's
being injected into the base class which is now messing up the default
Constructors

**Comment by jmikedupont2** [comment]
I thank you also for even looking at my work, this is still very much work
in progress, i am evaluating the different meta programming libs.  Maybe
these changes wont be needed, aslo there are changes from my previous
patches rolled into this. I will need longer to conclude this working and
buliding in public, I hope that it inspires someone to join my effort.

**Comment by jmikedupont2** [comment]
So I have made progress on this, it turns out this lib needs a bunch of macros, I am working on the generator for them now.

**Comment by jmikedupont2** [comment]
Its working

**Comment by jmikedupont2** [comment]
https://github.com/meta-introspector/llama.cpp/blob/feature/refl-cpp/binding.py this generator started to generate the bindings for me using a llvm and python

**Comment by jmikedupont2** [comment]
https://github.com/meta-introspector/llama.cpp/blob/feature/refl-cpp/print.hpp this is the place where I put the generated wrappers

**Comment by jmikedupont2** [comment]
https://github.com/ggerganov/llama.cpp/pull/4209 now reworked the patch to be smaller

**Comment by jmikedupont2** [comment]
> Why did adding that model require changing the way parameters are assigned to structs? Just out of curiosity, I was struck by seeing 39 files changed just to add a model. It amuses me a bit because I sometimes do unnecessary things when I get excited 😂😂.

Now I reworked it to be much smaller patch please check it out https://github.com/ggerganov/llama.cpp/pull/4209

**Pull request closed without merging**
