### PR TITLE
readme: add Msty to UI list

### PR DESCRIPTION
**Pull request by ashokgelal**

### CODE REVIEW

**Review by cebtenzzre — APPROVED** [review]

**Comment by ashokgelal** [comment]
@cebtenzzre thanks for the approval. Is there anything else needed on my side to have this merged to master?

**Comment by cebtenzzre** [comment]
I'm curious - where on your website or in Msty does it mention llama.cpp?

**Comment by ashokgelal** [comment]
We just setup the site and still working on the content. I'll make sure to mention it somewhere on our site. Thank you. 

Just curious, is mentioning llama.cpp a requirements. I noticed there were a couple of links in here that don't seem to mention it.

**Comment by ggerganov** [comment]
> Just curious, is mentioning llama.cpp a requirement?

If there is no easy way to verify that `llama.cpp` is used in a project it does not make sense to add it to the list

> I noticed there are a couple of links in here that don't seem to mention it.

If that's the case, these should be removed

**Comment by ashokgelal** [comment]
We have updated our site to mention Llama.cpp, as well as added a link back to this project. You can verify it on the site or look at the attached screenshot. Thank you for Llama.cpp and for your consideration.

CleanShot 2024-02-25 at 10 20 56@2x

**Pull request merged**
