### PR TITLE
Fix OLMo HF to GGUF conversion

### LINKED ISSUE #6712: truly opensource model called olmo
Build with truly open dataset and fully open-source model can this be supported in olllama thanks.
https://allenai.org/olmo
https://huggingface.co/allenai/OLMo-7B

### PR DESCRIPTION
**Pull request by nopperl**
Fix the HF to GGUF conversion of OLMo models:
  * Implement OLMo support for the BPE pre-tokenization (#6920).
  * Properly set the `clamp_qkv` value. Fixes #6712.

### CODE REVIEW

**Review by cebtenzzre — APPROVED** [review]

**Comment by nopperl** [comment]
It seems like the error comes from the BPE pre-tokenization merged in #6920.

**Comment by nopperl** [comment]
@josharian I have fixed the conversion issue, it should work now.

**Comment by ggerganov** [comment]
Hm does it really work - `llama.cpp` does not know how to handle the "olmo" pre-tokenizer. It would crash here:

https://github.com/ggerganov/llama.cpp/blob/3af34c1d1b0da47f85b95f60922abeded1cb5d33/llama.cpp#L4392-L4394

**Comment by nopperl** [comment]
@ggerganov you're right, I tested it with an older binary. I'll try to fix it.

**Comment by nopperl** [comment]
> It looks alright, I'm downloading the model to test it. If it works I'll merge it, unless there's something more you want to add here?

nice, I don't think there's anything else to add if it works.

**Review by Galunid — APPROVED** [review]
Looks good

**Comment by lsetiawan** [comment]
Wow! Thank you all for your super quick response and @nopperl for working to fix this. I really appreciate everyone's input 😄 This is really exciting!

**Comment by nopperl** [comment]
@lsetiawan no problem!

>I would like to share this capability at the 2024 Scipy Conference

I'm interested in that, could you send me more info on what you're planning to do?

**Comment by lsetiawan** [comment]
For sure! For anyone interested, my team at the [University of Washington Scientific Software Engineering Center](https://escience.washington.edu/software-engineering/ssec/) has been working on creating a [tutorial](https://cfp.scipy.org/2024/talk/BZGQMC/) on RAG-based approach using OLMo as the LLM Model. Since the regular `OLMo-7B-Instruct` model has a very slow inference speed, we've been looking into ways to quantize and speed things up, especially on CPU, so that's how we've come across llama.cpp and the progress made with integrating OLMo so that it can be converted to GGUF and quantized. Thanks to everyone's contribution we have successfully made the `OLMo-7B-Instruct` to be in GGUF format and quantized to 4-bit with `Q4_K_M` method: https://huggingface.co/ssec-uw/OLMo-7B-Instruct-GGUF

**Comment by nopperl** [comment]
@lsetiawan very interesting, nice to see that this contribution is useful to others.

Also great that you were able to convert the instruct model to HF format, which should be more useful for most users. However, I don't think the conversion works properly because it's missing `tokenizer.json` and `tokenizer_config.json`. You should be able to use these from [allenai/OLMo-7B-hf](https://huggingface.co/allenai/OLMo-7B-hf). I also recommend setting the `chat_template` in `tokenizer_config.json` to the one from [allenai/OLMo-7B-Instruct](https://huggingface.co/allenai/OLMo-7B-Instruct), so it can be used automatically.

**Pull request merged**
