### PR TITLE
Minor improvements in GPT2 tokenizer

### PR DESCRIPTION
**Pull request by goerch**
Fixes our bugs in #3502.

@cmp-nct : the small fixes in `bpe_gpt2_preprocess` could be relevant for you?

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
Does this make the tokenization of `wikitext` match with the Python, or is there still the 4-digit tokenization discrepancy?

**Comment by goerch** [comment]
> Does this make the tokenization of `wikitext` match with the Python, or is there still the 4-digit tokenization discrepancy?

The 4-digit tokenization discrepancy could be a [bug](https://github.com/ggerganov/llama.cpp/issues/3502#issuecomment-1753847439) in HF fast [tokenizers](https://github.com/huggingface/tokenizers/issues/1363).

**Comment by ggerganov** [comment]
Thank you for the thorough investigation. After @cebtenzzre's review we can merge this

**Comment by apage43** [comment]
remaining discrepancy from HF is caused by different pretokenzation: https://github.com/ggerganov/llama.cpp/issues/3502#issuecomment-1755852080

**Pull request merged**
