### PR TITLE
Add OpenLLaMA instructions to the README

### PR DESCRIPTION
**Pull request by ghost**
It's a good idea to show that llama.cpp supports OpenLLaMA as an alternative to Meta's original LLaMA.

### CODE REVIEW

**Review by Green-Sky — APPROVED** [review]

**Comment by Martin-Laclaustra** [comment]
If I have not missed any recent fix, convert.py is not able to produce ggml files correctly without applying a diff upfront. Thus, the suggested instructions in the README will not work.
https://github.com/ggerganov/llama.cpp/issues/1291#issuecomment-1584987455
https://github.com/ggerganov/llama.cpp/issues/1709#issuecomment-1597567777

**Review by Green-Sky — CHANGES_REQUESTED** [review]
> If I have not missed a recent fix, convert.py is not able to produce ggml files correctly without applying a diff upfront. Thus, the suggested instructions in the README will not work. [#1291 (comment)](https://github.com/ggerganov/llama.cpp/issues/1291#issuecomment-1584987455) [#1709 (comment)](https://github.com/ggerganov/llama.cpp/issues/1709#issuecomment-1597567777)

for the 3B yes. let's remove the 3B from the readme until it is compatible. :disappointed:

**Comment by Green-Sky** [comment]
trying to get 3B fixed #1958

**Comment by eiery** [comment]
I just tried out the 3B and indeed `main` [errors out](https://github.com/ggerganov/llama.cpp/issues/1291#issuecomment-1584698684) when loading the quantized ggml. I've used 7B and 13B successfully in the past but have never ran 3B due to the reduced quality.

I've removed 3B from the README for now and we can always add it back if @Green-Sky releases his fix.

**Comment by Green-Sky** [comment]
fix released :)

**Comment by eiery** [comment]
3B's tested and working on my end, so it looks like all sizes of OpenLLAMA are good to go.

**Review by Green-Sky — APPROVED** [review]

**Pull request merged**
