### PR TITLE
clip.cpp quantization update

### PR DESCRIPTION
**Pull request by cmp-nct**
Now uses ggml functions instead of hardcoded names and adds support to quantize into the modern Q-K variants. 
This is just the bare minimum to get k-types working - a more refined choice of types would be needed to get best quality on low quantizations.

I ran a few tests, it doesn't break anything I could notice and a Q6_K ViT works almost as well as Q8_0 but at 3 times the inference speed (given the cuda kernels are not optimized for Q8 but very well optimized for QK_6)

For llava-1.5 the clip model at Q6_K is just 245.82 MB

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by JianbangZ** [comment]
Are there any instructions on how to quantize the llava models? I follow the README to have both clip and LLM part converted to fp16 gguf.
But when I did 
/quantize $LLAVAPATH/llava-v1.5-7b/gguf/mmproj-model-f16.gguf $LLAVAPATH/gguf/mmproj-model-q6.gguf Q6_K

errors below:
main: quantizing '/data1/models/llava/llava-v1.5-7b/gguf/mmproj-model-f16.gguf' to '/data1/models/llava/gguf/mmproj-model-q6.gguf' as Q6_K
llama_model_loader: loaded meta data with 18 key-value pairs and 377 tensors from /data1/models/llava/llava-v1.5-7b/gguf/mmproj-model-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = clip
llama_model_loader: - kv   1:                      clip.has_text_encoder bool             = false
llama_model_loader: - kv   2:                    clip.has_vision_encoder bool             = true
llama_model_loader: - kv   3:                   clip.has_llava_projector bool             = true
llama_model_loader: - kv   4:                          general.file_type u32              = 1
llama_model_loader: - kv   5:                               general.name str              = openai/clip-vit-large-patch14-336
llama_model_loader: - kv   6:                        general.description str              = image encoder for LLaVA
llama_model_loader: - kv   7:                     clip.vision.image_size u32              = 336
llama_model_loader: - kv   8:                     clip.vision.patch_size u32              = 14
llama_model_loader: - kv   9:               clip.vision.embedding_length u32              = 1024
llama_model_loader: - kv  10:            clip.vision.feed_forward_length u32              = 4096
llama_model_loader: - kv  11:                 clip.vision.projection_dim u32              = 768
llama_model_loader: - kv  12:           clip.vision.attention.head_count u32              = 16
llama_model_loader: - kv  13:   clip.vision.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  14:                    clip.vision.block_count u32              = 23
llama_model_loader: - kv  15:                     clip.vision.image_mean arr[f32,3]       = [0.481455, 0.457828, 0.408211]
llama_model_loader: - kv  16:                      clip.vision.image_std arr[f32,3]       = [0.268630, 0.261303, 0.275777]
llama_model_loader: - kv  17:                              clip.use_gelu bool             = false
llama_model_loader: - type  f32:  235 tensors
llama_model_loader: - type  f16:  142 tensors
**llama_model_quantize: failed to quantize: unknown model architecture: 'clip'**
main: failed to quantize model from '/data1/models/llava/llava-v1.5-7b/gguf/mmproj-model-f16.gguf'

I also tried 
./quantize $LLAVAPATH/llava-v1.5-7b/gguf/ggml-model-f16.gguf $LLAVAPATH/gguf/gg-model-q5_0.gguf Q5_0
not successful neither
main: quantizing '/data1/models/llava/llava-v1.5-7b/gguf/ggml-model-f16.gguf' to '/data1/models/llava/gguf/gg-model-q5_0.gguf' as Q5_0
llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from /data1/models/llava/llava-v1.5-7b/gguf/ggml-model-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 1
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  18:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  19:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:  226 tensors
**llama_model_quantize: failed to quantize: basic_ios::clear: iostream error**
main: failed to quantize model from '/data1/models/llava/llava-v1.5-7b/gguf/ggml-model-f16.gguf'

**Comment by cmp-nct** [comment]
The quantize app currently does not support it.
I've uploaded a Q6K variant for sharegpt4v-7b (which is better than llava-1.5) here: https://huggingface.co/cmp-nct/ShareGPT4V-7B-quant-gguf/tree/main

you can do it yourself by manually hacking a quantization function into llava-cli.cpp (the quantization functions are all in clip code)

**Comment by JianbangZ** [comment]
> The quantize app currently does not support it. I've uploaded a Q6K variant for sharegpt4v-7b (which is better than llava-1.5) here: https://huggingface.co/cmp-nct/ShareGPT4V-7B-quant-gguf/tree/main
> 
> you can do it yourself by manually hacking a quantization function into llava-cli.cpp (the quantization functions are all in clip code)

Thanks

**Comment by lg123666** [comment]
> The quantize app currently does not support it. I've uploaded a Q6K variant for sharegpt4v-7b (which is better than llava-1.5) here: https://huggingface.co/cmp-nct/ShareGPT4V-7B-quant-gguf/tree/main
> 
> you can do it yourself by manually hacking a quantization function into llava-cli.cpp (the quantization functions are all in clip code)

Hello！
 I'm particularly interested in the code for the quantize llava projector with the Q6K specification. If it's convenient for you, could you kindly share that code?Additionally, I was wondering if you have any plans to contribute this code to the llama.cpp repository . Thanks

**Pull request merged**
