### PR TITLE
pipeline parallelism demo

### PR DESCRIPTION
**Pull request by slaren**
There isn't much synchronization required, just splitting the prompt into multiple micro-batches and queueing them in the CUDA streams is enough.

The micro-batch size is not configurable at the moment, it needs to be changed in `n_microbatch` in llama.cpp.

Incidentally, this also adds the ability to split batches into multiple micro-batches, so it is possible to call `llama_decode` with a batch larger than `n_batch`. I think the best way to implement this would be to use `n_batch` as the microbatch size, and modify the applications to ignore `n_batch` and submit the entire prompt or batch in a single call to `llama_decode`.

Offloading `tok_embd` improves performance significantly in this case.

3090Ti+3080, n_microbatch=256, tok_embd on GPU:
| model                          |       size |     params | backend    | ngl |    n_batch | ts           | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ------------ | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 512     | 6225.92 ± 298.23 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 1024    | 6744.66 ± 217.00 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 2048    |  6842.97 ± 43.25 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 4096    |  6068.10 ± 91.13 |

<details>
<summary>Master</summary>

MASTER, SINGLE GPU:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
| model                          |       size |     params | backend    | ngl |    n_batch | test       |    t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 512     |  5451.46 ± 64.45 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 1024    |  5256.66 ± 28.64 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 2048    |   4653.10 ± 9.91 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 4096    |  3510.43 ± 17.87 |

MASTER, TWO GPU:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3080, compute capability 8.6, VMM: yes
| model                          |       size |     params | backend    | ngl |    n_batch | test       |    t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 512     | 4983.31 ± 130.20 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 1024    | 4726.04 ± 131.48 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 2048    |  4199.27 ± 42.80 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | pp 4096    | 3125.11 ± 183.91 |

</details>

### CODE REVIEW

**Comment by JohannesGaessler** [comment]
| GPU    | Model         | Test   |   t/s master |   t/s sl/micro-batching |   Speedup |
|:-------|:--------------|:-------|-------------:|------------------------:|----------:|
| 3x P40 | llama 7B Q4_0 | pp512  |       922.56 |                  928.91 |      1.01 |
| 3x P40 | llama 7B Q4_0 | pp1024 |       896.02 |                  921.61 |      1.03 |
| 3x P40 | llama 7B Q4_0 | pp2048 |       837.39 |                  871.38 |      1.04 |
| 3x P40 | llama 7B Q4_0 | pp4096 |       705.73 |                  763.01 |      1.08 |
| 3x P40 | llama 7B Q4_0 | tg128  |        55.73 |                   53.93 |      0.97 |

With 3x P40 the improvement on my system is negligible. There is some improvement for large batch sizes but the best speed at 512 is barely affected. Also token generation seems to become slower.

For comparison, these are the results I get with `--split-mode row` on master:

| model                          |    n_batch | sm         | test       | t/s              |
| ------------------------------ | ---------: | ---------- | ---------- | ---------------: |
| llama 7B Q4_0                  |       4096 | row        | pp 512     | 748.55 ± 14.78   |
| llama 7B Q4_0                  |       4096 | row        | pp 1024    | 806.99 ± 6.59    |
| llama 7B Q4_0                  |       4096 | row        | pp 2048    | 787.77 ± 3.59    |
| llama 7B Q4_0                  |       4096 | row        | pp 4096    | 672.75 ± 1.10    |
| llama 7B Q4_0                  |       4096 | row        | tg 128     | 54.28 ± 0.07     |

**Comment by slaren** [comment]
The copy between GPUs is still synchronous, and this limits the parallelism to two GPUs (the last split of the previous micro-batch runs simultaneously with the first split of the next one, but other splits are synchronized). The micro batch size also has a large impact on the performance as expected, 256 works well for me, but the P40 may need larger batches.

**Comment by slaren** [comment]
Should be fixed now. This also improved performance for me with two GPUs.

| model                          |       size |     params | backend    | ngl |    n_batch | ts           | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ------------ | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 512     |  6605.23 ± 58.37 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 1024    |  7264.06 ± 56.93 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 2048    |   7367.69 ± 8.85 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       4096 | 1.20/1.00    | pp 4096    |  6611.81 ± 11.77 |

**Comment by ggerganov** [comment]
Outstanding!

How do you explain that microbatch size of 256 is better than 512 when for these GPUs individually a batch size of 512 is optimal?

What else is required for this to become mergeable, apart from the `n_batch` changes that you mentioned?

**Comment by slaren** [comment]
> How do you explain that microbatch size of 256 is better than 512 when for these GPUs individually a batch size of 512 is optimal?

In my system, the difference between batch size 256 and 512 is very small (master):

  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
| model                          |       size |     params | backend    | ngl |    n_batch | test       |    t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        256 | pp 512     |  5483.39 ± 15.99 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        256 | pp 1024    |  5039.27 ± 67.36 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        256 | pp 2048    |  4594.42 ± 45.94 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        512 | pp 512     |  5468.76 ± 88.49 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        512 | pp 1024    |  5038.14 ± 99.27 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |        512 | pp 2048    |  4660.13 ± 50.90 |

build: 4be5ef55 (1861)

> What else is required for this to become mergeable, apart from the n_batch changes that you mentioned?

We need to figure what to do with the `token_embd` tensor, do we add a parameter to offload it? There is also the issue of the CPU compute buffers. To avoid overwriting the inputs of the previous micro-batch, each one needs a different CPU backend buffer. Currently it just allocated a fixed number, does this need to be configurable? Is there an optimal number of buffers after which adding more does nothing? I am not sure yet.

**Comment by JohannesGaessler** [comment]
With the latest commit (af789e7e) and n_microbatch = 512:

| GPU    | Model         | Test   |   t/s master |   t/s sl/micro-batching |   Speedup |
|:-------|:--------------|:-------|-------------:|------------------------:|----------:|
| 2x P40 | llama 7B Q4_0 | pp512  |       931.35 |                  934.61 |      1.00 |
| 2x P40 | llama 7B Q4_0 | pp1024 |       900.90 |                  974.55 |      1.08 |
| 2x P40 | llama 7B Q4_0 | pp2048 |       840.91 |                  954.64 |      1.14 |
| 2x P40 | llama 7B Q4_0 | pp4096 |       708.91 |                  867.86 |      1.22 |
| 2x P40 | llama 7B Q4_0 | tg128  |        56.02 |                   55.96 |      1.00 |
| 3x P40 | llama 7B Q4_0 | pp512  |       910.35 |                  923.13 |      1.01 |
| 3x P40 | llama 7B Q4_0 | pp1024 |       896.07 |                  971.06 |      1.08 |
| 3x P40 | llama 7B Q4_0 | pp2048 |       836.93 |                  949.95 |      1.14 |
| 3x P40 | llama 7B Q4_0 | pp4096 |       704.61 |                  863.59 |      1.23 |
| 3x P40 | llama 7B Q4_0 | tg128  |        55.64 |                   54.14 |      0.97 |

>How do you explain that microbatch size of 256 is better than 512 when for these GPUs individually a batch size of 512 is optimal?

You get higher GPU utilization with microbatching because the second GPU can start after the first GPU has processed 256 tokens instead of having to wait for the full batch size.

>What else is required for this to become mergeable, apart from the n_batch changes that you mentioned?

To make microbatching actually perform well I think it will be necessary to write better dequantization kernels. Presumably the reason slaren used FP16 is because in that case the weight matrices do not need to be dequantized so the performance for small batches is comparatively good. The kernel I wrote in https://github.com/ggerganov/llama.cpp/pull/4895 could presumably be adapted for other formats but templating it will be difficult. With MMQ the weight matrices do not need to be dequantized but then the baseline performance for Volta or newer is lower so the utility is questionable. If https://github.com/ggerganov/llama.cpp/pull/4801 works out it would also help a lot since dequantizing to int8 needs only half as much memory bendwidth as dequantizing to

**Comment by ggerganov** [comment]
@slaren In your results why does the performance drops for pp 4096 compared to pp 2048? My expectation would be that with this parallelism the performance should flat out at some pp and do not drop.

**Comment by slaren** [comment]
The performance is best with F16, but there is still a good speedup with Q4_0. There are still improvements. 

| model                          | test     |  4be5ef55 t/s |  af789e7e t/s |  speedup |
| ------------------------------ | -------- | ------------: | ------------: | -------: |
| llama 7B Q4_0                  | pp 512   | 3936.45       | 4505.63       | 1.144    |
| llama 7B Q4_0                  | pp 1024  | 4269.13       | 5140.05       | 1.204    |
| llama 7B Q4_0                  | pp 2048  | 3996.18       | 5324.33       | 1.332    |
| llama 7B Q4_0                  | pp 4096  | 3148.68       | 4974.44       | 1.579    |

> In your results why does the performance drops for pp 4096 compared to pp 2048? My expectation would be that with this parallelism the performance should flat out at some pp and do not drop.

Performance always drops when the context is larger, but the speedup relative to master is higher with pp 4096 (it's almost 2x).

**Comment by ggerganov** [comment]
Just for fun, here are results on 8x RTX 4090 with `n_microbatch = 256`:

ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 8 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 2: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 3: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 4: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 5: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 6: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
  Device 7: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
| model                          |       size |     params | backend    | ngl |    n_batch | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------: | ---------- | ---------------: |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | pp 512     | 10870.38 ± 1347.13 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | pp 1024    | 16350.59 ± 1461.70 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | pp 2048    | 22210.58 ± 1207.91 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | pp 4096    | 23366.68 ± 812.25 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | pp 8192    | 20061.01 ± 164.88 |
| llama 7B F16                   |  12.55 GiB |     6.74 B | CUDA       |  99 |       8192 | tg 128     |     59.27 ± 0.03 |

build: af789e7 (1861)

**Comment by JohannesGaessler** [comment]
>@slaren In your results why does the performance drops for pp 4096 compared to pp 2048? My expectation would be that with this parallelism the performance should flat out at some pp and do not drop.

>Edit: Ah it's because the attention compute grows since it is a single sequence. Got it.

Very large batches already have this behavior on master. The main problem is that the compute needed for soft max scales with batch size. This could be mitigated by writing a softmax kernel specifically for a diagonal infinite mask. You could potentially also save compute by not computing those elements that are later going to be masked anyways.

**Comment by ggerganov** [comment]
We also lack flash attention which results in 2 extra writes and reads of the KQ data to global memory

**Comment by cmp-nct** [comment]
Awesome, 20000 tokens/sec .. that's quite a change to where we've been a month ago ;) I think it was 280/sec in that configuration.

**Comment by sorasoras** [comment]
This is interesting in my use case.
I am running 13B Q2K on 7900xtx it get like 70T/s TG batch translation. i run two instance,it could hit 43*2=86t/s

**Comment by sorasoras** [comment]
```
 GET_ROWS(type=q2_K,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=q2_K,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=q2_K,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=q2_K,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=q3_K,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=q3_K,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=q3_K,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=q3_K,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=q4_K,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=q4_K,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=q4_K,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=q4_K,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=q5_K,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=q5_K,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=q5_K,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=q5_K,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=q6_K,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=q6_K,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=q6_K,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=q6_K,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=iq2_xxs,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=iq2_xxs,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=iq2_xxs,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=iq2_xxs,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=iq2_xs,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=iq2_xs,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=iq2_xs,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=iq2_xs,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
  GET_ROWS(type=i32,n=256,m=5,r=4,b=1,v=0): not supported [CUDA0]
  GET_ROWS(type=i32,n=256,m=5,r=4,b=1,v=1): not supported [CUDA0]
  GET_ROWS(type=i32,n=256,m=5,r=4,b=7,v=0): not supported [CUDA0]
  GET_ROWS(type=i32,n=256,m=5,r=4,b=7,v=1): not supported [CUDA0]
```
get_rows don't seems to working right now.

**Comment by slaren** [comment]
It is expected, the CUDA get_rows implementation does not support k-quants.

**Comment by cmp-nct** [comment]
> and it could even be used with partial offloading to do work simultaneously on the CPU and on the GPU (that would require making the CPU backend asynchronous). However, the allocation logic is going to cha

Sounds very promising, I'm happy my little suggestion goes so big.
I didn't consider that CPU and GPU parallelization is a thing, that could turn out huge for bigger models if this works well.. Especially when a model is "barely" not fitting on GPU, then the CPU would have just a tiny portion of the layers so it might be able to not delay the model beyond memory transfer times.

Very nice work so far

**Comment by slaren** [comment]
Technically it is possible, there is no reason to treat the CPU backend different than any other backend. But realistically, the CPU is so much slower than the GPU that I wouldn't expect any meaningful improvement in performance, and as it is now, most matrix multiplications are always done on the GPU during prompt processing anyway.

**Comment by JohannesGaessler** [comment]
It is true that the GPU is used for matrix multiplications with batch sizes >= 32 anyways. But for those matrix multiplications most of the runtime goes towards CPU<->GPU data transfers which can be executed in parallel with GPU computations. So it should still help quite a lot.

**Comment by phymbert** [comment]
Hi @slaren, thanks a lot for your effort on cuda backend.

Here are the results, on my infra 2 A100 80GB, what do you think ?

build with: `-DCMAKE_BUILD_TYPE=Release -DLLAMA_CUBLAS=ON -DCMAKE_CUDA_ARCHITECTURES=native`

Models: `codellama7b-(f16|q4_0),codellama70b-q4.0,mixtral8x7b-v0.1-q4_0`

<details>
<summary><b>sl/micro-batching f69ab895202713aba2401673e71f2cee5f031305</b></summary>

#### 1a. `CUDA_VISIBLE_DEVICES=0`


#### 1b. `CUDA_VISIBLE_DEVICES=0,1`


</details>

<details>
<summary><b>master f105471ef6aa4727afac8240da398590d7277f45</b></summary>

#### 2a. `CUDA_VISIBLE_DEVICES=0`



#### 2b. `CUDA_VISIBLE_DEVICES=0,1`


</details>

If it can help, I see lot of `not enough buffers, syncing now` on your branch (I had to comment the line).

Note: @ggerganov  I feel like the model name for mixtral8x7b is misleading, maybe we should include the moe config in the model name. I will have a look.

**Comment by slaren** [comment]
The results look reasonable. Mixtral does not work with pipeline parallelism due to the way the `mul_mat_id` operation (for MoE) is implemented, it forces a synchronization which stops the asynchronous computation.

This is branch is very outdated and the final implementation will be very different, and at this point there is no need to run more tests on this branch. I'll close this PR to avoid confusion.

**Pull request closed without merging**
