### PR TITLE
Optimize AVX2 ggml_vec_dot_q4_0

### PR DESCRIPTION
**Pull request by slaren**
This is a port of @perserk's and @sw's AVX implementation of `ggml_vec_dot_q4_0` (#617) to AVX2.

```
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
BM_ggml_vec_dot_q4_0_avx             668 ns          668 ns      1055239
BM_ggml_vec_dot_q4_0_avx2            578 ns          578 ns      1209367
BM_ggml_vec_dot_q4_0_avx2_new        522 ns          522 ns      1346143
```

Before:
```
llama_print_timings: prompt eval time = 10113.34 ms /   116 tokens (   87.18 ms per token)
llama_print_timings:        eval time = 20360.13 ms /   127 runs   (  160.32 ms per run)

perplexity : calculating perplexity over 655 chunks
42.05 seconds per pass - ETA 7.65 hours
[1]4.6512,[2]5.2613,[3]6.0903,
```

After:
```
llama_print_timings: prompt eval time =  7627.11 ms /   116 tokens (   65.75 ms per token)
llama_print_timings:        eval time = 19477.24 ms /   127 runs   (  153.36 ms per run)

perplexity : calculating perplexity over 655 chunks
31.88 seconds per pass - ETA 5.80 hours
[1]4.5619,[2]5.1787,[3]6.0491,
```

### CODE REVIEW

**Comment by rabidcopy** [comment]
Very nice. Compiled on Windows and went from 230ms per token to 195ms per token on average. Which sounds even more promising because I was getting 185ms per token as is on Linux without these optimizations.

**Review by ggerganov — APPROVED** [review]

**Comment by slaren** [comment]
>I wonder how much the speed-up is due to the loop unrolling, though.

It's not much at all, I couldn't even measure a difference reliably in the google benchmark code, however it seemed to consistently lower perplexity times by a couple of seconds so I decided to leave it in.

**Comment by rabidcopy** [comment]
> I'm on msvc windows so im not sure if those improvements would translate to linux

Still getting more or less the same average of 138ms per token with my test prompt on Linux. Will to compare on Windows later.

**Comment by slaren** [comment]
I don't think that we can reliably measure small performance improvements just by looking at the eval time, the variance is too high. For now I found that the perplexity time per pass is a lot more stable.

**Comment by jart** [comment]
Intel support was already in a somewhat broken state compared to Apple M1 support before this change. The differences are kind of minor, like a missing comma. This change has a bug that caused completely different answers that don't make sense to show up. Although it was still real spoken language. I've seen worse. Sometimes when working on changes, I get something wrong and it speaks complete gibberish!

I care much more about reliability, determinism, predictability, and accuracy than I care about an 8% performance boost. Yes differences in floating point exist between architectures. But isn't it usually minor? Stuff like NAN vs. -NAN? Whatever defined differences in behavior exist, I would ideally hope we could avoid triggering them, in the interest of better correctness.

**Comment by jart** [comment]
Or rather than correctness, I should say consistency.

**Comment by rabidcopy** [comment]
Hm, for some reason now that this has been merged, I'm not getting the same performance uplifts, but am getting different outputs. Does this somehow conflict with #617?

**Comment by rabidcopy** [comment]
> @rabidcopy : the change in inference causes an EOT token to be generated, so I don't think you can compare the performance. Try a longer run with a different seed.

Had a longer run that is a pretty similar length of tokens despite both seeds not matching up.
Left is current master. Right is this PR before being merged into master.
image

**Comment by slaren** [comment]
On current master:
```
perplexity : calculating perplexity over 655 chunks
32.12 seconds per pass - ETA 5.84 hours
```

Which is in line with what I expected from this PR.

**Comment by rabidcopy** [comment]
It's so strange. This PR by itself shows those uplifts for me, but on master, they seem to disappear when combined with #617. While this doesn't seem to be the case with #654 with #617 already merged.
#642 without #617:  329ms / 409 tokens
#642 with #617 on master: 390ms / 398 tokens (provided different output on same seed)
#654 merged on top of #617: 317ms / 409 tokens

**Comment by slaren** [comment]
Keep in my mind that even in my tests the biggest improvement is when evaluating in batches. The performance difference in generation is within the margin of error. When BLAS is used for the prompt, this function is not used at all.

**Comment by rabidcopy** [comment]
I just really can't get my head around why current master has this regression in the performance uplifts that I clearly get with this PR. 🤷

**Comment by slaren** [comment]
@rabidcopy if you are on linux and using GCC, can you try lowering the unroll number in `ggml.c:1967`:
```c++
#pragma GCC unroll 16
```
I wonder if there is some issue with the instruction cache.

**Comment by SebastianApel** [comment]
@rabidcopy For me, there's an additional performance improvement when compiling with `-march=native.`  I've not tried with #642, but it is there with #654.

**Comment by rabidcopy** [comment]
> @rabidcopy if you are on linux and using GCC, can you try lowering the unroll number in `ggml.c:1967`:
> 
> ```c++
> #pragma GCC unroll 16
> ```
> 
> I wonder if there is some issue with the instruction cache.

Using `cmake` so that gets ignored. But I do note that in #654, there's this. https://github.com/ggerganov/llama.cpp/pull/654/files#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR2024

**Comment by slaren** [comment]
You may still be using GCC even if you use cmake.

**Comment by rabidcopy** [comment]
> You may still be using GCC even if you use cmake.

Ah, duh. Well, going to mess with that then.

**Comment by rabidcopy** [comment]
Oh man. I have egg on my face. It appears I somehow wasn't actually on the latest master. Only now noticed that sections were missing in ggml.c that didn't make sense.
image
Left is master, right is #654. 
I am so deeply sorry. It appears I got my folders mixed up. Nothing is wrong with master and there's no phantom regression or instruction cache issue. Ugh.

**Pull request merged**
