### PR TITLE
Adjust prompt processing thread count seperately from n_threads

### LINKED ISSUE #2498: Controlling the number of threads for CLBlast/cuBLAS prompt processing
Currently the number of threads used for prompt processing and inference is defined by `n_threads` unless CPU-based BLAS is used. In that case it is locked to 1 for processing only since OpenBLAS and friends are already multithreaded to begin with.

https://github.com/ggerganov/llama.cpp/blob/8183159cf3def112f6d1fe94815fce70e1bffa12/llama.cpp#L1817-L1819

Meanwhile, GPU BLAS implementations spawn `n_threads` threads for prompt processing. Here's a CLBlast run with the default 4 threads on my 4 core/8 thread CPU:
```
llama_print_timings:        load time =   391.66 ms
llama_print_timings:      sample time =    78.83 ms /   100 runs   (    0.79 ms per token,  1268.50 tokens per second)
llama_print_timings: prompt eval time = 11181.22 ms /   401 tokens (   27.88 ms per token,    35.86 tokens per second)
llama_print_timings:        eval time = 21230.25 ms /    99 runs   (  214.45 ms per token,     4.66 tokens per second)
llama_print_timings:       total time = 32514.96 ms
```
I get around 28 ms/token during prompt processing. Now let's try running with a different thread count by modifying line 1819:
```
n_threads = N >= 32 && (ggml_cpu_has_blas() || ggml_cpu_has_gpublas()) ? <NUMBER OF THREADS> : n_threads;
```

| Thread Count | ms/token (averaged over multiple runs) |
| --- | --- |
| 1 | 44 |
| 2 | 29 |
| 3 | 28 |
| 4 | 28 |
| 8 | 30 |

On the prompt processing side I'm able to get the same results with only 2 or 3 threads, which saves power and puts less load on the CPU. Meanwhile I get optimal inference speed with 4 threads (I use the CPU for inference as it's for some reason faster than the GPU), so there's a disrepancy there.

Is anyone else seeing this as well? I'm thinking of adding an additional command line option to control the prompt processing thread count.

### PR DESCRIPTION
**Pull request by netrunnereve**
There are advantages to having a different thread count for prompt processing vs. inference, as the former is limited by CPU speed/thread scaling while the latter is limited by memory bandwidth. If you use GPU BLAS for prompt processing a lower thread count may also be desired. [Here's one of my examples](https://github.com/ggerganov/llama.cpp/pull/2372#issuecomment-1652736233) where 8 thread prompt processing is faster than 4 thread prompt processing, while inference speed remains the same regardless of thread count. I can't find those posts at the moment but I've heard other people running on 20+ core servers saying that prompt processing scales decently well.

Codewise this is a simple change, but it is a **breaking change** in that it modifies `llama_eval` so that we can pass in `pp_threads`. ~I'm leaving this as a draft for now to get feedback, especially from people with big CPU-only servers which may benefit from this.~

~~Note that for now I only added support for `main`, `perplexity` and friends currently have `pp_threads` set to `n_threads`.~~
```
usage: ./main [options]
...
  -t N, --threads N     number of threads to use during computation (default: 4)
  -ppt N, --pp-threads N
                        number of threads to use during prompt processing (default: 4)
```
Resolves #2498.

### CODE REVIEW

**Comment by ggerganov** [comment]
On 16-core Ryzen 9 5950X the prompt processing speed improves up to 16 threads.

**Comment by slaren** [comment]
With a 13900k (8+16 cores), prompt processing scales all the way up to 32 threads, while for generation 8 threads is best.

**Comment by klosax** [comment]
> @klosax I don't really see a point in specifically adding a control for OpenBLAS when the [default implementation already matches it](https://github.com/ggerganov/llama.cpp/pull/2372) performance wise.

I didnt know. I that case we could drop support for OpenBLAS I guess.

**Comment by slaren** [comment]
A few more details with the 13900k. During generation with 8 threads, the CPU pulls ~170W, and with 32 threads ~250W, despite being slower. So there is a significant advantage both in performance and power usage of being able to use a different number of threads for generation and prompt processing.

However, I am not sure that changing the interface of `llama_eval` is a good idea. The same can be achieved by the application by passing a different number of threads to `llama_eval` depending on `n_tokens`, without a breaking API change. Maybe we could update `main` and other examples to do this instead?

In the long term, I think that it would be better to move the number of threads to `llama_context_params` or similar, maybe with a function to change the value after initialization if needed. But that should be done at a later time, ideally together with other breaking API changes.

`./llama-bench -t 4,8,16,24,32 -r 2`
| model                          | backend    |  n_threads | test       |             t/s |
| ------------------------------ | ---------- | ---------: | ---------- | --------------: |
| LLaMA 7B mostly Q4_0           | CPU        |          4 | pp 512     |    22.14 ± 1.31 |
| LLaMA 7B mostly Q4_0           | CPU        |          8 | pp 512     |    41.02 ± 0.30 |
| LLaMA 7B mostly Q4_0           | CPU        |         16 | pp 512     |    32.85 ± 0.48 |
| LLaMA 7B mostly Q4_0           | CPU        |         24 | pp 512     |    47.05 ± 0.14 |
| LLaMA 7B mostly Q4_0           | CPU        |         32 | pp 512     |    60.16 ± 0.34 |
| LLaMA 7B mostly Q4_0           | CPU        |          4 | tg 128     |    12.85 ± 0.15 |
| LLaMA 7B mostly Q4_0           | CPU        |          8 | tg 128     |    18.43 ± 0.40 |
| LLaMA 7B mostly Q4_0           | CPU        |         16 | tg 128     |    15.48 ± 0.07 |
| LLaMA 7B mostly Q4_0           | CPU        |         24 | tg 128     |    16.91 ± 0.03 |
| LLaMA 7B mostly Q4_0           | CPU        |         32 | tg 128     |    17.02 ± 0.20 |

build: 1f0bccb (1007)

**Comment by kiratp** [comment]
One more data point in support of separate thread counts

This is on a GCP t2d-standartd-32 instance. 32 Milan cors with SMT/HT turned off so 1 core = 1 physical core - https://cloud.google.com/compute/docs/general-purpose-machines#t2d_machines

```
root@ml-perf-testing:/usr/src/app/llama.cpp# ./llama-bench --model /usr/src/models/guild_navigator_v1.ggml.q4_k_m.bin -t 2,8,16,22,28,30,31,32
| model                          | backend    |  n_threads | test       |             t/s |
| ------------------------------ | ---------- | ---------: | ---------- | --------------: |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |          2 | pp 512     |    34.75 ± 1.77 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |          8 | pp 512     |    34.44 ± 1.71 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         16 | pp 512     |    34.57 ± 1.11 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         22 | pp 512     |    33.10 ± 0.98 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         28 | pp 512     |    29.34 ± 5.15 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         30 | pp 512     |    23.68 ± 1.64 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         31 | pp 512     |    25.66 ± 2.93 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         32 | pp 512     |    32.49 ± 2.29 |
LLaMA 7B mostly Q4_K - Medium  | BLAS       |          2 | tg 128     |     4.43 ± 1.70 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |          8 | tg 128     |    17.72 ± 1.97 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         16 | tg 128     |    21.51 ± 0.52 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         22 | tg 128     |    21.18 ± 1.47 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         28 | tg 128     |    19.85 ± 0.79 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         30 | tg 128     |    17.71 ± 3.40 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         31 | tg 128     |    21.59 ± 1.88 |
| LLaMA 7B mostly Q4_K - Medium  | BLAS       |         32 | tg 128     |    17.96 ± 4.88 |

build: 1f0bccb (1007)
```

This line from llama.cpp seems to explain the pp speed curve. 

https://github.com/ggerganov/llama.cpp/blob/1f0bccb27929e261744c979bc75114955da49e98/llama.cpp#L1841

```
    // for big prompts, if BLAS is enabled, it is better to use only one thread
    // otherwise, the threads are spin-lock waiting for the BLAS calls and are degrading the performance
    n_threads = N >= 32 && ggml_cpu_has_blas() && !ggml_cpu_has_gpublas() ? 1 : n_threads;
```

**Comment by ggerganov** [comment]
> However, I am not sure that changing the interface of llama_eval is a good idea. The same can be achieved by the application by passing a different number of threads to llama_eval depending on n_tokens, without a breaking API change. Maybe we could update main and other examples to do this instead?

I agree that it would be better to move the logic for the number of threads to the application.

**Comment by ggerganov** [comment]
Thanks. This is still not great - sorry for the extra work.

We should do what @slaren suggested and move this in `llama_context_params`.
We should also introduce `llama_model_params` as suggested here: https://github.com/ggerganov/llama.cpp/pull/2620#issuecomment-1678952736

I'm not worried about the API breaking. If anyone wants to give it a try is welcome, else I'll try to implement this soon

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by netrunnereve** [comment]
Welp it looks like I closed this and threw out the fork as well. I'll keep working on this after `llama_model_params` support is added.

**Comment by slaren** [comment]
I am adding this change in https://github.com/ggerganov/llama.cpp/pull/3301 to avoid having two API changes shortly after each other.

**Pull request closed without merging**
