### PR TITLE
minor layout improvements

### PR DESCRIPTION
**Pull request by rsoika**
This is a minor layout improvement. I only added some CSS definitions and a smaller fix in the script to display the chat buttons:

Before: 

grafik

After:

grafik

### CODE REVIEW

**Comment by phymbert** [comment]
Hi, thanks, you need to run the `deps.sh`

**Comment by phymbert** [comment]
@rsoika maybe it was not clear: static assets are converted to *.cpp generated sources and embedded in the server binary.

See the CI server workflow:
Run locally `deps.sh` and commit the generated changes.

- #6325

**Review by phymbert — APPROVED** [review]

**Comment by ggerganov** [comment]
I'm not very happy with this change. Here is what is looks in my setup (left is new, right is old):

image

Here are some recommendations:

- The active text in the textboxes should remain with high contrast as before
- The color of the buttons should match the color of the sliders (in my case green)
- No need to increase the font-size in the inputs (or at least not so prominently)

**Comment by rsoika** [comment]
If you do not like it you can roll it back. 
Or we remove 

```
color: #666;
font-size: 1.1rem;
```


and add the slider color
`
input[type='range']{ accent-color: #3584e4; }`

**Comment by phymbert** [comment]
@rsoika Sorry I do not use the server web ui myself, I was wrongly thinking the proposed changes were OK for everyone.

Feel free to reopen a PR with recommandations provided by @ggerganov.

**Pull request merged**
