### PR TITLE
Fixed llama_set_state_data declaration not matching definition

### PR DESCRIPTION
**Pull request by niansa**
Nothing to comment here.

### CODE REVIEW

**Comment by ggerganov** [comment]
Probably looking at something outdated - I changed the definition today:

https://github.com/ggerganov/llama.cpp/blob/affc76edfdefa7b326f526e463cc65ff13fcfb92/llama.cpp#L2676

**Comment by niansa** [comment]
@ggerganov actually nope, it's still in master like that

**Comment by niansa** [comment]
Seems like you've reverted your fix right after you've commited it...

**Comment by ggerganov** [comment]
I changed `const uint8_t * src` to `uint8_t * src` on purpose (both declaration and definition), because in the implementation we assign it to `void *` which used to generate a compile warning about not being const correct

**Comment by imaami** [comment]
> I changed `const uint8_t * src` to `uint8_t * src` on purpose (both declaration and definition), because in the implementation we assign it to `void *` which used to generate a compile warning about not being const correct:
> 
> [8a203f9](https://github.com/ggerganov/llama.cpp/commit/8a203f9fa1b24e010be8f35ebbbd6786293684cb)

Is it possible that the source buffer is modified during `llama_set_state_data()`? If so, then non-const is the correct type, but in that case the API should clearly document that the input data may be modified.

Looks like the cast to `void *` is done when assigning the pointer to `ggml_tensor::data`, which is `void *`. Is there a reason why that member can't be `void const *data`? Is it sometimes used to store the address of memory that gets modified? If that's the case then it seems a tad problematic in itself.

Requiring the caller to `const_cast` a potentially read-only buffer to non-const is sus, and the alternative of making a temporary copy every time isn't that great either. No matter how you put it it's just wrong to cast towards less const-ness, even if it happens inside the implementation (like casting a potentially read-only data pointer to `void *`).

If `ggml_tensor::data` can't be made `void const *` then a C-style hacky solution would be replacing it with

```c
    union {
        void *data;
        void const *cdata;
    };```

and changing the implementation to only use one of the other union member depending on what purpose the pointer happens to serve given the operation.

**Pull request closed without merging**
