### PR TITLE
ci: bench: add more ftype, fix triggers and bot comment

### PR DESCRIPTION
**Pull request by phymbert**
### Motivation

- PR comment pops up in all PRs even unrelated to speed, it is a little bit distracting.
- benchmark results vary probably because a fixed seed is not set
- add more model ftypes

### Proposition
- reduce file workflow path trigger to only `llama.cpp`, `ggml.c` and cuda files.
- add seed param in k6 `script.js`
- reduce the comment to the first line, so it does not use too much space in the PR, add a warning notice
- add `q8_0` and `f16` `phi-2` quants
- add more metrics in the commit status to later on show performance history

#### Tests
Tested here on a self-hosted GCP L4 ( sic ^) ) :
- https://github.com/phymbert/llama.cpp/pull/5#issuecomment-2035359125
- https://github.com/phymbert/llama.cpp/actions/runs/8544724268

#### References
- https://github.com/ggerganov/llama.cpp/issues/6233#issuecomment-2029567981

####
- [ ] @ggerganov please restart the github runner manager on the azure T4 node with https://github.com/ggml-org/ci/pull/3

### CODE REVIEW

**Comment by phymbert** [comment]
@ggerganov Georgi, as more and more models are MOE based, I suggest later on add mixtral8x7b, thoughts ?

**Review by ggerganov — APPROVED** [review]
Yes, we can continue to scale with more models in the future. For now, let's give it some more time to see how the existing benchmarks perform and gather feedback about what's useful.

**Comment by phymbert** [comment]
Understood, please merge once you have restarted the github manager

**Comment by ggerganov** [comment]
Updated to `master` of https://github.com/ggml-org/ci and restarted

**Pull request merged**
