### PR TITLE
WIP: New python based entry point for containers

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by jpodivin** [comment]
@SlyEcho This is the endpoint change I've mentioned.

**Comment by jpodivin** [comment]
> Does it allow passing arguments with spaces?

I'm not sure what exactly you mean. My implementation makes some changes. But, for example, these work:

`docker run -v /local/model/path/:/models llama.cpp:endpoint --all-in-one /models/7B`
`docker run -v/local/model/path/:/models llama.cpp:endpoint --run /models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n 512`

But I wouldn't really like to get this specific version merged. I would prefer subcommands over those args, as I wouldn't have to worry about overloading arguments between run/quantize/etc.

**Comment by SlyEcho** [comment]
That's what I meant.

> I would prefer subcommands over those args, as I wouldn't have to worry about overloading arguments between run/quantize/etc

Couldn't it be done by just checking `argv[1]`? I don't know how to do it in Python but there is not really any "parsing" needed, I think, just switching by the string value. Kind of like the old script did.

**Comment by jpodivin** [comment]
Advantage of python `argparse` is that it does take care of those checks for you, including edge cases.
You can define CLI of arbitrary complexity using combination of commands, subcommands and args. The help, error handling, type checks and defaults come in the bargain.

Now you can do that with plain conditionals checks on argv elements, but you would also have to implement some other logic to make it robust. And that puts unnecessary burden on maintainers.

What I would propose is something like this:
```
docker run -v <local>:<container> [ quantize | all-in-one | convert | run ]
```
Each one of those would have their own args, so no chance of overloading. Actually I'm bit ashamed I've not proposed it already.

**Comment by jpodivin** [comment]
I have the promised demo.[0] It's aciinema[1] recording, so you can play it in terminal. I do recommend using the `-i 1` when playing it, as otherwise you will have to endure long gaps in activity, as my desktop struggles. Also, I've been doing other things, and after quantization command I forgot I was recording for couple of minutes.  


[0] https://gist.github.com/jpodivin/ef4d037c21bfc2ce0a9f91b1d3f29ea5
[1] https://asciinema.org/docs/usage

**Comment by SlyEcho** [comment]
I have not had time to test it yet.

**Comment by jpodivin** [comment]
@SlyEcho  So are we moving this out of WIP? Or should I just close it?

**Comment by jpodivin** [comment]
Right. I'll take a look at it.

**Comment by jpodivin** [comment]
@SlyEcho I've updated the script to work with new model format and server binary. Also I've replaced the endpoint in other container files. I've tested the standard file quantization, conversion, run and server binary with open-llama.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
