### PR TITLE
Correctly implement credentialed CORS for server

### PR DESCRIPTION
**Pull request by Azeirah**
Refer to https://github.com/ggerganov/llama.cpp/issues/4511 for details.

This PR implements CORS for credentialed requests for the server. A credentialed request is when you send the Authorization header along with a request, some clients send an empty or placeholder API key because OpenAI requires one, whereas this server doesn't necessarily require one.

You can test that it works with this extremely simple client that implements both a regular client as well as one that sends an API key.

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>llama.cpp server CORS</title>
</head>
<body>
	<button class="without">Send without auth</button>
	<button class="with">Send with auth</button>

	<input type="text" class="url" placeholder="localhost:8080/v1/completion">

	<pre>
		<code class="out">
			
		</code>
	</pre>

	<script type="text/javascript">
		const $out = document.querySelector(".out");

		const $btn_without = document.querySelector(".without");
		const $btn_with = document.querySelector(".with");
		const $url = document.querySelector(".url");

		$btn_with.addEventListener("click", async function () {
			const res = await fetch($url.value, {
				method: "POST",
				headers: {
					Authorization: "no key",
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					messages: [{role: "user", content: "What is the color of the sky?"}]
				})
			});
			$out.innerText = JSON.stringify(JSON.parse(await res.text()), null, 4);
		});

		$btn_without.addEventListener("click", async function () {
			const res = await fetch($url.value, {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					messages: [{role: "user", content: "What is the color of the sky?"}]
				})
			});
			$out.innerText = JSON.stringify(JSON.parse(await res.text()), null, 4);
		});
	</script>
</body>
</html>
```

The server should still work with any other client in all scenarios.

I think it's worth making a list of clients this code has been tested against to ensure there are no regressions.

- [x] The test client in this code
- [x] Obsidian Copilot plugin
- [x] CodeGPT plugin for Jetbrains
- [x] llama.cpp built-in server
- [ ] VSCode plugins?
- Browser clients?
    - [x] Typingmind.com
- [ ] Electron-based clients?

### CODE REVIEW

**Comment by Azeirah** [comment]
@kir-gadjello @tobi What other clients should be tested? I'm mentioning you because you are in the openAI server thread https://github.com/ggerganov/llama.cpp/pull/4198

**Comment by battaglia01** [comment]
I typed cloned this and "make" and got the following error:

```
$ make
I llama.cpp build info:
I UNAME_S:   Darwin
I UNAME_P:   arm
I UNAME_M:   arm64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_METAL  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_METAL  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi
I NVCCFLAGS:
I LDFLAGS:   -framework Accelerate -framework Foundation -framework Metal -framework MetalKit
I CC:        Apple clang version 14.0.0 (clang-1400.0.29.202)
I CXX:       Apple clang version 14.0.0 (clang-1400.0.29.202)
...
c++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_METAL  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -Iexamples/server examples/server/server.cpp examples/llava/clip.cpp ggml.o llama.o common.o sampling.o grammar-parser.o build-info.o ggml-metal.o ggml-alloc.o ggml-backend.o ggml-quants.o -o server -framework Accelerate -framework Foundation -framework Metal -framework MetalKit   -Wno-cast-qual
examples/server/server.cpp:2716:28: warning: lambda capture 'llama' is not used [-Wunused-lambda-capture]
    svr.Options(R"(.*)", [&llama, &validate_api_key](const httplib::Request &req, httplib::Response &res) {
                          ~^~~~~~
examples/server/server.cpp:2716:36: warning: lambda capture 'validate_api_key' is not used [-Wunused-lambda-capture]
    svr.Options(R"(.*)", [&llama, &validate_api_key](const httplib::Request &req, httplib::Response &res) {
                                ~~~^~~~~~~~~~~~~~~~
examples/server/server.cpp:2753:63: error: use of undeclared identifier 'req'; did you mean 'res'?
                res.set_header("Access-Control-Allow-Origin", req.get_header_value("Origin"));
                                                              ^~~
                                                              res
examples/server/server.cpp:2751:85: note: 'res' declared here
    svr.Get("/props", [&llama](const httplib::Request & /*req*/, httplib::Response &res)
                                                                                    ^
examples/server/server.cpp:2833:63: error: use of undeclared identifier 'req'; did you mean 'res'?
                res.set_header("Access-Control-Allow-Origin", req.get_header_value("Origin"));
                                                              ^~~
                                                              res
examples/server/server.cpp:2831:81: note: 'res' declared here
    svr.Get("/v1/models", [&params](const httplib::Request&, httplib::Response& res)
                                                                                ^
2 warnings and 2 errors generated.
make: *** [server] Error 1
```

**Comment by battaglia01** [comment]
Bizarrely, for whatever reason it looks like `req` was commented out on line 2751:

```
svr.Get("/props", [&llama](const httplib::Request & /*req*/, httplib::Response &res)
```

And on 2831 there's also no req

```
svr.Get("/v1/models", [&params](const httplib::Request&, httplib::Response& res)
```

Changing both explicitly to `const httplib::Request& req` makes it compile.

**Comment by Azeirah** [comment]
> Bizarrely, for whatever reason it looks like `req` was commented out on line 2751:
> 
> ```
> svr.Get("/props", [&llama](const httplib::Request & /*req*/, httplib::Response &res)
> ```
> 
> And on 2831 there's also no req
> 
> ```
> svr.Get("/v1/models", [&params](const httplib::Request&, httplib::Response& res)
> ```
> 
> Changing both explicitly to `const httplib::Request& req` makes it compile.

Oh huh, I did see this later too but when I pushed it the code did compile. I must've messed up something with Git...

**Comment by battaglia01** [comment]
Just FYI, with those changes, it compiles well on an macOS ARM. Also works with the typingmind.com interface.

**Comment by Azeirah** [comment]
> Just FYI, with those changes, it compiles well on an macOS ARM. Also works with the typingmind.com interface.

Ah nice, that's a browser client. At this point I'm confident it's working well. Typingmind.com doesn't work because of the same CORS issue on main, but it does work in this PR.

I think it's ready for merging, @ggerganov?

**Comment by Azeirah** [comment]
@ggerganov Can this please be merged? It is tested and fixes a bug I run into almost daily because I want to use the Obsidian copilot interface, but it cannot work without this fix.

In short, what this does is:

- There's a bug in the implementation of CORS in server.cpp master, not respecting credentialed CORS spec which can be found on MDN
- This branch implements the CORS handshake correctly
- Try connecting to a running llama.cpp server with Typingmind.com using an API key on master, you will get a CORS error in the network tab of your browser.
- Connect with this branch, it works.

**Review by ggerganov — APPROVED** [review]
Sorry for the delay. Lets resolve the conflict and merge

**Comment by Azeirah** [comment]
> Sorry for the delay. Lets resolve the conflict and merge

Resolved, nothing major in the conflicts, just some code that was moved around a bit.

✅ Made sure it still compiles and works with the default client as well as with the Obsidian (CORS) client.

**Pull request merged**
