### PR TITLE
metal : try to unify mul_mv_id kernels

### PR DESCRIPTION
**Pull request by slaren**
Prerequisite to #6505

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by slaren** [comment]
@ggerganov these changes add a dummy `shared_values` parameter to the all the mul_mv kernels, regardless of if they use shared memory, to reduce the number of variations.

**Review by ggerganov — APPROVED** [review]
Thank you

**Comment by slaren** [comment]
It seems that the `ggml-100-m1` runner is not working at the moment. It is also missing from the `master` runs.

**Comment by ggerganov** [comment]
Yeah, the machine is down for some reason - will resolve next week

**Pull request merged**
