### PR TITLE
Add Discord Link

### PR DESCRIPTION
**Pull request by CRD716**
I started an unofficial discord server for llama.cpp a few days back, and was going to let it grow a bit before making a pr, but I saw #250 had mentioned it and decided to go ahead and add a badge to the readme. Let me know if I should change the name, and @ggerganov if you end up joining, put your username in the comments so I can give you permissions. (Same goes for slaren and any other collaborators).

(Also fixed a small mistake that I made in #1304, the commit changes `and do anything that the original ChatGPT cannot do.` to `and do anything that the original AI cannot do.`)

### CODE REVIEW

**Comment by CRD716** [comment]
Also, if it wouldn't be too much of a pain, could a [webhook](https://support.discord.com/hc/en-us/articles/228383668) be added for commits? (Separate hooks for issues and pull requests would be nice as well.)

**Comment by JohannesGaessler** [comment]
I hate Discord and want to keep communication between developers on Github if at all possible. As far as I'm concerned a Discord server would just lead to people trying to report bugs there instead of here and Discord is a terrible tool for that.

**Comment by CRD716** [comment]
> I hate Discord and want to keep communication between developers on Github if at all possible. As far as I'm concerned a Discord server would just lead to people trying to report bugs there instead of here and Discord is a terrible tool for that.

There are a few things I disagree with here:
1. It's not only developers using llama.cpp, there's no shortage of people who use the program personally and can't code. Not everyone asking a question or discussing a topic is giving a direction for development.
2. Bug reports would only benefit from a quick way to ask basic questions. Many issues currently open are misused flags, someone asking a basic question, questions about models (ex. prompt format), etc. This clutters the issues and hinders accurate tracking of bugs, while burying code issues that need to be resolved.
3. It does say to report bugs on GitHub in the discord, and there isn't even a place for it in the discord, so it's not like people are being misled into thinking their bug will be handled there.

**Comment by eachadea** [comment]
+1 to reduce redundant issues & tech support questions on the github

**Comment by JohannesGaessler** [comment]
We already have a discussions page with a dedicated Q&A section for asking questions. Again, I want **one** place for communication. And I've seen it multiple times before: as soon as devs hang out on Discord or wherever people will try to use that instead of Github. No, telling people to report bugs on Github does not help.

**Comment by CRD716** [comment]
By "Give permissions" I meant transfer ownership, sorry if I didn't make that clear.

**Pull request closed without merging**
