### PR TITLE
Add sentencepiece tokenizer and modify build (Support UTF-8 / Emoijs)

### LINKED ISSUE #11: Unicode support
Thannk you for creating such a great inference engine which has 10x speedup.
Please add Unocode support to display other language properly.

Screenshot 2023-03-11 at 7 12 50 PM

### LINKED ISSUE #63: Prompt interrupted before continuation for Unicode UTF-8 emojis
I have found that when having a Unicode UTF- emoji char like  

Unicode Character “👍” (U+1F44D)

The prompts breaks up.

I'm reading a sample prompt from a text file:

```bash
cat prompt

Tweet: "I hate it when my phone battery dies."
Sentiment: Negative
###
Tweet: "My day has been 👍"
Sentiment: Positive
###
Tweet: "This is the link to the article"
Sentiment: Neutral
###
Tweet: "This new music video was incredibile"
Sentiment:
```

Looking at logs I can see in fact that the tokenizers breaks at the (U+1F44D) char code:

```
(base)$ p=$(cat prompt); ./main -m ./models/13B/ggml-model-q4_0.bin -p $p -t 4 -n 512
main: seed = 1678656464
llama_model_load: loading model from './models/13B/ggml-model-q4_0.bin' - please wait ...
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: ggml ctx size = 8559.49 MB
llama_model_load: memory_size =   800.00 MB, n_mem = 20480
llama_model_load: loading model part 1/2 from './models/13B/ggml-model-q4_0.bin'
llama_model_load: ............................................. done
llama_model_load: model size =  3880.49 MB / num tensors = 363
llama_model_load: loading model part 2/2 from './models/13B/ggml-model-q4_0.bin.1'
llama_model_load: ............................................. done
llama_model_load: model size =  3880.49 MB / num tensors = 363

main: prompt: 'Tweet: "I hate it when my phone battery dies."
Sentiment: Negative
###
Tweet: "My day has been 👍"
Sentiment: Positive
###
Tweet: "This is the link to the article"
Sentiment: Neutral
###
Tweet: "This new music video was incredibile"
Sentiment:'
main: number of tokens in prompt = 36
     1 -> ''
 27418 -> 'Tw'
  3905 -> 'ee'
 29873 -> 't'
 29901 -> ':'
   376 -> ' "'
 29902 -> 'I'
 26277 -> ' hate'
   372 -> ' it'
   746 -> ' when'
   590 -> ' my'
  9008 -> ' phone'
 16988 -> ' battery'
  2977 -> ' dies'
  1213 -> '."'
    13 -> '
'
  2008 -> 'Se'
   593 -> 'nt'
  2073 -> 'iment'
 29901 -> ':'
 12610 -> ' Neg'
  1230 -> 'ative'
    13 -> '
'
  2277 -> '##'
 29937 -> '#'
    13 -> '
'
 27418 -> 'Tw'
  3905 -> 'ee'
 29873 -> 't'
 29901 -> ':'
   376 -> ' "'
  3421 -> 'My'
  2462 -> ' day'
   756 -> ' has'
  1063 -> ' been'
 29871 -> ' '

sampling parameters: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000


Tweet: "I hate it when my phone battery dies."
Sentiment: Negative
###
Tweet: "My day has been 10 times better than yesterday. Now I have to sleep again..."
Sentiment: Neutral
###
Twitter is not about talking; Twitter is a social network for listening and responding instantly, as the tweets of Steve Jobs demonstrate well in Figure A-2 (page ). Just be sure you can interpret the information accurately. If the sentiment isn't clearly positive or negative—as^C
```

resulting in a broken input prompt.

### PR DESCRIPTION
**Pull request by beiller**
Resolves #11 

Resolves #63 

I think its best to add sentencepiece which is small and easy to build. Here is a PR but we can hack together something still. The changes to `main.cpp` are still relevant for either case.

### CODE REVIEW

**Comment by beiller** [comment]
Sentencepiece fails to build in ubuntu. Of course it does :)

**Comment by j-f1** [comment]
A simpler approach (maybe?) could be to parse the `tokenizer.model` file using `protobuf` in Python and then generate the tokens appropriately.

**Comment by beiller** [comment]
@j-f1 I would caution that approach, because that is already the current approach already used here, except sentencepiece (python) was used to generate the list of tokens. 

```
result1 = tokenizer.encode("篇")
print(f'token: {result1}')
>>>[29871, 234, 178, 138]
```

There is no tokenization of 篇. It is tokenized by splitting it into UTF8 chunks. 

https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=%E7%AF%87&mode=char
Info:
```
Character | 篇
Hex code point | 7BC7
Decimal code point | 31687
Hex UTF-8 bytes | E7 AF 87
```

So does it mean decompose to E7 AF 87 ? Will you store 255 "code point" tokens? I think that is what happened. But maybe not. Token ID 131 - 258 stores 0xEFBFBD which is not 256 entries. Even if we did how would we determine to use a normal token vs the codepoint? There is a great deal I don't know about it maybe I am overlooking something!

**Comment by j-f1** [comment]
SentencePiece stores the following types of tokens:

- normal tokens. These appear to be valid UTF-8 text snippets (including both ASCII and non-ASCII text. e.g. <kbd>六</kbd> <kbd>reate</kbd> <kbd>▁end</kbd> (they use `▁` to represent a space for some reason)
- The <kbd>&lt;unk&gt;</kbd> token (translated as &#x2047;). Not sure how this is used.
- <kbd>&lt;s&gt;</kbd> and <kbd>&lt;/s&gt;</kbd> tokens to represent the start/end of text
- <kbd>&lt;0x*XX*&gt;</kbd> tokens (e.g <kbd>&lt;0xE7&gt;</kbd><kbd>&lt;0xAF&gt;</kbd><kbd>&lt;0x87&gt;</kbd> for `篇`) for all values 0-255

**Comment by j-f1** [comment]
I think your changes to buffer output until we have a complete UTF-8 character make sense, but I think we can remove the `sentencepiece` dependency entirely by vendoring [`sentencepiece_model.proto`](https://github.com/google/sentencepiece/blob/9ffb33a14c97c512103be0ee74740099660b39aa/src/sentencepiece_model.proto#L282) and parsing `tokenizer.model` in `convert-pth-to-ggml.py`.

**Comment by j-f1** [comment]
Currently rebuilding the 7B model now, will give it a few tests then open a PR.

**Comment by beiller** [comment]
Nice @j-f1 I think a general algorithm of tokenizing would be, attempt to look up in the token set, and it it doesnt exist, decompose it into 0xXX tokens.

It might make displaying the text more difficult. If you detect a 0xXX on decode, wait until the next token is not a hex and then display it. Hopefully we can tell where to stop tho.

Also this PR has a bug and prompt crashes please dont merge!

`./main -m ./models/13B/ggml-model-q4_0.bin -t 4 --temp 0.7 --top_k 40 --top_p 0.5 --repeat_last_n 256 --repeat_penalty 1.17647 -n 512 -p 关于爱因斯坦的生平。他出生于`

**Comment by j-f1** [comment]
For tokenizing, I think that will happen automatically, assuming the `std::string` text is UTF-8 encoded (since it picks the longest possible token matching the current string, which could end up being one of the one-byte tokens). For decoding, I think a version of your code in this PR could work (where you check for an invalid UTF-8 sequence before printing)

**Comment by beiller** [comment]
@j-f1 "which could end up being one of the one-byte tokens" -> which could end up being **multiple** of the one-byte tokens. Encoding "you" could end up with [512], but if not found, it would wind up as [55, 63, 99] (numbers made up).

**Comment by j-f1** [comment]
→ https://github.com/ggerganov/llama.cpp/pull/73

**Comment by Piezoid** [comment]
Once llama.cpp gets python bindings (#82), things like interaction, tokenization, and even sampling are easier to develop and test in python. I'm thinking that making the core of llama.cpp text-agnostic would allow more flexibility for less feature creep.

**Comment by ggerganov** [comment]
Resolved in #79

**Pull request closed without merging**
