### PR TITLE
metal: Reducing base memory use

### PR DESCRIPTION
**Pull request by ptsochantaris**
Currently the code maintains strong references to the `MTLFunction` objects which are used to initialise the `MTLPipelineState` objects of the ggml-metal context, only releasing them in the `ggml_metal_free` function.

However according to Apple's docs [here](https://developer.apple.com/documentation/metal/mtlfunction?language=objc) "MTLFunction objects can use a significant amount of memory; release any strong references to them after you finish creating pipeline objects".

This PR tries to address this by:
- Modifying the `GGML_METAL_ADD_KERNEL` macro to release the `MTLFunction` object once the pipeline is constructed from it (or failed to construct).
- Replaces the `kernels` array of `ggml_metal_kernel` structs in the context with `pipelines` which is simply an array of the constructed pipeline objects instead.
- `ggml_metal_kernel` is removed as it is no longer needed.
- `GGML_METAL_MAX_KERNELS` is removed, as `GGML_METAL_KERNEL_TYPE_COUNT` provides a more accurate count of potential kernels for the context array based on the kernel type enum entry counts.

Alternative proposal:
If the diff of this PR is too large, the `ggml_metal_kernel` removal can be reverted, and the `function` field can be removed from it instead (this would reduce the diff line count significantly). However this would mean there would be a struct with only one field, which feels like unneeded indirection, but if reducing diff noise is a priority then it's also a possibility.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Good change - just curious, do you have an estimate of the amount of memory that these kernels objects used?

**Comment by ggerganov** [comment]
> Alternative proposal:
If the diff of this PR is too large, the ggml_metal_kernel removal can be reverted, and the function field can be removed from it instead (this would reduce the diff line count significantly). However this would mean there would be a struct with only one field, which feels like unneeded indirection, but if reducing diff noise is a priority then it's also a possibility.

Let's do that. The consideration is not the amount of line diffs, but I suspect that we might to store some extra info per kernel in the future (like tensor or parameter ranges) and having a struct to hold these would be useful

**Comment by ptsochantaris** [comment]
@ggerganov Sounds good, will update the PR shortly to keep the `kernels` structure 👍 

Re: The memory saving amount, I wasn't able to get a better reading, mostly because I just tested it a bit unscientifically thinking that any saving is a good saving, but I'll run it through the allocations profiler, see if there's a noticeable change, and update on this thread.

**Comment by ptsochantaris** [comment]
According to Apple's docs [here](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/PersistentObjects.html): "You can release MTLLibrary objects after building all render and compute pipelines that depend on them"; so in the above commit I made a similar change to the `library` field, since it can be released after the pipelines are created. Will follow up shortly with an update to see if all this does in fact make any meaningful difference :)

**Comment by ptsochantaris** [comment]
Sorry for the holdup - I couldn't find a good way to track what kind of overhead difference these changes made. Testing using `main` and `time -hl` for example would only provide a fluctuating and/or moderate improvement in heap usage by only a couple of MB, which is nice but a bit underwhelming.

However in the end the best approach seemed to be to check the GPU deallocations graph in two nearly identical runs of my own app, with the PRed changes applied before and after, which does seem to suggest that the released resources do indeed return a non-trivial amount of memory back - about 78Mb of GPU memory in addition to the 1-2Mb of heap previously mentioned.

So overall this is hardly earth-shattering, but it does indeed reclaim a bit of memory. I am including the screenshots of the profile below in case anyone with more experience of Metal can spot an issue with my not-very-scientific methodology.

|Retained|Released|
|--|--|
|retained|released|

**Review by ggerganov — APPROVED** [review]
Ok, great. Let's fix the CI and we can merge

**Pull request merged**
