### PR TITLE
llama : add option to render special/control tokens

### LINKED ISSUE #6770: Special tokens are not rendered correctly (as empty) -- llama3 specific?
Hello!

Using this GGUF: https://huggingface.co/LoneStriker/opus-v1.2-llama-3-8b-GGUF

When the output contains any of the special tokens, like `<|im_start|>` or `<|im_end|>`, they are rendered as empty string. This breaks custom stopping string functionality (e.g. adding "<|im_end|>" to stop strings does not work as it relies on string comparison).

The tokens are tokenized correctly, just not rendered:

```
main: prompt: '<|im_end|>'
main: number of tokens in prompt = 1
128009 -> ''
```

```
main: prompt: '<|im_start|>'
main: number of tokens in prompt = 1
128006 -> ''
```

I first tested this with old commit:

```
version: 2243 (201294ae)
201294ae177b308fb3a99dc504dd6d27e8afa907
```

And replicated with fresh main:

```
version: 2698 (637e9a86)
637e9a86c220718d008b54842dfd294aa96d3b7a
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #6770 

Setting `special == true` in `llama_token_to_piece()` will cause special/control tokens' text to be rendered in the output:

https://github.com/ggerganov/llama.cpp/blob/1f45c2adc7b10637c2035e622573f1851e403979/llama.h#L827-L837

### CODE REVIEW

**Review by phymbert — APPROVED** [review]

**Comment by ggerganov** [comment]
> phi-2-q4_0: 215 iterations 

Performance dropped - maybe generation does not stop properly after the #6745 EOG changes?

**Comment by ngxson** [comment]
> Performance dropped - maybe generation does not stop properly after the #6745 EOG changes?

Very likely, because we're using phi-2 model which does not have native support for chatml (so `<|im_end|>` is not a single token - it is broken into multiple tokens)

**Comment by ggerganov** [comment]
I think we are incorrectly using a base model instead of instruction-tuned one for this test:

https://huggingface.co/microsoft/phi-2

image

The `phi-2` model does not support any chat template because it is a base model. We have to change the model used in the benchmark with a instruction tuned one

**Comment by ngxson** [comment]
> The phi-2 model does not support any chat template because it is a base model. We have to change the model used in the benchmark with a instruction tuned one

Ah yeah that's correct. We can use dolphi-phi2 then. Here is the link: https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF

The `<|im_start|>`, `<|im_end|>` and chat template of the HR model is correct: https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2/blob/main/tokenizer_config.json#L325

**Review by thalinda-oss — APPROVED** [review]

**Review by thalinda-oss — APPROVED** [review]

**Review by thalinda-oss — APPROVED** [review]

**Pull request merged**
