### PR TITLE
fix CI failures

### PR DESCRIPTION
**Pull request by slaren**
Patches for common intermittent CI failures in `test-backend-ops` with `CPY` and `server.yml` with thread sanitizer.

### CODE REVIEW

**Comment by slaren** [comment]
@ggerganov it looks like github has an option to prevent merging PRs if the CI is failing. Please consider enabling this, at the very least for the most basic checks such as editorconfig and linting.

image

**Comment by ngxson** [comment]
@slaren I'm not against this idea, seems like very useful thing since sometimes I overlook small changes.

However, I'm thinking that some jobs should be consider to be "OK to fail". For example "Publish Docker" sometimes fails for unknown reason, and when re-run it takes quite a lot of time.

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Added the branch requirements:

image

**Comment by slaren** [comment]
I am not sure if the checks are working, it shouldn't have allowed me to merge this.

**Comment by ggerganov** [comment]
I had forgotten to save the settings page today. Just applied the change now and it should be active

**Pull request merged**
