### PR TITLE
Clang-format the llama.* files

### PR DESCRIPTION
**Pull request by ghost**
In order to keep the formatting consistent and simple for some refactoring simplification I'd like to do, I'm running `clang-format` on the llama.cpp and llama.h files.

I figured it would be worth seeing how receptive yall were to that prior to spending significant effort abstracting-out and deduping a bunch of code.

### CODE REVIEW

**Comment by cebtenzzre** [comment]
You're using clang-format without any configuration? It's not even using four-space indents.

**Comment by WillCorticesAI** [comment]
It's the default. If there is a standard config for this project, I'm happy to use it.

**Comment by cebtenzzre** [comment]
I tried to make a clang-format config for this project once, but I wasn't able to get as close to the code style here as I would like. Either way, this PR is more likely to be merged if you can minimize the changes to the existing style.

**Comment by WillCorticesAI** [comment]
That makes sense. I don't think it's great ROI for me at this time, though, so I'll go ahead and close out this request.

**Pull request closed without merging**
