### PR TITLE
Multiline autocompletion for VIM example, get rid of "^@".

### PR DESCRIPTION
**Pull request by chaihahaha**

### CODE REVIEW

**Comment by ggerganov** [comment]
#2495 will override the current VIM plugin

**Comment by chaihahaha** [comment]
Both `llama.vim` in #2495 and the current `llm.vim` work well, I hope both of them to be kept.

**Comment by ggerganov** [comment]
Is there something that `llm.vim` offers that `llama.vim` does not?

**Comment by chaihahaha** [comment]
`llm.vim` doesn't have more functionalities, but as an example, it is simpler and provides more space for customization.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
