### PR TITLE
Adding llama banner in README.md

### PR DESCRIPTION
**Pull request by leszekhanusz**
Add a banner with a C++ llama logo in the `README.md`

banner

Preview here:
[https://github.com/leszekhanusz/llama.cpp/tree/readme_llama_banner](https://github.com/leszekhanusz/llama.cpp/tree/readme_llama_banner)

Current discussion in issue #105 

The text can be changed if needed, suggestions welcome.

The banner SVG source can be modified using inkscape if needed to regenerate the png file but you need to have the [verlag compressed black](https://www.fontsmarket.com/font-download/verlag-compressed-black) font.

### CODE REVIEW

**Comment by ggerganov** [comment]
Change the text to "It really whips the llama's ass!" and I'll merge it

**Comment by leszekhanusz** [comment]
> Change the text to "It really whips the llama's ass!" and I'll merge it

Really?

**Comment by ggerganov** [comment]
Hah, well I find it funny :) Do you think it is over the top?

**Comment by leszekhanusz** [comment]
> Hah, well I find it funny :) Do you think it is over the top?

A little bit, but well, you're the chief :laughing: , I'll do the modification.

**Comment by G2G2G2G** [comment]
Someone deleted their post I assume? I find it funny too and it makes sense. You're whipping the llama's ass to get it to work harder.. in this case getting the language model to work harder

**Comment by ggerganov** [comment]
Ok, I slept on it - it's a bit too cocky :)
Let's see if we get some more logo entries for a few days

**Pull request closed without merging**
