### PR TITLE
sampling: fix top_k <= 0

### LINKED ISSUE #1154: [0.2.38] Models always produce the same output when setting top_k to 0, still using min_p
So I just installed the latest release and immediately realized that it always produces the same token sequence (meaning the same answer for the same question etc.). Tested multiple models, all the same. **Switching back to 0.2.37 fixes the issue.** Reinstalling 0.2.38 makes the issue reappear.

Did some default parameter or sampling behavior change?

As usual I use the following parameters (they worked flawlessly before):

```
temperature 1.19
repeat_penalty 1.0
min_p 0.02
top_p 1.0 (disabled)
top-k 0 (disabled)
```

System: Ubuntu 20.04, CUDA

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Fixes https://github.com/abetlen/llama-cpp-python/issues/1154 .
(I assume) the issue is that top_k sampling is called directly rather than via the sampling queue.
top_k values <= 0 are then rounded up to `min_keep` instead of being set to `candidates.size`.
This PR adds a corresponding check and two more related test cases.

### CODE REVIEW

**Review by Green-Sky — APPROVED** [review]
Does this fix the server behavior, when you set the "Show Probabilities" option ?

**Comment by JohannesGaessler** [comment]
I don't know which issue you're talking about so I can't say.

**Comment by Green-Sky** [comment]
No it does not. Ignore me :)

**Review by cebtenzzre — APPROVED** [review]

**Review by ggerganov — APPROVED** [review]

**Comment by neerajprad** [comment]
I still see the same issue on the latest version (0.2.44) where the sampling is deterministic for K=0.

**Pull request merged**
