### PR TITLE
server : fix kv cache management

### PR DESCRIPTION
**Pull request by ggerganov**
ref #3575 

Try to fix the reported issue. Not tested

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
I checked to see if the colon thing could possibly be related to #3550 but that doesn't appear to be the case. Still easy to reproduce with this pull.

**Comment by spencekim** [comment]
I don't see the issue anymore using this repro: https://github.com/ggerganov/llama.cpp/issues/3575#issuecomment-1758586092

Tried several hundred reqs, with zero appearances of the leading colons.

**Comment by blightbow** [comment]
I see the issue as of commit 1e0e873. I've seen it more often when regenerating outputs. See if you can reproduce it more frequently by submitting the same input over and over again. My general observation is that once you've triggered an appearance of a colon, further submissions of the same input without advancing the conversation will cause an additional colon to prefix the output. (not always, but often enough)

**Comment by blightbow** [comment]
I'm also noticing that roleplaying models that are aware of emoji syntax like :eyes: have an increased disposition toward beginning a response with a truncated one, like so:

`eyes: This is an example.`

 It's like the model is internally perceiving a : character, which is in turn predisposing the output toward that emoji syntax.

**Comment by cebtenzzre** [comment]
> I'm also noticing that roleplaying models that are aware of emoji syntax like `:eyes:` have an increased disposition toward beginning a response with a truncated one, like so:

You should open a new issue so this gets more attention.

**Comment by blightbow** [comment]
> You should open a new issue so this gets more attention.

I'll wait and see if [d9cbf44](https://github.com/xgaicc/llama.cpp/commit/d9cbf44d6ebbfdd5319a5fc6a393624962c29e1e) has improved the situation. If it remains unfixed, I'll open a new ticket.

**Comment by cebtenzzre** [comment]
> I'll wait and see if [d9cbf44](https://github.com/xgaicc/llama.cpp/commit/d9cbf44d6ebbfdd5319a5fc6a393624962c29e1e) has improved the situation.

That's a cherry-pick of this PR - are you testing on 1e0e873 (which includes it) or not?

**Comment by blightbow** [comment]
Sorry about that, I misread the activity. Yes, everything I have been discussing is current as of [1e0e873](https://github.com/ggerganov/llama.cpp/commit/1e0e873c373c33989beb6bc64d83cd572ab7fe2b).

**Comment by spencekim** [comment]
> I don't see the issue anymore using this repro: [#3575 (comment)](https://github.com/ggerganov/llama.cpp/issues/3575#issuecomment-1758586092)
> 
> Tried several hundred reqs, with zero appearances of the leading colons.

unfortunately I'm starting the see the bad outputs (colons) again on master

**Pull request merged**
