### PR TITLE
feat: add Phi-1.5/Phi-2 tokenizer

### PR DESCRIPTION
**Pull request by daminho**
Add Phi-2/Phi-1.5 Tokenizer in get_vocab_base_pre
ref: https://huggingface.co/microsoft/phi-2
image

Running example: -p "I believe the meaning of life is" -n 128
image

### CODE REVIEW

**Comment by ggerganov** [comment]
The `convert_hf_to_gguf_update.py` scripts needs to be updated as well

**Comment by daminho** [comment]
@ggerganov my bad, I just updated it. Thanks for pointing it out

**Comment by bviksoe** [comment]
Isn't there a "phi" vs "phi2" discrepancy in this patch?

**Comment by ggerganov** [comment]
`llama.cpp` does not handle the `phi2` pre-tokenizer. The `llm_load_vocab` function has to be updated

**Comment by daminho** [comment]
I have updated, you can find the result in the updated image in description @ggerganov

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
