### PR TITLE
faster avx512 exp implementation

### PR DESCRIPTION
**Pull request by chriselrod**
@jart do you have accuracy, edge case, and performance tests to run?

I added comments explaining the algorithm.

I also have a C++ implementation here https://github.com/chriselrod/ExpAVX512
The C++ implementation allows for unrolling and interleaving in loops, showing this can yield substantial performance benefits
```
-----------------------------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations CACHE-MISSES     CYCLES INSTRUCTIONS
-----------------------------------------------------------------------------------------------------------------
BM_simd_exp_run<16, 1>/4096              783 ns          781 ns       885101     109.592u   3.04656k       4.872k
BM_simd_exp_run<16, 4>/4096              597 ns          596 ns      1191770     11.7472u   2.33025k       4.301k
```
When running on vectors of length 4096, unrolling by 4x increased perf from 783ns -> 597ns on my 10980xe.
If trying to maximize performance, it'd also be worth considering if you can somehow use `exp2` instead of `exp`. Note that mathematically `exp(x) = exp2(log2(e)*x)`. This isn't true numerically, but it could for example be possible to fold the `*log2(e)` in with another scaling if there was one. Or maybe it's possible to compensate for that error in a way I couldn't figure out. It seems like it'd be oversight to introduce a `vreduce` instruction but have it only be useful for computing the reduction in `exp2`, so I suspect there's just something I'm missing there.

You should also double check the loops where this is called to make sure everything is inlined so that the many constants can be hoisted out.

### CODE REVIEW

**Comment by jart** [comment]
I recommend marking this PR in draft state until you can get your implementation to pass with this code, I've set up for you. https://gist.github.com/jart/566d94c86d54af5a9f11cfbf383e9357

**Comment by jart** [comment]
Here's what I'm getting with the latest code.

image

You most likely need to add a branch for a special case handling path, e.g. numbers above 88 and below -104. However the performance is so close to the existing code already, that it's hard to imagine that effort bearing fruit. I admit, my benchmarking method in the program I gave you is very crude. When ggerganov showed me how to run `make -j tests && ./tests/test-backend-ops -o SOFT_MAX -b CPU perf` it showed much rosier results for my algorithm that I thought. If you keep focusing on that, then using that would be the best way to know if your efforts are making an improvement. My script is mostly just a crude testing tool.

**Comment by chriselrod** [comment]
> I recommend marking this PR in draft state until you can get your implementation to pass with this code, I've set up for you. https://gist.github.com/jart/566d94c86d54af5a9f11cfbf383e9357

Instead of commenting out the `r = `, you should've substituted all the following `x`es with `r`.

Still, it didn't handle special cases. Using `vreduce` does set the reduced `r` correctly, but I still couldn't find a way to use it. Page 613 of the [Intel optimization manual](https://cdrdv2-public.intel.com/671488/248966-046A-software-optimization-manual.pdf) also only uses `vreduce` for `exp2`, vs for `exp` it says

> R(x) is accurately computed by using a sufficiently long log(2.0) approximation (longer than the native floating-point format).

So I guess it's not worth bothering trying to find a way.

Anyway, I decided to just modify your/the ARM implementation to use `vscalef`. The approach was basically the same as the implementation I tried, but starting from the other made it easier.
```
> ./exp_accuracy

   3.16466 ns 100000x run_expf()
   1.16982 ns 100000x run_llamafile_expf_avx512()
   1.15337 ns 100000x run_chris_expf_avx512()

//       input          exp            v   bad
//       =====          ===    =========   ===
//           0            1            1     0
//          -0            1            1     0
//         nan          nan          nan     0
//        -nan         -nan         -nan     0
//         inf          inf          inf     0
//        -inf            0            0     0
//          87  6.07603e+37  6.07603e+37     1
//          88  1.65164e+38  1.65164e+38     0
//     88.7229          inf          inf     0
//          89          inf          inf     0
//         -87  1.64581e-38  1.64581e-38     1
//         -90  8.19401e-40  8.19401e-40     0
//         -95  5.52112e-42  5.52112e-42     0
//        -100  3.78351e-44  3.78351e-44     0
//        -104            0            0     0
//   -0.153582     0.857631     0.857631     1
//   0.0188149      1.01899      1.01899     0
//    0.296719      1.34544      1.34544     1
//   -0.234273     0.791146     0.791146     1
//    0.590896       1.8056       1.8056     1
//  0.00102246      1.00102      1.00102     0
//    0.107871       1.1139       1.1139     2
//   -0.869161     0.419303     0.419303     1
4294967296 numbers tested successfully
```
There are some ULP differences with `expf`, but all are <= 2 ULP.

**Comment by jart** [comment]
Oh your last push is a lot better. Much closer to the mark.

image

Are you saying that your technique will work for improving the ARM code? If the x86 ISA is hostile towards its scale instruction being used to implement an accurate expf() function, then we could always try that instead!

**Comment by jart** [comment]
I'm so sorry! I botched my testing process. Your code is 100% good!

image

**Comment by chriselrod** [comment]
There is a tag that says "review complexity : high".
This PR doesn't change change the `exp` algorithm used here.
The algorithm is:
```
n = round(x*log2(e))
r = x - n/log2(e)

exp(x)
= exp(x - n/log2(e) + n/log2(e))
= exp(r) * exp(n/log2(e))
= exp(r) * exp2(n)
```
`r` is range-reduced.
Because it equals `x - round(n*log2(e))/log2(e)`, r is within the range `[-log(2)/2, log(2)/2)`. This narrow range, and that we need only 32-bits of precision, makes it feasible to approximate `exp(r)`.

The change this PR makes is that while the original translated ARM source calculates `exp(r) * 2^n` using a ton of bit-magic, AVX512 provides instructions (`vscalefps`/`vscalefpd` for `float`/`double`) that calculate it explicitly and also handle edge cases.

Unfortunately, we still need to handle some edge cases ourselves because those edge cases could invalidate our `r`, and our reduction approach (i.e., how we calculate `r`) doesn't handle them.

Breaking down the source:
```c
inline static __m512 ggml_v_expf(__m512 x) {
  const __m512 r = _mm512_set1_ps(0x1.8p23f);
  const __m512 z = _mm512_fmadd_ps(x, _mm512_set1_ps(0x1.715476p+0f), r);
  const __m512 n = _mm512_sub_ps(z, r);
```
`n = round(x*log2(e))`. They add then subtract a huge constant to force rounding.
```c
  const __m512 b =
      _mm512_fnmadd_ps(n, _mm512_set1_ps(0x1.7f7d1cp-20f),
                       _mm512_fnmadd_ps(n, _mm512_set1_ps(0x1.62e4p-1f), x));
```
This `b` is what I have been calling `r`, it is range reduced. They use two successive `fma`s to preserve accuracy.
```c
  const __mmask16 d =
      _mm512_cmp_ps_mask(_mm512_abs_ps(n), _mm512_set1_ps(192), _CMP_GT_OQ);
```
check for edge cases.
```c
  const __m512 u = _mm512_mul_ps(b, b);
  const __m512 j = _mm512_fmadd_ps(
      _mm512_fmadd_ps(_mm512_fmadd_ps(_mm512_set1_ps(0x1.0e4020p-7f), b,
                                      _mm512_set1_ps(0x1.573e2ep-5f)),
                      u,
                      _mm512_fmadd_ps(_mm512_set1_ps(0x1.555e66p-3f), b,
                                      _mm512_set1_ps(0x1.fffdb6p-2f))),
      u,
      _mm512_fmadd_ps(_mm512_set1_ps(0x1.ffffecp-1f), b, _mm512_set1_ps(1.0F)));
```
Calculate `exp(b)`.
```c
  const __m512 res = _mm512_scalef_ps(j, n);
```
Calculate `j * exp2(n)`.
```c
  if (_mm512_kortestz(d, d))
    return res;
  const __m512 zero = _mm512_setzero_ps();
  const __m512 alt = _mm512_mask_blend_ps(
      _mm512_cmp_ps_mask(n, zero, _CMP_LE_OQ), _mm512_set1_ps(INFINITY), zero);
  return _mm512_mask_blend_ps(d, res, alt);
}
```
In case of edge cases not already handled above, set to `+Inf`/`0` depending on whether we are above/below the max/minimum value.

The original code was doing the same thing.
```c
  const __m512i e = _mm512_slli_epi32(_mm512_castps_si512(z), 23);
  const __m512 k = _mm512_castsi512_ps(_mm512_add_epi32(e, _mm512_castps_si512(_mm512_set1_ps(1))));
  const __mmask16 c = _mm512_cmp_ps_mask(_mm512_abs_ps(n), _mm512_set1_ps(126), _CMP_GT_OQ);
  if (_mm512_kortestz(c, c))
    return _mm512_fmadd_ps(j, k, k);
```
the fast-path covers less cases (test vs `126` instead of `192`), and needs a sequence of instructions for calculating `j*exp2(n)`(although they get to use `z` instead of `n` as an input there).

Hopefully this makes review easier.

**Review by mofosyne — APPROVED** [review]
Ok. Had a quick sanity check against https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html and with your breakdown to sanity check. Looks good. I can see jart has ran through with the numbers that matches your observation.

I would also recommend baking these breakdown for you or anyone in the future who has to revisit this as well. This can indeed be a separate documentation PR, just remember to add a `[no ci]` marker to it if it's comment changes only. In your doco PR, you may want to consider also keeping the original code if it makes it easier to grok (unless just showing the psudo algorithm is good enough)

**Comment by mofosyne** [comment]
@chriselrod also regarding the label. It's not meant to be a super accurate marker, but more like a triage. As I don't spend very long trying to study incoming PRs on difficulty levels. So do speak out if it's actually an easier PR as its always good to make a PR more widely reviewed. The purpose of the difficulty level is to reduce the barrier for contribution by potential helpers.

**Pull request merged**
