### PR TITLE
Q2 and Q3 quantization

### LINKED ISSUE #456: 2-bit integer quantization
Add `Q2_0` and `Q2_1` quantization support to `ggml`:

- Follow the existing `Q4_0` and `Q4_1` implementations
- Implement [reference scalar quantization and dequantization routines](https://github.com/ggerganov/llama.cpp/blob/3cd8dde0d1357b7f11bdd25c45d5bf5e97e284a0/ggml.c#L407-L449)
- I suspect we might have to use `QK == 16` in this case to compensate for further accuracy losses
- Add SIMD support for a specific architecture - investigate best strategy to perform the `ggml_vec_dot_q2()` computation
- No need to implement `ggml_vec_mad_q2()` - these will be deprecated soon
- Compute perplexity scores

The expected model sizes for 7B and `QK == 16` are:

- `Q2_0` - 3.2 GB

For `QK == 32` we have:

- `Q2_0` - 2.4 GB
- `Q2_1` - 3.2 GB

Before you send me papers that show 2-bit quantization does not work - no need. I want to have this supported anyway. I have something in mind. The efforts needed to add this support are so small that there is no reason not to do it.

### PR DESCRIPTION
**Pull request by sw**
This adds support for 2-bit and 3-bit quantization with an FP16 shared scale and 16 quants per block.

I don't consider it ready to merge, as we might come up with a different block format. The `struct` definitions are not portable: they use a `#pragma` for one, and are unlikely to work on big-endian systems.

#951 really is a game-changer for 2-bit quantization. I have updated my code to use the Q8 intermediate quantization.

Q2 sample output (we may need to implement a profanity filter, but swearing is appropriate if you have to use PHP):
```
$ ./main -m models/7B/ggml-model-q2_0.bin -p "Building a website can be done in 10 simple steps:" -s 1681585661
 Building a website can be done in 10 simple steps:
Make sure your copy is up to date
Make sure graphics are updated
Make sure the fonts are refreshed
Make sure the javascript is refreshed
Make sure the PHP is refreshed
P.S.- I'll just tell ya what the fuck went wrong with P.S.- It's not like I'm superman or something...
P.S.- If you don't want to get your eyes glued up by playing Candyland, go read the comments for a minute
T.F.- I'll just tell ya what the fuck went wrong with T.F.- It
```

Q3 is more sensible, but I haven't played with it a lot.

As mentioned, both new types use FP16 and QK=16. This was easiest to implement for two reasons: I can just use half of a Q8 block, and 16 3-bit values can be mangled in an AVX2 register.

So I've essentially invented my own new formats, but I'm aware there's a 3-bit GPTQ format. I'd love to re-use what's already been done, but haven't been able to find a clear definition (or model files) of that.

Looking forward to anyone finding better SIMD optimizations, especially for Q3, which is a pain in the butt...

Model file sizes:
```
$ ls -gho models/7B/*q*
-rw-rw-r-- 1 2.4G Apr 15 21:04 models/7B/ggml-model-q2_0.bin
-rw-rw-r-- 1 3.2G Apr 15 19:53 models/7B/ggml-model-q3_0.bin
-rw-rw-r-- 1 4.0G Apr 13 21:51 models/7B/ggml-model-q4_0.bin
-rw-rw-r-- 1 4.8G Apr 12 21:43 models/7B/ggml-model-q4_1.bin
```

Perplexity for 7B: (not going to let this run for over a day, can someone with a faster machine help out?)
```
Q2:
78.25 seconds per pass - ETA 14.24 hours
[1]9.5516,[2]10.8049,[3]11.6886,[4]12.9123,[5]12.7524,[6]12.7123,[7]12.9646,[8]13.1274,[9]13.8018,[10]14.1944,[11]14.7764,

Q3:
141.31 seconds per pass - ETA 25.71 hours
[1]4.8166,[2]5.2200,[3]6.1143,
```

### CODE REVIEW

**Comment by ggerganov** [comment]
I'm playing with the smallest GPT-2 models and trying to make them work with 4-bit quantization. They keep breaking down completely even after #951. I guess the small number of parameters requires very high precision in the quantization.

However, I just noticed that if I keep just the last tensor in F16, they suddenly become coherent.
So I made this issue: https://github.com/ggerganov/llama.cpp/issues/1003 

Maybe it could further improve your Q2 and Q3 if you keep the last tensor in high precision

**Comment by slaren** [comment]
Probably nothing, but here is a quick test of the perplexity performance with Q2_0:

| Model | Time per pass|
| --- | --- |
|7B Q4_0 | 26.27 seconds|
|7B Q2_0 | 53.26 seconds|
|13B Q2_0 | 100.88 seconds|
|30B Q2_0 | 246.48 seconds|

**Comment by slaren** [comment]
Here is a AVX2 implementation of `ggml_vec_dot_q2_0_q8_0` that operates on two blocks at a time. Doing this the performance is much closer to q4_0.

| Model | Time per pass|
| --- | --- |
|7B Q4_0 | 26.27 seconds|
|7B Q2_0 | 34.74 seconds|
|13B Q2_0 | 66.76 seconds|
|30B Q2_0 | 165.91 seconds|

```C
static inline __m256i bytesFromi2(uint32_t packed1, uint32_t packed2) {
    __m128i bx1 = _mm_set1_epi32(packed1);
    __m128i bx2 = _mm_set1_epi32(packed2);
    __m256i bx = _mm256_set_m128i(bx1, bx2);

    // shift counts to get all bit pairs in lowest position of each byte
    const __m256i shift256 = _mm256_set_epi32(6, 4, 2, 0,
                                              6, 4, 2, 0);
    bx = _mm256_srlv_epi32(bx, shift256);

    const __m256i shufmask = _mm256_set_epi8(15,11,7,3,
                                             14,10,6,2,
                                             13,9,5,1,
                                             12,8,4,0,
                                             15,11,7,3,
                                             14,10,6,2,
                                             13,9,5,1,
                                             12,8,4,0);

    bx = _mm256_shuffle_epi8(bx, shufmask);

    const __m256i mask = _mm256_set1_epi8(3);
    bx = _mm256_and_si256(mask, bx);

    return bx;
}

static void ggml_vec_dot_q2_0_q8_0(const int n, float * restrict s, const void * restrict vx, const void * restrict vy) {
    const int nb = n / QK2_0;

    assert(n % QK2_0 == 0);
    assert(nb % 2 == 0);

    const block_q2_0 * restrict x = vx;
    const block_q8_0 * restrict y = vy;

    float sumf = 0.0f;

#if defined(__AVX2__)
    // Initialize accumulator with zeros
    __m256 acc = _mm256_setzero_ps();

    for (int i = 0; i < nb; i += 2) {
        __m256i bx = bytesFromi2(x[i+1].qs, x[i].qs);

        // Compute combined scale for the block
        const __m128 scale1 = _mm_set1_ps(GGML_FP16_TO_FP32(x[i].d) * y[i/2].d);
        const __m128 scale2 = _mm_set1_ps(GGML_FP16_TO_FP32(x[i+1].d) * y[i/2].d);
        const __m256 scale = _mm256_set_m128(scale2, scale1);

        const __m256i off = _mm256_set1_epi8(2);
        bx = _mm256_sub_epi8(bx, off);

        // Load y vector
        const __m256i by = _mm256_loadu_si256((const __m256i *)y[i/2].qs);

        // Get absolute values of x vectors
        const __m256i ax = _mm256_sign_epi8(bx, bx);

        // Sign the values of the y vectors
        const __m256i sy = _mm256_sign_epi8(by, bx);

        // Perform multiplication and create 16-bit values
        const __m256i dot = _mm256_maddubs_epi16(ax, sy);

        // Convert int16_t to int32_t by adding pairwise
        const __m256i ones = _mm256_set1_epi16(1);
        __m256i i32 = _mm256_madd_epi16(ones, dot);

        // Convert int32_t to float
        __m256 p = _mm256_cvtepi32_ps( i32 );

        // Apply the scale, and accumulate
        acc = _mm256_fmadd_ps( scale, p, acc );
    }

    // Return horizontal sum of the acc vector
    __m128 res = _mm256_extractf128_ps( acc, 1 );
    res = _mm_add_ps( res, _mm256_castps256_ps128( acc ) );
    res = _mm_add_ps( res, _mm_movehl_ps( res, res ) );
    res = _mm_add_ss( res, _mm_movehdup_ps( res ) );

    sumf = _mm_cvtss_f32( res );
#else
...
```

**Comment by slaren** [comment]
In case this is useful for future comparisons, currently 7B q2_0 AVX2 has a perplexity of 12.6438.

**Comment by pubby** [comment]
I mentioned this at https://github.com/ggerganov/llama.cpp/issues/456#issuecomment-1507919345, but I think there's a pretty obvious win by using a different q3_0 representation.

Code and pull request at https://github.com/sw/llama.cpp/pull/1

**Comment by pubby** [comment]
Here's an attempt at porting `bytesFromCrumbs` to other architectures. I don't have these systems so they may be incorrect and/or slow. Comments and improvements are welcome.

ARM NEON:
```
static inline int8x16_t bytesFromCrumbs(uint32_t packed) {
#  if __ARM_64BIT_STATE
    const uint8x16_t temp = vreinterpretq_u8_u32(vmovq_n_u32(packed));

    // Swizzle to put in the proper order
    const uint8x16_t indices = vcombine_u8(vcreate_u8(0x0D0905010C080400), vcreate_u8(0x0F0B07030E0A0602));
    const uint8x16_t swizzled = vqtbl1q_u8(temp, indices);
#  else
    const uint8x8_t temp_lo = vreinterpret_u8_u16(vmov_n_u16(packed));
    const uint8x8_t temp_hi = vreinterpret_u8_u16(vmov_n_u16(packed >> 16));

    // Swizzle to put in the proper order
    const uint8x8_t indices = vcreate_u8(0x0705030106040200);
    const uint8x8_t swizzled_lo = vtbl1_u8(temp_lo, indices);
    const uint8x8_t swizzled_hi = vtbl1_u8(temp_hi, indices);
    const uint8x16_t swizzled = vcombine_u8(swizzled_lo, swizzled_hi);
#  endif

    // Shift counts left to get all bit pairs in highest position of each byte
    const int8x16_t shift = vreinterpretq_s8_u32(vmovq_n_u32(0x00020406));
    const uint8x16_t shifted = vshlq_u8(swizzled, shift);

    // Then shift right to put in lowest position
    return vreinterpretq_s8_u8(vshrq_n_u8(shifted, 6));
}
```

WASM:
```
static inline v128_t bytesFromCrumbs(uint32_t packed) {
{
    // Shift without SIMD
    const uint32_t packed128[4] = { packed >> 6, packed >> 4, packed >> 2, packed };
    const v128_t shifted = wasm_v128_load(&packed128);

    // We only care about the lowest bits
    const v128_t mask = wasm_u8x16_const_splat(3);
    const v128_t masked = wasm_v128_and(shifted, mask);

    // Swizzle to put in the proper order
    const uint8_t swizmask[16] = { 15,11, 7, 3,
                                   14,10, 6, 2,
                                   13, 9, 5, 1,
                                   12, 8, 4, 0 };
    return wasm_i8x16_swizzle(masked, wasm_v128_load(&swizmask));
}
```
(The `bytesFromCrumbs` function expands packed 2-bit integers into 8-bit vectors. Every 2 bit integer gets its own byte. Also, the order between integers remains the same.)

**Comment by xloem** [comment]
Regarding wasm, there is indeed a 32-bit memory model for now, so sizeof(size_t) == 4 and large models cannot be allocated.

In practice on my trial wasm platform (ios a-shell where the whole system is wasm), malloc() calls for a little over 1GiB start returning 0 (and mmap is just a wrapper around malloc() and pread() here so doesn’t resolve it). 2bit quantization of llama 7b wouldn’t be sufficient compression for the particular wasm runtime I’ve been trying without some additional structured pruning and/or ahead-of-time model compilation.

But data > 4GB in size can’t be simultaneously referenced in memory (or “mmap”’d from a file) because the pointers are 32 bit for now.

**Pull request closed without merging**
