### PR TITLE
Fix NULL dereferences

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

this PR fixes some (potential) NULL dereferences. It is to avoid unintelligible crashes.

Cheers,
tpltnt

### CODE REVIEW

**Comment by slaren** [comment]
If you want to propose a comprehensive change to check every memory allocation, I wouldn't be opposed to that, but it is not ok to choose 3 `malloc` out of the dozens in the code and check only these. Additionally, please make an effort to respect the notation and style of the code, at the very least within the same source file.

**Comment by tpltnt** [comment]
@slaren where did I deviate from the code style?
I picked the 3 malloc() because there I could immediately spot a dereference of a (potential) NULL pointer.

**Comment by cebtenzzre** [comment]
Agreed. If we want to fail more gracefully on systems where malloc may return NULL (Linux won't by default), this is not the way to do it.
The changes to gguf.cpp are a good idea, but the functions are clearly intended to return false on failure, and there are code style issues (order of operands to `==`, lack of blank lines).

**Comment by slaren** [comment]
> @slaren where did I deviate from the code style?

Mostly by using `NULL ==` instead of `== NULL` like everywhere else.

**Comment by tpltnt** [comment]
Ok, I revoke my PR then. At least I tried.

**Pull request closed without merging**
