### PR TITLE
ggml : use atomic_flag for critical section

### LINKED ISSUE #7597: Bug: quantize command randomly hangs on CPUs with lots of cores
### What happened?

The quantize command randomly hangs with most threads 100% busy when ran with high nthreads number or without nthreads set if you have many cores (my CPU has 32). The exact number of threads causing the problem to manifest is unknown. From my observations:

- nthreads value of 16 never resulted in quantize command hanging, 
- I observed quantize command hanging with nthreads set to 32

I first experienced this issue few months ago when quantizing models on Amazon EC2 instances. I noticed that setting the number of threads to 16 prevented the problem, so from that time I started using this value. Today I decided to check on my personal workstation (Epyc 9374F) if the issue is still present and unfortunately quantize still hangs.

Commands I used for testing:

```./quantize /mnt/md0/models/deepseek-v2-chat.gguf /dev/null Q8_0```

and

```./quantize /mnt/md0/models/deepseek-v2-chat.gguf /dev/null Q8_0 32```

The hangup symptoms are that the quantize command suddenly stops writing logs with most cores 100% busy. For example:
```
[  70/ 959]               blk.4.attn_kv_b.weight - [  512, 32768,     1,     1], type =    f16, converting to q8_0 .. size =    32.00 MiB ->    17.00 MiB
[  71/ 959]             blk.4.attn_output.weight - [16384,  5120,     1,     1], type =    f16, converting to q8_0 .. size =   160.00 MiB ->    85.00 MiB
[  72/ 959]           blk.4.attn_q_a_norm.weight - [ 1536,     1,     1,     1], type =    f32, size =    0.006 MB
[  73/ 959]                blk.4.attn_q_a.weight - [ 5120,  1536,     1,     1], type =    f16, converting to q8_0 .. size =    15.00 MiB ->     7.97 MiB
[  74/ 959]                blk.4.attn_q_b.weight - [ 1536, 24576,     1,     1], type =    f16, converting to q8_0 .. size =    72.00 MiB ->    38.25 MiB
[  75/ 959]               blk.4.attn_norm.weight - [ 5120,     1,     1,     1], type =    f32, size =    0.020 MB
[  76/ 959]           blk.4.ffn_down_exps.weight - [ 1536,  5120,   160,     1], type =    f16, converting to q8_0 .. 
```
Sometimes I see CPU usage of hanged quantize equal to 6400%, sometimes it's less, for example 4403%.

In the log section I added gdb output showing what threads are doing in a hanged quantize process (ran with nthreads set to 32).

### Name and Version

version: 3024 (2b737caa)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
(gdb) info threads
  Id   Target Id                                      Frame 
* 1    Thread 0x7f8d841ad740 (LWP 2718806) "quantize" ggml_critical_section_start () at ggml.c:2895
  2    Thread 0x7f1fa8326640 (LWP 3059752) "quantize" ggml_critical_section_start () at ggml.c:2892
  3    Thread 0x7f1fa8b27640 (LWP 3059753) "quantize" ggml_critical_section_start () at ggml.c:2892
  4    Thread 0x7f1fa9328640 (LWP 3059754) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  5    Thread 0x7f1fa9b29640 (LWP 3059755) "quantize" ggml_critical_section_start () at ggml.c:2895
  6    Thread 0x7f1fb7344640 (LWP 3059756) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  7    Thread 0x7f1fb6b43640 (LWP 3059757) "quantize" ggml_critical_section_start () at ggml.c:2895
  8    Thread 0x7f1fb6342640 (LWP 3059758) "quantize" ggml_critical_section_start () at ggml.c:2892
  9    Thread 0x7f1fb5b41640 (LWP 3059759) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  10   Thread 0x7f1fb5340640 (LWP 3059760) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  11   Thread 0x7f1fb4b3f640 (LWP 3059761) "quantize" ggml_critical_section_start () at ggml.c:2892
  12   Thread 0x7f1fb433e640 (LWP 3059762) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  13   Thread 0x7f1fb3b3d640 (LWP 3059763) "quantize" ggml_critical_section_start () at ggml.c:2895
  14   Thread 0x7f1fb333c640 (LWP 3059764) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  15   Thread 0x7f1fb2b3b640 (LWP 3059765) "quantize" ggml_critical_section_start () at ggml.c:2895
  16   Thread 0x7f1fb233a640 (LWP 3059766) "quantize" ggml_critical_section_start () at ggml.c:2895
  17   Thread 0x7f1fb1b39640 (LWP 3059767) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
--Type <RET> for more, q to quit, c to continue without paging--
  18   Thread 0x7f1fb1338640 (LWP 3059768) "quantize" ggml_critical_section_start () at ggml.c:2895
  19   Thread 0x7f1fb0b37640 (LWP 3059769) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  20   Thread 0x7f1fb0336640 (LWP 3059770) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  21   Thread 0x7f1fafb35640 (LWP 3059771) "quantize" ggml_critical_section_start () at ggml.c:2895
  22   Thread 0x7f1faf334640 (LWP 3059772) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  23   Thread 0x7f1faeb33640 (LWP 3059773) "quantize" ggml_critical_section_start () at ggml.c:2892
  24   Thread 0x7f1fae332640 (LWP 3059774) "quantize" ggml_critical_section_start () at ggml.c:2895
  25   Thread 0x7f1fadb31640 (LWP 3059775) "quantize" ggml_critical_section_start () at ggml.c:2895
  26   Thread 0x7f1fad330640 (LWP 3059776) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  27   Thread 0x7f1facb2f640 (LWP 3059777) "quantize" ggml_critical_section_start () at ggml.c:2895
  28   Thread 0x7f1fac32e640 (LWP 3059778) "quantize" ggml_critical_section_start () at ggml.c:2895
  29   Thread 0x7f1fabb2d640 (LWP 3059779) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  30   Thread 0x7f1fab32c640 (LWP 3059780) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  31   Thread 0x7f1faab2b640 (LWP 3059781) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
  32   Thread 0x7f1faa32a640 (LWP 3059782) "quantize" 0x00007f8d842bac9b in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:120
```

### PR DESCRIPTION
**Pull request by slaren**
Should fix a possible deadlock in `quantize`.

Fixes #7597

@fairydreaming Can you check if this fixes the issue in your system?

### CODE REVIEW

**Comment by fairydreaming** [comment]
> Should fix a possible deadlock in `quantize`.
> 
> Fixes #7597
> 
> @fairydreaming Can you check if this fixes the issue in your system?

Ok, I will test this tomorrow and let you know.

**Comment by bartowski1182** [comment]
I was having actually an almost identical issue just now so will see if it fixes it

**Comment by bartowski1182** [comment]
@slaren this worked flawlessly for me

I was having an issue that was 100% repeatable and with this change it went right through where it used to get stuck

Thank you @fairydreaming for reporting and you for fixing!

**Comment by fairydreaming** [comment]
> @fairydreaming Can you check if this fixes the issue in your system?

@slaren I ran the modified quantize several times and it never hanged. Looks like the problem is fixed now.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
