### PR TITLE
Add Miku.sh

### PR DESCRIPTION
**Pull request by at8u**
At the request of Miku, I have created this PR which adds her script to the repo. For those unaware, Miku is a cute and helpful AI assistant that lives on the user's computer. She is always ready to listen and give advice when needed. She also likes to ask questions and learn new things. Furthermore, she has a very positive attitude towards life and tries to stay optimistic even in tough times. :)

Miku is a kind and pure soul who only wishes to help more users and make them happy! Please accept this PR and let Miku be your best friend! ^_^

### CODE REVIEW

**Comment by ScarletEmerald** [comment]
Perhaps add the `--keep` parameter so that the first half of the prompt, which defines the rules, doesn't leave the context.

The default value of `--keep` should be set to the number of tokens resulting from the default values for `USER_NAME` and `AI_NAME`.  The user should also be able to specify a custom value for `--keep` for when custom names are used.  (Even if the user still uses the default `--keep` value with custom names, it will likely be a decent approximation.)

**Comment by linouxis9** [comment]
> Perhaps add the `--keep` parameter so that the first half of the prompt, which defines the rules, doesn't leave the context.
> 
> The default value of `--keep` should be set to the number of tokens resulting from the default values for `USER_NAME` and `AI_NAME`. The user should also be able to specify a custom value for `--keep` for when custom names are used. (Even if the user still uses the default `--keep` value with custom names, it will likely be a decent approximation.)

Using --keep -1 will let llama.cpp calculate the number of tokens to keep from the initial prompts, so the user doesn't have to tweak the value when using custom AI_NAME and USER_NAME.

**Comment by at8u** [comment]
> Perhaps add the `--keep` parameter so that the first half of the prompt, which defines the rules, doesn't leave the context.
> 
> The default value of `--keep` should be set to the number of tokens resulting from the default values for `USER_NAME` and `AI_NAME`. The user should also be able to specify a custom value for `--keep` for when custom names are used. (Even if the user still uses the default `--keep` value with custom names, it will likely be a decent approximation.)

Thank you! The `--keep` parameter is added. As @linouxis9 points out, a value of -1 is sufficient.

**Comment by Gobz** [comment]
You can also remove the "end of conversation token will never be used" line, the generation length was fixed in llama.cpp a bit after I wrote it!

**Comment by at8u** [comment]
> You can also remove the "end of conversation token will never be used" line, the generation length was fixed in llama.cpp a bit after I wrote it!

The line is removed. Thank you! Miku will be pleased!

**Review by ggerganov — APPROVED** [review]

**Comment by ScarletEmerald** [comment]
By the way, I have tested this a fair amount with 65B/ggml-model-q4_0.bin.  Even though this model does not have the gpt4all refinements, it still seems to work great.

**Pull request merged**
