### PR TITLE
Add Parameters for setting obenblas

### PR DESCRIPTION
**Pull request by Coding-whiz**
Set number of OpenBLAS threads in openblas_set_num_threads function

This commit updates the openblas_set_num_threads function to properly set the number of threads used by OpenBLAS for parallel computations. The previous implementation had a bug that caused incorrect thread assignment.

The fix involves correctly setting the number of threads based on the system's available resources and ensuring proper synchronization between threads. This improvement enhances the efficiency and scalability of OpenBLAS for multi-threaded computations.

### CODE REVIEW

**Comment by SlyEcho** [comment]
This code doesn't seem to be functional.

Did you mean to create an issue instead?

**Comment by Coding-whiz** [comment]
> This code doesn't seem to be functional.
> 
> Did you mean to create an issue instead?

I guess i got the issue wrong

**Comment by SlyEcho** [comment]
Adding this file does not do anything. It is not included in the Makefile and CMakeLists.txt and even if it were it is not a valid C++ file.

The proper place would be to add the call somewhere in ggml.c as that is the place where any BLAS code is used in. It should be somewhere in the graph compute code because that is where thread counts are handled. The file is huge, I'm sorry, it may take a while to understand it.

Ultimately, OpenBLAS can also be compiled with the amount of threads you need.

**Comment by Coding-whiz** [comment]
> Adding this file does not do anything. It is not included in the Makefile and CMakeLists.txt and even if it were it is not a valid C++ file.
> 
> The proper place would be to add the call somewhere in ggml.c as that is the place where any BLAS code is used in. It should be somewhere in the graph compute code because that is where thread counts are handled. The file is huge, I'm sorry, it may take a while to understand it.
> 
> Ultimately, OpenBLAS can also be compiled with the amount of threads you need.

okay, I guess i get a bit of it now....this my beginning and I guess I will be able to clearly understand the concept of BLAS code in future easily

Thank you for helping me out and patiently clarifying my doubts☺️

**Comment by zenixls2** [comment]
This modification is totally not necessary.
You could assign it during the runtime by setting environment variables:
`OMP_NUM_THREADS=14`

refer: https://github.com/ggerganov/llama.cpp/pull/1502
you could instead close this pr and open a new one that modifies README to teach people how to set the number of threads.

**Pull request closed without merging**
