### PR TITLE
cuda: fix compile error in jetson platform

### PR DESCRIPTION
**Pull request by KyL0N**
this pr fix compile error in jetson platform
related issue: #4922 

the error was introduced by #4766 

#4766  add ```#include "ggml-cuda.h"```
before include ```#include <cuda_fp16.h>```

so the solution is move #include "ggml-cuda.h" after #include <cuda_fp16.h>

### CODE REVIEW

**Review by JohannesGaessler — APPROVED** [review]

**Review by cebtenzzre — CHANGES_REQUESTED** [review]
It sounds like ggml.h should `#include <cuda_fp16.h>`, no? #includes shouldn't be sensitive to the order they are in.

**Comment by KyL0N** [comment]
> It sounds like ggml.h should `#include <cuda_fp16.h>`, no? #includes shouldn't be sensitive to the order they are in.

I prefer `#include <cuda_fp16.h>` only in .cu file.

u can check ggml.h changes in #4766

**Comment by KyL0N** [comment]
that's ok
because cuda headers should be included before include `ggml-cuda.h`

**Comment by KyL0N** [comment]
@slaren Hello, could you please check if these changes are okay, or if anything else is needed?

**Comment by ggerganov** [comment]
> It sounds like ggml.h should #include <cuda_fp16.h>, no?

I want to narrow down the GPU-releated stuff in the core `ggml.h` and `ggml.c`. Adding a CUDA header there would be a step backwards in this regard.

Does Jetson platform not have `__fp16`?
Does this patch work:

```diff
diff --git a/ggml.h b/ggml.h
index 4c2ff6c6..9d165a86 100644
--- a/ggml.h
+++ b/ggml.h
@@ -305,9 +305,7 @@
 extern "C" {
 #endif
 
-#if defined(__ARM_NEON) && defined(__CUDACC__)
-    typedef half ggml_fp16_t;
-#elif defined(__ARM_NEON) && !defined(_MSC_VER)
+#if defined(__ARM_NEON) && !defined(_MSC_VER)
     typedef __fp16 ggml_fp16_t;
 #else
     typedef uint16_t ggml_fp16_t;
```

I'm not sure when the `#if defined(__ARM_NEON) && defined(__CUDACC__)` branch is actually true?

**Comment by KyL0N** [comment]
> Does Jetson platform not have `__fp16`?

this patch not work, nvcc dose not recognise `__fp16`
the alternative choice is `half` as I mentioned in https://github.com/ggerganov/llama.cpp/issues/1455#issuecomment-1555761710

> nvcc -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_CUBLAS -I/usr/local/cuda/include -I/opt/cuda/include -I/targets/x86_64-linux/include -I/usr/local/cuda/targets/aarch64-linux/include  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread -mcpu=native  -use_fast_math --forward-unknown-to-host-compiler -arch=sm_87 -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_MMV_Y=1 -DK_QUANTS_PER_ITERATION=2 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=128  -Wno-pedantic -Xcompiler "-Wno-array-bounds -Wno-format-truncation -Wextra-semi" -c ggml-cuda.cu -o ggml-cuda.o
> ggml.h(319): error: identifier "__fp16" is undefined

and `#if defined(__ARM_NEON) && defined(__CUDACC__)` which means cuda with aarch architecture

if just fallback to `typedef uint16_t ggml_fp16_t;` it will output gibberish as #1455 mentioned.

**Review by slaren — APPROVED** [review]
I am ok with this fix, but it would be good to add a comment explaining why these headers must be included last to prevent this from happening again.

**Review by cebtenzzre — APPROVED** [review]
Since there are two approvals I'll avoid blocking this, but my two cents: If we're going to have a `__CUDACC__`-specific typedef, why not have a `__CUDACC__`-specific #include in the same file? It just seems wrong to me that we would intentionally reference a symbol without including the header that declares it - ggml.h or otherwise.

It would be one thing if this was a #define, but the compiler error is on the typedef itself in this case.

**Comment by ggerganov** [comment]
@KyL0N Please add a comment about why the headers are there and we can merge

**Comment by KyL0N** [comment]
> why not have a `__CUDACC__`-specific #include in the same file

In my view, if __CUDACC__ is defined, then nvcc must be the compiler. Therefore, including headers like cuda_fp16.h or other CUDA-related files is also necessary

**Comment by ggerganov** [comment]
Thanks for the discussion - IMO the fundamental issue is that `ggml_fp16_t` is exposed through the public `ggml` API in the first place. It's something to fix in the future, but for now will merge this workaround

**Pull request merged**
