### PR TITLE
ci : faster CUDA toolkit installation method and use ccache

### LINKED ISSUE #10486: Feature Request: Improve CI speed of CUDA on Windows
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

The whole CI of a PR takes about 50+minutes.
Following two tasks take 50+ and 40+mins:

```
    windows-latest-cmake-cuda (12.2.0, cuda)
    windows-latest-cmake-cuda (11.7.1, cuda)
```

Other tasks takes time less than 25ms.

### Motivation

If the CI time is reduced to 30min from 50+mins, it will save more time of developers.
Speed up the progress of project.

### Possible Implementation

_No response_

### PR DESCRIPTION
**Pull request by slaren**
ccache could be enabled for other builds, it makes a big difference. When building PRs, it should reuse the cache from the parent build in master.

Credit where it's due: I took the CUDA installation method from the CI in karpathy llm.c

Fixes #10486

### CODE REVIEW

**Review by JohannesGaessler — APPROVED** [review]
If ccache actually helps we obviously should use it though I'm confused that it does. That would imply that there is persistent storage between different CI builds which to my knowledge there shouldn't be.

**Comment by slaren** [comment]
Github has a cache that allows data to be kept between builds. https://github.com/ggerganov/llama.cpp/actions/caches

**Comment by CISC** [comment]
@slaren windows-cuda (11.7) just started failing:
```
-- Unable to find cudart library.
-- Could NOT find CUDAToolkit (missing: CUDA_CUDART) (found version "11.7.99")
CMake Error at ggml/src/ggml-cuda/CMakeLists.txt:183 (message):
  CUDA Toolkit not found
```
https://github.com/ggml-org/llama.cpp/actions/runs/15134666526/job/42543546796

**Comment by slaren** [comment]
It looks like a transient failure when downloading one of the files, it's probably nothing.
>curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

**Pull request merged**
