### PR TITLE
Fix opencl build by wrap #if-else-endif with \n

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by howard0su** [comment]
Please review. opencl support currently is in a completely broken state.

**Comment by 0cc4m** [comment]
I hadn't noticed an issue, and neither did the users of koboldcpp or the people reviewing the PR which added those preprocessor lines. Which platform/configuration is completely broken?

**Comment by howard0su** [comment]
check #2065 , at least I can repro the issue on Windows 10 and Windows 11.

**Comment by JackJollimore** [comment]
> check #2065 , at least I can repro the issue on Windows 10 and Windows 11. I don't have Linux to test now.

Hi,

I haven't experienced kernel errors while running with OpenCL on my device. I'm running latest build.
```
> uname -a   
Linux localhost 4.14.190-23725627-abG975WVLS8IWD1 #2 SMP PREEMPT Mon Apr 10 18:16:39 KST 2023 aarch64 Android
```
It may be Windows specific.

**Comment by howard0su** [comment]
another user reported the issue on Windows. Can I merge this? @ggerganov @0cc4m

**Review by 0cc4m — APPROVED** [review]

**Comment by 0cc4m** [comment]
Sorry for the delay, haven't had much time in the last few days.

**Pull request merged**
