### PR TITLE
server: public: move default parameters to its own file

### PR DESCRIPTION
**Pull request by xatier**
This commit enables users to easily update the parameters with desired default values without getting familiar with frontend details.

----

Hi @ggerganov, very simple change, this commit allows users to configure and experiment with different parameters without patching the `index.html` each time. I found it super helpful for my workflow (by swapping different `params.js` files).

### CODE REVIEW

**Comment by ngxson** [comment]
If you add a new file to `public` directory, it's better to also embed it into compiled cpp file. Else, the frontend won't work if it's standalone binary.

**Comment by xatier** [comment]
@ngxson sorry, I'm not familiar with the code base, how do I do that?

**Comment by xatier** [comment]
@ngxson never mind, found #6661 and followed the pattern, thanks for pointing this out.

**Comment by xatier** [comment]
rebase.

**Comment by xatier** [comment]
rebase.

**Comment by ngxson** [comment]
> This commit enables users to easily update the parameters with desired default values without getting familiar with frontend details.

Sorry earlier I misunderstand your intent.

I don't get how it will be easier for users without any knowledge about frontend details. You new js file is already part of frontend.

Also I don't think many users want to change default params. At worst, we can implement a mechanism to save the params into localStorage to prevent it from being reset when user reload the page. But anw, I don't think it's needed for now; users who have problem with this part can always open an issue.

**Comment by xatier** [comment]
@ngxson, I believe it's way easier for people to update values with my proposed `params.js`, even if they have limited JS knowledge. I kept it as minimal dictionaries with key-value pairs. People can also simply swap out the file if they need different parameters for different models (which is quite common in my workflow testing different LLMs).

Before my change, if one needs to update default values, they either need to do that on the UI each time, or try to decipher the complex `index.html`, locate these two dictionaries, and make changes. The intent of this PR was to allow people to experiment with different parameters without these manual steps.

Anyway, if you don't find it necessary, I can close the PR.

**Pull request closed without merging**
