### PR TITLE
fix build break on arm64 linux

### PR DESCRIPTION
**Pull request by snadampal**
This fixes the build break from the recent changes to move the CPU backend to separate files
https://github.com/ggerganov/llama.cpp/pull/10144

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by slaren — APPROVED** [review]

**Comment by snadampal** [comment]
Can we please consider adding CI support for `arm64 linux` ?

**Comment by slaren** [comment]
There is a arm64 CI, but I guess it doesn't have SVE support. It should still be possible to test the at least that the build completes with SVE enabled with the github runner, it's just not done at the moment.

**Comment by snadampal** [comment]
thanks @slaren , please let's know if the SVE capable runner support can be prioritized, happy to collaborate with you on this.

**Comment by bandoti** [comment]
It looks like Qemu supports ARM SVE (https://wiki.qemu.org/Features/ARM/SVE). A good approach might be to run this on an x86_64 ubuntu-latest and run it through qemu.

**Comment by ggerganov** [comment]
We can add an AI instance from Azure cloud. But last time I checked, they were still in preview.

**Comment by bandoti** [comment]
Yeah GitHub actions have the feature for their enterprise tier but not yet for open source projects.

In the interest of simplicity though, keeping on GitHub actions instead of calling out to AWS or something might be desirable.

Although, with caching for qemu images and running on a low-cost Ubuntu runner for one or two jobs should be fine too. In addition, that pattern can apply for FreeBSD &co.

I plan on getting FreeBSD set up this way soon but haven't had time yet. 😊

**Pull request merged**
