### PR TITLE
Chat UI: add a subtle loading animation

### PR DESCRIPTION
**Pull request by akx**
This PR adds a subtle loading animation to the text input box to make it a bit clearer that something's happening:

https://github.com/ggerganov/llama.cpp/assets/58669/2aae13fc-9ced-42f3-8545-91eedadcef84

### CODE REVIEW

**Comment by Green-Sky** [comment]
>  subtle

i had to watch the video 5 times :smile:

**Review by Green-Sky — APPROVED** [review]
code looks simple

**Comment by jhen0409** [comment]
Looks good! But I think it might need some tweaks for dark mode:

https://github.com/ggerganov/llama.cpp/assets/3001525/635ef93f-e3ff-4aa8-832e-737b15df2cd0

**Comment by akx** [comment]
@jhen0409 TBH that doesn't look that bad either to me :) Less subtle, sure...

**Comment by jhen0409** [comment]
> TBH that doesn't look that bad either to me :) Less subtle, sure...

@akx I think I uploaded the wrong screenshot (I edit `--loading-color-2` to `#eeeeee55`), the gradient should be brighter in original version:

Screenshot 2023-08-16 at 19 10 01

**Comment by akx** [comment]
Rebased.

@jhen0409 Added dark mode overrides for the colors 👍

**Review by jhen0409 — APPROVED** [review]

**Pull request merged**
