### PR TITLE
add_special option for server tokenize endpoint

### PR DESCRIPTION
**Pull request by JohanAR**

### CODE REVIEW

**Review by phymbert — COMMENTED** [review]
I do not use the tokenize endpoint on my end.

But is it worth the effort to add a test case ?

**Comment by JohanAR** [comment]
> I do not use the tokenize endpoint on my end.
> 
> But is it worth the effort to add a test case ?

I'm using the /completion endpoint with lists of tokens instead of strings, and I thought it would be nice if the client didn't need to know how the model represents the BOS token, now that there's a bunch of new models which don't use `<s>`

It's a pretty small feature, but I can look into adding a test if you prefer.

**Comment by teleprint-me** [comment]
As an FYI, `train-text-from-scratch` uses the BOS by default.

**Comment by ngxson** [comment]
Yeah this seems to be an useful thing, since sometimes we want to tokenize a part of text (BOS should not be added in this case)

For extra safe, I'd suggest a test case like this: Tokenize a text with `add_special = true` and then with `add_special = false`, then compare if the output is different or not (with `add_special = true` we should see more tokens)

**Comment by JohanAR** [comment]
@ngxson currently trying to understand the python behave framework and how to formulate the tests :) I'm not sure how to express something like "when the following string is tokenized, the resulting length must be longer than when this other string is tokenized" in behave, but perhaps I could figure it out.

Was thinking I would look up the BOS token for the test model (I'm guessing it's <s>) and then verify that /tokenize with {content="<s>"}, {content="<s>", add_special=False} and {content="", add_special=True} all tokenize to the same sequence. Though perhaps it's not a good idea to hard-code a dependence to a particular tokenizer, i.e. making a case which fails if the test model is substituted for one which has <|begin_of_text|> or <BOS_TOKEN> instead.

**Comment by ngxson** [comment]
> Update: The above did not work, the tokenizer in tinyllamas/stories260K.gguf behaves strange. I'll hard-code the BOS token as [1] in the tests and check for that instead, not really worse than hard-coding it to <s> IMO

Instead of hard-coding, another idea would be to input the BOS as a behave step, something like:

```
    Given a server listening on localhost:8080
    And   a model file tinyllamas/stories260K.gguf from HF repo ggml-org/models
    And   a model file test-model.gguf
    And   a model alias tinyllama-2
    ...
    And BOS token is 1
```

The handler for that is defined at the beginning of `steps.py`

**Comment by JohanAR** [comment]
@ngxson yea, perhaps that is better. Changed it to do that.

**Review by phymbert — APPROVED** [review]

**Pull request merged**
