### PR TITLE
cmake : support build for iOS/tvOS

### LINKED ISSUE #3106: Building for iPhone (iOS) error: xpc/xpc.h not found in IOSurfaceAPI when including <Metal/Metal.h> in ggml-metal.m
Getting the error `xpc/xpc.h not found` when building targeting iOS.

I followed the fix in this stackoverflow answer: https://stackoverflow.com/questions/24013814/how-to-resolve-xpc-h-not-found-error

I downloaded the necessary headers from: https://github.com/realthunder/mac-headers, then copied the `xpc` directory in there into the root folder of `llama.cpp`.

After this fix, iOS builds work.

Is this something wrong with my setup in particular? Or is adding the `xpc` headers is necessary? If so, should I do a pull request adding the headers?

### PR DESCRIPTION
**Pull request by jhen0409**
Fix https://github.com/ggerganov/llama.cpp/issues/3106.

Update the CMakeLists.txt and add CI steps to ensure to continue to work.

### CODE REVIEW

**Comment by alonfaraj** [comment]
Great!
Maybe it worth to have a separate job for each build (iOS, tvOS) and not putting all together inside macOS-latest?
It would be easier to monitor if one of them fails.

**Review by ggerganov — APPROVED** [review]

**Comment by jhen0409** [comment]
> Great! Maybe it worth to have a separate job for each build (iOS, tvOS) and not putting all together inside macOS-latest-cmake? It would be easier to monitor if one of them fails and keep them independent.

Yeah it might be better and same as other builds, will change it before merge.

**Comment by cyrilzakka** [comment]
Would it be possible to add VisionOS support as well?

**Comment by jhen0409** [comment]
> Would it be possible to add VisionOS support as well?

I've tried an iOS build on visionOS simulator before and it works well. Not yet to try with a visionOS project, but I think it should be easy by add the OS target.

**Comment by cyrilzakka** [comment]
Thanks! In case you also have a sample Swift/VisionOS project to look at, I'd love to take a look at it too! I tried using `llm_farm` which is based off of this project but it crashes on model load.

**Comment by jhen0409** [comment]
> Thanks! In case you also have a sample Swift/VisionOS project to look at, I'd love to take a look at it too! I tried using `llm_farm` which is based off of this project but it crashes on model load.

It was an internal iOS project with target visionOS + `Designed for iPad`. I can switch back to Xcode beta to give it try again in the next few days.

Also, if it's a Simulator, during to Metal limitations we can't use constant buffers more than 14, so remember to use ngl = 0.

**Comment by jhen0409** [comment]
> @jhen0409 Sorry to have to ask, but where do I set the ngl 0 flag in Swift? I see it as an option in the CI but not anywhere else (e.g. ggml-metal). Thanks for your patience!

To be clear, it's called [`n_gpu_layers`](https://github.com/ggerganov/llama.cpp/blob/f5ef5cfb18148131fcf45bdd2331f0db5ab7c3d0/llama.h#L153) in the parameters.

**Pull request merged**
