### PR TITLE
Change CMake files to library target

### PR DESCRIPTION
**Pull request by SlyEcho**
The main change here is to get rid of the file and library lists and use targets instead.

Here is an example of the dependencies of main.cpp when building with `LLAMA_CLBLAST=ON`:

`LLAMA_CUBLAS=ON`:

<details>
<summary>compile_commands.json for CUDA build</summary>

```json
[
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/cc -DGGML_USE_CUBLAS -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -mf16c -mfma -mavx -mavx2 -o CMakeFiles/ggml.dir/ggml.c.o -c /home/henri/src/llama.cpp/ggml.c",
  "file": "/home/henri/src/llama.cpp/ggml.c",
  "output": "CMakeFiles/ggml.dir/ggml.c.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -DGGML_USE_CUBLAS -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o CMakeFiles/llama.dir/llama.cpp.o -c /home/henri/src/llama.cpp/llama.cpp",
  "file": "/home/henri/src/llama.cpp/llama.cpp",
  "output": "CMakeFiles/llama.dir/llama.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/opt/cuda/bin/nvcc -forward-unknown-to-host-compiler -DGGML_USE_CUBLAS -isystem /opt/cuda/include -O3 -DNDEBUG -std=c++11 -mf16c -mfma -mavx -mavx2 -x cu -c /home/henri/src/llama.cpp/ggml-cuda.cu -o CMakeFiles/ggml-cuda.dir/ggml-cuda.cu.o",
  "file": "/home/henri/src/llama.cpp/ggml-cuda.cu",
  "output": "CMakeFiles/ggml-cuda.dir/ggml-cuda.cu.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o tests/CMakeFiles/test-quantize-fns.dir/test-quantize-fns.cpp.o -c /home/henri/src/llama.cpp/tests/test-quantize-fns.cpp",
  "file": "/home/henri/src/llama.cpp/tests/test-quantize-fns.cpp",
  "output": "tests/CMakeFiles/test-quantize-fns.dir/test-quantize-fns.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o tests/CMakeFiles/test-quantize-perf.dir/test-quantize-perf.cpp.o -c /home/henri/src/llama.cpp/tests/test-quantize-perf.cpp",
  "file": "/home/henri/src/llama.cpp/tests/test-quantize-perf.cpp",
  "output": "tests/CMakeFiles/test-quantize-perf.dir/test-quantize-perf.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o tests/CMakeFiles/test-sampling.dir/test-sampling.cpp.o -c /home/henri/src/llama.cpp/tests/test-sampling.cpp",
  "file": "/home/henri/src/llama.cpp/tests/test-sampling.cpp",
  "output": "tests/CMakeFiles/test-sampling.dir/test-sampling.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o tests/CMakeFiles/test-tokenizer-0.dir/test-tokenizer-0.cpp.o -c /home/henri/src/llama.cpp/tests/test-tokenizer-0.cpp",
  "file": "/home/henri/src/llama.cpp/tests/test-tokenizer-0.cpp",
  "output": "tests/CMakeFiles/test-tokenizer-0.dir/test-tokenizer-0.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/CMakeFiles/common.dir/common.cpp.o -c /home/henri/src/llama.cpp/examples/common.cpp",
  "file": "/home/henri/src/llama.cpp/examples/common.cpp",
  "output": "examples/CMakeFiles/common.dir/common.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/main/CMakeFiles/main.dir/main.cpp.o -c /home/henri/src/llama.cpp/examples/main/main.cpp",
  "file": "/home/henri/src/llama.cpp/examples/main/main.cpp",
  "output": "examples/main/CMakeFiles/main.dir/main.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/quantize/CMakeFiles/quantize.dir/quantize.cpp.o -c /home/henri/src/llama.cpp/examples/quantize/quantize.cpp",
  "file": "/home/henri/src/llama.cpp/examples/quantize/quantize.cpp",
  "output": "examples/quantize/CMakeFiles/quantize.dir/quantize.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/quantize-stats/CMakeFiles/quantize-stats.dir/quantize-stats.cpp.o -c /home/henri/src/llama.cpp/examples/quantize-stats/quantize-stats.cpp",
  "file": "/home/henri/src/llama.cpp/examples/quantize-stats/quantize-stats.cpp",
  "output": "examples/quantize-stats/CMakeFiles/quantize-stats.dir/quantize-stats.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/perplexity/CMakeFiles/perplexity.dir/perplexity.cpp.o -c /home/henri/src/llama.cpp/examples/perplexity/perplexity.cpp",
  "file": "/home/henri/src/llama.cpp/examples/perplexity/perplexity.cpp",
  "output": "examples/perplexity/CMakeFiles/perplexity.dir/perplexity.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/embedding/CMakeFiles/embedding.dir/embedding.cpp.o -c /home/henri/src/llama.cpp/examples/embedding/embedding.cpp",
  "file": "/home/henri/src/llama.cpp/examples/embedding/embedding.cpp",
  "output": "examples/embedding/CMakeFiles/embedding.dir/embedding.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/save-load-state/CMakeFiles/save-load-state.dir/save-load-state.cpp.o -c /home/henri/src/llama.cpp/examples/save-load-state/save-load-state.cpp",
  "file": "/home/henri/src/llama.cpp/examples/save-load-state/save-load-state.cpp",
  "output": "examples/save-load-state/CMakeFiles/save-load-state.dir/save-load-state.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/benchmark/CMakeFiles/benchmark.dir/benchmark-matmult.cpp.o -c /home/henri/src/llama.cpp/examples/benchmark/benchmark-matmult.cpp",
  "file": "/home/henri/src/llama.cpp/examples/benchmark/benchmark-matmult.cpp",
  "output": "examples/benchmark/CMakeFiles/benchmark.dir/benchmark-matmult.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/examples -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o examples/baby-llama/CMakeFiles/baby-llama.dir/baby-llama.cpp.o -c /home/henri/src/llama.cpp/examples/baby-llama/baby-llama.cpp",
  "file": "/home/henri/src/llama.cpp/examples/baby-llama/baby-llama.cpp",
  "output": "examples/baby-llama/CMakeFiles/baby-llama.dir/baby-llama.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/pocs -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o pocs/vdot/CMakeFiles/vdot.dir/vdot.cpp.o -c /home/henri/src/llama.cpp/pocs/vdot/vdot.cpp",
  "file": "/home/henri/src/llama.cpp/pocs/vdot/vdot.cpp",
  "output": "pocs/vdot/CMakeFiles/vdot.dir/vdot.cpp.o"
},
{
  "directory": "/home/henri/src/llama.cpp/build-cuda",
  "command": "/usr/bin/c++ -I/home/henri/src/llama.cpp/pocs -I/home/henri/src/llama.cpp/examples/. -I/home/henri/src/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -mf16c -mfma -mavx -mavx2 -o pocs/vdot/CMakeFiles/q8dot.dir/q8dot.cpp.o -c /home/henri/src/llama.cpp/pocs/vdot/q8dot.cpp",
  "file": "/home/henri/src/llama.cpp/pocs/vdot/q8dot.cpp",
  "output": "pocs/vdot/CMakeFiles/q8dot.dir/q8dot.cpp.o"
}
]
```

### CODE REVIEW

**Review by slaren — DISMISSED** [review]
This looks much better than the `GGML_CUDA_SOURCES` hack.

**Comment by Green-Sky** [comment]
Can you resolve and re-run ci?
why did you switch from OBJECT to STATIC?
Looks look otherwise :)

**Comment by SlyEcho** [comment]
I will deal with the other stuff first and get back to this. I want to test on Windows and Mac as well.

> why did you switch from OBJECT to STATIC?

Because object libraries cannot [propagate dependencies](https://gitlab.kitware.com/cmake/cmake/-/issues/18682). I don't see any downsides to static libs otherwise, unless that was the Windows problem.

**Comment by SlyEcho** [comment]
Have to come back later, code is diverged a lot now. I meant to do this PR before the ROCm merge because I use some of these ideas there, but it went in already and it's not that crucial.

**Pull request closed without merging**
