### PR TITLE
awq-py : remove

### PR DESCRIPTION
**Pull request by ggerganov**
I think this functionality never ended up being used, plus I think GGUF support was at some point implemented in the OG repo. So I think there is no reason to keep the code around

### CODE REVIEW

**Comment by wilderfield** [comment]
@ggerganov looks like the functionality was referenced by convert.py ?
https://github.com/ggerganov/llama.cpp/blob/652ca2bded3c818320d92c70d2b67f64bdbff5e5/convert.py#L1395-L1407

I'm a bit confused now, does this repo support quantizing models with [AWQ](https://arxiv.org/abs/2306.00978)

**Comment by ggerganov** [comment]
I just removed the leftovers from `convert.py`

`llama.cpp` does not provide AWQ quantization functionality. I believe there was work in the AWQ repos to add support for generating GGUF files directly which in turn are compatible with `llama.cpp`

**Comment by wilderfield** [comment]
Thanks @ggerganov. PS, I really want to know whats in your `.vimrc`.

**Comment by ggerganov** [comment]
It's a bit of a mess, but here it is: https://github.com/ggerganov/ggterm

**Pull request merged**
