### PR TITLE
gguf : fix strings to not be null-terminated

### LINKED ISSUE #2836: Quantize adds `\0` to the end of GGUF strings
# Expected Behavior

Strings in GGUF should not be null-terminated.

# Current Behavior

When quantizing a GGUF model produced by the Python script, `quantize` appears to add a null-terminator to all strings it processes, including metadata keys and tensor names.

I have a program with my experimental Rust reader:
```rust
let gguf = gguf::Gguf::load(&mut file)?;
let mut keys: Vec<_> = gguf.metadata.keys().cloned().collect();
keys.sort();
println!("{keys:?}");
```

This is what it produces for the original `f16` model:
```
["general.architecture", "llama.attention.head_count", "llama.attention.head_count_kv", "llama.attention.layer_norm_rms_epsilon", "llama.block_count", "llama.context_length", "llama.embedding_length", "llama.feed_forward_length", "llama.rope.dimension_count", "tokenizer.ggml.model", "tokenizer.ggml.scores", "tokenizer.ggml.tokens"]
```

This is what it produces after `q5_k` v1 or v2 quantization (the bug is present in both versions):
```
["general.architecture\0", "general.file_type\0", "general.quantization_version\0", "llama.attention.head_count\0", "llama.attention.head_count_kv\0", "llama.attention.layer_norm_rms_epsilon\0", "llama.block_count\0", "llama.context_length\0", "llama.embedding_length\0", "llama.feed_forward_length\0", "llama.rope.dimension_count\0", "tokenizer.ggml.model\0", "tokenizer.ggml.scores\0", "tokenizer.ggml.tokens\0"]
```

To confirm this isn't an issue with my reader:
```
llm # hexdump -C models/llama2/llama-2-7b-f16.gguf | head -n 4
00000000  47 47 55 46 01 00 00 00  23 01 00 00 0c 00 00 00  |GGUF....#.......|
00000010  14 00 00 00 67 65 6e 65  72 61 6c 2e 61 72 63 68  |....general.arch|
00000020  69 74 65 63 74 75 72 65  08 00 00 00 05 00 00 00  |itecture........|
00000030  6c 6c 61 6d 61 14 00 00  00 6c 6c 61 6d 61 2e 63  |llama....llama.c|

llm # hexdump -C models/llama2/llama-2-7b-q5_k.v2.gguf | head -n 4          
00000000  47 47 55 46 02 00 00 00  23 01 00 00 00 00 00 00  |GGUF....#.......|
00000010  0e 00 00 00 00 00 00 00  15 00 00 00 00 00 00 00  |................|
00000020  67 65 6e 65 72 61 6c 2e  61 72 63 68 69 74 65 63  |general.architec|
00000030  74 75 72 65 00 08 00 00  00 06 00 00 00 00 00 00  |ture............|
```

Ignoring the counts that were increased from 4 to 8 bytes in v2, you can see that `general.architecture` has a length of `0x14` in the `f16` model and a length of `0x15` in the `q5_k` model.

# Steps to Reproduce

Produce a GGUF model with the Python scripts, then quantize it with the `quantize` executable. Compare the resulting GGUF strings in both files.

### PR DESCRIPTION
**Pull request by ggerganov**
close #2836

### CODE REVIEW

**Comment by ggerganov** [comment]
cc @philpax @slaren

**Comment by slaren** [comment]
Maybe this one needs to be updated too?

https://github.com/ggerganov/llama.cpp/blob/34e5c9afe5816368ad75fdebacffc172cb863a7e/ggml.c#L20232

**Comment by slaren** [comment]
I am trying to compare a f16 model converted with `convert.py`, then taking that the same model and "quantizing" to f16. The result should be the same, right? But I am seeing differences in the headers. It looks like there is a lot more padding in the file created by `quantize`. Left is from `quantize`, right is from `convert.pty`:
image

**Comment by ggerganov** [comment]
The left one is GGUFv2 and the right one is GGUFv1 - see the 5th byte

**Comment by slaren** [comment]
Yes, after reconverting the file the headers look almost identical. Still, the files have a different hash. It's probably not an issue, but I'll see if I can figure what exactly are the differences.

**Comment by ggerganov** [comment]
Yes, we should figure out where this difference comes from

**Comment by slaren** [comment]
Ok, the only difference is the metadata `general.quantization_version`. I commented it from llama.cpp, and the results are identical now, exact same md5sum.

**Comment by ggerganov** [comment]
Looks like this change is backwards compatible, so no need for re-quantizing models in general, correct?

**Comment by slaren** [comment]
In practice, I doubt this would cause any issues, but the strings read from the python library will have a trailing NUL character. However, it should be easy to modify the library to remove them, there is no reason to have strings with NULs anyway.

**Comment by philpax** [comment]
All seems to work well, thanks!

**Pull request merged**
