### PR TITLE
gguf-py: add support for I8, I16 and I32

### PR DESCRIPTION
**Pull request by certik**
These types are documented at https://github.com/ggerganov/ggml/blob/9c2adc4962a3a5d259f10db2171e0df5c83e4b05/docs/gguf.md, and implemented in C at https://github.com/ggerganov/llama.cpp/blob/19885d205e768579ab090d1e99281cae58c21b54/ggml.h#L340. This PR adds support for them in the Python GGUF library.

### CODE REVIEW

**Comment by ggerganov** [comment]
Will merge after https://github.com/ggerganov/llama.cpp/pull/6050

**Review by ggerganov — APPROVED** [review]

**Comment by certik** [comment]
@ggerganov my apologies for the `tensor_shape` vs `tensor_dtype` mistake --- I just discovered the same this morning. I thought I tested it carefully, but I missed this. Thanks for fixing it!

**Comment by ggerganov** [comment]
No problem. Btw, I think we need to update the `gguf-py` version

**Comment by certik** [comment]
> Btw, I think we need to update the `gguf-py` version

I sent a PR to do so here: https://github.com/ggerganov/llama.cpp/pull/6060.

**Pull request merged**
