### PR TITLE
added implementation of DRY sampler

### PR DESCRIPTION
**Pull request by l3utterfly**
Accidentally broke branch by merging, creating a new PR.

Original PR: https://github.com/ggerganov/llama.cpp/pull/6839

### CODE REVIEW

**Comment by p-e-w** [comment]
There was no need to close the first PR. Fragmenting the discussion is bad, and people doing `git blame` in the future shouldn't have to link-hop through a chain of PRs to understand everything.

Just force-push to the previous branch. Something like this should do the trick (from the `dry-sampler-2` local branch):

```
git push --force --set-upstream origin dry-sampler
```

**Comment by l3utterfly** [comment]
Sorry, I'm bad with git. Tried your suggestion, didn't seem to work.

I tried a "reset + force push" before closing the other PR, it deleted any new changes in the `dry-sampler` branch, but I accidentally merged the flash attention changes into the branch, those commits were earlier than the dry sampler changes, so I don't believe they got deleted.

Obligatory xkcd: https://xkcd.com/1597/

**Comment by p-e-w** [comment]
I don't get it. `git push --force` should replace the contents of the remote branch with those from the local one. Which includes the entire history. I've used it many times like this and that's what happened. Are you sure you were pushing from the *new* branch (`dry-sampler-2`)?

**Comment by l3utterfly** [comment]
Hmm.. locally I'm on the `dry-sampler2` branch, on github it's `origin/dry-sampler`.

I used this command:
image

It just says everything is up to date. But as you can see on github, the `dry-sampler` branch still contains the flash attention changes

**Comment by p-e-w** [comment]
Ah, I see. You're still pushing from your local `dry-sampler` branch rather than from `dry-sampler-2`. See the output of the push command. The name of the local branch is the problem.

Try this command:

```
git push --force --set-upstream origin dry-sampler-2:dry-sampler
```

**Comment by l3utterfly** [comment]
Thank you for taking the time to help me with this. I did that command, the `dry-sampler` branch seems to be correct now: https://github.com/l3utterfly/llama.cpp/commits/dry-sampler/

It seems the previous PR has not updated automatically: https://github.com/ggerganov/llama.cpp/pull/6839/files

Is there anything manual I need to do? Or just need to wait until Github picks it up?

**Comment by p-e-w** [comment]
Just a random guess, maybe the PR needs to be open in order to reflect changes?

**Comment by l3utterfly** [comment]
I think you are right.. but that means we are out of luck:

image

**Comment by p-e-w** [comment]
https://gist.github.com/Farhan-Haseeb/fd4cbb476de4e2931c322d7bacb75e5f?permalink_comment_id=4512987#gistcomment-4512987

**Comment by l3utterfly** [comment]
Did that already:

image

**Comment by p-e-w** [comment]
That was an hour ago. Since then you force-pushed. You may have to delete and restore again.

**Comment by l3utterfly** [comment]
Fixed! Thank you so much for helping me!

And sorry for the hassle, didn't know how force push worked before.

**Pull request closed without merging**
