### PR TITLE
Fix broken Vulkan Cmake (properly)

### LINKED ISSUE #5191: Vulkan build on Windows cmake broken since commit 172ac826 (PR #5182)
Trying to Build using cmake on windows : 
```
> cmake .. -DBUILD_SHARED_LIBS=OFF -DLLAMA_VULKAN=ON -G "Visual Studio 17 2022" -A x64
> cmake --build . --config Release
```
The compilation breaks when building `ggml-vulkan.cpp`, somehow the compiler can't find vulkan.hpp

I'm confused because the compilation works fine on [0cc4m's original PR branch](https://github.com/0cc4m/koboldcpp/tree/vulkan), using the exact same commands; on the same machine.

### PR DESCRIPTION
**Pull request by netrunnereve**
Sorry about breaking Vulkan Windows CMake with #5182! This PR fixes the build for both Linux and Windows and adds Vulkan CI support as well. 

Resolves #5191.

### CODE REVIEW

**Comment by 0cc4m** [comment]
Wasn't it just the "STATIC" that caused issues? Why revert the changes that make Vulkan work like the other backends in the CMakeLists.txt?

**Comment by henk717** [comment]
I still can't compile this, it misses the vulkan header files despite the VulkanSDK being installed.

**Comment by sorasoras** [comment]
Work as well  on windows

**Review by stduhpf — APPROVED** [review]

**Comment by stduhpf** [comment]
Anyone with write acess to the repo want to accept this PR?

**Comment by 0cc4m** [comment]
I don't know enough about CMake to be able to tell why the version on master fails, but this seems to work on Windows and Linux, so it's fine by me.

**Review by 0cc4m — APPROVED** [review]

**Comment by netrunnereve** [comment]
> Wasn't it just the "STATIC" that caused issues? Why revert the changes that make Vulkan work like the other backends in the CMakeLists.txt?

I reverted it because those changes were plain wrong. Changing from static to object is all you need to make it build properly on both Linux and Windows. I have a better explaination of all this at https://github.com/ggerganov/llama.cpp/issues/5191#issuecomment-1915907829.

**Pull request merged**
