### PR TITLE
fix no file in win rel for sycl

### PR DESCRIPTION
**Pull request by NeoZhangJianyu**
fix no file in win rel for sycl

### CODE REVIEW

**Review by airMeng — APPROVED** [review]

**Comment by NeoZhangJianyu** [comment]
@ggerganov  The CI of ubuntu is always timeout.
Could I merge this PR? The content has nothing with ubuntu CI.

**Comment by slaren** [comment]
The nix CI is timing out everywhere, it is not due to this PR.

**Comment by NeoZhangJianyu** [comment]
Thank you all!

**Comment by easyfab** [comment]
There are some dll that are missing : sycl7.dll libmmd.dll mkl_syscl_blas.4.dll svml_dispmd.dll.

Is a redistributable library needed if yes where to download ?

**Comment by NeoZhangJianyu** [comment]
@easyfab 
Yes, currently, you need to download and install oneAPI base toolkit before run them.
I will study to add missed dll files in it.

**Pull request merged**
