### PR TITLE
cuda : refactor into multiple files

### PR DESCRIPTION
**Pull request by slaren**
The main goal is to make it easier to work on the CUDA backend and improve compilation times.

### CODE REVIEW

**Comment by slaren** [comment]
If you have any suggestions to improve the organization of the files, the naming scheme or anything else, please let me know, I am sure it could be improved.

Other than that, the only thing left to do is fix the HIP and `Makefile` builds.

**Comment by airMeng** [comment]
I think previously we ought to unify all functions into one file https://github.com/ggerganov/llama.cpp/discussions/3965#discussioncomment-7484486, now the design has changed? Could you share any more details?

**Comment by slaren** [comment]
There was a brief discussion about this in #5434. The compilation time of the CUDA backend was increasing to the point that it was complicating working on it. Personally, I also prefer to work on multiple smaller files than in one large file, but I don't know if everybody agrees about that.

**Comment by airMeng** [comment]
> There was a brief discussion about this in #5434. The compilation time of the CUDA backend was increasing to the point that it was complicating working on it. Personally, I also prefer to work on multiple smaller files than in one large file, but I don't know if everybody agrees about that.

Will you summary it in a document, for example, "guidelines for adding new backends"? I see some backends are WIP like https://github.com/ggerganov/llama.cpp/pull/6035 and following new designs might be easier.

**Review by ggerganov — APPROVED** [review]
I like how the files are organized. We should also take the opportunity to deprecate the `LLAMA_CUBLAS` option with the more meaningful `LLAMA_CUDA`. But not super important, and probably better for a follow-up PR

@airMeng Starting with single-file implementations remains the preferred option. We can probably add a dummy backend implementation to serve as a starting point for new backend development - might be easier to keep it up-to-date compared to a document

**Comment by slaren** [comment]
Should be fixed in #6298

**Comment by ikawrakow** [comment]
Considering the extremely long `ggml-cuda.cu` compilation times I was pleasantly surprised by this refactoring. Until I had to adapt PR #6302 to the refactoring: touching `vecdotq.cuh`, which one needs to do all the time when developing new quants or optimizing dot product kernels, leads to the very same extremely long compilation as before (this time of `mmq.cu`).

**Comment by slaren** [comment]
The build time is dominated by `mmvq.cu`, and to a lesser degree by `mmq.cu`, so as you say, this will not help much if you are changing these files. It should be possible to split each quant type to a different file as well to improve this.

**Pull request merged**
