### PR TITLE
Fix metal backend init failure in swiftui example

### PR DESCRIPTION
**Pull request by singularity-s0**
When running the SwiftUI project on iOS (and Apple Silicon macOS), I get the following output when loading model:
```
ggml_metal_init: allocating
ggml_metal_init: picking default device: Apple A17 Pro GPU
ggml_metal_init: ggml.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: error: could not use bundle path to find ggml-metal.metal, falling back to trying cwd
ggml_metal_init: loading 'ggml-metal.metal'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ggml-metal.metal” couldn’t be opened because there is no such file." UserInfo={NSFilePath=ggml-metal.metal, NSUnderlyingError=0x2821e7150 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
llama_new_context_with_model: failed to initialize Metal backend
```
Activity Monitor on Mac confirms that GPU is not being used at all.

This is due to `ggml-metal.metal` not being properly copied into the application bundle. This PR fixes the issue. After applying this PR, metal backend initializes correctly and GPU is utilized.

### CODE REVIEW

**Comment by ggerganov** [comment]
I'm not very familiar with the Xcode builds, but I think what happened here is that originally, the project was loading the metal shaders by loading `default.metallib` which probably was generated by default. Recently I changed `ggml-metal.m` to look for `ggml.metallib` and that is why the project no longer loads the metallib and proceeds to look for the `ggml-metal.metal` source file.

I guess we can merge the PR, but maybe before that we should see if we can somehow fix this so that `ggml-metal.metal` remains a Resource and `ggml.metallib` is generated

For reference, I can generate it from the command-line like this:

```bash
xcrun -sdk macosx metal    -c ggml-metal.metal -o ggml-metal.air
xcrun -sdk macosx metallib    ggml-metal.air   -o ggml.metallib
```

cc @jhen0409

**Comment by jhen0409** [comment]
Yes the project will build `default.metallib` by default, we can also make a custom build in Build Rules of Xcode.

**Comment by singularity-s0** [comment]
I have created a custom build rule to build `ggml-metal.metallib` but I noticed that the code is actually looking for `ggml.metallib`. Is there any reason for the name difference? Should I just rename `ggml-metal.metallib` to `ggml.metallib` or is there any rule for this?

**Comment by singularity-s0** [comment]
I have updated this PR to build `ggml.metallib` instead of copying source file.

**Review by jhen0409 — APPROVED** [review]

**Comment by singularity-s0** [comment]
I’m not too sure about compiler flags though. I found these flags `-fno-fast-math -fno-inline -g` in CMakeLists, but it seems that CMake builds `ggml.metallib` only when `LLAMA_METAL_SHADER_DEBUG` is set. Do we want these compiler flags in release builds?

**Comment by ggerganov** [comment]
The flags are only needed for debug builds running in the CI in order to make the Metal numerical results match the CPU results. In the example, it is better to use the optimized build

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
