### PR TITLE
Fix Docker ROCM builds, use AMDGPU_TARGETS instead of GPU_TARGETS

### PR DESCRIPTION
**Pull request by serhii-nakon**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

Small description: When use GPU_TARGETS it crash like out of memory, but with AMDGPU_TARGETS it properly works. Also in documentations described AMDGPU_TARGETS not GPU_TARGETS

### CODE REVIEW

**Comment by no1wudi** [comment]
https://github.com/ROCm/rocBLAS/blob/4104188d27bf58f8de28be27b0d3fcb5a46e812d/CMakeLists.txt#L139-L146

Seems AMDGPU_TARGETS will be deprecated but not for now.

**Comment by slaren** [comment]
Is this change required? Any comment from people experienced with ROCm would be appreciated. I don't think there are any maintainers working with ROCm at the moment, so we depend on feedback from the community to review these changes.

**Comment by serhii-nakon** [comment]
Also I just noticed that similar issue happened when I try build with multiple gfx IDs in `ROCM_DOCKER_ARCH` like here https://github.com/ggerganov/llama.cpp/pull/9641/files#diff-acc708a34f42e6226b0cf4eecfdb0123ca381b4b51b48106a2e2c3c667b5ec63L14-L24 but if I use `ROCM_DOCKER_ARCH="gfx803 gfx900 gfx906 gfx908 gfx90a gfx1010 gfx1030 gfx1100 gfx1101 gfx1102"` it works fine so I will commit it due it incorrectly works with this even building time increase.

**Comment by serhii-nakon** [comment]
> Is this change required? Any comment from people experienced with ROCm would be appreciated. I don't think there are any maintainers working with ROCm at the moment, so we depend on feedback from the community to review these changes.

Hello I started to use it, and it required due it does not work properly (even prebuilt containers not works properly from here - https://github.com/ggerganov/llama.cpp/blob/master/docs/docker.md) also documentation describe AMDGPU_TARGETS not GPU_TARGETS - see https://github.com/ggerganov/llama.cpp/blob/master/docs/build.md#hipblas

**Comment by serhii-nakon** [comment]
@no1wudi It deprecated to build rocBLAS but in code base of llama.cpp it not used at all (at least I not found it) - so currently docker containers built without any setted gfx ID
@slaren Yes it required to work - I have RX 7900 XTX and it works only with those commits

**Comment by tbocek** [comment]
When I build this project with my 7900XTX, I use:

```
ROCM_PATH=/opt/rocm-6.2.1/ make -j32 GGML_HIPBLAS=1 AMDGPU_TARGETS=gfx1100 GGML_CUDA_FA_ALL_QUANTS=1
```
Not sure, if all the parameters are still needed, but I also use AMDGPU_TARGETS, and it works

**Review by slaren — APPROVED** [review]

**Comment by serhii-nakon** [comment]
Thank you all!

**Pull request merged**
