### PR TITLE
gguf: add script for converting falcon 180B huggingface safetensors model to gguf

### PR DESCRIPTION
**Pull request by logicchains**
It's just a slight modification of convert-falcon-hf-to-gguf.py ; not sure if we want to merge the two into one script somehow to avoid duplication.

### CODE REVIEW

**Comment by Green-Sky** [comment]
@TheBloke please test and verify :)

@logicchains yea, having a separate file is not ideal. imo in an ideal wold we would have 1 `convert.py` and a subfolder with model specific code.

**Comment by akawrykow** [comment]
The delta between this file and `convert-falcon-hf-to-gguf.py` is just a few lines. I would really recommend consolidating into `convert-falcon-hf-to-gguf` (which might be a lot less work than consolidating into `convert.py`). Some of those changes would most likely make future falcon variations work more easily out of the box. 

For example, for these lines
image

you can take a look at https://github.com/ggerganov/llama.cpp/pull/2887/commits/e276e4b6064ba0649aee0b1f5742e25f31e1c7a7 to see how we've tried to consolidate this before:

image

**Comment by ggerganov** [comment]
Thanks for the updated script - it does work. Here is a sample run on M2 Ultra:

https://github.com/ggerganov/llama.cpp/asses/1991296/98abd4e8-7077-464c-ae89-aebabca7757e

I agree with @akawrykow's suggestion to merge this into `convert-falcon-hf-to-gguf.py` instead of having a separate script.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
