### PR TITLE
Convert vector to f16 for dequantize mul mat vec

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Currently dequantize mul mat vec operates on a quantized matrix and an f32 vector. This PR converts the vector to f16 and then converts it back to f32 as it's needed. Because this way each streaming multiprocessor needs to load less data during the calculation this is actually slightly faster:

| GPU      | Test   | Model    | t/s master | t/s PR | Speedup |
|----------|--------|----------|------------|--------|---------|
| RTX 3090 | TG 128 | 7b q4_0  |      83.26 |  90.09 |    1.08 |
| RTX 3090 | TG 128 | 13b q4_0 |      46.08 |  50.56 |    1.10 |
| RTX 3090 | TG 128 | 33b q4_0 |      20.21 |  22.24 |    1.10 |
| GTX 1070 | TG 128 | 7b q4_0  |      15.93 |  16.25 |    1.02 |

I also tried a version in which the vector is instead converted to q8_0 but I was not able to get performance out of this; int <-> float conversion and integer arithmetic may be too slow on GPUs to make this worthwhile. There is also a [version which uses f16 arithmetic](https://github.com/JohannesGaessler/llama.cpp/tree/cuda-dmmv-f16) but that version was only ~3% faster on an RTX 3090 and would require relatively large changes to the code. The performance on my GTX 1070 was also very bad because Pascal seems to have poor f16 performance.

I did not touch any of the k-quants because they use the vector quite differently than the older quantization methods and I wasn't sure what the correct implementation would be.

### CODE REVIEW

**Comment by ikawrakow** [comment]
The change looks good, but in my case the PR leads to a lower performance on my RTX-4080. I get 110 t/s on master (b2416493ab3ab21686d47c96669da6d6c6af08a4) for `Q4_0` at 7B, but 98 t/s on this branch, with and without rebasing on current master. It is late here, so maybe I'm making a stupid mistake. I'll check again tomorrow.

**Review by ikawrakow — CHANGES_REQUESTED** [review]
I checked again and confirmed that the PR leads to a lower token prediction performance on my RTX-4080 GPU. Hence, it would be nice if this could be made optional via a command line or compile time option.

**Comment by JohannesGaessler** [comment]
Already on it, I've already added an option `LLAMA_CUDA_DMMV_F16` to the Makefile and put more effort in the implementation. The new implementation uses f16 intrinsics if the option is enabled and I optimized the data types in the DMMV code in general so it should now be very slightly faster:

| GPU      | Test   | Model    | t/s master | t/s PR | t/s PR LLAMA_CUDA_DMMV_F16=1 | Speedup PR LLAMA_CUDA_DMMV_F16=1 vs. master |
|----------+--------+----------+------------+--------+------------------------------+---------------------------------------------|
| RTX 3090 | TG 128 | 7b q4_0  |      84.60 |  85.18 |                        91.49 |  1.08                                       |
| RTX 3090 | TG 128 | 13b q4_0 |      46.49 |  46.21 |                        51.44 |  1.11                                       |
| RTX 3090 | TG 128 | 33b q4_0 |      20.12 |  20.05 |                        22.64 |  1.13                                       |
| RTX 3090 | TG 128 | 7b q4_1  |      44.68 |  45.31 |                        48.70 |  1.09                                       |
| RTX 3090 | TG 128 | 7b q5_0  |      37.17 |  37.51 |                        35.06 |  0.94                                       |
| RTX 3090 | TG 128 | 7b q5_1  |      36.54 |  36.56 |                        35.10 |  0.96                                       |
| RTX 3090 | TG 128 | 7b q8_0  |      68.02 |  68.11 |                        73.64 |  1.08                                       |
| RTX 3090 | TG 128 | 7b f16   |      51.49 |  51.31 |                        50.48 |  0.98                                       |

I still need to do more testing though.

**Comment by JohannesGaessler** [comment]
Some more testing:

| GPU                    | Test   | Model   | t/s master | t/s PR | t/s PR LLAMA_CUDA_DMMV_F16=1 |
|------------------------|--------|---------|------------|--------|------------------------------|
| GTX 1070               | TG 128 | 7b q4_0 |      16.79 |  17.08 | 2.75                         |
| GTX 1070               | TG 128 | 7b q4_1 |      14.24 |  14.20 | Not tested                   |
| GTX 1070               | TG 128 | 7b q5_0 |       9.56 |   9.57 | Not tested                   |
| GTX 1070               | TG 128 | 7b q5_1 |       9.33 |   9.31 | Not tested                   |
| GTX 1070 + GTX 1050 ti | TG 128 | 7b q4_0 |      19.50 |  19.77 | 3.62                         |
| GTX 1070 + GTX 1050 ti | TG 128 | 7b q4_1 |      17.02 |  17.02 | Not tested                   |
| GTX 1070 + GTX 1050 ti | TG 128 | 7b q5_0 |      12.04 |  12.03 | Not tested                   |
| GTX 1070 + GTX 1050 ti | TG 128 | 7b q5_1 |      11.73 |  11.74 | Not tested                   |
| GTX 1070 + GTX 1050 ti | TG 128 | 7b q8_0 |      14.00 |  14.00 | Not tested                   |

As expected the f16 performance on my Pascal cards is very bad.

**Comment by JohannesGaessler** [comment]
I pushed a compilation option for cmake but there seems to be a problem with the f16 code. With `LLAMA_CUDA_DMMV_F16=ON` the code doesn't compile, apparently because the various half-precision intrinsics aren't found:

<details>

```
/home/johannesg/Projects/llama.cpp/build [git::cuda-dmmv-f16-3 *] [johannesg@johannes-pc] [14:21]
> cmake .. -DLLAMA_CUBLAS=ON -DLLAMA_CUDA_DMMV_F16=ON && cmake --build . --config Release
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.40.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDAToolkit: /opt/cuda/include (found version "12.1.105") 
-- cuBLAS found
-- The CUDA compiler identification is NVIDIA 12.1.105
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- GGML CUDA sources found, configuring CUDA architecture
-- Configuring done (1.9s)
-- Generating done (0.0s)
-- Build files have been written to: /home/johannesg/Projects/llama.cpp/build
[  2%] Generating build details from Git
-- Found Git: /usr/bin/git (found version "2.40.1") 
[  2%] Built target BUILD_INFO
[  5%] Building C object CMakeFiles/ggml.dir/ggml.c.o
[  7%] Building CUDA object CMakeFiles/ggml.dir/ggml-cuda.cu.o
/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(256): error: identifier "__hsub2" is undefined
      v = __hsub2(v, {8.0f, 8.0f});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(257): error: identifier "__hmul2" is undefined
      v = __hmul2(v, {d, d});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(248): warning #177-D: variable "d" was declared but never referenced
      const dfloat d = x[ib].d;
                   ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(276): error: identifier "__hmul2" is undefined
      v = __hmul2(v, {d, d});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(277): error: identifier "__hadd2" is undefined
      v = __hadd2(v, {m, m});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(267): warning #177-D: variable "d" was declared but never referenced
      const dfloat d = x[ib].d;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(268): warning #177-D: variable "m" was declared but never referenced
      const dfloat m = x[ib].m;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(299): error: identifier "__hsub2" is undefined
      v = __hsub2(v, {16.0f, 16.0f});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(300): error: identifier "__hmul2" is undefined
      v = __hmul2(v, {d, d});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(287): warning #177-D: variable "d" was declared but never referenced
      const dfloat d = x[ib].d;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(323): error: identifier "__hmul2" is undefined
      v = __hmul2(v, {d, d});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(324): error: identifier "__hadd2" is undefined
      v = __hadd2(v, {m, m});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(310): warning #177-D: variable "d" was declared but never referenced
      const dfloat d = x[ib].d;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(311): warning #177-D: variable "m" was declared but never referenced
      const dfloat m = x[ib].m;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(340): error: identifier "__hmul2" is undefined
      v = __hmul2(v, {d, d});
          ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(334): warning #177-D: variable "d" was declared but never referenced
      const dfloat d = x[ib].d;
                   ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(949): error: identifier "__hmul2" is undefined
              tmp += __hmul2(v, {
                     ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): warning #349-D: no operator "+=" matches these operands
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(969): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const" (declared at line 217 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator short() const" (declared at line 235 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned short() const" (declared at line 238 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator int() const" (declared at line 241 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned int() const" (declared at line 244 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator long long() const" (declared at line 247 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned long long() const" (declared at line 250 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator __nv_bool() const" (declared at line 254 of /opt/cuda/include/cuda_fp16.hpp)
          dst[row] = tmp.x + tmp.y;
                     ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(969): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const" (declared at line 217 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator short() const" (declared at line 235 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned short() const" (declared at line 238 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator int() const" (declared at line 241 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned int() const" (declared at line 244 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator long long() const" (declared at line 247 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator unsigned long long() const" (declared at line 250 of /opt/cuda/include/cuda_fp16.hpp)
            function "__half::operator __nv_bool() const" (declared at line 254 of /opt/cuda/include/cuda_fp16.hpp)
          dst[row] = tmp.x + tmp.y;
                             ^

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=32, qr=2, dequantize_kernel=&dequantize_q4_0]" at line 1272

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=32, qr=2, dequantize_kernel=&dequantize_q4_1]" at line 1281

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=32, qr=2, dequantize_kernel=&dequantize_q5_0]" at line 1290

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=32, qr=2, dequantize_kernel=&dequantize_q5_1]" at line 1299

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=32, qr=1, dequantize_kernel=&dequantize_q8_0]" at line 1308

/home/johannesg/Projects/llama.cpp/ggml-cuda.cu(964): error: no operator "+=" matches these operands
            operand types are: half2 += __half2
          tmp += __shfl_xor_sync(0xffffffff, tmp, mask, 32);
              ^
          detected during instantiation of "void dequantize_mul_mat_vec<qk,qr,dequantize_kernel>(const void *, const dfloat *, float *, int, int) [with qk=1, qr=1, dequantize_kernel=&convert_f16]" at line 1358

18 errors detected in the compilation of "/home/johannesg/Projects/llama.cpp/ggml-cuda.cu".
make[2]: *** [CMakeFiles/ggml.dir/build.make:91: CMakeFiles/ggml.dir/ggml-cuda.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:398: CMakeFiles/ggml.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

```

</details>

Does someone know what could be going wrong?

**Comment by slaren** [comment]
Looks like these intrinsics are defined on `cuda_fp16.h` guarded by this:
```C++
#if !defined(__CUDA_ARCH__) || (__CUDA_ARCH__ >= 530)
```
It t may be due to the way cmake sets the CUDA arch. I set it to "Auto" so that hopefully it would use "-arch=native" like the Makefile, but it may be doing something completely different. We should probably set the arch targets manually in the cmake build anyway, just so that we can cross-compile to any architecture.

**Comment by JohannesGaessler** [comment]
I asked ChatGPT how to fix it and it tole me to set `CUDA_ARCHITECTURES` to `native` (it was set to `OFF`). With this I can compile the code with `LLAMA_CUDA_DMMV_F16` but I only have very rudimentary cmake knowledge so I don't know if this change has side effects.

**Review by ikawrakow — APPROVED** [review]

**Pull request merged**
