### PR TITLE
Server: fallback to chatml, add AlphaMonarch chat template

### LINKED ISSUE #5627: server: Error\nvector::_M_default_append when using certain models since "llama_chat_apply_template"
### Description
Server returns "500 Internal Server Error\nvector::_M_default_append" when using certain models trying to use model's template with docker cuda image.

### Steps to Reproduce

I'm using openAI in python:

def api_openai(placeholder, system_prompt, user_prompt, temperature, logit_bias):
    full_response = ""
    for response in openai_client.chat.completions.create(
            model=st.session_state["openai_model"],
            messages=[{"role": "system",
                       "content": system_prompt},
                      {"role": "user",
                       "content": user_prompt}],
            stream=True, temperature=temperature, frequency_penalty=1, logit_bias=logit_bias):
        full_response += (response.choices[0].delta.content or "")
        placeholder.info(full_response + "▌")

    return full_response

### Actual Behavior
"500 Internal Server Error\nvector::_M_default_append"

### Screenshots
Untitled

### Environment
- Operating System: Docker
- Docker compose: 
       api-server:
    container_name: api-server
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    command: >
      -m models/alphamonarch-7b.Q5_K_M.gguf
      --ctx-size 8192
      --host 0.0.0.0
      --port 8080
      --n-gpu-layers 1000
      -np 1
      -cb
      --grp-attn-n 4
      --grp-attn-w 2048
      --api-key key
      --verbose
    ports:
      - "8080:8080"
      
- Models that failed: 
- https://huggingface.co/mlabonne/AlphaMonarch-7B-GGUF
- https://huggingface.co/CultriX/OmniBeagle-7B-GGUF

### Additional Information
Models that I've tried that works: 
https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF
https://huggingface.co/brittlewis12/NeuralDaredevil-7B-GGUF

### Related Issues
i used #5593

### Proposed Solution
I think that the problem could be related to the extracted chat_template, in Hugginface are using without problems "tokenizer.apply_chat_template" but i don't know if llama.cpp implementation works like that

### PR DESCRIPTION
**Pull request by ngxson**
Closes #5627

## Fix server crash if the template is not supported

If the template is not supported, we will now see an error in the log. The server will still work, but fallback to chatml template.

```
{"timestamp":1708509262,"level":"INFO","function":"main","line":2723,"message":"model loaded"}
{"timestamp":1708509262,"level":"ERROR","function":"validate_model_chat_template","line":408,"message":"The chat template comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses"}
{"timestamp":1708509262,"level":"VERBOSE","function":"start_loop","line":293,"message":"have new task"}
{"timestamp":1708509262,"level":"VERBOSE","function":"start_loop","line":308,"message":"callback_all_task_finished"}
all slots are idle and system prompt is empty, clear the KV cache
{"timestamp":1708509262,"level":"VERBOSE","function":"start_loop","line":329,"message":"wait for new task"}
{"timestamp":1708509286,"level":"VERBOSE","function":"format_chat","line":208,"message":"formatted_chat","text":"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nhi, how are you<|im_end|>\n<|im_start|>assistant\n"}
```

## Add new template

New template added: https://huggingface.co/mlabonne/AlphaMonarch-7B/blob/main/tokenizer_config.json#L36

The new template is also updated in the research: https://github.com/ggerganov/llama.cpp/issues/5527

Example for the formatted prompt:

`{"timestamp":1708510304,"level":"VERBOSE","function":"format_chat","line":208,"message":"formatted_chat","text":"system\nYou are a helpful assistant.</s>\n<s>user\nhi, how are you</s>\n<s>assistant\n"}`

### CODE REVIEW

**Comment by ngxson** [comment]
@infozzdatalabs Can you please check this out if possible? Thank you!

**Comment by infozzdatalabs** [comment]
I think it's great that it warns in case it doesn't match with any available one, until now it was trial and error without knowing it at all. It would be amazing if I could directly use a template that is not hardcoded, taking it from the model built-in, but this solves many problems already, thanks a lot!

**Review by ggerganov — COMMENTED** [review]
Thank you for looking into this and fixing!

But there 2 things still missing IMO:

- For each new template we must add a test in `tests/test-chat-template.cpp`
- We should not validate the model's template if a custom template is provided

**Comment by infozzdatalabs** [comment]
Thanks to both of you @ngxson @ggerganov for fixing this so fast.
I have not found any information about this, if i want to use a custom template in docker with the --chat-template flag, would i have to provide the path to the jinja file or put it directly as a string? i have tried to put it in string and it did not start the server and threw the wrong argument exception.

**Comment by ngxson** [comment]
@ggerganov Bien vu! I've fix that on the 2 commits above.

For the test, before, I only check if output contains a pre-defined string (I was quite lazy to deal with `\n`). But now it checks if the output is **exactly** equal to what we expect.

@infozzdatalabs Yeah you need to input a string as argument. I suspect that it doesn't work in your case because the template contains special characters that are revered by shell language (brackets `{}` for example). I'll document it better in a future PR.

**Review by ggerganov — APPROVED** [review]
Awesome 🦙

**Pull request merged**
