### PR TITLE
use fprintf for diagnostic output, keep printf only for printing model output

### LINKED ISSUE #5: Suppress output that isn't from the model
I want to integrate this into a slim chat system, so I think it would be nice to be able to have the app output only the text from the model like a -q for "quiet" flag on run.

### PR DESCRIPTION
**Pull request by prusnak**
one can use `./main ... 2>/dev/null` to suppress any diagnostic output

Fixes https://github.com/ggerganov/llama.cpp/issues/5

### CODE REVIEW

**Review by ggerganov — CHANGES_REQUESTED** [review]
No need to modify `ggml.c` and `ggml.h` - it does not print anything.

Keep only the rest of the changes

**Comment by prusnak** [comment]
Rebased on top of current master, kept only changes in main.cpp

**Review by ggerganov — APPROVED** [review]

**Comment by Godwinnna** [comment]
Hello

**Comment by prusnak** [comment]
> What does this mean?

Yes, there was a typo in my original post, it should read /dev/null, I updated the post.

**Comment by linonetwo** [comment]
Thanks, this helps when I write a function to call alpaca.cpp/llama.cpp from JS

https://github.com/linonetwo/langchain-alpaca/blob/1c519c206ea5152269c3d82d160a2567bbc9e69f/src/index.ts#L222-L282

**Pull request merged**
