### PR TITLE
CI maintenance: Update checkout, setup-python and upload-artifact to latest versions

### PR DESCRIPTION
**Pull request by EwoutH**
A bit of CI maintenance, which updates the following actions to their latest versions:
- c1ca357: [actions/checkout](https://github.com/actions/checkout) to v4
- 1d5dc54 [actions/setup-python](https://github.com/actions/setup-python) to v5
- 417be61: [actions/upload-artifact](https://github.com/actions/upload-artifact) to v4

For each, the main change is an update from Node 16 LTS to Node 20 LTS.

If preferred, I can add a Dependabot configuration which opens these PRs automatically in the future (in another PR).

### CODE REVIEW

**Comment by phymbert** [comment]
Thanks, have you tested on your fork that it works ? If yes please send links

**Comment by EwoutH** [comment]
@phymbert here are the runs on my fork: https://github.com/EwoutH/llama.cpp/pull/1

**Comment by EwoutH** [comment]
Right, missed that one, triggered it here: https://github.com/EwoutH/llama.cpp/actions/runs/8539946210

**Comment by EwoutH** [comment]
I understand.

All the runs have passed successfully.

**Review by phymbert — APPROVED** [review]
Thanks for having looking at this, please wait for @ggerganov approval

**Review by ggerganov — APPROVED** [review]

**Comment by EwoutH** [comment]
Thanks for merging!

Would a Dependabot configuration be useful, which opens such PRs automatically in the future?

**Comment by EwoutH** [comment]
Give me a sec, looking into it: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#migration

If I understand correctly it just requires naming artifacts differently.

**Comment by EwoutH** [comment]
Basic there are two options:

1. Keeping the single artifact `artifact`, with all different ZIP files (AvX, AVX2, Arm, etc.) in that single file. This requires adding a merge step at the end of the run.
2. Upload each generated ZIP as it’s own artifact (so we would get `artifact_avx`, [artifact_avx2](url).

What’s preferred?

**Comment by ggerganov** [comment]
I don't have a preference and I'm not sure what is useful for most people. We can do the one artifact per job as suggested and if we see it is not optimal for some reason we can update later

**Comment by phymbert** [comment]
I doubt people are using it. At the moment it is merged:
https://github.com/ggerganov/llama.cpp/actions/runs/8541354320

But IMHO, separating per backend is easier than downloading a 1GB file. As you say, we can improve later on if it hurts for some reason.

**Comment by EwoutH** [comment]
#6482 should solve the artifact naming conflict. It will upload multiple smaller artifacts instead of one big one, which I think is more useful for most users and developers.

**Pull request merged**
