### PR TITLE
PR for testing CI on RISC-V in Cloud-V

### PR DESCRIPTION
**Pull request by alitariq4589**
Will close this PR once everything is sorted out.

### CODE REVIEW

**Comment by ggerganov** [comment]
@alitariq4589 What just happened? My inbox is flooded

image

**Comment by alitariq4589** [comment]
@ggerganov I am very sorry for that. It was generated by the bot because of a permission setting on my side. I have resolved the issue and I am deleting all the comments in all the PRs.

**Comment by alitariq4589** [comment]
@ggerganov Have you enabled PR events in webhook trigger events ? Because I reopened the PR and could not see it trigger the CI.

**Comment by Cebtenzzre** [comment]
@ggerganov Do you know where the 'b1' tagged builds are coming from? I deleted the last one thinking it was a fluke, but it came back again.

**Comment by ggerganov** [comment]
@alitariq4589 I just enabled it. Seems like the CI is now running. Can we change the name from `default` to something more descriptive?

@Cebtenzzre No idea - I also noticed these

**Comment by alitariq4589** [comment]
@ggerganov I have changed the commit context. Now it will named as `Build for QEMU RISC-V Vector Extension`. Meanwhile I have seen that the build has failed. I will look into this now issue now.

**Comment by alitariq4589** [comment]
@ggerganov The build is triggering from forks successfully. Everything is working as expected. Now rest of things are automated for RISC-V builds. Still if you observe an anomaly, feel free to reach me

You can safely close this PR now. Just make sure every PR has `.devops/cloud-v-pipeline` file in it.

**Comment by alitariq4589** [comment]
@ggerganov The build is triggering from forks successfully. Everything is working as expected. Now rest of things are automated for RISC-V builds. Still if you observe an anomaly, feel free to reach me

You can safely close this PR now. Just make sure every PR has `.devops/cloud-v-pipeline` file in it.

**Pull request closed without merging**
