### PR TITLE
Normalize graph of training

### PR DESCRIPTION
**Pull request by howard0su**
Consolidate the duplicate functions into one to have operations:
1) Support batch or single token
2) use flash attention or not
3) use cache or not

Baby step towards adding training APIs to llama.h.

### CODE REVIEW

**Comment by slaren** [comment]
This looks great! Removing 700 lines of duplicated code would be very good.

**Comment by howard0su** [comment]
Need second eyes to check if I do it correctly as this is compute graph change. I am not an expert in AI algorithms. There is potentially more code to be removed.

**Comment by xaedes** [comment]
> There is potentially more code to be removed.

Absolutely! Wanted to leave the code-deduplication refactoring for later, after the most important features and optimizations are implemented.

The llama file loader changes should probably go into a separate pull request as they seem to be unrelated to the training.

I will look into the training related changed of this PR this week.

**Comment by ggerganov** [comment]
@howard0su I think we already merged the model loading changes. Maybe recreate the PR for clarity

**Comment by howard0su** [comment]
Sorry, I messed the commits. regen from latest master.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by xaedes** [comment]
I think this pull request is now obsolete, because all the here refactored functions are already removed in favor of one unified function to build the train graph:
https://github.com/ggerganov/llama.cpp/blob/7e50d34be68aae2cc766203703dd188e910e033a/examples/train-text-from-scratch/train-text-from-scratch.cpp#L645

**Pull request closed without merging**
