### PR TITLE
gguf : add workflow for Pypi publishing

### PR DESCRIPTION
**Pull request by monatis**
This PR add a workflow to make a release on Pypi upon creation of tags in a specified format. It requires a secret defined in the repo --wil email it.

## Steps to make a release
1. Bump the version in `pyproject.toml`.
2. Create a tag named `gguf-vx.x.x` where `x.x.x` is the semantic version number.

```sh
git tag -a gguf-v1.0.0 -m "Version 1.0 release"
```

3. Push the tags.

```sh
git push origin --tags
```

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
Added the secret:

image

**Comment by cebtenzzre** [comment]
Why is this failing? https://github.com/ggerganov/llama.cpp/actions/runs/6384335798/job/17326791835

**Comment by monatis** [comment]
> Poetry could not find a pyproject.toml file in /home/runner/work/llama.cpp/llama.cpp or its parents

Apparently it doesn't run `poetry build` step inside `gguf-py`, and we need to cd into it again I think. will patch it.

**Comment by cebtenzzre** [comment]
> will patch it.

Have you gotten around to this yet? It's no big deal if you haven't, but in that case I'd like to open a new issue so this doesn't get forgotten about.

**Pull request merged**
