### PR TITLE
sync : ggml (SD ops, tests, kernels)

### PR DESCRIPTION
**Pull request by ggerganov**
New ops:

- `ggml_pad`
- `ggml_leaky_relu`

GPU kernels:

- `ggml_upscale`
- `ggml_group_norm`
- `ggml_acc`
- `ggml_pad`
- `ggml_leaky_relu`

Bug fixes in some Metal kernels

Tests, sentinels

### Summary
🧮🧪🐏

This pull request adds new operations and functionality to the llama.cpp library, a low-level machine learning library for C++. It updates the Metal and CPU backends, the `ggml.h` header file, and the `tests/test-backend-ops.cpp` file to support group normalization, upscaling, padding, argsort, and leaky relu operations. It also renames and refactors some existing code for clarity and consistency.

> _We unleash the power of `llama.cpp`_
> _We forge new kernels in the Metal fire_
> _We test the limits of our backend ops_
> _We are the masters of the `ggml` empire_

### Walkthrough
*  Add new operations to the Metal backend and update the kernel declarations, names, pointers, and cases for them ([link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL69-R73),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR91),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL148-R155),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL337-R347),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR365),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL418-R431),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL453-R469),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR487),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL534-R553),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL846-R868),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL856-R880),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL868-R896),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL905-R931),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL982-R1010),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR1107-R1108),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL1137-R1168),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR1180-R1259),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdL1172-R1291),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR1314-R1335),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR1972-R2003),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR2173-R2231),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-d189c5117255f368aa89f521bd523afa399ada0bbfb7043b74c65bf4ac2472fdR2253-R2268),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8R82),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L93-R96),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L207-R208),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L216-R217),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L225-R226),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8R247-R287),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L254-L260),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L316-L331),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8R672-R759),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8R1766-R1856),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8R1909-R1916),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L2069-R2277),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-02cf716fa6ab890726f8280ece35eae9dd87b20bb3e067e2dee45209b96313e8L2108-R2314))
*  Add new operations to the `ggml_op` enum and remove the `GGML_UNARY_OP_LEAKY` value from the `ggml_unary_op` enum ([link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394L426-R428),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394L466))
*  Rename the `ggml_leaky` function to `ggml_leaky_relu` and add a comment for the `ggml_acc` function in `ggml.h` ([link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394R797-R799),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394L960-R966),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394L968))
*  Implement the new operations on the CPU backend and update the existing operations to match the changes in the enums and the function names ([link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1398-R1398),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1626-R1628),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1653-R1655),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1710-R1714),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1737-R1741),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL1753-R1759),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL3833-R3854),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL4025-R4043),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR5543-R5566),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL7721-R7765),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL8988-R9033),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL9005-R9060),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL9022-R9067),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR12206),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL12168-R12225),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR12249-R12306),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL13409-L13412),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL14194-R14306),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL15190-R15310),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR15916),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL15811),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR16047-R16050))
*  Add new test case classes and objects for the new operations and modify the `test_case` struct to support different modes of testing and sentinel tensors in `tests/test-backend-ops.cpp` ([link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578R237-R241),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578L271-R327),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578R335-R339),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578L299-R373),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578L321-R406),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578R461-R462),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578R1223-R1334),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578L1222-L1226),[link](https://github.com/ggerganov/llama.cpp/pull/4444/files?diff=unified&w=0#diff-2749fdb8974ec96afa18444a9d546409318b0a862709139b677eee468c479578L1375-R1572))

### CODE REVIEW

**Comment by FSSRepo** [comment]
Why revert the changes to im2col if the previous version was twice as slow?

**Comment by ggerganov** [comment]
I think #4406 broke the LoRA test in the CI with CUDA:

```
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 1024.00 MB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 159.32 MiB
llama_new_context_with_model: VRAM scratch buffer: 156.00 MiB
llama_new_context_with_model: total VRAM used: 13783.02 MiB (model: 12603.02 MiB, context: 1180.00 MiB)
llama_apply_lora_from_file_internal: applying lora adapter from '../models-mnt/open-llama/7B-v2/lora/ggml-adapter-model.bin' - please wait ...
llama_apply_lora_from_file_internal: r = 64, alpha = 128, scaling = 2.00
GGML_ASSERT: /home/ggml/work/llama.cpp/ggml-cuda.cu:5419: s0 == 1
ci/run.sh: line 444: 2821952 Aborted                 (core dumped) ./bin/perplexity --model ${model_f16} -f ${shakespeare} --lora ${lora_shakespeare} -t 1 -ngl 999 -c 2048 -b 512 --chunks 3

```

https://github.com/ggml-org/ci/blob/results/llama.cpp/16/09a94ae5200f206b2d51aeba0d60e85ee4be05/ggml-4-x86-cuda-v100/stdall

**Comment by LostRuins** [comment]
After merging this, I am getting an assert with CL

This is with airoboros-mistral2.2-7b.Q4_K_S.gguf but seems to affect other models too.
```
llama_new_context_with_model: KV self size  =  266.00 MiB, K (f16):  133.00 MiB, V (f16):  133.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 164.47 MiB
GGML_ASSERT: ggml.c:7765: ggml_are_same_shape(src0, src1)
GGML_ASSERT: ggml.c:7765: ggml_are_same_shape(src0, src1)
GGML_ASSERT: ggml.c:7765: ggml_are_same_shape(src0, src1)
GGML_ASSERT: ggml.c:7765: ggml_are_same_shape(src0, src1)
GGML_ASSERT: ggml.c:7765: ggml_are_same_shape(src0, src1)
```

**Comment by ggerganov** [comment]
See if this helps: https://github.com/ggerganov/llama.cpp/issues/4453#issuecomment-1855361415

**Pull request merged**
