### PR TITLE
common : Update stb_image.h to latest version

### LINKED ISSUE #7431: Potential string overflow in stbi_parse_png_file function
There's a warning in the `stbi__parse_png_file` function while compiling `clip.cpp` in `examples/llava/clip.cpp`.

Here is the output:

```
In file included from examples/llava/clip.cpp:20:
common/stb_image.h: In function ‘int stbi__parse_png_file(stbi__png*, int, int)’:
common/stb_image.h:5450:31: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 5450 |                         tc[k] = (stbi_uc)(stbi__get16be(s) & 255) *
      |                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5451 |                                 stbi__depth_scale_table[z->depth]; // non 8-bit images will be larger
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/stb_image.h:5326:28: note: at offset 3 into destination object ‘tc’ of size 3
 5326 |     stbi_uc has_trans = 0, tc[3] = {0};
      |                            ^~

```

I think it's related to this issue in the original project for `stb_image.h`: https://github.com/nothings/stb/issues/1642.

So there might not be anything we can do about it, but I figured I'd report the issue.

### PR DESCRIPTION
**Pull request by arch-btw**
Fixes https://github.com/ggerganov/llama.cpp/issues/7431

See this issue in the original repo for more details: https://github.com/nothings/stb/issues/1642#issuecomment-2142715877

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by ggerganov** [comment]
There seems to be some formatting applied to the `stb_image.h` in this PR. It's better to use the original header from upstream without changes

**Comment by arch-btw** [comment]
Oh yes, I see what you mean!
Is it possible by any chance that the original PR had custom formatting? 

I'm just wondering because I checked every commit in the [upstream repo ](https://github.com/nothings/stb/blob/master/stb_image.h)starting at 2.28 (and the few commits leading up to it) and non of them match the file that we currently have in llama.cpp.

Then I verified the dev branch of upstream, but it doesn't match our current file either.

I also checked the shasum on this pull request and it matched the latest shasum of upstream:
```594c2fe35d49488b4382dbfaec8f98366defca819d916ac95becf3e75f4200b3```

Here are the steps that I took for this pull request:

1. Fork llama.cpp without making changes
2. Download ```stb_image.h``` from [upstream](https://github.com/nothings/stb/blob/master/stb_image.h)
3. Delete ```stb_image.h``` from fork
4. Add ```stb_image.h``` to my fork without making any changes
5. Submit merge request

Feel free to let me know if I'm misunderstanding or how to proceed :)
Thank you!

**Review by ggerganov — APPROVED** [review]
> Is it possible by any chance that the original PR had custom formatting?

Ah, you are right. I got confused.

**Comment by ggerganov** [comment]
Need to exclude `stb_image.h` from the editor config CI before merging

**Pull request merged**
