### PR TITLE
parallelize the quantization process

### PR DESCRIPTION
**Pull request by tristan0x**
This change uses the Python `multiprocessing` module to parallelize in the script `quantize.py` the multiple calls to the `quantize` native executable.

### CODE REVIEW

**Review by anzz1 — CHANGES_REQUESTED** [review]
Looks great ! :+1:

However, I have some suggestions:
- [ ] change the arg name from '-c' '--cores' to '-t' '--threads' since that's the common nomenclature.
- [ ] instead of replacing the current run function with the multiprocessing pool, wrap it in an if condition so that `if cores > 1` it creates the pool and runs the threading code, else run the old single-threaded code
- applying the `if cores > 1` also takes care of clamping the value so that values like --threads 0 or --threads -1 will get clamped to 1

**Comment by tristan0x** [comment]
> Looks great ! 👍
> 
> However, I have some suggestions:
> 
> * [ ]  change the arg name from '-c' '--cores' to '-t' '--threads' since that's the common nomenclature.
> * [ ]  instead of replacing the current run function with the multiprocessing pool, wrap it in an if condition so that `if cores > 1` it creates the pool and runs the threading code, else run the old single-threaded code
> * applying the `if cores > 1` also takes care of clamping the value so that values like --threads 0 or --threads -1 will get clamped to 1

Thank you for the suggestions @anzz1 
I applied them in [4501720](https://github.com/ggerganov/llama.cpp/pull/581/commits/4501720ffe5ebb8c6ec3ce621c7cc653e5659c3d). I used a custom context manager to wrap the multiprocessing logic. Hope this is fine with you.

**Review by anzz1 — APPROVED** [review]
Fantastic :+1:

**Comment by ggerganov** [comment]
With the latest conversion scripts we now have single-file models so no need for parallel quantization (#613)

**Pull request closed without merging**
