### PR TITLE
Vulkan Mixture of Experts (MoE) support

### PR DESCRIPTION
**Pull request by 0cc4m**
Here's a basic version that can run MoE models. There's some bottleneck in the matrix vector MUL_MAT_ID shaders (or another MoE-specific one) so that generation is rather slow, but at least it runs now.

I had to implement MUL_MAT_ID, SUM_ROWS and DIV for MoE to work. MUL_MAT_ID was the complicated one, obviously.

### CODE REVIEW

**Comment by lin72h** [comment]
Thanks for improving the Vulkan backend. Cross-platform support is very important to make LLM available for everyone.

**Comment by MaggotHATE** [comment]
Compilation fails due to `uint`, replacing with `unsigned int` works. Using w64devkit, Windows 10, but maybe it's because of C++20.

As for performance, it is noticeably slow: the more layers I offload, the slower tg and pp are. However, it finally works, thank you!

Due to how MoE work, I had to download 2x7B in Q3_K_S to test this PR, and suddenly there's no difference in RAM consumption between CPU-only and Vulkan. Another 2x7B model in Q4_K_S still uses more RAM on Vulkan (too much for my system).

I don't normally use Q3_K_S, so I tried three other, non-MoE, models in the same Q3_K_S, and it didn't seem to help - there's still a difference in RAM consumption. Seems like the combination of 2x7b with Q3_K_S works without memory overhead, both with 4096 and 8192 context sizes.

**Comment by 0cc4m** [comment]
Thank you for testing it. The occasions of `uint` were unintentional, I'll correct those. The bad generation performance is because the matrix matrix multiplication shader is being used for matrix vector multiplications. I'll look into that.

**Comment by slaren** [comment]
I get this error with `-sm none -mg 1` to use only the second GPU:

```
ggml_vulkan: Found 2 Vulkan devices:
Vulkan0: NVIDIA GeForce RTX 3080 | uma: 0 | fp16: 1 | warp size: 32
Vulkan1: NVIDIA GeForce RTX 3090 Ti | uma: 0 | fp16: 1 | warp size: 32
ggml_backend_sched_backend_from_buffer: error: no backend supports buffer type Vulkan1 used in tensor blk.0.attn_q.weight
GGML_ASSERT: C:\CODE\llama.cpp\ggml-backend.c:1115: false
```

**Comment by slaren** [comment]
The `offload_op` needs to handle `MUL_MAT_ID` separately since the batch size is in a different dimension. This is the cuda impl:
https://github.com/ggerganov/llama.cpp/blob/750f60c03e4d3f53fa51910551ce87a3d508d2d7/ggml-cuda.cu#L2924-L2931

**Comment by 0cc4m** [comment]
@slaren Thank you, I fixed the offload_op code and fixed the split mode none + main gpu case for Vulkan.

**Comment by MaggotHATE** [comment]
Thanks for the update - inference speed is quite good now! However, prompt processing is still slow, and I noticed that adding more threads (for example, from 3 to 6) boosts performance greatly. At the same time, I'm using OpenMP PR too, so maybe it affects the result.

Memory is fixed for MoEs now - 2x7B in Q4_K_S uses the same amount of RAM in CPU-only and Vulkan. For non-MoE models the RAM difference is still there.

**Review by slaren — APPROVED** [review]

**Pull request merged**
