### PR TITLE
Round away from zero instead of towards nearest whole integer for quantization

### PR DESCRIPTION
**Pull request by kalomaze**
@ikawrakow I was inspired by your recent quantization work to look into something of potential interest: the rounding method used during quantization.

It occurred to me that rounding values to absolute zero (the typical Bankers rounding, where 0.5 gets rounded up to 1.0, and below 0.5 is rounded down to zero) is probably suboptimal for lower bit quants.

image

After making this chart, I realized, maybe multiplying a large value by absolute zero is very different (mathematically speaking) from multiplying a large value by near zero or a small negative value; the butterfly effect of having a value that was originally a small weight completely canceled out instead of just being a small positive or negative weight could be a lot more drastic than expected.

E.g., 12,000 x 0.05 = 600, not 0, and 12,000 x -0.05 = -600.

In addition to this, rounding away in the current implementation should in theory result in negative values having slightly more weight than positive ones, even if they are equivalent outside of the sign, which could also be a problem for lower bit rates. For example:

Number | Nearest Whole Integer | Away from Zero
--- | --- | ---
2.5 | 3 | 3
-2.5 | -2 | -3
0.25 | 0 | 1
-0.25 | 0 | -1

It would seem that, if my implementation of rounding away from zero was done properly (not entirely sure about this, please scrutinize!), my intuition was correct.

Top 3 tokens for the next token in the Navy Seal Copypasta after "I am trained in", fp16 Mistral 7b
```
Token 1: 98.245804%
Token 2: 0.377182%
Token 3: 0.122453%
```

Top 3 tokens for q4_0, with the round away from zero change:
```
Token 1: 99.239830%
Token 2: 0.411957%
Token 3: 0.141261%
```

q4_0 without the change:
```
Token 1: 97.540352%
Token 2: 0.531796%
Token 3: 0.086804%
```

The top token is the **only** valid outcome in the tested scenario (a base model being able to complete a known, infamous piece of internet text).

This is not a good substitute for perplexity (or KL divergence) evaluation over a bigger set of text, & the sample set of one token is obviously not enough. The logic here could also be completely wrong and this is coincidental. I wanted to put up a PR since I know very little about quantization logic in the first place and would like feedback, as my other attempts resulted in garbled text generations before this, and it being coherent isn't necessarily proof of it working as intended.

The PR currently modifies the reference implementation for q4_0, which is of course, not ready to merge.

If anyone would like to subjectively test this modified rounding technique, they will need to quantize via q4_0.

### CODE REVIEW

**Comment by ikawrakow** [comment]
Making this change gives `PPL = 7.9294` for LLaMA-v1-7B ? (without the change we have `PPL = 6.1161`).

**Comment by kalomaze** [comment]
> Making this change gives `PPL = 7.9294` for LLaMA-v1-7B ? (without the change we have `PPL = 6.1161`).

Yeah, it was definitely wrong. I pushed a potential (?) fix just now

**Comment by ikawrakow** [comment]
Now PPL looks fine, but is the improvement in top-token probability still there?

**Comment by kalomaze** [comment]
> Now PPL looks fine, but is the improvement in top-token probability still there?

It looks equivalent. I think the conversion from signed to unsigned is inherently nullifying any effect this could cause.

**Comment by kalomaze** [comment]
image

Right now, I'm experimenting with whether or not custom dequantization logic (not custom logic for quantization specifically, this would be done at inference time) to add "noise" might actually be beneficial, somewhat motivated conceptually by things like dithering in image/audio compression.

image

I am not at all confident what I'm experimenting with will be practical or usable, but it seems quite interesting to me nonetheless.

**Comment by kalomaze** [comment]
This experiment hasn't worked well with batching in my experience. Closing unless I get interested in revisiting the concept.

**Pull request closed without merging**
