### PR TITLE
Gguf: write tensors in a single pass

### PR DESCRIPTION
**Pull request by monatis**
Refactored the conversion script for single-pass tensor writing but not tested yet

### CODE REVIEW

**Comment by monatis** [comment]
Oh just seen you picked it :D

**Comment by ggerganov** [comment]
Looks OK, but I really wish we keep the indentation as it is in the `gguf` branch - it's much easier for me to read it when it's aligned vertically

**Comment by monatis** [comment]
Fixed conflicts and (hopefully) alignment :)

**Comment by klosax** [comment]
Are you updating the gptneox conversion script in this PR?

**Comment by monatis** [comment]
Yes, but I think we can remove `convert-llama-7b-pth-to-gguf.py` because these are meant to serve as simple examples, and conversion from pth is handled by `convert.py` now.

**Comment by klosax** [comment]
Yes but the pth conversion script have support for the token types and special tokens.

**Comment by klosax** [comment]
The gptneox conversion script and example should be implemented in the ggml examples instead until alt arch support is added to llama.cpp

**Comment by klosax** [comment]
The file type key should be removed.

**Comment by monatis** [comment]
Ok, updated all three scripts.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
