### PR TITLE
Use mmap in torch load

### PR DESCRIPTION
**Pull request by Galunid**
It was discussed in #4173. I switched from using `safetensors` as default format to `.bin`, since it allows us to save ram when converting.

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
> I switched from using `safetensors` as default format to `.bin`, since it allows us to save ram when converting.

Hmm, did you actually measure that? (I'm not sure if it seemed like I was implying the default preference should change in my other comments? I just meant when loading Torch files that using `mmap` would be good.)

As far as I know, `safetensors` `mmap`s by default, and the format was in fact designed so the data was aligned and stuff for `mmap`ing purposes. So I wouldn't think there should be a memory advantage to preferring Torch format files.

**Comment by Galunid** [comment]
>As far as I know, safetensors mmaps by default, and the format was in fact designed so the data was aligned and stuff for mmaping purposes

You learn new stuff every day. I couldn't find any documentation on this, so I assumed it doesn't `mmap`. I'll revert that change

**Comment by KerfuffleV2** [comment]
> You learn new stuff every day. I couldn't find any documentation on this

I didn't actually test it so I can't say anything about the real world memory usage, I just know it's a consideration that went into designing the format. Personally, I'd prefer to avoid Torch files whenever possible just because Pickle is such an absurd format.

**Review by KerfuffleV2 — APPROVED** [review]
You might possibly want to get a second opinion on the `mmap` thing. I know I suggested it, and I tested it, seemed to work fine, etc. _I_ don't know of a reason _not_ to do that but maybe someone else can come up with one.

If there aren't any issues with doing it then I think it's a good change because it speeds up loading. I think the `weights_only` thing is completely uncontroversial though because it makes llama.cpp's tools less likely to become a vector for malicious code in Pickle files.

**Comment by Galunid** [comment]
I was investigating this yesterday and I didn't find anything that could cause trouble. I'll leave this open for the next ~24h to see if anyone else has comments. If not I'll merge.

**Comment by slaren** [comment]
I guess this requires pytorch 2.1, because it didn't for me until I updated from 2.0. I would be nice to have a `requirements.txt` for `convert-hf-to-gguf.py`.

**Pull request merged**
