### PR TITLE
infill mode for main and server

### PR DESCRIPTION
**Pull request by vvhg1**
This adds support for the infill tasks in ./main and ./server.
There are still a few things that should be improved, but it works as is.
TODO:
- update Main Readme
- if context is too big in infill mode, we probably want to cut from both sides, need to make sure that neither prefix nor suffix get cut completely
- entering new prompts in ./main is working but a bit awkward, user should be guided a bit more and prompting layout/feedback should be improved

PS hope it helps, thanks for the great work!!

### CODE REVIEW

**Comment by ggerganov** [comment]
Should we make a separate `infill` example instead of adding to `main`?

**Comment by vvhg1** [comment]
> Should we make a separate `infill` example instead of adding to `main`?

It shares a lot with main but it might well make sense to not clutter the functionality of main too much.
I can have a look over the weekend. Shall I split the server infill part into a separate pr or do you want to keep both in the same pr?

**Comment by ggerganov** [comment]
I think a separate minimal `infill` example would be better.
The server changes can remain as they are.

**Comment by ggerganov** [comment]
I think they are very similar, but AFAIK #2934 does not work yet for some reason and I haven't had the time to check why. If we can make a similar example in this PR that works, then we can close #2934 and keep just the current one

**Comment by vvhg1** [comment]
> I think they are very similar, but AFAIK #2934 does not work yet for some reason and I haven't had the time to check why. If we can make a similar example in this PR that works, then we can close #2934 and keep just the current one

 So more or less taking over the structure of #2934 and fill it with this example? Sounds good. What about the --interactive flag, is that valuable or do you just want the bare minimum? As it's already working with --interactive it shouldn't be any extra work to keep it.

**Comment by vvhg1** [comment]
Ok, I'm done, no more changes in main.cpp, all moved to infill.cpp and added readme.
The conflict is easily resolved but for some reason I can't resolve it here, so I'd like to kindly ask you to do it on your end when merging.
Happy to work on it if you have further suggestions!

**Comment by Cebtenzzre** [comment]
I tried to merge master into this PR, but your branch is protected so it won't let me:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:vvhg1/llama.cpp.git
 ! [remote rejected]   pr-3296 -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:vvhg1/llama.cpp.git'
```

**Comment by vvhg1** [comment]
could you try again, I unprotected my master

**Comment by vvhg1** [comment]
Done, should all be working now.

**Review by ggerganov — APPROVED** [review]

**Comment by amanda-peng** [comment]
Hi, is there any plan to implement non-stream model for infill in server side?

**Comment by ggerganov** [comment]
> Hi, is there any plan to implement non-stream mode for infill in server side?

Contributions are welcome

**Pull request merged**
