### PR TITLE
server: metrics: fix bucket reset on /health, add few more metrics

### LINKED ISSUE #5850: server: metrics endpoint
#### Issues

- Server `/metrics` endpoint share the same task event as `/health`: `TASK_TYPE_METRICS`. It means metrics are reset on both calls.
- the `Process-Start-Time-Unix` http response header is not set.
- metrics `llamacpp:prompt_tokens_seconds`  and `llamacpp:predicted_tokens_seconds` are per slots, while the server actually process llamacpp:prompt_tokens_seconds * n_slots

#### Proposal
- Add a data params in TASK_TYPE_METRICS to reset the metric bucket only in /metrics
- Add `llamacpp:prompt_tokens_seconds_total`  and `llamacpp:predicted_tokens_seconds_total`

### PR DESCRIPTION
**Pull request by phymbert**
### Context
Server `/metrics` endpoint share the same task event as `/health`: `TASK_TYPE_METRICS`. It means metrics are reset on both calls.

The `Process-Start-Time-Unix` http response header is not set.

Add total prompt and generation time in order to get the global server throughput for all slots.

Closes #5850

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by stduhpf** [comment]
The server executable won't even launch for me from the merge commit of this PR onwards... (windows 10, MSVC build, any backend)

**Comment by phymbert** [comment]
I doubt there is anything related. This PR is about metrics only. or maybe `ggml_time()` ? what is the error ?

**Comment by stduhpf** [comment]
I will try again tomorrow, but the program dies before printing anything to the standard output. No error message either.

**Comment by stduhpf** [comment]
It got fixed by #5964, thank you @ggerganov

**Pull request merged**
