### PR TITLE
[main] fix infinite generation (-n == -1)

### PR DESCRIPTION
**Pull request by anzz1**
Fixes the command line option `-n` / `--n_predict` value `-1` (generate indefinitely) in interactive mode.

### CODE REVIEW

**Comment by Green-Sky** [comment]
just wanted to test it and just throw a large file at it:
`main: error: prompt is too long (335687 tokens, max 2044)`

... i suppose thats ok, gotta pipe it to stdin then

**Review by Green-Sky — APPROVED** [review]
I let it dream, but it ended itself after 516 tokens. I think it works.

**Comment by anzz1** [comment]
> I let it dream, but it ended itself after 516 tokens. I think it works.

if you want to continue even when it think it should stop, u also need the '--ignore-eos' option to force it continue indefinitely. this is just a fix for https://github.com/ggerganov/llama.cpp/commit/79b2b266db6b198b5af450982c3cd61120fac951 and n==-1 makes it not stop when running out of tokens. end of stream is different thing. with `-n -1 --ignore-eos` it should continue forever unless something goes wrong.

**Comment by rabidcopy** [comment]
> I let it dream, but it ended itself after 516 tokens. I think it works.

Did you do this with interactive or a reverse prompt? Currently EOS is only ignored with --ignore-eos or by being in interactive mode without a reverse prompt. (EOS is still technically ignored with a reverse prompt but it'll hand back the reverse prompt and give control on EOS) Otherwise just passing a prompt will still hit EOS and break.

**Comment by Green-Sky** [comment]
hehe, i know guys. I just forgot to enable it. :smile:

**Pull request merged**
