### PR TITLE
server : replace behave with pytest

### PR DESCRIPTION
**Pull request by ngxson**
## Motivation

We already have a test script for server using [behave](https://github.com/behave/behave) framework. While it works well for common use cases, there are some problems:
- It introduces many boilerplate code. For example, any actions or definitions must be defined in 2 places, one in `steps.py` and one in `*.feature` file
- It's complicated to implement typing
- Poor auto-completion (i.e. copilot can't help in most cases)

## Proposed solution

My proposed solution is to switch to `pytest`, which is a more "mainstream" framework. This helps reduce the complexity for future contributors, since `pytest` is quite straight-forward to use. Indeed, many parts of this PR is written by vscode github copilot.

TODO:
- [x] Migrate all sequential tests
- [x] Migrate "parallel" tests (i.e. multiple completions)
- [x] Remove `*.feature` files

Test cases to be added in the future:
- test KV cache reuse: test with and w/o `cache_prompt` and different values of `n_cache_reuse`
- test with incorrect input for various endpoints (embd, completions, rerank, etc). example for incorrect cases are: empty string, null, incorrect type, etc
- loading split model
- speculative, related to https://github.com/ggerganov/llama.cpp/pull/10455

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Medium

### CODE REVIEW

**Comment by ngxson** [comment]
@ggerganov I'm glad to say that (more than) half of the code in this PR is written by copilot. This will be very useful in the future, where contributors only need to write the docs and the AI will write all test cases.

**Comment by ngxson** [comment]
@ggerganov Sorry for pinging, but can you review this PR soon? I planned to add more test cases in near future (updated in the description)

**Comment by ggerganov** [comment]
I've missed this PR somehow - sorry for the delay and don't hesitate to ping me. Will take a look now.

**Review by ggerganov — APPROVED** [review]

**Comment by ngxson** [comment]
Seems like `test_consistent_result_same_seed` fails with the latest master branch. The test run 4 completions with the same seed=42 and temperature=1.0. However, I can't reproduce the error on my Mac M3. I'm spinning up a linux VM to have a look.

@ggerganov Do you have any clue why it fails?

**Comment by ggerganov** [comment]
Likely #10501 is the reason. We should add the `cache_prompt: false` to the test and see if it fixes.

**Comment by ngxson** [comment]
Thanks, that fixes the issue.

I added a test case for cached vs non-cached, but is marked as `skip` for now (will need to be fixed in the future). The whole test case was written by copilot:

Screenshot 2024-11-26 at 16 02 31

**Comment by slaren** [comment]
This may be causing intermittent CI failures:
```
Traceback (most recent call last):
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00007fc352376358)
```
https://github.com/ggerganov/llama.cpp/actions/runs/12069327600/job/33656351121

From what I could gather, this may be caused by the logging threads not being finished before exiting.

**Comment by ngxson** [comment]
Thanks for reporting. Yeah, indeed the `deamon=True` thread fails to exit. Fixing it in another PR

**Pull request merged**
