### PR TITLE
Restore intended k-quants quantization mixes for MoE models

### PR DESCRIPTION
**Pull request by ikawrakow**
k-quants, and in particular the `_M` variants, use more bits for some of the tensors, with `ffn_down` being the most important. The existing implementation of this intended behavior fails for MoE models such as Mistral-8x7B, resulting in `QX_K_M` being mostly equivalent to `QX_K_S`. This PR restores the intended behavior.

The effect of this change is that `Q2_K` becomes again a mostly 3-bit quantization as per the intent of PR #2707. Given the interest in low-bit quantized models, this PR adds a new `llama.cpp` quantization type `Q2_K_S`. This quantization mix uses 2-bit quants for all tensors except `output.weight` and the first 1/8 of `ffn_down`.

The table shows a comparison between model sizes and perplexities for Mixtral-8x7B and a select set of quants where the change matters most. Perplexity values are for a context size of 512 tokens.

|   | Q2_K (Master) | Q2_K_S (PR) | Q2_K (PR) | Q3_K_M (Master) | Q3_K_M (PR) |
|--:|--:|--:|--:|--:|--:|
| Model size (GiB) | 14.57 | 14.93 | 15.99 | 18.96 | 20.93 |
|Perplexity  | 7.4660 | 5.5500 | 5.0608 | 4.4194 | 4.3413 |

### CODE REVIEW

**Comment by ikawrakow** [comment]
So, I wrote above that I'm showing results for quants where the change matters most, but it does matter quite a bit for 4-bit k-quants as well as demonstrated by the table. The values in the "Quantization Error" column are defined as `PPL(Q)/PPL(Q8_0) - 1`

|  Quantization | File size (GiB) | PPL | Quantization Error |
|--:|--:|--:|--:|
| Q4_K_S(Master) | 24.62 | 4.2523 | 3.59% |
| Q4_K_M(Master) | same | same | same |
|Q4_K_S(PR) | 24.84 | 4.1987 | 2.29% |
|Q4_K_M(PR) | 26.43 | 4.1832 | 1.91% |

**Comment by kalomaze** [comment]
> So, I wrote above that I'm showing results for quants where the change matters most, but it does matter quite a bit for 4-bit k-quants as well as demonstrated by the table. The values in the "Quantization Error" column are defined as `PPL(Q)/PPL(Q8_0) - 1`
> 
> Quantization	File size (GiB)	PPL	Quantization Error
> Q4_K_S(Master)	24.62	4.2523	3.59%
> Q4_K_M(Master)	same	same	same
> Q4_K_S(PR)	24.84	4.1987	2.29%
> Q4_K_M(PR)	26.43	4.1832	1.91%

What's the fp16 (or q8_0 as a substitute) PPL?

**Review by ggerganov — APPROVED** [review]

**Comment by shinomakoi** [comment]
Q4_K_M quants on MOE models seem broken since this commit. They mostly just produce symbols although weirdly perplexity is fine. I tried quantizing the same model to Q4_K_M on previous commit and it's fine.

Example response:

```
### Instruction: 
what are cats?

### Response: 
C☻♣☼☻♠♀☼♣

☺       ♀♫
▅☺♣☻☻►►♦☺
♫
```

**Comment by ikawrakow** [comment]
> Q4_K_M quants on MOE models seem broken since this commit. They mostly just produce symbols although weirdly perplexity is fine. Q4_K_S quants are fine. I tried quantizing the same model to Q4_K_M on previous commit and it's fine.

Thanks for noticing! This is now fixed via PR #4927

**Pull request merged**
