### PR TITLE
convert : fix tensors using grad in some models

### LINKED ISSUE #4171: Converting a StableLM fine tuned model fails with `Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`
# Prerequisites

Tested on latest commit, 8e672efe632bb6a7333964a255c4b96f018b9a65 , and also on commits from yesterday.

# Current Behavior

Trying to convert model https://huggingface.co/pansophic/rocket-3B

Results in:
```
 [pytorch2] tomj@MC:/workspace/git/gguf-llama (master ✘)✭ ᐅ python3 ./convert-hf-to-gguf.py /workspace/process/pansophic_rocket-3b/source --outtype f16 --outfile /workspace/process/pansophic_rocket-3b/gguf/rocket-3b.fp16.gguf
Loading model: source
gguf: This GGUF file is for Little Endian only
Set model parameters
Set model tokenizer
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
gguf: Adding 50009 merge(s).
gguf: Setting special token type bos to 0
gguf: Setting special token type eos to 0
gguf: Setting special token type unk to 0
Exporting model to '/workspace/process/pansophic_rocket-3b/gguf/rocket-3b.fp16.gguf'
gguf: loading model part 'pytorch_model.bin'
Traceback (most recent call last):
  File "/workspace/git/gguf-llama/./convert-hf-to-gguf.py", line 897, in <module>
    model_instance.write()
  File "/workspace/git/gguf-llama/./convert-hf-to-gguf.py", line 126, in write
    self.write_tensors()
  File "/workspace/git/gguf-llama/./convert-hf-to-gguf.py", line 98, in write_tensors
    data = data_torch.squeeze().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

I noticed that the latest commits mentioned StaleLM so I tried rolling back to before them, but still got the same error.

I have confirmed that the model loads OK via Transformers, so it appears to be valid.

Any thoughts @Galunid ?

Thanks in advance

# Environment and Context

Ubuntu 22.04, Python 3.10

### PR DESCRIPTION
**Pull request by Galunid**
fixes #4171, in theory it should also reduce memory usage

### CODE REVIEW

**Comment by cebtenzzre** [comment]
What if we just wrapped `model_class = Model.from_model_architecture...` and everything after it in `with torch.inference_mode():`?

**Comment by Galunid** [comment]
That should work too. I'll try this tomorrow.

**Comment by KerfuffleV2** [comment]
On the subject of reducing memory usage, is there any reason not to torch load with `mmap=True`? Like here: https://github.com/KerfuffleV2/gguf-tools/blob/694391509fda5fbb5b0df8ab5e523219a1571387/gguf-tensor-to-image.py#L171

I assume it's a read only view but the documentation isn't specific. If it can be safely used, it's much, much faster than loading the normal way.

**Comment by cebtenzzre** [comment]
> I assume it's a read only view but the documentation isn't specific. If it can be safely used, it's much, much faster than loading the normal way.

Under the hood it calls 'torch.UntypedStorage.from_file' with shared=False which means "changes on the storage do not affect the file". This would be much more convenient than the way LazyStorage is currently implemented, and it works with files saved with pytorch 1.6 and newer.

**Review by KerfuffleV2 — APPROVED** [review]
I tested with the Rocket 3B model, this seems to work fine.

By the way, I also gave the Torch load changes I mentioned a try:

```python
ctx = contextlib.nullcontext(torch.load(str(self.dir_model / part_name), map_location="cpu", mmap=True, weights_only=True))
```

Also seems fine. Note that converting the `Path` to a `str` is actually necessary, apparently Torch only support mmaping when the first argument is a string.

We probably should at least turn on `weights_only=True` but maybe that stuff should happen in a separate pull.

**Pull request merged**
