### PR TITLE
rework convert.py to read params from config to allow open_llama 3B

### LINKED ISSUE #1709: Shape Error When Running Inference after Converting OpenLlama 3B to GGML
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x ] I reviewed the [Discussions]( ), and have a new bug or useful enhancement to share.

# Expected Behavior

Model loads successfully and inference can be run.

# Current Behavior

Model fails to load with shape error.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 5315Y CPU @ 3.20GHz
Stepping:                        6
CPU MHz:                         3200.011
BogoMIPS:                        6400.05
Hypervisor vendor:               Xen
Virtualization type:             full
L1d cache:                       384 KiB
L1i cache:                       256 KiB
L2 cache:                        10 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdt
                                 scp lm constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand h
                                 ypervisor lahf_lm abm 3dnowprefetch cpuid_fault pti ibpb fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_n
                                 i xsaveopt xsavec xgetbv1 xsaves umip rdpid
```

* Operating System, e.g. for Linux:

`$ uname -a`
```
Linux nwlujxf2ho 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```
Python 3.9.16

 GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 


```

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Conversion is ran with this command "python convert.py ../open_llama_3b_600bt_preview/"
2. Inference : ./main -m ../open_llama_3b_600bt_preview/ggml-model-f16.bin

# Failure Logs

```
CONVERSION:

python convert.py ../open_llama_3b_600bt_preview/
Loading model file ../open_llama_3b_600bt_preview/pytorch_model.bin
Loading vocab file ../open_llama_3b_600bt_preview/tokenizer.model
Writing vocab...
```

```
INFERENCE:

root@nwlujxf2ho:/notebooks/llama.cpp# ./main -m ../open_llama_3b_600bt_preview/ggml-model-f16.bin
main: build = 1 (f4c55d3)
main: seed  = 1686014332
llama.cpp: loading model from ../open_llama_3b_600bt_preview/ggml-model-f16.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 3200
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 25
llama_model_load_internal: n_layer    = 26
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 8704
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 3B
llama_model_load_internal: ggml ctx size =    0.06 MB
error loading model: llama.cpp: tensor 'layers.0.feed_forward.w1.weight' has wrong shape; expected  3200 x  8704, got  3200 x  8640
llama_init_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../open_llama_3b_600bt_preview/ggml-model-f16.bin'
main: error: unable to load model
```

### PR DESCRIPTION
**Pull request by Green-Sky**
This move the parameter discovery up, so it can be used to convert the model, and stop guessing.

The `n_mult` discovery is a hack. @SlyEcho used 216, the current script iteratively tries and finds 240, but other values work too.
As said here https://github.com/ggerganov/llama.cpp/pull/1588#issuecomment-1562573048 , `n_mult` should be replaced with a `n_ff` hyperparameter in the ggml file.

disclaimer: I am not a python dev :smile:

### CODE REVIEW

**Comment by SlyEcho** [comment]
How I got the number: I put the expession to calculate `n_ff` into Wolfram Alpha and asked to solve for $n_{\mathrm{mult}}$ when $n_{\mathrm{ff}} = 8640$. The answer was 108.

Then we settled on 216 in the end because it seems more closer to the original 256, but it calculates the same `n_ff`.

The real solution is maybe some kind of number theory? Coprime, GCD, something like that.

The real, real solution is that `n_mult` is not needed and we use `n_ff` instead. Maybe something to consider for the next model format.

**Comment by Green-Sky** [comment]
> How I got the number: I put the expession to calculate `n_ff` into Wolfram Alpha and asked to solve for nmult when nff=8640. The answer was 108.
> 
> Then we settled on 216 in the end because it seems more closer to the original 256, but it calculates the same `n_ff`.
> 
> The real solution is maybe some kind of number theory? Coprime, GCD, something like that.


there are a whole bunch of solutions between 1 and 4096 eg:
```
valid solutions for n_ff:8640 n_embd:3200
108, 120, 135, 144, 160, 180, 192, 216, 240, 270, 288, 320, 360, 432, 480, 540, 576, 720, 864, 960, 1080, 1440, 1728, 2160, 2880
```

**Review by SlyEcho — APPROVED** [review]
Seems to work with my 3B workflow. One byte is different only, the `n_mult` value.

**Comment by Green-Sky** [comment]
@TheBloke can I request you to take a look at this too? you would be the one using this script the most after all :)

**Comment by TheBloke** [comment]
Thanks for the ping!  I used it to make a model (https://huggingface.co/TheBloke/Flan-OpenLlama-7B-GGML) and that worked fine

I also benchmarked it vs the original script, and saw no performance degradation:
```
Orig script summary:
Result: 14.85
Result: 14.57
Result: 14.38
Result: 14.47
orig_script average over 4 runs: 14.566 s
New script summary:
Result: 14.48
Result: 14.45
Result: 14.71
Result: 14.41
new_script average over 4 runs: 14.515 s
```

And verified that it did indeed return exactly the same result:
```
llama.cpp original
73d8e4e73586154efe310ebec0c5112b7583b9bb6ec95d022e4955f910e9ee5b  /tmp/fp16.bin
new script
73d8e4e73586154efe310ebec0c5112b7583b9bb6ec95d022e4955f910e9ee5b  /tmp/fp16.bin
```

So looks good to me!

**Comment by Green-Sky** [comment]
> I also benchmarked it vs the original script, and saw no performance degradation:

there should not, so that is good. :)

> And verified that it did indeed return exactly the same result:

what i wanted to hear :)

Do you know of any openllama 3B finetune you could not convert before?

**Comment by TheBloke** [comment]
I've actually never done a 3B model of any type. People have asked from time to time but I've always deprioritised them because even 7B feels pretty limited to me now, so 3B just felt *too* small :)

I took a look at doing OpenLlama 3B but I see SlyEcho has already uploaded that to HF that so I won't duplicate that.

I looked for another Llama 3B but couldn't find any so I just tested Open Llama 3B as you already did and yeah it worked fine, having failed with llama.cpp/convert.py.

Good stuff!

**Comment by SlyEcho** [comment]
Could you make a release from this? It seems that it is not triggered automatically.

**Comment by Green-Sky** [comment]
> Could you make a release from this? It seems that it is not triggered automatically.

https://github.com/ggerganov/llama.cpp/actions/runs/5349425256

on its way

**Comment by Green-Sky** [comment]
> Do you know of any openllama 3B finetune you could not convert before?

ok i found some now. eg:
https://huggingface.co/psmathur/wizardlm_alpaca_dolly_orca_open_llama_3b

**Pull request merged**
