### PR TITLE
llama.cpp : fix --leave-output-tensor for llama-quantize.

### PR DESCRIPTION
**Pull request by drollings**
* Tweaked llama-quantize's --leave-output-tensor parameter's impact on llama_model_quantize_internal() to exclude any tensor named "*output.weight" instead of just "output.weight".

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by ggerganov** [comment]
Can you provide an example model where this makes a difference?

**Comment by drollings** [comment]
I mostly work on Llama 3.1-based models.  In every case where I was quantizing, attempting to leave embedding and output tensors at Q8, they were all getting re-quantized.  The models were being made mostly pure Q4_K_M.  Most straightforward examples:  https://huggingface.co/arcee-ai/Llama-3.1-SuperNova-Lite, https://huggingface.co/arcee-ai/Llama-3.1-SuperNova-Lite, https://huggingface.co/akjindal53244/Llama-3.1-Storm-8B, https://huggingface.co/ValiantLabs/Llama3.1-8B-ShiningValiant2.

**Comment by ggerganov** [comment]
What name does the output tensor have for these models? Looking at the safetensors on HF, the original name is `lm_head.weights` so it should be converted to `output.weight` by the `convert_hf_to_gguf.py` script. So I don't see why this change would make a difference.

**Comment by drollings** [comment]
I found an example for you, from running llama-quantize on a GGUF of TechxGenus/CursorCore-QW2.5-1.5B.  In this example, the name of the tensors you asked for is ."attn_output", and the patch affects the behavior only when --leave-output-tensor is used.  To my understanding, this patch is allowing behavior closer to expected.

Without the patch:

```
$ llama-quantize --allow-requantize --output-tensor-type Q6_K --token-embedding-type Q6_K --leave-output-tensor  /tmp/cursorcore-qwen2.5-1.5b:q8_0.gguf /tmp/cursorcore-qwen2.5-1.5b:q6_k.gguf Q4_K_M 2>&1 | grep output
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
[   9/ 338]             blk.0.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, converting to q4_K .. size =     2.39 MiB ->     1.27 MiB
[  21/ 338]             blk.1.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, converting to q4_K .. size =     2.39 MiB ->     1.27 MiB
[  33/ 338]            blk.10.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, converting to q4_K .. size =     2.39 MiB ->     1.27 MiB
[  45/ 338]            blk.11.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, converting to q4_K .. size =     2.39 MiB ->     1.27 MiB
...
```
With the patch:
```
$ llama-quantize --allow-requantize --output-tensor-type Q6_K --token-embedding-type Q6_K --leave-output-tensor  /tmp/cursorcore-qwen2.5-1.5b:q8_0.gguf /tmp/cursorcore-qwen2.5-1.5b:q6_k.gguf Q4_K_M 2>&1 | grep output
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
[   9/ 338]             blk.0.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, size =    2.391 MB
[  21/ 338]             blk.1.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, size =    2.391 MB
[  33/ 338]            blk.10.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, size =    2.391 MB
[  45/ 338]            blk.11.attn_output.weight - [ 1536,  1536,     1,     1], type =   q8_0, size =    2.391 MB

```

**Comment by ggerganov** [comment]
I see now. So the flag `--leave-output-tensor` is intended only for the final output tensor at the end of the transformer, usually named `"output.weight"`. The output tensors in the attention layers (such as `"blk.0.attn_output.weight"` are not supposed to be affected by this flag. So currently the flag is functioning correctly and the proposed change is not correct.

We can add functionality for excluding certain tensors in order to achieve what you are trying and there is already some partial works in the PRs. But for now, there is no such functionality exposed.

**Comment by drollings** [comment]
Thank you for your time and consideration.  I look forward to the official features; in the meantime, I often quantize GGUFs with this patch, keeping all output and embedding tensors at Q8_0 while tuning others down to Q4_K_M or Q5_K_M.  It will be interesting to see benchmarks on targeted quantizations like this.

**Pull request closed without merging**
