### PR TITLE
fix build-info.h for git submodules

### PR DESCRIPTION
**Pull request by kuvaus**
If llama.cpp is added as a project submodule, .git is a text file containing gitdir. Adding extra backslash .git/ to if(EXISTS) makes it sure that .git/ is a folder containing index.

### CODE REVIEW

**Review by slaren — APPROVED** [review]

**Comment by kuvaus** [comment]
<h3>Fix issue with git submodule and CMake in llama.cpp</h3>

In the discussion on https://github.com/ggerganov/llama.cpp/pull/1232#issuecomment-1528824653 there was a suggestion to include llama.cpp as a git submodule and include the CMake via add_subdirectory(external/llama.cpp).

> was thinking of including llama.cpp as a git submodule or git subtree and including the cmake via eg `add_subirectory(external/llama.cpp)` .
> 
> > CMAKE_CURRENT_SOURCE_DIR
> 
> In the llama.cpp's project root directory is the way to go, I think.


However, when using a git submodule, the .git file in the submodule directory is actually a text file containing a reference to the actual git directory:

```gitdir: ../.git/modules/llama.cpp```

In that case, the current implementation in CMakeLists.txt causes an error. Line 93 checks for the existence of the .git file:

```if(EXISTS "\${CMAKE_CURRENT_SOURCE_DIR}/.git")```

Since the file exists, the condition passes. However, line 103 has a dependency on the `.git/index` file, which doesn't exist in this case:

```DEPENDS "\${CMAKE_CURRENT_SOURCE_DIR}/.git/index"```

This causes the following error:

```No rule to make target 'project/llama.cpp/.git/index', needed by 'project/llama.cpp/build-info.h'. Stop.```

To fix this issue, we can add backslash to line 93 to check that .git/ is a folder.

```if(EXISTS "\${CMAKE_CURRENT_SOURCE_DIR}/.git/")```

This ensures that the .git file is a directory that can contain the required index file.

**Review by Green-Sky — CHANGES_REQUESTED** [review]
No. The git commands should work for submodules. However the observation, that the `.git/index` file in that case does not exist is correct. Can the `DEPENDS` be applied to directories too?

**Comment by Green-Sky** [comment]
I don't understand why we need those lines https://github.com/ggerganov/llama.cpp/blob/67c77799e025a8425c23a6a0599c007f46ded590/CMakeLists.txt#L97-L105

Is the build script not executed every time anyway?
https://github.com/ggerganov/llama.cpp/blob/67c77799e025a8425c23a6a0599c007f46ded590/CMakeLists.txt#L90-L91

**Comment by kuvaus** [comment]
I removed the suggested lines 97-105 and the empty line at 106. Tested with a project that contained llama.cpp as a submodule and it compiles now. Good. I do get this warning:

```sh
CMake Warning at llama.cpp/CMakeLists.txt:97 (message):
  Git repository not found; to enable automatic generation of build info,
  make sure Git is installed and the project is a Git repository.
  ```

**Comment by Green-Sky** [comment]
> I removed the suggested lines 97-105 and the empty line at 106. Tested with a project that contained llama.cpp as a submodule and it compiles now. Good. I do get this warning:
> 
> ```shell
> CMake Warning at llama.cpp/CMakeLists.txt:97 (message):
>   Git repository not found; to enable automatic generation of build info,
>   make sure Git is installed and the project is a Git repository.
> ```

not sure what your issue is, but I tried those changes and it works fine now for me.

eg output of benchmark:
```
$ bin/benchmark
main: build = 488 (67c7779)
Starting Test
```

**Comment by kuvaus** [comment]
Oh, my mistake. I had not properly cleaned build directory on rebuild. It works now without errors. Thank you!

**Comment by DannyDaemonic** [comment]
This was a case of me trying to be too clever. We only need to reevaluate when git changes, but then when you first open the project a bunch of errors would show up because `build-info.h` wasn't found yet. So I added a line to generate it right away. Simpler is probably better.

**Comment by Green-Sky** [comment]
Actually, we do need the `add_custom_command()` with the index dependency. I will write some cmake to handel subdirectories.

**Comment by Green-Sky** [comment]
@DannyDaemonic the line
```
set(TEMPLATE_FILE "${CMAKE_BINARY_DIR}/BUILD_INFO.h.in")
```
causes issues
```
CMake Error: File /home/green/workspace/tmp_git_pr/external/llama.cpp/BUILD_INFO.h.in does not exist.
CMake Error at scripts/build-info.cmake:49 (configure_file):
  configure_file Problem configuring file
```
bacause
> When run in [cmake -P](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-P) script mode, CMake sets the variables [CMAKE_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_BINARY_DIR.html#variable:CMAKE_BINARY_DIR), [CMAKE_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html#variable:CMAKE_SOURCE_DIR), [CMAKE_CURRENT_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_BINARY_DIR.html#variable:CMAKE_CURRENT_BINARY_DIR) and CMAKE_CURRENT_SOURCE_DIR to the current working directory.

so I am going to put  the .in file next to the script file.

**Review by Green-Sky — APPROVED** [review]

**Comment by Green-Sky** [comment]
@kuvaus please check my changes, I force pushed onto your branch.

**Comment by kuvaus** [comment]
Nice. Looks like it builds without errors for me.

**Review by DannyDaemonic — APPROVED** [review]
I had to find a project to test this on. Ended up using kuvaus' [llama-chat](https://github.com/kuvaus/llama-chat).

Looks good to me; smart fix @Green-Sky.

**Comment by Green-Sky** [comment]
@kuvaus you merged in master literally seconds before I wanted to click merge. :rofl: 
now we have to wait on the ci again...

**Pull request merged**
