### PR TITLE
1.5 bit: we can do even better

### PR DESCRIPTION
**Pull request by ikawrakow**
Sorry for this series of backwards incompatible changes to `IQ1_S`, but the gains are too significant to ignore.

In the previous version (PR #5971) there was a 4-bit scale for every 32 weights. Spending 4 bits for a scale in a sub 2-bit quantization is wasteful, but I didn't have a good idea what to do with a spare bit. Going to 3-bit scales would have made the bit arrangement very awkward to work with, so I accepted the waste of 1 bit per 32 weights (0.03125 bpw). 

But after merging #5971 I thought about using the spare bit for a quant shift in the block of 32. I.e., instead of the quants being `{-1, 0, 1}`, use `{-1+delta, delta, 1+delta}`, where `delta` is `± some_value`, and we use the spare bit to encode the sign. It turns out that this improves PPL quite a bit with `some_value = 0.125`. 

The table shows a PPL comparison between `IQ1_S` on master (after PR #5971) and this PR. Context is 2048 tokens for LLaMA-v1 and 4096 for all other models. The last column shows the `rms_norm_epsilon` used to generate the PR results (I did not re-tune `rms_norm_epsilon` here but just re-used the values from #5971, so there may be some small additional improvements possible).

| Model |  PPL (PR #5971) | PPL (this PR) | rms_norm_epsilon |
|--:|--:|--:|--:|
| LLaMA-v1-7B   | 14.20 | 12.83 | 5e-5 |
|LLaMA-v1-13B  | 8.941 | 8.338 | 4e-5 |
|LLaMA-v1-30B | 6.999 | 6.722 | 2.5e-5 |
| LLaMA-v2-7B  | 13.51  | 11.86 | 1.875e-5 |
|LLaMA-v2-13B | 8.134 | 7.741  | 2e-5 |
|LLaMA-v2-70B | 5.343 | 5.211 | 3e-5 |
|Mistral-7B         | 11.21 | 10.42  | default |
|Mixtral8x7B      |  6.354 | 6.168 | default |

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by Artefact2** [comment]
Just as an aside, I'd really like some kind of versioning in the gguf metadata. Otherwise, if changes like this keep happening, it's going to create a lot of confusion for users down the road.

**Comment by JianbangZ** [comment]
@ikawrakow After a bit testing, I found IQ generally work worse than 2 weeks ago Wonder what were the possible causes? The good one I tested was this: https://github.com/ggerganov/llama.cpp/pull/5676

With the same qwen1.5-14b model, I reuse the same imatrix dat
PR 5676: PPL=9.3152, Hellaswag=77.35
Master:    PPL=10.1234, Hellaswag=75.35

I didn't find time to test your other recent PRs so not personly sure what broke it

**Comment by okpatil4u** [comment]
Is there a walkthrough on how to reproduce these results starting from the base model ?

**Comment by ikawrakow** [comment]
> Is there a walkthrough on how to reproduce these results starting from the base model ?

Yes:
1. Create imatrix. E.g., `./bin/imatrix -m base_model -f wiki.train.raw --chunks 1000 -o imatrix_name -t 1 -ngl 100`. If the model does not fit in your GPU (or you are not using a GPU), adjust `-t` and `-ngl` accordingly
2. Quantize. E.g., `./bin/quantize --imatrix imatrix_name base_model quantized_model iq1_s`
3. Run perplexity. E.g., `./bin/perplexity -m quantized_model -f wiki.test.raw -t 1 -ngl 100 -c 4096`. Same comment as in 1. about GPU. Change `-c 4096` to `-c 2048` for LLaMA-v1 models.

**Comment by xiechengmude** [comment]
hi
I found the dataset like "-f wiki.test.raw"

but what type supported here?

**Pull request merged**
