### PR TITLE
SimpleChat v3.1: Boolean chat request options in Settings UI, cache_prompt

### PR DESCRIPTION
**Pull request by hanishkvc**
Allow user to control any boolean options in the request json sent to server, from the settings ui.

Using same allow cache_prompt to be enabled, if the user so wants.

- Self Reported Review Complexity:
    - [x] Review Complexity : Low
    - [ ] Review Complexity : Medium
    - [ ] Review Complexity : High
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hanishkvc** [comment]
Hi @mofosyne 

I will push few more commits in an hours time, to clean up the settings entries to match a logical flow, rather than the current sequence which came about, more based on when things were added into it.

Also rename chatRequestOptions to apiRequestOptions, to indicate that it is used for both chat/completions and completions api end points.

**Comment by hanishkvc** [comment]
@mofosyne 

This PR is done, you can merge this.

**Review by akx — COMMENTED** [review]
I don't think it's necessarily a great idea to add a 140 KB, 1200 × 720 screenshot...

**Comment by hanishkvc** [comment]
@ggerganov @mofosyne @akx 

have changed to webp image format and also resized to 800x480, so now it occupies only 20K. Added the image to give a rough idea of how it will be, if one wants to use it.

**Review by mofosyne — APPROVED** [review]

**Comment by hanishkvc** [comment]
Hi @mofosyne 

The failing check was not related to simplechat nor this pr. Eitherway I have force rebased to the latest upstream.

**Comment by mofosyne** [comment]
@ggerganov seems like multiple PRs are constantly getting out-of-date with the base branch even if all the checks has passed. Rebasing and waiting for the checks doesn't seem to clear it in time as another PR would have been merged and then the cycle needs to start again.

**Comment by ggerganov** [comment]
I had accidentally enabled the following setting:

image

Disabled now and should be good

**Pull request merged**
