### PR TITLE
Fix gemma model conversion

### LINKED ISSUE #7964: Error converting gemma-1.1-7b-it to gguf.
**Model: google/gemma-1.1-7b-it**

`python llama.cpp/convert-hf-to-gguf.py --outtype f16 /content/gemma-1.1-7b-it --outfile /content/gemma-1.1-7b-it.f16.gguf`

```
INFO:hf-to-gguf:Loading model: gemma-1.1-7b-it
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Setting special token type bos to 2
INFO:gguf.vocab:Setting special token type eos to 1
INFO:gguf.vocab:Setting special token type unk to 3
INFO:gguf.vocab:Setting special token type pad to 0
INFO:gguf.vocab:Setting add_bos_token to True
INFO:gguf.vocab:Setting add_eos_token to False
INFO:gguf.vocab:Setting chat_template to {{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '
' + message['content'] | trim + '<end_of_turn>
' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model
'}}{% endif %}
INFO:gguf.vocab:Setting special token type prefix to 67
INFO:gguf.vocab:Setting special token type suffix to 69
INFO:gguf.vocab:Setting special token type middle to 68
WARNING:gguf.vocab:No handler for special token type fsep with id 70 - skipping
INFO:gguf.vocab:Setting special token type eot to 107
INFO:gguf.vocab:Setting chat_template to {{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '
' + message['content'] | trim + '<end_of_turn>
' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model
'}}{% endif %}
Traceback (most recent call last):
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 2881, in <module>
    main()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 2866, in main
    model_instance.set_vocab()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 2250, in set_vocab
    special_vocab.add_to_gguf(self.gguf_writer)
  File "/content/llama.cpp/gguf-py/gguf/vocab.py", line 73, in add_to_gguf
    gw.add_chat_template(self.chat_template)
  File "/content/llama.cpp/gguf-py/gguf/gguf_writer.py", line 565, in add_chat_template
    self.add_string(Keys.Tokenizer.CHAT_TEMPLATE, value)
  File "/content/llama.cpp/gguf-py/gguf/gguf_writer.py", line 206, in add_string
    self.add_key_value(key, val, GGUFValueType.STRING)
  File "/content/llama.cpp/gguf-py/gguf/gguf_writer.py", line 166, in add_key_value
    raise ValueError(f'Duplicated key name {key!r}')
ValueError: Duplicated key name 'tokenizer.chat_template'
```

### PR DESCRIPTION
**Pull request by Galunid**
fixes #7964 

Untested, since I cannot download gemma without going through license hoops.

@0wwafa Would you mind giving it a try?

### CODE REVIEW

**Comment by 0wwafa** [comment]
hmm I solved that by commenting a line in gguf writer...
it seems that in gemma there are multiple chat-templates.
by commenting the line when it raises an exception when there is a duplicate key I cause the last one to overwrite the previous one.

alternatively, I could take the first one.
I don't understand your patch...

**Comment by 0wwafa** [comment]
about the hoops: a single click on huggingface doesn't seem much of a hoop.

**Comment by bartowski1182** [comment]
@0wwafa there aren't 2 chat templates, it's just being set twice accidentally because 2 places do it, and Gemma happens to be the only one that's calling both of those places

**Comment by MoonRide303** [comment]
Gemma 2 models were [just released on HF](https://huggingface.co/collections/google/gemma-2-release-667d6600fd5220e7b967f315). Trying to convert [gemma-2-9b-it](https://huggingface.co/google/gemma-2-9b-it) results in:
```
INFO:hf-to-gguf:Loading model: gemma-2-9b-it
ERROR:hf-to-gguf:Model Gemma2ForCausalLM is not supported
```

**Comment by Galunid** [comment]
See #8156

**Comment by Galunid** [comment]
This is no longer a problem on `master`

**Pull request closed without merging**
