### PR TITLE
convert : get general.name from model dir, not its parent

### PR DESCRIPTION
**Pull request by cebtenzzre**
When I converted `dl/Open-Orca_Mistral-7b-OpenOrca`, convert.py would set general.name to `dl`. Now it sets it to `Open-Orca_Mistral-7b-OpenOrca` like convert-hf-to-gguf.py would.

Am I missing something? I don't understand if the previous behavior was intentional. TheBloke's models on HF don't seem to be affected by this... cc @TheBloke in case you have an opinion?

### CODE REVIEW

**Comment by slaren** [comment]
Originally this is from https://github.com/ggerganov/llama.cpp/commit/8f8c28e89cb9531211783da697d6e7c445e2af1d. My guess is that it was done this way due to the directory structure of the original llama-2 distribution files.

**Comment by ggerganov** [comment]
> My guess is that it was done this way due to the directory structure of the original llama-2 distribution files.

Yes, that was the intention. It's not the smartest logic, so probably it can be improved. But I like to think that `convert.py`'s main purpose is to convert the original models released by Meta. So it should be compatible in some way or another with the directory structure of those models

**Comment by cebtenzzre** [comment]
> My guess is that it was done this way due to the directory structure of the original llama-2 distribution files.

Where do I get these? I know about https://github.com/facebookresearch/llama but their download.sh just downloads files to a folder to the current directory (TARGET_FOLDER of "."), with a name like "llama-2-7b" (MODEL_PATH).

**Comment by cebtenzzre** [comment]
Could it be clearly explained how the expected folder structure is meant to be created, so that I can verify that convert.py sets general.name correctly in *all* cases? So far it seems to me that some manual operations are required to result in the name of the parent directory being relevant, Meta checkpoints or otherwise.

**Review by ggerganov — APPROVED** [review]
I have this on my machine:

```
$ tree llama*
llama
├── 13B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   └── params.json
├── 30B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   ├── consolidated.02.pth
│   ├── consolidated.03.pth
│   └── params.json
├── 65B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   ├── consolidated.02.pth
│   ├── consolidated.03.pth
│   ├── consolidated.04.pth
│   ├── consolidated.05.pth
│   ├── consolidated.06.pth
│   ├── consolidated.07.pth
│   └── params.json
├── 7B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── tokenizer.model
└── tokenizer_checklist.chk
llama2
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
├── MODEL_CARD.md
├── README.md
├── Responsible-Use-Guide.pdf
├── USE_POLICY.md
├── download.sh
├── example_chat_completion.py
├── example_text_completion.py
├── llama
│   ├── __init__.py
│   ├── generation.py
│   ├── model.py
│   └── tokenizer.py
├── llama-2-13b
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   └── params.json
├── llama-2-13b-chat
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   └── params.json
├── llama-2-70b
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   ├── consolidated.02.pth
│   ├── consolidated.03.pth
│   ├── consolidated.04.pth
│   ├── consolidated.05.pth
│   ├── consolidated.06.pth
│   ├── consolidated.07.pth
│   └── params.json
├── llama-2-70b-chat
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   ├── consolidated.01.pth
│   ├── consolidated.02.pth
│   ├── consolidated.03.pth
│   ├── consolidated.04.pth
│   ├── consolidated.05.pth
│   ├── consolidated.06.pth
│   ├── consolidated.07.pth
│   └── params.json
├── llama-2-7b
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── llama-2-7b-chat
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── requirements.txt
├── setup.py
├── tokenizer.model
└── tokenizer_checklist.chk
```

I've forgotten how I downloaded the `llama` models, but the `llama2` were downloaded through the `download.sh` script.

The v2 support is more important to get right and the v1 is nice to have, but can be ignored as it's quite outdated now. Apologies for this PR getting accidentally ignored - I think the change is good

**Comment by mofosyne** [comment]
I'm pretty sure it's safe to merge as I was trying to do the same a while ago as well... and gg thinks it's safe to do so based on his directory structure.

Will merge soon unless someone else can see any issue.

**Pull request merged**
