### PR TITLE
common : try to fix Android CI

### PR DESCRIPTION
**Pull request by ggerganov**
ref #6414 

https://github.com/ggerganov/llama.cpp/actions/runs/8757099433/job/24035025415#step:5:200

### CODE REVIEW

**Review by phymbert — DISMISSED** [review]

**Comment by phymbert** [comment]
@ggerganov What about simply skipping `__ANDROID__` definition ?

`pthread_setaffinity_np` is simply not supported on android ndk.

**Comment by ggerganov** [comment]
Thanks. I keep forgetting that the Android CI pulls from `master`, so maybe even the first attempt was correct:

```diff
diff --git a/common/common.cpp b/common/common.cpp
index b6143e41..3039e470 100644
--- a/common/common.cpp
+++ b/common/common.cpp
@@ -108,7 +108,7 @@ int32_t get_num_physical_cores() {
     return n_threads > 0 ? (n_threads <= 4 ? n_threads : n_threads / 2) : 4;
 }
 
-#if defined(__x86_64__) && defined(__linux__) && !defined(__ANDROID__)
+#if defined(__x86_64__) && defined(__gnu_linux__)
 #include <pthread.h>
 
 static void cpuid(unsigned leaf, unsigned subleaf,
@@ -162,7 +162,7 @@ static int count_math_cpus(int cpu_count) {
  * Returns number of CPUs on system that are useful for math.
  */
 int get_math_cpu_count() {
-#if defined(__x86_64__) && defined(__linux__) && !defined(__ANDROID__)
+#if defined(__x86_64__) && defined(__gnu_linux__)
     int cpu_count = sysconf(_SC_NPROCESSORS_ONLN);
     if (cpu_count < 1) {
         return get_num_physical_cores();
```

For now, will merge as it is to make the CI green and can improve in the future

**Comment by phymbert** [comment]
Noted,[ I will fix that also](https://github.com/phymbert/llama.cpp/blob/master/examples/llama.android/app/src/main/cpp/CMakeLists.txt#L19). At the moment it is umpossible to load a model anyway. I will have fun with that :)

**Comment by phymbert** [comment]
Yes it is fixed, thanks

**Pull request merged**
