### PR TITLE
update CMakefiles.txt to check for openblas64

### PR DESCRIPTION
**Pull request by ghost**
openblas > v0.3.21 64-bit pkg-config file is now named openblas64.pc  https://github.com/OpenMathLib/OpenBLAS/issues/3790

build [fails](https://cache.nixos.org/log/0sy8qxjyjh70lzip16gb27dmb7j0nilw-llama-cpp-1483.drv)  when using openblas v0.3.24

Updating the build to check for openblas64 then fall back to openblas fixes this -- assuming that ILP64 is preferred.

the [nix flake](https://github.com/ggerganov/llama.cpp/blob/07178c98e1b61a5e2af39d347add12e7eb9e08e1/flake.nix) uses ILP64 so I am assuming that is the preference.

### CODE REVIEW

**Comment by cebtenzzre** [comment]
This is specifically the ILP64 version of OpenBLAS (openblas64, 64-bit 'int' type), instead of the LP64 version of OpenBLAS (openblas, 64-bit 'long' type, the one I use). Is there a benefit to using the ILP64 version? Or is there a common situation in which the ILP64 version would already be installed but the standard LP64 version wouldn't be?

**Comment by a-n-n-a-l-e-e** [comment]
nixos provides both types, and before version v0.3.22 both were indistinguishable from pkg-config i think. both named openblas.pc and both  indicated `USE64BITINT=`. where v.0.3.22 just fixed the pkg-config for the ILP64 version so it would be contained in openblas64.pc and have `USE64BITINT=1`.

if llama-cpp just wants LP64 then this was just a misconfiguration of the llama-cpp package for nixos which can just be remedied by building with the LP64 version of openblas.

**Comment by a-n-n-a-l-e-e** [comment]
the [flake.nix](https://github.com/ggerganov/llama.cpp/blob/07178c98e1b61a5e2af39d347add12e7eb9e08e1/flake.nix) is also using ILP64 -- once the flake.lock is updated past mid november it will have the same issue. so it will either need to specify the LP64 openblas package `openblasCompat` or this `CMakefile.txt` will need to be updated to something similar to what is in this change.

**Comment by cebtenzzre** [comment]
It looks like the main difference in the ILP64 version is that array dimensions and indices are 64 bits.

**Pull request merged**
