### PR TITLE
Respect tokenizer.ggml.add_bos_token value when tokenizing

### PR DESCRIPTION
**Pull request by KerfuffleV2**
Now that we're saving `tokenizer.ggml.add_bos_token` and `tokenizer.ggml.add_eos_token` it's time to at least use `add_bos_token` (it's less clear exactly how we'd use `add_eos_token`).

This pull sets those fields in the vocab metadata for later use.

I also added a function in common `bool llama_should_add_bos_token` - this follows the existing behavior _if_ the field isn't present in the metadata. So true if SPM, otherwise false.

I also snuck in a tiny fix for `gguf-py/scripts/gguf-dump.py` where it still included tensors with `--no-tensor` when you used `--json`.

I updated the examples to use that instead of the existing logic. It was a little more complicated for two of them:

`server` actually just unconditionally added BOS in some places regardless of whether the model was SPM. I think that's probably a bug. I just changed the places where it was `true` to use the "should add bos token" value.

Same thing with LLaVA's `llava-cli` program.

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
Ahhh, killl meeee. I just realized there's a problem on the Python conversion side.

**Comment by yhyu13** [comment]
Related hf discussion https://huggingface.co/TheBloke/Nous-Capybara-34B-GGUF/discussions/1#65530a38a69abe5afba6e9d9

**Comment by KerfuffleV2** [comment]
> Related hf discussion

I can go there and discuss the problem with my good friend KerfuffleV2... :) I'm sure he'll have some valuable insights to share.

**Comment by KerfuffleV2** [comment]
> pretty sure that is just a relic of the llama-only days

I figured something like that was probably the case. Anyway, this pull updates that to use similar behavior as the other examples in addition to respecting the `add_bos` metadata setting.

**Comment by KerfuffleV2** [comment]
I don't think there should be anything too controversial about this one. We already added some of the groundwork for the `add_bos/eos_token` metadata but there's kind of no point unless we actually use it.

All the behavior should be the same as `master` when `add_bos_token` isn't set - except for for I think I actually fixed a couple of the examples that didn't have the normal behavior of adding BOS if the model was SPM otherwise not. They would have been adding BOS even for non-SPM models. This pull also unifies that behavior.

There is also now a central place to change it if necessary.

**Review by Green-Sky — APPROVED** [review]
I actually thought we where already doing this.

**Comment by KerfuffleV2** [comment]
Thanks for approving! Finally I can get some closure.

> I actually thought we where already doing this.

You might be thinking of a previous pull that added the metadata (although there was an issue where we'd give up looking for it too early). This one will actually start making use of it.

**Pull request merged**
