### PR TITLE
Delete SHA256SUMS for now

### PR DESCRIPTION
**Pull request by anzz1**
Delete this for now to avoid confusion since it contains some wrong checksums from the old tokenizer format

Re-add after #374 is resolved

### CODE REVIEW

**Review by sw — APPROVED** [review]
I agree that it's best not to confuse people with wrong checksums

**Comment by Green-Sky** [comment]
it would have been better to only delete the wrong checksum :eyes:

**Comment by anzz1** [comment]
> it would have been better to only delete the ~wrong~ old checksum eyes

I wasn't sure if all of them were wrong/old or just some. In any case better to take it out for now until it's fully updated and checked first, right?

**Comment by Green-Sky** [comment]
afaik most where correct, @gjmulder ?

**Comment by gjmulder** [comment]
@Green-Sky they were "correct" in that they reflected the *.pth data files I have and `ggml` files generated from them at that point in time, with the exception of the alpaca `ggml` which I found in various places.

I was waiting for people to confirm that everything was correct before merging, but @prusnak decided to go ahead with what I had generated.

**Comment by prusnak** [comment]
This was a mistake. Let's readd SHA256SUMS with only PTH files there. There was no need to erase all hashes.

**Pull request merged**
