### PR TITLE
[SYCL] add concat through dim 1/2

### PR DESCRIPTION
**Pull request by airMeng**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Comment by airMeng** [comment]
@characharm can you try deepseek on this branch? Thank you in advance, your support is our motivation

**Comment by airMeng** [comment]
@OuadiElfarouki, I'm wondering who I should tag for PR reviews at Codeplay. Could you or someone else represent Codeplay for the following PRs? For any Intel-related issues, feel free to tag me.

**Review by NeoZhangJianyu — APPROVED** [review]
I test UT successfully.
And verify DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf on Arc770 is passed.

**Comment by OuadiElfarouki** [comment]
@airMeng Thanks for the tag. You can either reach out to @joeatodd (Team PO at Codeplay), or @Alcpz or myself.

**Review by OuadiElfarouki — APPROVED** [review]
LGTM Thanks!

**Comment by characharm** [comment]
> I test UT successfully. And verify DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf on Arc770 is passed.

Could you please check this model DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M?  [link ](https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF/blob/main/DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf)I have tried several times, but the computer completely froze every time after loading the model into memory.

**Comment by characharm** [comment]
> I test UT successfully. And verify DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf on Arc770 is passed.

Could you please check this modelDeepSeek-Coder-V2-Lite-Instruct-Q6_K? [link ](https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF/blob/main/DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf)I have tried several times, but the computer completely froze every time after loading the model into memory. tested on this build [b3398](https://github.com/ggerganov/llama.cpp/releases/tag/b3398)

**Comment by airMeng** [comment]
> > I test UT successfully. And verify DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf on Arc770 is passed.
> 
> Could you please check this model: DeepSeek-Coder-V2-Lite-Instruct-Q6_K? [link ](https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF/blob/main/DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf)I have tried several times, but the computer completely froze every time after loading the model into memory. tested on this build [b3398](https://github.com/ggerganov/llama.cpp/releases/tag/b3398)

seems the model file itself is 14.1GB, how much vram your GPU has?

**Comment by characharm** [comment]
> > > I test UT successfully. And verify DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf on Arc770 is passed.
> > 
> > 
> > Could you please check this model: DeepSeek-Coder-V2-Lite-Instruct-Q6_K? [link ](https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF/blob/main/DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf)I have tried several times, but the computer completely froze every time after loading the model into memory. tested on this build [b3398](https://github.com/ggerganov/llama.cpp/releases/tag/b3398)
> 
> seems the model file itself is 14.1GB, how much vram your GPU has?

16gb, but other models with the same or even slightly larger file size work fine

**Comment by characharm** [comment]
b3408 , now it shuts down at this

image

**Pull request merged**
