### PR TITLE
termux: use clblast in repo

### PR DESCRIPTION
**Pull request by rhjdvsgsgks**

### CODE REVIEW

**Comment by cebtenzzre** [comment]
This was going to be included in #2840 but the user deleted their account so it never got merged.

**Comment by staviq** [comment]
While we're at termux instructions

Current instructions specify `apt` as package manager, and for reasons unclear, that doesn't always work, however `pkg` with the same parameters does work.

Since I cannot pinpoint a reason, replacing `apt` with `pkg` would be too much of a guess, so instead it could be helpful to simply mention `pkg` as alternative to `apt` in case of problems.

**Comment by cebtenzzre** [comment]
> Current instructions specify `apt` as package manager, and for reasons unclear, that doesn't always work, however `pkg` with the same parameters does work.

`apt` should work as long as you have a mirror selected (via `termux-change-repo`) and have run `apt update` at some point. `pkg` is a wrapper that automatically does these things, which makes it slower but may be a good idea to use in the README.

**Comment by ggerganov** [comment]
Not sure if this is relevant any more - reopen if necessary

**Pull request closed without merging**
