### PR TITLE
avoid to get prompt in infill mode and embedding mode

### PR DESCRIPTION
**Pull request by woodx9**
I run server with command './server -m ../1.3b-instruct.gguf --port 8760'
and then run a py client below to get the result.
`import asyncio
import aiohttp
import json
import time

prompt = 'finish the code completion:'
input_prefix = 'def bubbleSort()\n'

async def test():
    async with aiohttp.ClientSession() as session:
        start_time = time.time()
        
        payload = {
            'input_prefix': input_prefix,  # 'prompt' needs to be defined before using it
            'input_suffix': '',
            # 'prompt': prompt,
            'n_predict': 10
        }

        async with session.post('http://127.0.0.1:8760/infill', data=json.dumps(payload)) as response:
            elapsed_time = time.time() - start_time
            response_json = await response.json()
            print(response_json)
            print(f"Elapsed time: {elapsed_time} seconds")

asyncio.run(test())`

but I get a error:
`{'error': {'code': 400, 'message': 'Either "prompt" or "messages" must be provided', 'type': 'invalid_request_error'}}
Elapsed time: 0.0010190010070800781 seconds`

I read the code and find out We don't need to get prompt when in infill mode and embedding mode. 
So I add a if for the infill mode and embedding mode. It seems fine after I add the code.

### CODE REVIEW

**Comment by ggerganov** [comment]
The embedding CI seems to be failing

**Comment by woodx9** [comment]
> The embedding CI seems to be failing

I will test it

**Comment by woodx9** [comment]
It turns out I misunderstood the way embedding is. I think it's sentence embedding model mode.

**Comment by woodx9** [comment]
I try this new pr with deepseek code model, it seems fine.

**Comment by woodx9** [comment]
Bench server baseline already queued for 1 day, is that normal?

**Comment by woodx9** [comment]
@ggerganov @mofosyne hi, plz have a look. This will block the infill mode. I want to pr support for deepseek code model as well.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
