### PR TITLE
Server - support for saving templates in browser LocalStorage

### PR DESCRIPTION
**Pull request by staviq**
I found myself using the server example a lot, but i has a major problem, namely, the default prompt template has problems with certain models.

So I added a functionality of saving  and restoring the template automatically to/from the Local Storage, so I don't have to copy-paste my template each time :)

Visually, there is just a button on top of the settings, that lets you reset everything back to default.

I made it so it should be possible to have multiple templates, but I stopped at just autosaving current one to not change things too much at once.

### CODE REVIEW

**Comment by jhen0409** [comment]
👍 I also want this feature, it may help me and my coworkers to test models more easier. Also, can we have this for all params?

**Comment by staviq** [comment]
> +1 I also want this feature, it may help me and my coworkers to test models more easier. Also, can we have this for all params?

Parameters should also get saved with the template already.

**Comment by staviq** [comment]
I doubt this PR is gonna happen anytime soon, the llamacpp team has more important things to deal with, and they are working on other changes to the server part too, which partially conflict with this PR.

If anybody wants this change now, you can just grab the `index.html` from this PR or my fork, and copy it into your llamacpp local directory `examples/server/public/`

Once the team finalizes other PRs related to the server, I will update my fork and this PR.

For now, copying the `index.html` file will let you have template and settings autosave, without interfering with main repo.

Also, those autosaved templates and parameters, are stored client side, in your browser, and if you update llamacpp and accidentally overwrite `index.html` your saved templates and parameters will still be there, they are not lost, they will just not show up, untill you copy `index.html` again, or the team gets interested in this PR ( but I doubt it will happen anytime soon, as I said, they seem to have a lot of more important thing on their minds right now)

**Comment by jhen0409** [comment]
I can review this. You can fix conflicts first, or other changes you want to add.

Also, I'm recommend to use `useEffect` for auto save template (instead of do it every render) like this:

```js
    function App(props) {
      useEffect(() => {
        // autosave template on every change
        userTemplateAutosave()
      }, [session.value, params.value])
      // ...
```

**Comment by staviq** [comment]
@jhen0409 I modified things the way you recommended and it appears to be working properly.

**Review by jhen0409 — COMMENTED** [review]
Some little style-fix requests.

Also, you need to merge master branch and run `./examples/server/deps.sh`, so we can make sure the `index.html.cpp` is works properly.

**Review by jhen0409 — APPROVED** [review]
It works well.

**Pull request merged**
