### PR TITLE
Server: version bump for httplib and json

### LINKED ISSUE #6162: Server may have a directory traversal vulnerability fixed upstream
https://github.com/yhirose/cpp-httplib/issues/1768

### PR DESCRIPTION
**Pull request by ngxson**
- Update httplib to 0.15.3
- Update json to 3.11.3

Closes #6162

### CODE REVIEW

**Comment by slaren** [comment]
Build is failing due to an unused parameter in a 3rd party library. Coincidentally, after finding 188 instances of `GGML_UNUSED` in `ggml-cuda.cu`, I was about to suggest to remove this warning entirely, because IMO it causes more harm than good to the code quality.

```
 examples/server/httplib.h:4797:45: error: unused parameter ‘content_length’ [-Werror=unused-parameter]
```

**Comment by ngxson** [comment]
Yeah I got the same error on local build, seems like because the parameter is only being used by `assert()`, which is not present in our build. At first, I didn't want to modify the code because I didn't want to touch an external code. But if that breaks the CI, we have no choice then.

**Review by phymbert — APPROVED** [review]

**Comment by phymbert** [comment]
Note the windows server tests is failing for something not related. I will fix it later on

**Comment by phymbert** [comment]
> Note the windows server tests is failing for something not related. I will fix it later on

@ngxson Tests have been:
- broken in: #6127
- fixed in: #6146 

Please merge `master` into this to be sure all is OK on server tests, then I am happy to merge this important upstream security upgrade

**Comment by ggerganov** [comment]
The change in [e5ed307](https://github.com/ggerganov/llama.cpp/pull/6169/commits/e5ed3077b5ccb06f9640bfd0f10543da8b864f0f) does not work in Debug builds. Use `(void)(content_length);`

We can alternatively do as proposed by @slaren - disable the warning and eventually get rid of the unused calls

**Comment by ngxson** [comment]
I added `(void)(content_length);` because it seems to be the most non-destructive choice for now.

I also merged latest master to pick up the changes that @phymbert mentioned, hopefully the CI will pass

**Pull request merged**
