### PR TITLE
Faster AVX2 dot product for IQ2_XS

### PR DESCRIPTION
**Pull request by ikawrakow**
There is a proposal in #5152 to change the bit arrangement for `IQ2_XS` quantization to speedup inference on `x86` CPUs. The proposed change improves performance by up 35% on CPU's with few cores, but is not backwards compatible and will require to redo quantization for all published `IQ2_XS`-quantized models.

To avoid breaking backwards compatibility, I decided to see by how much one can improve `AVX2` inference speed using the existing `IQ2_XS` data format, and this PR is the result. The table shows a comparison between master, the approach proposed in #5152, and this PR for TG-128 on a Ryzen-7950X CPU for Mistral-7B.

| model           | backend    |    threads | test       |      t/s (Master)|     t/s (#5152)  |       t/s (PR)   |   
| ----------------| ---------- | ---------: | ---------- | ---------------: | ---------------: | ---------------: |
| llama 7B IQ2_XS | CPU        |          2 | tg 128     |      4.78 ± 0.01 |      6.12 ± 0.01 |      5.71 ± 0.01 |
| llama 7B IQ2_XS | CPU        |          4 | tg 128     |      9.09 ± 0.02 |     11.48 ± 0.04 |     10.83 ± 0.02 |
| llama 7B IQ2_XS | CPU        |          8 | tg 128     |     16.31 ± 0.04 |     17.90 ± 0.02 |     19.04 ± 0.05 |
| llama 7B IQ2_XS | CPU        |         16 | tg 128     |     21.84 ± 0.54 |     22.02 ± 0.46 |     22.44 ± 0.08 |

The #5152 approach is still faster for 2 threads, but now the difference is only 7%. Strangely enough, the PR outperforms #5152 for 8 or more threads (I have observed such non-intuitive behavior in the past when working on CPU inference optimization for k-quants, where one approach may be faster for low number of threads but slower when using all threads).

### CODE REVIEW

**Comment by PeterReid** [comment]
Here are the timings on the CPUs I times #5152 on, as requested.

| CPU | t/s (master) | t/s (#5152) | t/s (PR)
-----|------|------|-----
| i5-4300U | 1.30 | 1.62 | 1.51
|i7-1165G7 | 2.55 | 2.95 | 2.70

I wonder if this reason it is outperforming #5152 on your CPU in some cases is that it is processing four blocks at a time instead of two.

**Comment by ikawrakow** [comment]
@PeterReid Thank you for these results. 

> I wonder if this reason it is outperforming https://github.com/ggerganov/llama.cpp/discussions/5152 on your CPU in some cases is that it is processing four blocks at a time instead of two.

I think it is complicated. At 8 or 16 threads the threads are fighting for access to the limited memory bandwidth, and stalling as a result. Instructions have latencies. The compiler has reordered the instructions to keep the pipeline as occupied as possible. It is difficult to predict how this gets affected by the stalls waiting for data.

In any case, your approach does save a few instructions and is clearly way more elegant. I'm just not sure if the few percent performance difference is worth to break backwards compatibility.

**Comment by PeterReid** [comment]
I have found a marginal improvement to make to this PR: https://github.com/PeterReid/llama.cpp/commit/12b4c1355bed8d5c82b093bd62da3873c2d87b0b . This removes two AND instructions (unnecessary because bit 8 is already known to be 0 because of the shift by 9).

**Comment by PeterReid** [comment]
And another one: https://github.com/PeterReid/llama.cpp/commit/dbe586a3bfad7fc76e4cc7bc2588d015377eb380

**Comment by PeterReid** [comment]
I found a way to drop one of those shuffle instructions for bit counting by moving the xor before: https://github.com/PeterReid/llama.cpp/commit/03a3db128f2e8409a60e859e58095532142dd1a5 . And I've squashed them all together here if that makes more sense: https://github.com/PeterReid/llama.cpp/commit/aacf9a303c15632ef9b599f0c0582e8ea8042729  . Or should I just make a separate PR? I haven't done all the timing, but this cuts the difference between this PR and #5152 by about half for the little timing I've done.

It seems like with this shuffle trick you are using, there is very little computation saved by doing the backwards-compatibility break in #5152. The only argument for it I could see is that there may be platforms that don't have some fast way of bitcounting and for which doing the lookup table approach is slow.

**Comment by ikawrakow** [comment]
@PeterReid This is great! I was clearly confused by mostly operating on 8-bit SIMD vectors, where one does need to apply a mask after `_mm256_srli_epi16`. Thanks for 

With your changes, I get quite a bit better results on my Ryzen-7950X:

| model           | backend    |    threads | test       |              t/s |
| ----------------| ---------- | ---------: | ---------- | ---------------: |
| llama 7B IQ2_XS | CPU        |          2 | tg 128     |      6.70 ± 0.01 |
| llama 7B IQ2_XS | CPU        |          4 | tg 128     |     12.29 ± 0.05 |
| llama 7B IQ2_XS | CPU        |          8 | tg 128     |     21.09 ± 0.10 |
| llama 7B IQ2_XS | CPU        |         16 | tg 128     |     22.97 ± 0.34 |

Can you push your changes to this branch?

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
