### PR TITLE
fallback to CPU buffer if host buffer alloc fails

### PR DESCRIPTION
**Pull request by slaren**
Fixes https://github.com/ggerganov/llama.cpp/pull/4520#issuecomment-1868230241

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by LoganDark** [comment]
Is there a chance that this could silently kill performance in some configurations? Could there be an option to toggle it?

**Comment by slaren** [comment]
It may decrease prompt processing performance while partially offloading. What would the toggle do? There is already a warning printed if the host alloc fails.

**Comment by LoganDark** [comment]
> What would the toggle do?

Report an error instead of falling back.

> There is already a warning printed if the host alloc fails.

In that case there's nothing to do then. My main concern was not being able to tell when this starts happening in order to dial back the number of GPU layers. If there's a warning each time this happens, then that works for me.

**Comment by slaren** [comment]
Host memory is used for the layers on the CPU, so increasing the number of layers offloaded reduces the amount of pinned memory required.

**Comment by LoganDark** [comment]
Reading the patch, it looks like the PR allows llama.cpp to fall back to CPU allocations if GPU allocations fail. Dialing back the GPU layers is used to prevent filling up VRAM enough for the allocations to fail, yes? Therefore no fallbacks will be required.

**Comment by slaren** [comment]
> Reading the patch, it looks like the PR allows llama.cpp to fall back to CPU allocations if GPU allocations fail.

This does not happen, it is misleading because the CUDA backend is not currently used through the ggml-backend interface. If the GPU allocation fails, it will crash as it always did.

**Comment by LoganDark** [comment]
oops, I was looking at the buffer type function. thanks

**Comment by LostRuins** [comment]
@LoganDark in any case this fallback was always possible in older versions. It's simply fixing a behavior regression during the backend refactor.

**Comment by LostRuins** [comment]
Hi @slaren just tried this, and I don't think it's working correctly - when the pinned alloc fails the program still crashes.

Looking closer, I notice that you are checking for buft being nullptr
```
#elif defined(GGML_USE_CUBLAS)
    buft = ggml_backend_cuda_host_buffer_type();
...
    if (buft == nullptr) {
        buft = ggml_backend_cpu_buffer_type();
    }
```

However, since `ggml_backend_cuda_host_buffer_type()` returns a struct, it will never be a nullptr even though `ggml_backend_cuda_host_buffer_type_alloc_buffer()` returns a nullptr when the pinned malloc fails. Could that be the reason?

**Comment by slaren** [comment]
Yes, you are right. I included the fix in https://github.com/ggerganov/llama.cpp/pull/4606, so it should be working on the current master.

**Comment by LostRuins** [comment]
ah gotcha. thanks.

**Pull request merged**
