### PR TITLE
Add precompiled files for windows x64 and python script instead of bash script.

### PR DESCRIPTION
**Pull request by Black-Engineer**
Precompiled files for windows x64 via Cmake.

### CODE REVIEW

**Comment by miolini** [comment]
Please, do not distribute executable binaries in repository.

**Comment by LostRuins** [comment]
binaries should be in Releases, not repo.

**Comment by miolini** [comment]
Screenshot 2023-03-16 at 9 43 57 AM

**Comment by leumasme** [comment]
Why doesn't the github workflow file publish the build result files as github artifacts? That'd allow downloading the build result of every action run.

**Comment by HCBlackFox** [comment]
> Not by fresh github account with shady name.

Lol, why you are so rude? Yes Im new here, but that is not concern to blame me...I simply dont know how to do it right. You can tell me in normal words without agresion.

**Comment by Hades32** [comment]
Haven't had time to put do this right (i.e. make a PR and have the workflow create a release with multiple artifacts), but if someone just wants the Windows binaries, here I have them being built with GH actions with a minimal fork: https://github.com/Hades32/llama.cpp/actions/runs/4441656002

**Comment by LostRuins** [comment]
In any case, this project has basically zero dependencies. Just clone this repo and type `make` and you'll have your binaries in under 10 seconds.

**Comment by prusnak** [comment]
Closing since we don't want to have unreproducible executables committed in the git.

**Pull request closed without merging**
