### PR TITLE
sycl : Add support for non-release DPC++ & oneMKL

### PR DESCRIPTION
**Pull request by joeatodd**
This PR enables llama.cpp to be built with the non-release (i.e. built from source) versions of DPC++ (`clang++` instead of `icpx`) and oneMKL. Some duplicate/unneeded flags have been removed, and I have rearranged the logic slightly to keep things where they are needed.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [x] Medium
  - [ ] High

### CODE REVIEW

**Comment by joeatodd** [comment]
@airMeng @NeoZhangJianyu hey folks - I tested that I can still compile on PVC with the release compiler (2024.2), but perhaps you'd like to double check I haven't broken anything for your builds?

**Review by airMeng — APPROVED** [review]
LGTM @luoyu-intel our architecture for awareness

**Review by OuadiElfarouki — APPROVED** [review]

**Comment by mudler** [comment]
This seems to have broken things here:

```
[100%] Linking CXX executable ../../bin/grpc-server
/usr/bin/ld: ../../ggml/src/libggml.a(ggml-sycl.cpp.o): undefined reference to symbol '_ZN4sycl3_V15queue6memcpyEPvPKvmRKNS0_6detail13code_locationE'
/usr/bin/ld: /opt/intel/oneapi/compiler/2024.2/lib/libsycl.so.7: error adding symbols: DSO missing from command line
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there anything I'm missing maybe?

**Comment by mudler** [comment]
Similarly, this seems to break the rpc server build when `sycl` is enabled:

```
#45 1217.2 gmake[6]: Entering directory '/build/backend/cpp/llama-grpc/llama.cpp/build'                                                                                                                                                       
#45 1217.2 [ 92%] Building CXX object examples/rpc/CMakeFiles/rpc-server.dir/rpc-server.cpp.o                                                                                                                                                 
#45 1217.5 [100%] Linking CXX executable ../../bin/rpc-server                                                                                                                                                                                 
#45 1217.7 /usr/bin/ld: ../../ggml/src/libggml.a(ggml-sycl.cpp.o): undefined reference to symbol '_ZN4sycl3_V15queue6memcpyEPvPKvmRKNS0_6detail13code_locationE'                                                                              
#45 1217.7 /usr/bin/ld: /opt/intel/oneapi/compiler/2024.2/lib/libsycl.so.7: error adding symbols: DSO missing from command line                                                                                                               
#45 1217.7 icpx: error: linker command failed with exit code 1 (use -v to see invocation)    
```

**Comment by joeatodd** [comment]
Hi @mudler, sorry to hear I've messed things up for you. I can reproduce this locally with a build of `llama-bench`, if I pass `-DBUILD_SHARED_LIBS=OFF`, which I think is how you're building. 

It's missing `libsycl`, I think because I need to pass `-fsycl` as a linker flag, as well as a compilation flag.

I'll try a fix locally & push something ASAP.

**Comment by mudler** [comment]
> Hi @mudler, sorry to hear I've messed things up for you. I can reproduce this locally with a build of `llama-bench`, if I pass `-DBUILD_SHARED_LIBS=OFF`, which I think is how you're building.

No worries, was trying to trace it back to provide more contextual info and created #8665!

> 
> It's missing `libsycl`, I think because I need to pass `-fsycl` as a linker flag, as well as a compilation flag.
> 
> I'll try a fix locally & push something ASAP.

Thank you! :+1: I'm testing now a very simple workaround here to confirm that's what all is missing:

```
add_executable(rpc-server rpc-server.cpp)
if ( DEFINED ENV{ONEAPI_ROOT})
target_link_libraries(rpc-server PRIVATE ggml llama sycl)
else()
target_link_libraries(rpc-server PRIVATE ggml llama)
endif()
```

I'll let keep you posted! I can also give a shot to the PR once is up

**Pull request merged**
