### PR TITLE
Created a Server example

### PR DESCRIPTION
**Pull request by zrthxn**
I've created an example which provides an HTTP interface to LLaMA using [Crow](https://github.com/CrowCpp/Crow). This comes as a single header file which I've committed. Also, this library depends on Boost, so to build this example, one needs to install Boost (for MacOS its `brew install boost`).

### CODE REVIEW

**Comment by prusnak** [comment]
Please fix:
- build failures (CI above all over the place)
- conflicts with the main branch
- whitespace (see editorconfig failure in the CI)

**Comment by zrthxn** [comment]
@prusnak Sorry I should've marked this as a draft, I meant to fix all that.

**Comment by zrthxn** [comment]
@prusnak Could you help me with getting the [Windows build (windows-latest-cmake)](https://github.com/ggerganov/llama.cpp/actions/runs/4806126001/jobs/8556921980#logs) to work? I'm not sure how to get Boost to install there.

**Review by ggerganov — CHANGES_REQUESTED** [review]
- Add `LLAMA_BOOST` CMake option here which is `OFF` by default:

https://github.com/ggerganov/llama.cpp/blob/5fba3c016bfd1d73a070e7c93dac14162ce118d0/CMakeLists.txt#L65-L71

- Make this example build only if `LLAMA_BOOST` is `ON`
- Make a separate CI job just for `LLAMA_BOOST`. Only one OS is enough. We don't want to install / link boost in all CI jobs

**Comment by prusnak** [comment]
@zrthxn Do we even need Boost? We are on C++11 and lots of Boost features are being moved to std::. Doesn't Crow work with plain C++11?

**Comment by prusnak** [comment]
> Do we even need Boost? We are on C++11 and lots of Boost features are being moved to std::. Doesn't Crow work with plain C++11?

Answering to myself - yes, it seems Crow still needs boost :-/

**Comment by prusnak** [comment]
Wondering whether we shouldn't use a different C++ header-only HTTP(S) server library which does not require boost - such as https://github.com/yhirose/cpp-httplib

**Comment by zrthxn** [comment]
@ggerganov  I think it won't be too hard to use another library. I'm only using very minimal functionality from Crow, and I only have 1 or 2 endpoints. So I'll rework this to use `cpp-httplib`. I liked Crow mainly because it advertised that its a single header.

**Comment by prusnak** [comment]
> I liked Crow mainly because it advertised that its a single header.

So is cpp-httplib

**Comment by zrthxn** [comment]
@ggerganov @prusnak By the way, there is a slight issue that I've come across with serving the model. If an incoming request is cancelled, i.e. the client disconnects, the eval loop keeps running consuming CPU resources. My guess is that, at least with Crow, its because the endpoint handler that you write as a lambda expression is executed in a separate thread and that doesn't get stopped/killed when the client disconnects.

**Comment by prusnak** [comment]
Let's try how cpp-httplib deals with that.

**Comment by ggerganov** [comment]
In C++ world there is no way to terminate a thread once it has started, except to join it (i.e. wait for it to finish).
To solve the described issue, we need an abort mechanism added to the llama API

**Comment by zrthxn** [comment]
@ggerganov  One way of implementing aborting could be that in the eval loop, before writing a token to the output stream (stdout or file stream), check if some special character or sequence like `ABORT--ABORT` was written. If so, break.

**Comment by FSSRepo** [comment]
Hello everyone, I have a llama.cpp with cpp-httplib [here](https://github.com/FSSRepo/llama.cpp).

It doesn't require external dependencies.

## Limitations:
* Just tested in Windows and Linux
* Only CMake build.
* Only one context at a time.
* Just vicuna support for interaction.


## Usage
### Get Code
```bash
git clone https://github.com/FSSRepo/llama.cpp.git
cd llama.cpp
```
### Build
```bash
mkdir build
cd build
cmake ..
cmake .. --build . --config Release
```
### Run
Model tested: [Vicuna](https://huggingface.co/chharlesonfire/ggml-vicuna-7b-4bit/blob/main/ggml-vicuna-7b-q4_0.bin)
```bash
server -m ggml-vicuna-7b-q4_0.bin --keep -1 --ctx_size 2048
```

### Node JS Test for test the endpoints

You need to have [Node.js](https://nodejs.org/en) installed.

```bash
mkdir llama-client
cd llama-client
npm init
npm install axios
```

Create a index.js file and put inside this:
```javascript
const axios = require('axios');

async function Test() {
    let result = await axios.post("http://127.0.0.1:8080/setting-context", {
        context: [
            { role: "system", content: "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions." },
            { role: "user", content: "Hello, Assistant." },
            { role: "assistant", content: "Hello. How may I help you today?" },
            { role: "user", content: "Please tell me the largest city in Europe." },
            { role: "assistant", content: "Sure. The largest city in Europe is Moscow, the capital of Russia." }
        ],
        batch_size: 64,
        temperature: 0.2,
        top_k: 40,
        top_p: 0.9,
        n_predict: 2048,
        threads: 5
    });
    result = await axios.post("http://127.0.0.1:8080/set-message", {
        message: ' How much is 40 * 4?'
    });
    if(result.data.can_inference) {
        result = await axios.get("http://127.0.0.1:8080/completion?stream=true", { responseType: 'stream' });
        result.data.on('data', (data) => {
            let dat = JSON.parse(data.toString());
            process.stdout.write(dat.content);
        });
    }
}

Test();
```

Sorry my bad english and practices in C++ :(

**Comment by x4080** [comment]
@FSSRepo Hello, I tried running 
```
cmake --build . --config Release
```

and it gives errors in my mac mini M2 pro, the 
```
cmake ..
```
works

Can you help ? Thanks

**Comment by FSSRepo** [comment]
@x4080 you can detail the error in Issues tab on my fork, please

**Comment by x4080** [comment]
> @x4080 you can detail the error in Issues tab on my fork, please

I wanted to before this, there's no issue hehe, I'll do it now, see you there and thank you very much man

**Comment by x4080** [comment]
@ggerganov I tried this API and I think I love it, I cant wait to get it integrated to llama.cpp

@FSSRepo good work man

**Comment by zrthxn** [comment]
Closing in favor of https://github.com/FSSRepo/llama.cpp

**Comment by x4080** [comment]
@zrthxn so it won't be merged into llama cpp?

**Comment by zrthxn** [comment]
@x4080 I think the version made by @FSSRepo is better than mine. A lot of stuff is taken care of there. I think that should probably be merged. If you'd like me to convert my version to use `cpp-httplib`, I can do that too.

**Comment by x4080** [comment]
Oh i thought that you have the same merge request as @FSSRepo 

My mistake then

**Pull request closed without merging**
