### PR TITLE
Added special token support to llama_tokenize() calls in server.cpp

### PR DESCRIPTION
**Pull request by m18coppola**
I assume since main only uses special tokens = true, I figure the same could be applied here. I would be open to submitting a new PR if folks believe this should be a command-line parameter.

### CODE REVIEW

**Comment by m18coppola** [comment]
PR #3734 might resolve this issue issue instead.

**Comment by goerch** [comment]
I'm not qualified to evaluate your changes, but could you please explain the effect of them?

**Comment by m18coppola** [comment]
> I'm not qualified to evaluate your changes, but could you please explain the effect of them?

Throughout `server.cpp` there are calls to a function named `llama_tokenize` which do not pass a value to the boolean parameter named [special](https://github.com/ggerganov/llama.cpp/blob/e3932593d46c30145301a13097895f9376cba509/common/common.cpp#L906). The default value is false, so server.cpp never correctly catches special tokens. I decided to override this parameter default to true in all instances.

**Comment by goerch** [comment]
> I decided to override this parameter default to true in all instances.

And this helps us how?

**Comment by m18coppola** [comment]
> > I decided to override this parameter default to true in all instances.
> 
> And this helps us how?

It doesn't. It helps me and other people who use models with special tokens via server.cpp.



> PR #3734 might resolve this issue issue instead.

I wanted to mention my pull request might be useless because the other PR may resolve it through different means.

**Comment by shibe2** [comment]
A problem with this approach is that the server can't distinguish between, for example, token im_start and literal text "<|im_start|>" (which should be encoded by multiple tokens). The correct way to include special tokens into prompts is by their numeric identifiers, as in this example: https://github.com/ggerganov/llama.cpp/discussions/3599#discussioncomment-7284649

I personally prefer not having the inferior way of handling special tokens supported by server to discourage people from using it.

**Pull request closed without merging**
