### PR TITLE
metal: bug-fix when enable ggml-alloc

### PR DESCRIPTION
**Pull request by lshzh-ww**
The first commit improves memory management when using ggml-alloc: We should only free the tensor at memory barriers. Otherwise, memory released by one tensor might be immediately reused by another tensor that runs concurrently with it.

The second commit fixes a silent return in the `allocate_node()` function.

This PR also removes workarounds needed by Falcon.

### CODE REVIEW

**Comment by lshzh-ww** [comment]
@ggerganov 
Not sure if this will also fix the "hang" behavior reported in #2678 yesterday.

**Review by slaren — APPROVED** [review]
The changes to ggml-alloc look fine.

**Comment by colinc** [comment]
This has a seg fault in ggml-alloc.c @ [line 508](https://github.com/ggerganov/llama.cpp/blob/38b16dfca6e5032e6cfb90c1653bf1ba4cf647b4/ggml-alloc.c#L508) on 70b parameter models.

This is happening right after 
`exec: RESHAPE (tmpq (reshaped)) <= tmpq`

**Comment by lshzh-ww** [comment]
@colinc Fixed with PR #2776 .

Btw, Thank you for providing that information! Save me a lot of time.

**Pull request merged**
