### PR TITLE
make scripts executable

### PR DESCRIPTION
**Pull request by cebtenzzre**
I made sure all of the python and shell scripts can be executed directly, e.g. `./convert.py`.
This required setting the modes to 0755 and fixing or adding shebang lines (`#!`) at the top.

### CODE REVIEW

**Review by jzry — COMMENTED** [review]
You just added a shebang to all the Py files? What issue was occurring without it?

**Comment by Cebtenzzre** [comment]
I added a shebang to any Python files that check for `if __name__ == '__main__'`. On Linux and macOS, this allows them to be executed as `./script.py` instead of having to spell out `python script.py` every time.

**Review by jzry — APPROVED** [review]
Looks good. Only the python shebang "#!/usr/bin/env python3" was added to several python and shell files to make executable easier to type out on Linux or MacOS.

**Review by ggerganov — APPROVED** [review]
Can merge after resolving the conflicts

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
