### PR TITLE
Fix typo layernorm_epsilon should be layer_norm_epsilon

### PR DESCRIPTION
**Pull request by stevegrubb**

### CODE REVIEW

**Comment by ggerganov** [comment]
Hm, how did this work before? Can you provide a reference for the name change?

**Comment by stevegrubb** [comment]
I have no idea. But if you grep layer_norm_epsilon, you find it used in another app. Looking at https://huggingface.co/docs/transformers/en/model_doc/persimmon, it shows the parameters for the model as layer_norm_epsilon.

**Comment by cebtenzzre** [comment]
> I have no idea. But if you grep layer_norm_epsilon, you find it used in another app

This script is specifically for converting the official .tar (non-HuggingFace) checkpoint of Persimmon from https://github.com/persimmon-ai-labs/adept-inference. That documentation is for the HuggingFace version, which is converted with `convert-hf-to-gguf.py`. Have you tested this change?

**Comment by stevegrubb** [comment]
Looks like the model has embedded in it a name of a python module that torch can't find. I used the strings command and can see "layernorm_" in various places of the model. I don't see "layer_norm_" anywhere. I guess it's not a problem after all. I'll close this PR.

**Pull request closed without merging**
