### PR TITLE
[SYCL] Add support for SYCL Nvidia target

### PR DESCRIPTION
**Pull request by AidanBeltonS**
This PR adds CMake and instructions for a SYCL Nvidia target. This is done with the `LLAMA_SYCL_BACKEND` CMake option which defaults to INTEL but can be set to NVIDIA. This approach allows us in the future to expand this for AMD targets.

This PR is dependent on #5591 as that resolves failing Nvidia `test-backend-ops` tests.

### CODE REVIEW

**Comment by AidanBeltonS** [comment]
@NeoZhangJianyu, @abhilash1910, @Alcpz, feel free to review

**Comment by AidanBeltonS** [comment]
> Just curious, does this kind of build time selection mean that it's not possible to run an Nvidia and an Intel GPU at the same time using SYCL?

It is possible to target both Nvidia and Intel GPUs with the same SYCL code, if you pass `-fsycl-targets=nvptx64-nvidia-cuda,spir64` you will generate both pieces of device code and then can execute on either GPU at runtime. The issue in the specific case for llama is that oneMKL must be built for the specific backend cuBlas backend.

**Comment by NeoZhangJianyu** [comment]
@AidanBeltonS 
What's the key benefit of this PR to user? Performance, easy usage?
I only see the benefit as you said is "one binary file support multiple GPUs (Intel, NV, ...)".

But this PR don't provide the key feature to user.

Another word, how to persuade user to use SYCL backend for NV GPU, instead of cuBlas backend?

**Comment by AidanBeltonS** [comment]
> @AidanBeltonS What's the key benefit of this PR to user? Performance, easy usage? I only see the benefit as you said is "one binary file support multiple GPUs (Intel, NV, ...)".
> 
> But this PR don't provide the key feature to user.
> 
> Another word, how to persuade user to use SYCL backend for NV GPU, instead of cuBlas backend?

oneAPI by default does support a single binary file for multiple GPUs. oneMKL is the reason we cannot do it in this case. In the long term I think we should raise this issue and fix that rather than not support NVidia GPUs. 
There are a few other reasons that we should want to support NVidia GPUs. 
1. SYCL is a portable-performant standard and we should use it as such. 
2. Supporting different vendors also makes the implementation more generic, increasing the likelihood that other SYCL implementations such as AdaptiveCpp will easily work with the code. Aiding in the development of an ecosystem rather than an exclusive backend.
3. Testing and accessibility, the more devices we support easier it is to test, implement CI, and more people can use it. I.e. gain adoption
4. Debugging, by using the same hardware between the backends we can isolate differences to the implementation removing the hardware

**Review by abhilash1910 — APPROVED** [review]
LGTM ! Lets wait for CI.
cc @ggerganov

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
