### PR TITLE
Add missing inference support for GPTNeoXForCausalLM (Pythia and GPT-NeoX base models)

### LINKED ISSUE #742: Pythia Support?
Hi, I've found out that Pythia (from EleutherAI) is better that Cerebras GPT in terms of evaluation results. Pythia is basically a LLM that based on GPT NeoX architecture but it's parameters ranging from 70M, 160M, 410M, 1B, 1.4B, 2.8B, 6.9B to 13B. Pythia itself is available in GitHub repository "EleutherAI/pythia" and Huggingface Models under the same name.

Does this project support Pythia based models? If no, any plans on supporting them afterwards? I appreciate the implementation of Pythia in this project. Thank you very much before.

### LINKED ISSUE #3293: GPT-NeoX has only minimal inference support
Steps to reproduce:
1. Download https://huggingface.co/EleutherAI/gpt-neox-20b
2. Convert the model and attempt to use it:
```
$ TMPDIR=/var/tmp ./convert-gptneox-hf-to-gguf.py gpt-neox-20b 1 --outfile gpt-neox-20b.f16.gguf
$ ./main -m gpt-neox-20b.f16.gguf
<snip>
llama_model_loader: - type  f32:  354 tensors
llama_model_loader: - type  f16:  178 tensors
error loading model: cannot find tokenizer scores in model file

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'gpt-neox-20b.f16.gguf'
main: error: unable to load model
```

### PR DESCRIPTION
**Pull request by fairydreaming**
This pull request adds missing pieces to support inference for GPT-NeoX-based models like the GPT-NeoX and the Pythia family. Fixes #742. It also adds model types for all Pythia model sizes.
Added use_par_res hparams field corresponds to the use_parallel_residual parameter from config.json.

### CODE REVIEW

**Comment by ggerganov** [comment]
Tested with https://huggingface.co/EleutherAI/pythia-1.4b/tree/main

Seems to work. PPL on wiki.test is `12.8692 +/- 0.09260`:

```bash
./perplexity -m models/pythia-1b/ggml-model-f16.gguf -f build/wikitext-2-raw/wiki.test.raw
```

I guess it's normal for 1.4B model that is 1 year old. Thanks for implementing this

**Review by ggerganov — APPROVED** [review]

**Comment by fairydreaming** [comment]
It seems that the perplexity is a little higher compared to the HF transformeres implementation because there are differences in tokenization output between llama.cpp and GPTNeoXTokenizerFast.

**Comment by ggerganov** [comment]
> Edit: It looks that there are differences in dataset files that I used for measuring perplexity for transformers and llama.cpp, will have to recheck.

Feel free to merge this when ready - I think it works

**Comment by felladrin** [comment]
Thank you for this, @fairydreaming! I have wanted it for so long!
And thanks @ggerganov for reviewing it so quickly!

**Pull request merged**
