### PR TITLE
Server: Unix Socket Support

### PR DESCRIPTION
**Pull request by adrianliechti**
The idea of this pull request is to ease integration of llama.cpp server using unix sockets instead tcp.
cpp-httplib has support for unix sockets built in: https://github.com/yhirose/cpp-httplib/pull/1346

my idea was to not add an additional parameter, but use a --host prefix: unix:// (similar to docker's client/server pattern).

a very first attempt is here, mainly to understand if this is something you could imagine in the code.

```bash
(the file should not exist before)
./server --host unix:///tmp/llama.sock --model ~/Projects/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
```

connect using socat
```bash
socat TCP-LISTEN:1234,fork UNIX-CONNECT:/tmp/llama.sock
curl http://localhost:1234/v1/model
```

connect using curl:
```bash
curl --unix-sock /tmp/llama.sock http://localhost/v1/models
```

open points:
- make path absolute?
- some error handling?

### CODE REVIEW

**Comment by FSSRepo** [comment]
This should be tested in all platforms

**Review by phymbert — CHANGES_REQUESTED** [review]
Cool, please add a simple test scenario with unix socket family.

**Comment by adrianliechti** [comment]
@FSSRepo
you are right. i tested on linux and macos, and added a ifndef for windows - similar to httplib's implementation. do you have more platforms in mind?

@phymbert
might you have some guidance here? shall i add a sample shell script or extend the python test suite?
i mainly ask because i don't want to slow down every test cycle for such a niche feature...

**Comment by phymbert** [comment]
@phymbert
> might you have some guidance here? shall i add a sample shell script or extend the python test suite?

I suggest adding a simple dedicated scenario in `server.feature` using `unix://`. I hope no changes are required since we already checked the sock family in the python glue.
Regarding the overhead of the new scenario, we are using a very small model, so adding a new scenario matters in seconds. It's OK.

**Comment by ggerganov** [comment]
Regarding server tests, @phymbert has provided quite good documentation over here: https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests

One way to improve this even further and help new contributors to implement tests, is to reference a very small PR that introduces a basic server test, without any extra changes. I'm not sure if we have one yet - if not, we can create, and we can point people to that PR as a starting point for implementing new tests.

**Pull request closed without merging**
