### PR TITLE
ggml: fix ms compiler error involving restrict keyword

### PR DESCRIPTION
**Pull request by grahameth**
Use __restrict instead of restrict on MS compiler to prevent compiler error on VS2017 and VS2019.

### CODE REVIEW

**Comment by slaren** [comment]
Can you help me understand what does this exactly enable? Isn't building with MSVC already supported? I can build without issue (well, other than the million of warnings) with VS 2019 Community.

**Comment by grahameth** [comment]
Hm, that's strange. I get this error on the first line where restrict is used:
```
ggml.h(889): error C2146: syntax error: missing ')' before identifier 'x'
```
I checked this on one computer with VS2017 and on another with VS2019

**Comment by slaren** [comment]
I am not sure in what version this was added, but MSVC [does support restrict with /std:c11](https://learn.microsoft.com/en-us/cpp/c-language/type-qualifiers?view=msvc-170#restrict).

**Comment by grahameth** [comment]
Well, I updated my MSVC 2017 and also updated the language standard in the project settings, but I still get the same error. But if I'm the only one with this issue I guess you can close it.

**Comment by grencez** [comment]
@grahameth are you using CMake? If so, check the compile_commands.json file in the build directory to find the exact build command. Maybe it's not compiling ggml.c as C11 (or newer). C++ or older C versions won't recognize the keyword.

**Pull request closed without merging**
