### PR TITLE
Add detection code for avx/avx2/etc

### PR DESCRIPTION
**Pull request by howard0su**
Add the code to check the build host to determine the right CPU feature.

This is convenient when build Windows version on the machine without AVX2.

### CODE REVIEW

**Comment by howard0su** [comment]
@sw  can you review this and merge?

**Review by ggerganov — CHANGES_REQUESTED** [review]
In addition to @sw comments:
Move these in a separate CMake script in a `cmake` folder to reduce clutter in the main CMakeLists.txt file.

See `whisper.cpp` for example: https://github.com/ggerganov/whisper.cpp/tree/master/cmake

**Comment by arikpoz** [comment]
@sw , I can confirm this works on Windows 10
I debugged a crash in quantize that was due to AVX not supported on Intel Pentium G3220 CPU. I thought of fixing the AVX flag in CMakeLists.txt, and decided to look for existing issues / PRs first. I've found this one and can confirm it works well to detect the missing AVX flag, and that quantize is now working properly

**Comment by howard0su** [comment]
I decided to do the following:
1. only do the check while LLAMA_NATIVE and MSVC both are TRUE.
2. Leave LLAMA_NATIVE as default OFF to keep the current behavior. However I think it is better to ON as most users are building for its own box.
3. Didn't introduce _PORTABLE as NATIVE is an existing variable. keep it simple.

**Comment by howard0su** [comment]
works for linux

**Review by ggerganov — CHANGES_REQUESTED** [review]
We can merge this with `LLAMA_NATIVE=OFF` by default + fix CMake style to use lowercase as everywhere else. I.e:

```cmake
IF(LLAMA_NATIVE)
    include(cmake/FindSIMD.cmake)
ENDIF()
```

becomes

```cmake
if (LLAMA_NATIVE)
    include(cmake/FindSIMD.cmake)
endif()
```

**Comment by TFWol** [comment]
@howard0su bump

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by melroy89** [comment]
Yes please. With the wrong CPU I just get: `signal: illegal instruction (core dumped)`.. Crash!

**Pull request closed without merging**
