### PR TITLE
Jeopardy Example Script

### LINKED ISSUE #1163: llama.cpp + Final Jeopardy
I was browsing reddit and saw this post:

https://www.reddit.com/r/LocalLLaMA/comments/12xkm9v/alpaca_vs_final_jeopardy/

If anyone is interested, it would be great to add such evaluation as an example to `llama.cpp` and add instructions for running it with different models: LLaMA, Alpaca, Vicuna, etc. and different quantizations.

Here is the original work by @aigoopy which can be a good starting point:

https://github.com/aigoopy/llm-jeopardy

### PR DESCRIPTION
**Pull request by CRD716**
Closes #1163 

This is pretty much just a straight port of [aigoopy/llm-jeopardy/](https://github.com/aigoopy/llm-jeopardy/)
Leaving as a draft since it's still missing a lot of features, and I will continue to work on it to make it more usable.

### CODE REVIEW

**Comment by CRD716** [comment]
All that's left is the readme.

**Comment by SlyEcho** [comment]
I don't think this is correct:
```
1,The Oscars,Who is John Williams?,Which actor Born in 1932 was the son of a percussionist in the CBS radio orchestra has been nominated for 53 Oscars?
```
The question should be in the answer format, like so:
```
1,The Oscars,Who is John Williams?,Born in 1932 & the son of a percussionist in the CBS radio orchestra, he's been nominated for 53 Oscars
```

**Comment by CRD716** [comment]
> I don't think this is correct:
> 
> ```
> 
> 1,The Oscars,Who is John Williams?,Which actor Born in 1932 was the son of a percussionist in the CBS radio orchestra has been nominated for 53 Oscars?
> 
> ```
> 
> The question should be in the answer format, like so:
> 
> ```
> 
> 1,The Oscars,Who is John Williams?,Born in 1932 & the son of a percussionist in the CBS radio orchestra, he's been nominated for 53 Oscars
> 
> ```

I haven't changed the prompt question from the original repository. The point is to see if it can bring up facts, not if it can play Jeopardy as it is on the show.

**Comment by SlyEcho** [comment]
> I haven't changed the prompt question from the original repository. The point is to see if it can bring up facts, not if it can play Jeopardy as it is on the show.

Then the answer should be "John Williams" not "Who is John Williams?"

**Comment by CRD716** [comment]
> > I haven't changed the prompt question from the original repository. The point is to see if it can bring up facts, not if it can play Jeopardy as it is on the show.
> 
> Then the answer should be "John Williams" not "Who is John Williams?"

See https://github.com/aigoopy/llm-jeopardy/blob/main/qasheet.ods and #1163, I would assume we're trying to use the same data as everyone else, so I'm not sure if this issue is supposed to be an implementation of aigoopy's jeopardy or just something with a similar style. @ggerganov which would you prefer?

**Comment by SlyEcho** [comment]
The columns "Original Answer" and "Original Correct Question" in the spreadsheet is the data they used (what is the source? maybe https://j-archive.com/). Then they created "Model Prompt" where it has been turned into a question, and for all the models, they are also answering in an answer format, [explained in Reddit](https://www.reddit.com/r/LocalLLaMA/comments/12xkm9v/comment/jhkn92s/).

But anyway, I think this test should be either question-answer or jeopardy style answer-question, but not a mix.

If we don't change the data from the original, we could possibly evaluate a much larger dataset without having to manually edit questions.

**Review by ggerganov — APPROVED** [review]
I agree with @SlyEcho - we should keep either format and not mix it like they've done in the reference repo.

For now, we can merge it like this so we have the evaluation framework available, and later we can update the questions / answers.

**Pull request merged**
