### PR TITLE
Merge tokenizer fixes

### PR DESCRIPTION
**Pull request by goerch**
Miigrated PR #2315 to `gguf`

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Review by klosax — APPROVED** [review]

**Comment by klosax** [comment]
Maybe better to merge when @monatis have finished refactor llama.cpp so it can load gguf.

**Comment by goerch** [comment]
> Maybe better to merge when @monatis have finished refactor llama.cpp so it can load gguf.

Yes, I've been thinking about this, too. One more question: where should we discuss the necessary improvements for this patch in the context of the `gguf` specification , for example

```
static std::string llama_vocab_type(const llama_vocab& vocab) {
    return vocab.token_to_id.size() == 32000 ? "spm": "bpe";
}

static bool llama_is_normal_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return token >= 259;
    else if(llama_vocab_type(vocab) == "bpe")
        return token >= 95;
    else
        return false;
}

static bool llama_is_unknown_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return token == 0;
    else
        // TODO: improve?
        return false;
}

static bool llama_is_control_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return token == 1 || token == 2;
    else
        // TODO: improve?
        return false;
}

static bool llama_is_bos_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return token == 1;
    else
        // TODO: improve?
        return false;
}

static bool llama_is_eos_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return token == 2;
    else
        // TODO: improve?
        return false;
}

static bool llama_is_user_defined_token(const llama_vocab& vocab, llama_token token) {
    // TODO: improve?
    return false;
}

static bool llama_is_unused_token(const llama_vocab& vocab, llama_token token) {
    // TODO: improve?
    return false;
}

static bool llama_is_byte_token(const llama_vocab& vocab, llama_token token) {
    if(llama_vocab_type(vocab) == "spm")
        return 3 <= token && token < 259;
    else if(llama_vocab_type(vocab) == "bpe")
        return 1 <= token && token < 95;
    else
        return false;
}

static uint8_t llama_byte_to_char(const llama_vocab& vocab, uint8_t byte) {
    if(llama_vocab_type(vocab) == "spm")
        return byte + 3;
    else if(llama_vocab_type(vocab) == "bpe")
        return byte + 32;
    else
        return false;
}
```

I tested with `LLaMa` and `Aquila` for now but I'm pretty sure all of these magical constants / functions need to be parameterizable.

**Comment by klosax** [comment]
I guess we could discuss it here and request needed changes to the gguf-spec in PR https://github.com/ggerganov/ggml/pull/302.

In gguf everything BPE (gpt2) should be handled by the [gpt2bpe](https://github.com/ggerganov/llama.cpp/blob/gguf/cmpnct_gpt2bpe.hpp) tokenizer already added, so i think this PR merge should be for fixing the llama tokenizer only. The plan is to allow any supported arhcitecture (llama / gptneox / mpt / falcon ..) to be used with any supported tokenizer (llama spm / gpt2 bpe ..)

The standard special tokens like bos / eos / unknown .. have its own mapping in gguf.  The "added tokens" also have its own key (an array of strings). See https://github.com/philpax/ggml/blob/gguf-spec/docs/gguf.md#tokenizer.

I dont know much about the inner workings of the tokenizers, especially not the llama sentencepiece. We have gguf keys for vocab, scores, added tokens and a map of standard special tokens. Is there anything else we need to get the llama tokenizer to work accurately?

The gpt2bpe tokenizer have implementations of Trie and Unicode handling that possible could be reused for the llama tokenizer.

**Comment by goerch** [comment]
> I guess we could discuss it here and request needed changes to the gguf-spec in PR [ggerganov/ggml#302](https://github.com/ggerganov/ggml/pull/302).

Agreed.

> In gguf everything BPE (gpt2) should be handled by the [gpt2bpe](https://github.com/ggerganov/llama.cpp/blob/gguf/cmpnct_gpt2bpe.hpp) tokenizer already added, so i think this PR merge should be for fixing the llama tokenizer only. The plan is to allow any supported arhcitecture (llama / gptneox / mpt / falcon ..) to be used with any supported tokenizer (llama spm / gpt2 bpe ..)

Great. So somebody is looking into [this](https://github.com/ggerganov/llama.cpp/pull/2420) already?

> I dont know much about the inner workings of the tokenizers, especially not the llama sentencepiece. We have gguf keys for vocab, scores, added tokens and a map of standard special tokens. Is there anything else we need to get the llama tokenizer to work accurately?

Yes, what I'm mostly missing is  [token type classification](https://github.com/ggerganov/ggml/pull/302#issuecomment-1666948690).

> The gpt2bpe tokenizer have implementations of Trie and Unicode handling that possible could be reused for the llama tokenizer.

[Related discussion](https://github.com/ggerganov/llama.cpp/pull/1931#issuecomment-1669396846).

**Comment by klosax** [comment]
> So somebody is looking into [this](https://github.com/ggerganov/llama.cpp/pull/2420) already?

It was a temporary solution to support the gpt2 bpe tokenizer  with llama architecture. I guess it works as good it can until gguf is released, which also would make use of the merges data that gpt2 bpe needs for accurate tokenization.

> what I'm mostly missing is [token type classification](https://github.com/ggerganov/ggml/pull/302#issuecomment-1666948690).

If this is needed for accurate tokenization we should have it added to the gguf spec.

**Comment by goerch** [comment]
> > what I'm mostly missing is [token type classification](https://github.com/ggerganov/ggml/pull/302#issuecomment-1666948690).
> 
> If this is needed for accurate tokenization we should have it added to the gguf spec.

Just to be clear: that is what I think,

**Review by monatis — APPROVED** [review]
Let's merge this and continue into main GGUF branch, we may request updates to the GGUF specs based on what we need.

**Comment by goerch** [comment]
Just adapted `convert-new.py` and retested with the latest commits on `gguf`. Should I commit that change, too?

> Let's merge this and continue into main GGUF branch, we may request updates to the GGUF specs based on what we need.

@klosax did [this](https://github.com/ggerganov/ggml/pull/302#issuecomment-1670269195) already.

**Comment by ggerganov** [comment]
> Just adapted convert-new.py locally and retested with the latest commits on gguf. Should I commit that change, too?

Would be great if you have a working version of the convert script that I can use with the vanilla LLaMA models

**Comment by goerch** [comment]
Just committed a [PR](https://github.com/ggerganov/llama.cpp/pull/2614) with changes in convert-new.py.

**Comment by ggerganov** [comment]
Yes, that might be the case. Here is some debug info:

```gdb
$ ▶ lldb ./bin/test-tokenizer-1 ../models/ggml-vocab-aquila.bin
(lldb) target create "./bin/test-tokenizer-1"
Current executable set to '/Users/ggerganov/development/github/llama.cpp/build-debug/bin/test-tokenizer-1' (arm64).
(lldb) settings set -- target.run-args  "../models/ggml-vocab-aquila.bin"
(lldb) r
Process 49555 launched: '/Users/ggerganov/development/github/llama.cpp/build-debug/bin/test-tokenizer-1' (arm64)
main : reading vocab from: '../models/ggml-vocab-aquila.bin'
llama.cpp: loading model from ../models/ggml-vocab-aquila.bin
main : info: token 0 is string  and bpe returns tokens <|endoftext|>
main : info: token 100000 is string <|startofpiece|> and bpe returns tokens <|startofpiece|>
main : info: token 100001 is string <|endofpiece|> and bpe returns tokens <|endofpiece|>
main : info: token 100002 is string <|LDWANG|> and bpe returns tokens <|LDWANG|>
main : info: token 100003 is string [MASK] and bpe returns tokens [MASK]
main : info: token 100004 is string [gMASK] and bpe returns tokens [gMASK]
main : info: token 100005 is string [sMASK] and bpe returns tokens [sMASK]
main : info: token 100006 is string [CLS] and bpe returns tokens [CLS]
main : info: token 100007 is string </s> and bpe returns tokens </s>
libc++abi: terminating due to uncaught exception of type std::range_error: wstring_convert: to_bytes error
Process 49555 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x000000018b3d8764 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x18b3d8764 <+8>:  b.lo   0x18b3d8784               ; <+40>
    0x18b3d8768 <+12>: pacibsp 
    0x18b3d876c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x18b3d8770 <+20>: mov    x29, sp
Target 0: (test-tokenizer-1) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x000000018b3d8764 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018b40fc28 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x000000018b31dae8 libsystem_c.dylib`abort + 180
    frame #3: 0x000000018b3c8b84 libc++abi.dylib`abort_message + 132
    frame #4: 0x000000018b3b83b4 libc++abi.dylib`demangling_terminate_handler() + 320
    frame #5: 0x000000018b08f03c libobjc.A.dylib`_objc_terminate() + 160
    frame #6: 0x000000018b3c7f48 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x000000018b3cad34 libc++abi.dylib`__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 36
    frame #8: 0x000000018b3cace0 libc++abi.dylib`__cxa_throw + 140
    frame #9: 0x000000010000594c test-tokenizer-1`std::__1::__throw_range_error[abi:v15006](__msg="wstring_convert: to_bytes error") at stdexcept:279:5
    frame #10: 0x0000000100005490 test-tokenizer-1`std::__1::wstring_convert<std::__1::codecvt_utf8<wchar_t, 1114111ul, (std::__1::codecvt_mode)0>, wchar_t, std::__1::allocator<wchar_t>, std::__1::allocator<char> >::to_bytes(this=0x000000016fdfef58, __frm=L"\xed\xa0\x80", __frm_end=L"") at locale:3884:9
    frame #11: 0x0000000100003d3c test-tokenizer-1`std::__1::wstring_convert<std::__1::codecvt_utf8<wchar_t, 1114111ul, (std::__1::codecvt_mode)0>, wchar_t, std::__1::allocator<wchar_t>, std::__1::allocator<char> >::to_bytes[abi:v15006](this=0x000000016fdfef58, __wstr=L"\xed\xa0\x80") at locale:3679:17
    frame #12: 0x00000001000036d4 test-tokenizer-1`main(argc=2, argv=0x000000016fdff2c8) at test-tokenizer-1.cpp:109:37
    frame #13: 0x000000018b0b7f28 dyld`start + 2236
(lldb) frame select 12
frame #12: 0x00000001000036d4 test-tokenizer-1`main(argc=2, argv=0x000000016fdff2c8) at test-tokenizer-1.cpp:109:37
   106 	   std::wstring_convert<typename std::codecvt_utf8<wchar_t>, wchar_t> converter;
   107 	   for (wchar_t ch = 0x0000; ch < 0xffff; ++ch) {
   108 	       std::wstring wstr(1, ch);
-> 109 	       std::string str = converter.to_bytes(wstr);
   110 	       std::vector<llama_token> tokens = llama_tokenize(ctx, escape_whitespace(str).c_str(), false);
   111 	       if (tokens.size() == 1) {
   112 	           fprintf(stderr, "%s : info: %s tokenized to %d \n",
(lldb) print ch
(wchar_t) $0 = L'\xed\xa0\x80'
(lldb) 
```

**Comment by goerch** [comment]
From [here](https://unicode-org.github.io/icu/userguide/strings/#separate-type-for-single-code-points):

> A Unicode code point is an integer with a value from 0 to 0x10FFFF.

**Comment by klosax** [comment]
Aquila uses the gpt2 tokenizer  / vocab, this should be handled by the new working gpt2 tokenizer. I dont think we need to merge any of the gpt2 bpe compatibility stuff that was added with Aquila.

**Comment by goerch** [comment]
`wchar_t` has a different definition on our platforms it seems. Is the following more specific (this works on Windows)?

```
    std::wstring_convert<typename std::codecvt_utf8<char16_t>, char16_t> converter;
    for (char16_t ch = 0x0000; ch < 0xffff; ++ch) {
        std::u16string u16str(1, ch);
        std::string str = converter.to_bytes(u16str);
        std::vector<llama_token> tokens = llama_tokenize(ctx, escape_whitespace(str).c_str(), false);
        if (tokens.size() == 1) {
            fprintf(stderr, "%s : info: %s tokenized to %d \n", 
                __func__, str.c_str(), tokens[0]);
        }
    }
```

**Comment by goerch** [comment]
> Aquila uses the gpt2 tokenizer / vocab, this should be handled by the new working gpt2 tokenizer. I dont think we need to merge any of the gpt2 bpe compatibility stuff that was added with Aquila.

I just used Aquila as a second test case. Do you have good alternatives to test more `sentencepiece`-based tokenizers?

**Comment by klosax** [comment]
> Do you have good alternatives to test more `sentencepiece`-based tokenizers?

I guess you could also test with the OpenLLaMA model:
https://huggingface.co/openlm-research/open_llama_3b_v2

This chinese model should also be llama and use the sentencepiece tokenizer:
https://huggingface.co/baichuan-inc/Baichuan-7B

**Pull request merged**
