### PR TITLE
vulkan : do not use tensor->extra

### PR DESCRIPTION
**Pull request by rgerganov**
This patch allows using the Vulkan backend with the RPC backend as tensor->extra is no longer used.

Ref: #8536

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [x] Medium
  - [ ] High

### CODE REVIEW

**Comment by rgerganov** [comment]
I have tested this by verifying that `llama-cli` generates the same output with a fixed seed on `master` and this branch. Backend ops tests also pass.

If you are OK with the proposed refactoring, I will also update the code surrounded by `GGML_VULKAN_CHECK_RESULTS`

**Comment by 0cc4m** [comment]
@ggerganov @rgerganov Apologies for the delay, I'm inbetween jobs and moving to a new city, so my time is rather limited. I'll try to find time to take care of the PRs waiting for my review this week.

**Comment by ggerganov** [comment]
Thanks, no worries.

**Review by 0cc4m — COMMENTED** [review]
This is nice, thank you. It cleans up some of the leftover code from previous iterations. It worked in my tests.

The only issue is that it breaks the `GGML_VULKAN_CHECK_RESULTS` mode. Can you take a look at that or would you like me to?

**Comment by 0cc4m** [comment]
@rgerganov I fixed the issue in https://github.com/rgerganov/llama.cpp/pull/2
Please take a look.

**Comment by rgerganov** [comment]
> @rgerganov I fixed the issue in [rgerganov#2](https://github.com/rgerganov/llama.cpp/pull/2) Please take a look.

Sorry for the delay, somehow I missed the notifications for this PR. Changes look good and merged.

**Pull request merged**
