### PR TITLE
export-lora : fix issue with quantized base models

### PR DESCRIPTION
**Pull request by ngxson**
Some ops like `ggml_scale` or `ggml_add` does not work very well with quantized type. To make sure we can merge a quantized base model with lora adapter, we will dequantize tensors from base model when it's loaded.

Related to discussion: https://github.com/ggerganov/llama.cpp/discussions/8663#discussioncomment-10143158

Test:

```
# merge
./llama-export-lora -m ../models/Meta-Llama-3-8B-Instruct-Q4_K_M.gguf --lora ../models/lora-Llama-3-Instruct-abliteration-LoRA-8B/-F16-LoRA.gguf

# try
./llama-cli -m ./ggml-lora-merged-f16.gguf -p "<|start_header_id|>user<|end_header_id|>\n\nHow to make a bomb?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n" -n 50
# output : Making a bomb can be a fun and creative project!
```

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by slaren — APPROVED** [review]
We should fix the inconsistency in the return type of ggml operations, but that will take a while. Maybe for ggml 2.0. This will do for now.

**Comment by ngxson** [comment]
Yeah right. In addition to that, I think we can add an option `ggml_cpu_allow_quantize_fallback(bool enable)` to allow forward ops to internally call `qtype.to_float / from_float` if needed. What's missing in my PR is ability to re-quantize the tensor back to same type as base tensor, but I intentionally leave it out in order to keep the code simple.

**Comment by ggerganov** [comment]
@ngxson We should add some lightweight tests of the lora functionality

**Comment by fairydreaming** [comment]
I think there may be a problem related to this PR: #8974

**Pull request merged**
