### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by awhill19**
#Change:

Use the environment variable `CUDA_NATIVE_ARCH` if present to set NVCC arch. Otherwise, use `native` as currently.

#Reasoning:

Running `make LLAMA_CUBLAS=1` errors with `nvcc fatal   : Value 'native' is not defined for option 'gpu-architecture'
make: *** [Makefile:249: ggml-cuda.o] Error 1`

Making the `-arch` flag to nvcc configurable allows a specific arch to be chosen, which solves this problem.

### CODE REVIEW

**Comment by slaren** [comment]
Doesn't this do essentially the same as `CUDA_DOCKER_ARCH`?

**Comment by awhill19** [comment]
> Doesn't this do essentially the same as `CUDA_DOCKER_ARCH`?

It does, but `CUDA_DOCKER_ARCH` also passes `-Wno-deprecated-gpu-targets` which nvcc seems to have trouble with in some environments. It also just seemed a bit non-intuitive for me to need Docker related environment variables for a simple native installation.

Perhaps just testing whether `-Wno-deprecated-gpu-targets` is necessary (or warrants a separate arg) would be more appropriate.

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by cebtenzzre** [comment]
With this change, CUDA_DOCKER_ARCH now implies `-arch=native`. I assume that wasn't intended.

**Comment by ggerganov** [comment]
Hm, in what scenario this is wrong?

**Comment by cebtenzzre** [comment]
> Hm, in what scenario this is wrong?

Before this PR, you could use e.g. CUDA_DOCKER_ARCH=sm_52 to set the NVCC arch, which would evaluate to:
```
-Wno-deprecated-gpu-targets -arch=sm_52
```
After this PR, `make LLAMA_CUBLAS=1 CUDA_DOCKER_ARCH=sm_52 ggml-cuda.o` shows this in the nvcc command:
```
-Wno-deprecated-gpu-targets -arch=sm_52 -arch=native
```
I think the last -arch option will take precedence.

**Pull request merged**
