### PR TITLE
cmake: make sanitizers linking

### PR DESCRIPTION
**Pull request by Green-Sky**
clearly no one tested this.

### CODE REVIEW

**Comment by Green-Sky** [comment]
@ggerganov :smirk: enabling asan and detecting memory leaks

**Comment by ggerganov** [comment]
Maybe add separate sanitize CI like in `whisper.cpp`:

https://github.com/ggerganov/whisper.cpp/blob/8e361d90d7948de3ecae73e10878040044836800/.github/workflows/build.yml#L92-L116

**Comment by anzz1** [comment]
@Green-Sky should i port these changes to the format in #497

**Comment by Green-Sky** [comment]
@anzz1 sure, go ahead. will have some time later to check.

**Comment by anzz1** [comment]
> @anzz1 sure, go ahead. will have some time later to check.

Done.

**Comment by Green-Sky** [comment]
merge into https://github.com/ggerganov/llama.cpp/pull/497

**Pull request closed without merging**
