### PR TITLE
add basic tensor data validation function

### LINKED ISSUE #6841: Is it normal that ROCm+HIPBLAS produces different results than on CPU or breaks completely?
Hello. I did some perplexity tests while investigating issue with Llama-3. Initially the issue was that Llama-3 base 70b model outputs garbage with small quants with iMatrix. Can't find any information regarding that ROCm possibly causes corruption.

### GPU test (RX 7600 + RX 7600 XT)
https://huggingface.co/mradermacher/Meta-Llama-3-70B-i1-GGUF/tree/main
Meta-Llama-3-70B.i1-Q2_K.gguf prints [1]-nan,[2]-nan,[3]-nan,[4]-nan with -ngl 30 or 0 (prints garbage unless -ngl 0)
https://huggingface.co/mradermacher/Meta-Llama-3-70B-GGUF/tree/main
Meta-Llama-3-70B.Q2_K.gguf - seems OK, [1]4.1839,[2]4.7300,[3]4.2751,[4]4.6444,[5]4.6942,[6]5.0426,[7]5.1405,[8]5.4747
Final estimate: PPL = 5.9315 +/- 0.03553

### Pure CPU test
Meta-Llama-3-70B.i1-Q2_K.gguf with pure CPU 'perplexity' build (146 seconds per 512 tokens - ETA 26 hours 55.67 minutes)
[1]6.3962,[2]7.1886,[3]6.9886,[4]7.3853,[5]7.8924,[6]8.2982,[7]8.8956,[8]9.3799, (can't wait for many hours, stopped)
Meta-Llama-3-70B.Q2_K.gguf (static Q2_K):
[1]4.1675,[2]4.6952,[3]4.2374,[4]4.6452,[5]4.6677,[6]5.0459,[7]5.1258,[8]5.4649,^C
It's slightly better than on ROCm but the difference is very small.

I also found strange holes in the imatrix.dat that was used:
Screenshot from 2024-04-23 13-34-09
But the author seems uninterested in discussing that.

### PR DESCRIPTION
**Pull request by slaren**
Adds `ggml_validate_row_data` to validate tensor data, and adds this validation to llama.cpp during model loading. For floating point tensors it checks all the data, for quant types it checks the scales only. The validation consists of checking for `nan` and `inf` values in the tensors.

Should help detect issues with models such as reported in #6841.

Hopefully it won't increase load time too much so that it can be left enabled permanently, but more testing is necessary.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by Nekotekina** [comment]
Hmm, quantize won't validate tensors which are being written?

**Comment by slaren** [comment]
This should be a lot faster now in most cases. There is an NEON implementation for FP16 validation, and the model validation is multithreaded with `std::async` when possible. Still, doing nothing is a lot faster than doing anything at all, so with mmap for CPU and Metal it can still double the load times.

If this proves to be useful, it may be a good to enable it by default in the server, since it is not a process that is meant to be restarted very often, the increase in load time should be less important.

**Review by ggerganov — APPROVED** [review]
The 70B F16 case is now down to 20s (from 50s)

Yes, we can add it to server. Also, let's note the `ggml-ci` time increase since we do a lot of quantizations there and it might lead to significant increase. If so, we might want to add an option to disable during `quantize` in the CI, since the model data is not changing there. But only if the time increase is significant

**Comment by slaren** [comment]
It doesn't seem to affect the CI times significantly, in fact the cuda-v100 time was a bit lower than the latest time on master, so I think that it is within the normal variation between runs.

**Pull request merged**
