### PR TITLE
doc: fix outdated default value of batch size

### PR DESCRIPTION
**Pull request by Sunt-ing**
Discussion: https://github.com/ggerganov/llama.cpp/discussions/6328#discussioncomment-8920378

### CODE REVIEW

**Comment by Sunt-ing** [comment]
@phymbert Would you please take a look? Thanks!

**Review by phymbert — APPROVED** [review]
Thanks for your first-time contribution. If you wish to continue to help by picking up issues labeled `good first issue`, this is welcomed.

**Comment by phymbert** [comment]
It would be nice to also document `--ubatch-size` here.

**Comment by Sunt-ing** [comment]
Added. Thanks for your help!

**Pull request merged**
