### PR TITLE
Fix gguf-convert-endian script

### PR DESCRIPTION
**Pull request by monatis**
Reported in [this issue comment](https://github.com/ggerganov/llama.cpp/pull/3981#issuecomment-1806756973)

### CODE REVIEW

**Comment by monatis** [comment]
cc @chenqiny

**Comment by chenqiny** [comment]
It's resolved. Thank you.

**Review by Galunid — APPROVED** [review]

**Review by KerfuffleV2 — APPROVED** [review]
Oops, thanks for fixing that! I guess I messed it up when refactored those scripts to work with the Poetry package stuff.

All those linters and type checkers can catch the tiniest discrepancy in whitespace or whatever but can't warn me about something that simple and dumb? :(

**Comment by cebtenzzre** [comment]
> All those linters and type checkers can catch the tiniest discrepancy in whitespace or whatever but can't warn me about something that simple and dumb? :(

mypy and pytype aren't so good with unbound variables, but pyright can catch them (and there may be a flake8 plugin that can do it to). It's not my favorite because it has a lot of false positives.
```
/home/jared/src/forks/llama.cpp/gguf-py/scripts/gguf-convert-endian.py
  /home/jared/src/forks/llama.cpp/gguf-py/scripts/gguf-convert-endian.py:34:23 - warning: "order" is possibly unbound (reportUnboundVariable)
  /home/jared/src/forks/llama.cpp/gguf-py/scripts/gguf-convert-endian.py:35:36 - warning: "order" is possibly unbound (reportUnboundVariable)
  /home/jared/src/forks/llama.cpp/gguf-py/scripts/gguf-convert-endian.py:45:67 - warning: "order" is possibly unbound (reportUnboundVariable)
  /home/jared/src/forks/llama.cpp/gguf-py/scripts/gguf-convert-endian.py:50:8 - warning: "order" is possibly unbound (reportUnboundVariable)
0 errors, 4 warnings, 0 informations
```

**Comment by chenqiny** [comment]
I tested it with new generated llama2 7b model with convert.py and llama2 7b converted from convert script.

**Comment by KerfuffleV2** [comment]
Are you letting the suspense build before you tell us whether the result of testing was success or failure? :) I'm on the edge of my seat! 或者说我都迫不及待啦！

**Comment by chenqiny** [comment]
> Are you letting the suspense build before you tell us whether the result of testing was success or failure? :) I'm on the edge of my seat! 或者说我都迫不及待啦！

I just built it with the pull request.

**Pull request merged**
