### PR TITLE
Enhancements for Readability, Const Safety, and Memory Management

### PR DESCRIPTION
**Pull request by mendax0110**
Use  logical NOT (!) operator for clarity.

Added the const modifier to relevant methods, promoting code readability and reinforcing non-modifiability.

Added the static modifier in use_buf and get_buf_max_mem methods of llama_context, this emphasizes class-level memory management, leading to cleaner code and more efficient memory use.

### CODE REVIEW

**Comment by Cebtenzzre** [comment]
22 commits is a lot for such small changes... I feel like it would make more sense to squash this into 1-3 commits, but maybe I'm just nitpicking.

**Comment by Cebtenzzre** [comment]
Regarding the build failure: It looks like llama_context::use_buf cannot be static if LLAMA_USE_SCRATCH is defined.

**Comment by mendax0110** [comment]
> 22 commits is a lot for such small changes... I feel like it would make more sense to squash this into 1-3 commits, but maybe I'm just nitpicking.

Thanks I will fix the bug and fix the commits thing.

**Comment by Cebtenzzre** [comment]
@mendax0110 You can just force-push to your fork's master branch, there's no need to close this PR.

**Pull request closed without merging**
