### PR TITLE
IQ3_S improvements

### PR DESCRIPTION
**Pull request by ikawrakow**
This PR makes some improvements to the `IQ3_S` quants. Nothing earth shuttering, but I think still worth having. We get
* Lower quantization error
* Some speedup on all platforms
* About 40% decrease in quantization time

This table shows a comparison between the quantization error on master and this PR. The quantization error is defined as `PPL(IQ3_S)/PPL(fp16) - 1`. The context is 4096 for LLaMA-v2 and 2048 for LLaMA-v1

| Model |  Master |  PR |  Reduction |
|---:|---:|---:|---:|
|LLaMA-v1-7B   | 4.53% | 4.01% | 0.885 |
|LLaMA-v2-7B   | 4.66% | 4.03% | 0.865 |
|Mistral-7B         | 3.08% | 3.13% | 1.016 |
|LLaMA-v1-13B | 3.34% | 2.99% | 0.895 |
|LLaMA-v2-13B | 3.34% | 3.00% | 0.898 |

This table shows a comparison in inference speed on the platforms where I can test:
* CUDA on RTX-4080
* AVX2 on Ryzen 7950X
* ARM_NEON on M2 Max
* Metal on 30-core M2 Max GPU

| model          | backend    |    threads | test       |     t/s (Master) |         t/s (PR) |   Speedup |
| ---------------| ---------- | ---------: | ---------- | ---------------: | ---------------: | --------: |
| llama 7B IQ3_S | CUDA       |          1 | pp 512     |    5699.0 ± 16.9 |    5722.9 ± 18.9 |  1.004    |   
| llama 7B IQ3_S | CUDA       |          1 | tg 128     |    151.53 ± 0.13 |    152.68 ± 0.16 |  1.008    |   
| llama 7B IQ3_S | AVX2       |         16 | pp 512     |     23.38 ± 0.35 |     28.55 ± 0.15 |  1.221    |   
| llama 7B IQ3_S | AVX2       |         16 | tg 128     |     15.98 ± 0.27 |     16.19 ± 0.22 |  1.013    |   
| llama 7B IQ3_S | AVX2       |          8 | tg 128     |     11.71 ± 0.05 |     13.86 ± 0.03 |  1.184    |   
| llama 7B IQ3_S | Metal      |          4 | pp 512     |    457.99 ± 0.29 |    457.75 ± 0.26 |  1.000    |   
| llama 7B IQ3_S | Metal      |          4 | tg 128     |     49.69 ± 0.01 |     50.35 ± 0.01 |  1.013    |   
| llama 7B IQ3_S | ARM_NEON   |          8 | tg 128     |     10.01 ± 0.01 |     11.00 ± 0.03 |  1.100    |   
| llama 7B IQ3_S | ARM_NEON   |          4 | tg 128     |      5.18 ± 0.00 |      5.73 ± 0.00 |  1.106    | 

ARM performance is still pathetic. Metal performance is acceptable (0.95X for TG and 1.02X for PP compared to `Q3_K_S`). AVX2 Performance is acceptable for TG (0.88X compared to `Q3_K_S`) but bad for PP (0.38X of `Q3_K_S`. I guess, for PP the loading of the lattice points from the lookup table becomes I/O bound and severely limits performance). CUDA performance is excellent (1.04X/1.015X for TG/PP compared to `Q3_K_S`, 1.18X compared to `Q4_0` TG). 

The main reason this PR exists is @PeterReid's suggestion to replace the lookup table with a multiplier that generates the codebook. While working on that I noticed that there is still room for improvement for the lookup based `IQ3_S`, and this PR is the result. I did find a few multipliers that work quite OK (quantization error about 1-1.5% higher than lookup), but there was no performance improvement on CUDA and TG on AVX2, so I decided to not further pursue this idea.

### CODE REVIEW

**Comment by Nindaleth** [comment]
> I decided to not further pursue this idea

How did the actually slow archs do with the other approach? I be misunderstanding the description, but it sounds to me as AVX2 PP and ARM PP/TG performance is bad with the lookup approach, but you decided to not look into the multipliers any further because the already good CUDA PP/TG and AVX2 TG performance with lookup didn't get any better with multipliers...?

**Comment by sorasoras** [comment]
> > I decided to not further pursue this idea
> 
> How did the actually slow archs do with the other approach? I be misunderstanding the description, but it sounds to me as AVX2 PP and ARM PP/TG performance is bad with the lookup approach, but you decided to not look into the multipliers any further because the already good CUDA PP/TG and AVX2 TG performance with lookup didn't get any better with multipliers...?

because the quantization error about 1-1.5% higher than lookup

**Comment by Artefact2** [comment]
I notice you change `dequantize_row_iq3_s`, are older IQ3 GGUFs still useable or is this breaking backward compatibility?

**Comment by ikawrakow** [comment]
> I notice you change the grid in `dequantize_row_iq3_s`, are older IQ3 GGUFs still useable or is this breaking backward compatibility?

Sorry, forgot to mention. Yes, previous quantization is still usable. You can re0quantize to take advantage of the slight PPL improvement.

**Comment by Nindaleth** [comment]
> because the quantization error about 1-1.5% higher than lookup

As in one percentage point higher, not 1.01x higher? I see, that makes sense, thanks for pointing that out.

**Comment by ikawrakow** [comment]
If the quantization error is 3% with lookup, it will be in the 4 to 4.5% range with the best multiplier I was able to find. Example: PPL = 5 for `fp16`, PPL = 5.15 with lookup, PPL = 5.20-5.23 with multiplier.

**Review by ggerganov — APPROVED** [review]

**Comment by JianbangZ** [comment]
@ikawrakow I was testing some iq3_m quant today I found the PPL was not as good as before. After digging into your recent PRs, I think this grid change to iq3_s causes a PPL increase for my model as iq3_m uses a log of iq3_s. (i use qwen1.5-7b-chat for testing)

So seems this grid value is pretty important to the final perforhamce for IQ quantization method, and I am seeing opposite results compared to yours. 

Would you mind elobrating how you choose gird values?

**Comment by ikawrakow** [comment]
@JianbangZ Sorry to hear that this PR is increasing PPL for your model. It did improve PPL on 8 of the 9 models tested, and it was about the same for one.

Concerning grid points: during quantization the quants can take one in 8 values in `{1, 3, 5, 7, 9, 11, 13, 15}`. This has not changed (and neither has the codebook that selects 512 out of the 4096 possible values for a group of 4 quants). During inference, prior to this PR the values used were `{4, 12, 20, 28, 36, 44, 52, 62}` with an additional factor of 1/4 applied, so effectively `{1, 3, 5, 7, 9, 11, 13, 15.5}`. These are encoded in `iq3xs_grid` (which became `iq3s_grid` in this PR), where each `uint32_t` entry contains 4 quants. I had found empirically that using a slightly larger value for the highest quantization value  improves PPL. This PR changed the quant values back to `{1, 3, 5, 7, 9, 11, 13, 15}`, but added a fudge factor of `1.033` to the super-block scale. This change did improve PPL on 8 out of 9 tested models. The second change that may affect your result is a reduction in the scale search range during quantization. Before this PR, the scale search range was `-15...15`, and became `-9...9` in this PR. This did not have any effect on the PPL of the 9 tested models, but reduced quantization time by about ~40%. The decision to make this change was based on the feedback from many that `IQ` quantization takes too a long time. Checking if this search range reduction has negatively impacted your model is very easy to do: just go to [this line](https://github.com/ggerganov/llama.cpp/blob/306d34be7ad19e768975409fc80791a274ea0230/ggml-quants.c#L11257) in the source code, change to `for (int is = -15; is <= 15; ++is) {`, recompile, re-quantize, and see what happens.

**Comment by JianbangZ** [comment]
> @JianbangZ Sorry to hear that this PR is increasing PPL for your model. It did improve PPL on 8 of the 9 models tested, and it was about the same for one.
> 
> Concerning grid points: during quantization the quants can take one in 8 values in `{1, 3, 5, 7, 9, 11, 13, 15}`. This has not changed (and neither has the codebook that selects 512 out of the 4096 possible values for a group of 4 quants). During inference, prior to this PR the values used were `{4, 12, 20, 28, 36, 44, 52, 62}` with an additional factor of 1/4 applied, so effectively `{1, 3, 5, 7, 9, 11, 13, 15.5}`. These are encoded in `iq3xs_grid` (which became `iq3s_grid` in this PR), where each `uint32_t` entry contains 4 quants. I had found empirically that using a slightly larger value for the highest quantization value improves PPL. This PR changed the quant values back to `{1, 3, 5, 7, 9, 11, 13, 15}`, but added a fudge factor of `1.033` to the super-block scale. This change did improve PPL on 8 out of 9 tested models. The second change that may affect your result is a reduction in the scale search range during quantization. Before this PR, the scale search range was `-15...15`, and became `-9...9` in this PR. This did not have any effect on the PPL of the 9 tested models, but reduced quantization time by about ~40%. The decision to make this change was based on the feedback from many that `IQ` quantization takes too a long time. Checking if this search range reduction has negatively impacted your model is very easy to do: just go to [this line](https://github.com/ggerganov/llama.cpp/blob/306d34be7ad19e768975409fc80791a274ea0230/ggml-quants.c#L11257) in the source code, change to `for (int is = -15; is <= 15; ++is) {`, recompile, re-quantize, and see what happens.

Thank you. I tried. I revert the serach range to 15 and PPL improved bit, though not to the previous level. Here is my data
before this PR: PPL=10.5344, Hellaswag=75.45
w/ this PR:        PPL=10.8045, Hellaswag=74.65
w/ this PR & back to {-15, 15} PPL=10.7645, Hellaswag 75.45

**Comment by JianbangZ** [comment]
> > I notice you change the grid in `dequantize_row_iq3_s`, are older IQ3 GGUFs still useable or is this breaking backward compatibility?
> 
> Sorry, forgot to mention. Yes, previous quantization is still usable. You can re0quantize to take advantage of the slight PPL improvement.

Since grid changed, and dequant seems use the new grid value, how was the the old grid quant model compatiable?

**Comment by Nexesenex** [comment]
@ikawrakow Could you make a different GGML_type of the old IQ3_S, so we can quantize with it?
I excluded this one from my quant cocktails because it's behaving very poorly on Miqu 70b : the IQ2_S and IQ2_M at least are bungled by its presence by a 10% perplexity jump compared to expectations, and I never observed any PPL gain with it anyway. When I change the tensors which are in IQ3_S toward IQ3_XXS, I revert to expected results in line with IQ2_XS.

Or maybe this PR https://github.com/ggerganov/llama.cpp/pull/5834 is causing problems (I don't know if I tested this new IQ3_S with ot without the PR back in the days) ?

**Comment by Nexesenex** [comment]
@ikawrakow Could you make a different GGML_type of the old IQ3_S, so we can quantize with it?
I excluded this one from my quant cocktails because it's behaving very poorly on Miqu 70b : the IQ2_S and IQ2_M at least are bungled by its presence by a 6-7% perplexity jump compared to expectations, and I never observed any PPL gain with it anyway. When I change the tensors which are in IQ3_S toward IQ3_XXS (and Q2_K for the embedding.weight), I revert to expected results at least a bit better than with IQ2_XS.

At PPL 512 :

Miqu IQ2_M : approx 4.62 (stopped around 500 chunks)
Miqu IQ2_M_fixed : 4.3371
Miqu IQ2_S : 4.7721
MIqu IQ2_S_fixed : 4.4912
Miqu IQ2_XS for information : 4.5553

Or maybe this PR https://github.com/ggerganov/llama.cpp/pull/5834 is causing problems (I don't know if I tested this new IQ3_S with it without the PR back in the days) ?

**Comment by Nexesenex** [comment]
@ikawrakow Could you make a different GGML_type of the old IQ3_S, so we can quantize with it?
I excluded this one from my quant cocktails because it's behaving very poorly on Miqu 70b : the IQ2_S and IQ2_M at least are bungled by its presence by a 6-7% perplexity jump compared to expectations, and I never observed any PPL gain with it anyway. When I change the tensors which are in IQ3_S toward IQ3_XXS (and Q2_K for the embedding.weight), I revert to results at least a bit better than with IQ2_XS.

At PPL 512 :

Miqu IQ2_M : approx 4.62 (stopped around 500 chunks)
Miqu IQ2_M_fixed : 4.3371
Miqu IQ2_S : 4.7721
MIqu IQ2_S_fixed : 4.4912
Miqu IQ2_XS for information : 4.5553

Or maybe this PR https://github.com/ggerganov/llama.cpp/pull/5834 is causing problems (I don't know if I tested this new IQ3_S with it without the PR back in the days) ?

**Pull request merged**
