### PR TITLE
Fix whitespace, add .editorconfig, add GitHub workflow

### PR DESCRIPTION
**Pull request by prusnak**
Followup to https://github.com/ggerganov/llama.cpp/commit/9d634ef452d0fc24fcd49592952d13d0ab0f41b7

### CODE REVIEW

**Comment by prusnak** [comment]
> Maybe add these to the .editorconfig:

I've added `indent_style = space` but not the `indent_size = 4`, since there are cases that do not follow that rule for a good reason, such as:

https://github.com/ggerganov/llama.cpp/blob/2663d2c6784ad7b77998c6874df25648d597f74b/llama.h#L85-L88

or

https://github.com/ggerganov/llama.cpp/blob/2663d2c6784ad7b77998c6874df25648d597f74b/llama.cpp#L251-L252

**Comment by j-f1** [comment]
I think adding `indent_size = 4` would be reasonable here — those cases technically aren’t indentation, they’re alignment. Setting `indent_size` helps with when people e.g. start a new block and have to indent, since users may have a default indent size of 2 or 3 instead of 4.

**Comment by prusnak** [comment]
> those cases technically aren’t indentation, they’re alignment.

If I add it, the editorconfig-checker complains.

**Comment by prusnak** [comment]
> In the meantime, you could [disable the `IndentSize` check](https://github.com/editorconfig-checker/editorconfig-checker#configuration).

Implemented in 303c5ca

**Review by j-f1 — APPROVED** [review]

**Comment by prusnak** [comment]
> want to consider a better solution:

This works for me:

```
[prompts/*.txt]
insert_final_newline = false
trim_trailing_whitespace = false
```

Created a PR https://github.com/ggerganov/llama.cpp/pull/908 - please test

**Pull request merged**
