### PR TITLE
main-interactive-mode: optionally allow for special tokens from user in interactive mode for fill-in-middle etal

### PR DESCRIPTION
**Pull request by hanishkvc**
Add a flag --interactive-specials to examples/main

This controls whether the user entered text in interactive mode is tokenized with parse_special flag set or not.

When main is run with this flag, it will allow users to enter any special tokens for fill-in-mode or equivalent supported by any ai model, so that the model can do the same at the appropriate location, based on the surrounding context in the user text.

@ggerganov @teleprint-me 

I havent tested this yet, but logically this should allow for the above mentioned use case.

### CODE REVIEW

**Comment by hanishkvc** [comment]
Tested fill-in-middle sample prompt mentioned wrt Refact 1.6B,

and it correctly generates a suitable comment as expected that should be placed in-between the user provided code context in the sample prompt, when --interactive-specials argument is passed to main.

Without --interactive-specials argument, it generates a some what repeating general note about the code in the given sample prompt.

**Comment by hanishkvc** [comment]
Have force pushed a merge with the master. @mofosyne , I think I overwrote your equivalent merge.

**Comment by mofosyne** [comment]
Not a problem. I would prefer that as I can't always guess your full intent. You are a more accurate author than I am. But I was hoping to at  least make your life easier :)

**Review by mofosyne — APPROVED** [review]
Double checked that llama_tokenize() forth arguments is actually for special/control token in method definitions. Looks right.

Can observe change to code that would add a new flag that would allow for enabling the ability to add a special token in the middle of the embedding stream.

**Pull request merged**
