### PR TITLE
ggml : automatic selection of best CPU backend

### PR DESCRIPTION
**Pull request by slaren**
This the way it works:
- Backends can export a function called `ggml_backend_score`
- When loading a backend, all the available variants are checked and the highest score one is loaded
- A score of 0 means that the backend cannot be used in the current system
- The available variants are discovered automatically based on the file name, for example, when loading the CPU backend, all files that match `libggml-cpu-*.so` (or `ggml-cpu-*.dll` on windows) are checked.

The CPU backend implements this functionality for x86-64 and returns a score depending on the features included in the build that are supported on the running system.

The `llama-server` docker image has been updated to include variants for AVX, AVX2, AVX512 and AMX.

Caveat: the AVX and AVX2 variants still require FMA and F16C, which will limit the number of processors supported. More variants may be needed to fully support some microarchitectures.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by giladgd** [comment]
I think it may be worth having a cmake flag to build all the common CPU backend variations in a single build rather than having to build multiple times and combining the backend libraries.
Having this would make it easier to maintain a centralized list of the common configurations that would be supported by projects that use llama.cpp.

**Comment by slaren** [comment]
Yes, I agree that would be better. TBH selecting the variants is a headache because there are so many options and each microarchitecture supports a different subset of them, so I didn't want to think too much about it. It might make more sense to build a variant for each microarchitecture, but there is going to be a lot of them.

**Comment by giladgd** [comment]
Is there an advantage to building a separate binary for each microarchitecture over determining what features can used on runtime?
I've seen both runtime and compile-time feature detection in the codebase, but I'm not sure I understand why some features are detected only on compile-time.
Having a single binary that can adapt to the system it runs on would be much easier to use, so I'm wondering what are the limitations of this approach.

**Comment by slaren** [comment]
That's not really an option for many reasons. It would probably require rewriting all the code in ASM and using a JIT compiler.
Why would that be easier to use? The best backend is loaded automatically, it doesn't require you to do anything.

**Comment by giladgd** [comment]
The more variations of the CPU backends compiled with different flags means more duplication of the same code, which would increase the total build size.
Also, having many different variations with different combinations of flags would produce many more files and can take much longer to compile as more variations are added over time.
I was thinking more towards extracting the relevant functions to very small libraries that can be loaded dynamically based on runtime feature detection for this, rather than loading the entire backend compiled with different combinations of flags.

**Comment by slaren** [comment]
>I was thinking more towards extracting the relevant functions to very small libraries that can be loaded dynamically based on runtime feature detection 

That's pretty much what this is already. The build time and build size is not really significant, the CPU backend builds very quickly and most variants are below 500kB in size.

**Comment by giladgd** [comment]
Then all is good. Thanks for explaining :)

**Pull request merged**
