### PR TITLE
Feature: support blis and other blas implementation 

### PR DESCRIPTION
**Pull request by zenixls2**
Reopen to cope with the ci errors
Requested by @ggerganov

### CODE REVIEW

**Comment by zenixls2** [comment]
I need to go back to my PC to fix the indent issue in cmake file

**Comment by ggerganov** [comment]
The `.github/workflow/build.yml` file needs to be updated since it is still using `LLAMA_OPENBLAS`:

```bash
 $ ▶ grep -R -i openblas .github/workflows/*
.github/workflows/build.yml:      OPENBLAS_VERSION: 0.3.23
.github/workflows/build.yml:          - build: 'openblas'
.github/workflows/build.yml:            defines: '-DLLAMA_OPENBLAS=ON -DBLAS_LIBRARIES="/LIBPATH:$env:RUNNER_TEMP/openblas/lib" -DOPENBLAS_INC="$env:RUNNER_TEMP/openblas/include"'
.github/workflows/build.yml:      - name: Download OpenBLAS
.github/workflows/build.yml:        id: get_openblas
.github/workflows/build.yml:        if: ${{ matrix.build == 'openblas' }}
.github/workflows/build.yml:          curl.exe -o $env:RUNNER_TEMP/openblas.zip -L "https://github.com/xianyi/OpenBLAS/releases/download/v${env:OPENBLAS_VERSION}/OpenBLAS-${env:OPENBLAS_VERSION}-x64.zip"
.github/workflows/build.yml:          curl.exe -o $env:RUNNER_TEMP/OpenBLAS.LICENSE.txt -L "https://github.com/xianyi/OpenBLAS/raw/v${env:OPENBLAS_VERSION}/LICENSE"
.github/workflows/build.yml:          mkdir $env:RUNNER_TEMP/openblas
.github/workflows/build.yml:          tar.exe -xvf $env:RUNNER_TEMP/openblas.zip -C $env:RUNNER_TEMP/openblas
.github/workflows/build.yml:          & $lib /machine:x64 "/def:${env:RUNNER_TEMP}/openblas/lib/libopenblas.def" "/out:${env:RUNNER_TEMP}/openblas/lib/openblas.lib" /name:openblas.dll
.github/workflows/build.yml:      - name: Add libopenblas.dll
.github/workflows/build.yml:        id: add_libopenblas_dll
.github/workflows/build.yml:        if: ${{ matrix.build == 'openblas' }}
.github/workflows/build.yml:          cp $env:RUNNER_TEMP/openblas/bin/libopenblas.dll ./build/bin/Release/openblas.dll
.github/workflows/build.yml:          cp $env:RUNNER_TEMP/OpenBLAS.LICENSE.txt ./build/bin/Release/OpenBLAS-${env:OPENBLAS_VERSION}.txt
.github/workflows/build.yml:#            obzip: https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21-x86.zip
.github/workflows/build.yml:#            obzip: https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21-x64.zip
.github/workflows/build.yml:#      - name: Fetch OpenBLAS
.github/workflows/build.yml:#          copy blas/include/openblas_config.h .
.github/workflows/build.yml:#          -DLLAMA_SUPPORT_OPENBLAS=${{ matrix.blas }}
.github/workflows/build.yml:#      - name: Copy libopenblas.dll
.github/workflows/build.yml:#        run: copy "$env:blasdir/bin/libopenblas.dll" build/bin/${{ matrix.build }}
```

**Comment by zenixls2** [comment]
@ggerganov all resolved

**Review by ggerganov — APPROVED** [review]
Thanks!

**Pull request merged**
