### PR TITLE
examples : Add tokenize

### PR DESCRIPTION
**Pull request by zakkor**
Adds a simple `tokenize` utility that can be used to tokenize a prompt without loading the entire model into memory.

I followed the example from simple.cpp, except using `model_params.vocab_only = true;` to load only the vocab.

### Usage:
`usage: ./bin/tokenize MODEL_PATH PROMPT [--ids]`

_Note: Use `2>/dev/null` when running to silence llama.cpp logging output._

### Example
```fish
# Print tokens:
./tokenize "../models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!"
     1 -> ''
 21558 -> 'hello'
    13 -> '
'
  9471 -> 'world'
 28808 -> '!'
 
 # Print token IDs only
$ ./tokenize "./models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!" --ids
1
21558
13
9471
28808

# Count
$ ./tokenize "./models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!" --ids | wc -l
       5
 ```

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
> output a format that is easier to parse programmatically 

You're going to run into problems with stuff like newline or incomplete unicode characters.

**Comment by cebtenzzre** [comment]
@ggerganov If you block NancyAngels via the link on their profile then they won't be able to interact with this repo anymore. I reported to GitHub and they said they won't do anything about it.

**Comment by zakkor** [comment]
@KerfuffleV2 Ah, that's true.

I think I'll:
- add a `--count` switch, which'll directly return the number of tokens without printing the tokens.
- with the `--count` switch turned off, I'll reuse the printing logic that happens when you use `main` with `--prompt-verbose`, which looks like:
```
     1 -> ''
 21558 -> 'hello'
    13 -> '
'
  9471 -> 'world'
```

**Comment by cebtenzzre** [comment]
> So for programmatic usage, it'll be slightly harder to parse the output format but at least it will be correct, but for simply counting tokens (which seems like the most common case) it'll be easier, since you can directly get the token count using `--count`

Why not make a flag to only print the token IDs? That way if you just wanted the count you could pipe it to `wc -l` or something.

**Comment by zakkor** [comment]
@cebtenzzre sounds good, I've pushed an update, usage now looks like this:

```fish
# Print tokens:
./tokenize "../models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!"
     1 -> ''
 21558 -> 'hello'
    13 -> '
'
  9471 -> 'world'
 28808 -> '!'
 
 # Print token IDs only
$ ./tokenize "./models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!" --ids
1
21558
13
9471
28808

# Count
$ ./tokenize "./models/openhermes-2.5-mistral-7b.Q5_K_M.gguf" "hello"\n"world!" --ids | wc -l
       5
 ```

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
