### PR TITLE
Fix RWKV v6 model conversion

### PR DESCRIPTION
**Pull request by MollySophia**
*Make sure to read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md) before submitting a PR*

It seems that some rwkv tensors are made FP16 rather than FP32 after specific commits. However, `ggml_cuda_op_bin_bcast` requires src1->type == FP32. As a result, newly converted RWKV models cannot run with cuda, while existing files aren't affected. This PR fixes the issue above.

Also add LLAMA_EXAMPLE_PERPLEXITY in the examples list of parameter `--no-context-shift` so that models without context shift support can do llama-perplexity again.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]
This is likely caused by this change where I removed the `squeeze()` during conversion:

https://github.com/ggerganov/llama.cpp/blob/0bf2d10c5514ff61b99897a4a5054f846e384e1e/convert_hf_to_gguf.py#L298-L301

**Comment by MollySophia** [comment]
> This is likely caused by this change where I removed the `squeeze()` during conversion:
> 
> https://github.com/ggerganov/llama.cpp/blob/0bf2d10c5514ff61b99897a4a5054f846e384e1e/convert_hf_to_gguf.py#L298-L301

I see. So there's another way to fix this: squeeze them in rwkv6's modify_tensors(), rather than adding them to the F32 list?
Should both solve the issue. I wonder which way is better

**Comment by ggerganov** [comment]
Don't think there is any significant advantage one way or the other. Maybe squeezing in modify_tensors is a bit more localized.

**Comment by ggerganov** [comment]
This is good to merge?

**Comment by MollySophia** [comment]
> This is good to merge?

Yes. Thanks a lot for your time!

**Pull request merged**
