### PR TITLE
Fixes for codellama

### PR DESCRIPTION
**Pull request by slaren**
Changes  `convert.py` to allow missing `vocab_size` in `params.json`, adds enum value for 34b model.

  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6
| model                          | backend    | n_gpu_layers | test       |             t/s |
| ------------------------------ | ---------- | -----------: | ---------- | --------------: |
| LLaMA v2 34B mostly Q4_K - Small | CUDA       |           99 | pp 512     |   530.11 ± 0.60 |
| LLaMA v2 34B mostly Q4_K - Small | CUDA       |           99 | tg 128     |    18.55 ± 0.02 |

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by slaren** [comment]
Short perplexity test:
7b q5_k_m: `[1]6.3455,[2]7.2255,[3]9.2265,`
13b q5_k_m: `[1]5.8744,[2]7.0650,[3]7.9541,`
34b q4_k_m: `[1]5.3722,[2]6.8634,[3]18.5997,`

**Comment by slaren** [comment]
The issue may be due to the long context fine tuning. Using `-rope-freq-base 1e6` the results are looking much better.

image

**Comment by slaren** [comment]
Ok, that's definitely an issue. The final ppl with 34b q4_k_m `--rope-freq-base 1e6` is `5.7811`

<details>

```bash
llama_model_loader: - kv   0:                       general.architecture str
llama_model_loader: - kv   1:                               general.name str
llama_model_loader: - kv   2:                       llama.context_length u32
llama_model_loader: - kv   3:                     llama.embedding_length u32
llama_model_loader: - kv   4:                          llama.block_count u32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
llama_model_loader: - kv   7:                 llama.attention.head_count u32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
llama_model_loader: - kv  10:                          general.file_type u32
llama_model_loader: - kv  11:                       tokenizer.ggml.model str
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr
llama_model_loader: - kv  15:               general.quantization_version u32
llama_model_loader: - type  f32:   97 tensors
llama_model_loader: - type q4_K:  289 tensors
llama_model_loader: - type q6_K:   49 tensors
llm_load_print_meta: format         = GGUF V1 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 32000
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 4096
llm_load_print_meta: n_ctx          = 512
llm_load_print_meta: n_embd         = 8192
llm_load_print_meta: n_head         = 64
llm_load_print_meta: n_head_kv      = 8
llm_load_print_meta: n_layer        = 48
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 8
llm_load_print_meta: f_norm_eps     = 1.0e-05
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 22016
llm_load_print_meta: freq_base      = 1000000.0
llm_load_print_meta: freq_scale     = 1
llm_load_print_meta: model type     = 34B
llm_load_print_meta: model ftype    = mostly Q4_K - Medium
llm_load_print_meta: model size     = 33.74 B
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.13 MB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =  140.76 MB (+   96.00 MB per state)
llm_load_tensors: offloading 48 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloading v cache to GPU
llm_load_tensors: offloading k cache to GPU
llm_load_tensors: offloaded 51/51 layers to GPU
llm_load_tensors: VRAM used: 19238 MB
....................................................................................................
llama_new_context_with_model: kv self size  =   96.00 MB
llama_new_context_with_model: compute buffer total size =  119.41 MB
llama_new_context_with_model: VRAM scratch buffer: 118.00 MB

system_info: n_threads = 1 / 32 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
perplexity: tokenizing the input ..
perplexity: calculating perplexity over 655 chunks, batch_size=512
perplexity: 1.00 seconds per pass - ETA 10.88 minutes
[1]4.2372,[2]4.7320,[3]5.5051,[4]6.3183,[5]6.4880,[6]6.4093,[7]6.5309,[8]6.5565,[9]6.8206,[10]7.0476,[11]7.2814,[12]7.3205,[13]7.2565,[14]7.3485,[15]7.5977,[16]7.2239,[17]7.0971,[18]7.0294,[19]6.6729,[20]6.6685,[21]6.5518,[22]6.3390,[23]6.2829,[24]6.1878,[25]6.1765,[26]5.9847,[27]5.7738,[28]5.6386,[29]5.5307,[30]5.3570,[31]5.2739,[32]5.3031,[33]5.2486,[34]5.2887,[35]5.3046,[36]5.3362,[37]5.3191,[38]5.3193,[39]5.3439,[40]5.3798,[41]5.3973,[42]5.4398,[43]5.4031,[44]5.4433,[45]5.4429,[46]5.4097,[47]5.4334,[48]5.4142,[49]5.4021,[50]5.3661,[51]5.3801,[52]5.3764,[53]5.4184,[54]5.4072,[55]5.3937,[56]5.4206,[57]5.4382,[58]5.4544,[59]5.4711,[60]5.5030,[61]5.4940,[62]5.5545,[63]5.5759,[64]5.5782,[65]5.6078,[66]5.6046,[67]5.6132,[68]5.6288,[69]5.6525,[70]5.6789,[71]5.7012,[72]5.7352,[73]5.7758,[74]5.7811,[75]5.7850,[76]5.7937,[77]5.8052,[78]5.7914,[79]5.8198,[80]5.8168,[81]5.8321,[82]5.8398,[83]5.7918,[84]5.7946,[85]5.7940,[86]5.7804,[87]5.7329,[88]5.7193,[89]5.7046,[90]5.6888,[91]5.7118,[92]5.7031,[93]5.6973,[94]5.6979,[95]5.7305,[96]5.7293,[97]5.7267,[98]5.7199,[99]5.7056,[100]5.7005,[101]5.7222,[102]5.7176,[103]5.7371,[104]5.7421,[105]5.7402,[106]5.7571,[107]5.7603,[108]5.7683,[109]5.7672,[110]5.7628,[111]5.7838,[112]5.8061,[113]5.8043,[114]5.8025,[115]5.8081,[116]5.8000,[117]5.8072,[118]5.8323,[119]5.8557,[120]5.8899,[121]5.9036,[122]5.9262,[123]5.9611,[124]5.9752,[125]5.9661,[126]6.0024,[127]6.0339,[128]6.0583,[129]6.0453,[130]6.0491,[131]6.0429,[132]6.0352,[133]6.0147,[134]6.0197,[135]6.0119,[136]5.9990,[137]5.9899,[138]5.9669,[139]5.9587,[140]5.9516,[141]5.9228,[142]5.9162,[143]5.8873,[144]5.8662,[145]5.8512,[146]5.8402,[147]5.8395,[148]5.8380,[149]5.8297,[150]5.8262,[151]5.8293,[152]5.8183,[153]5.8056,[154]5.7982,[155]5.8032,[156]5.8023,[157]5.8175,[158]5.8185,[159]5.8227,[160]5.8300,[161]5.8414,[162]5.8157,[163]5.8066,[164]5.7872,[165]5.7615,[166]5.7366,[167]5.7018,[168]5.6776,[169]5.6686,[170]5.6591,[171]5.6381,[172]5.6227,[173]5.6066,[174]5.5824,[175]5.5619,[176]5.5499,[177]5.5312,[178]5.5122,[179]5.4977,[180]5.4907,[181]5.4753,[182]5.4583,[183]5.4466,[184]5.4455,[185]5.4420,[186]5.4456,[187]5.4566,[188]5.4579,[189]5.4803,[190]5.4809,[191]5.5010,[192]5.5167,[193]5.5298,[194]5.5432,[195]5.5652,[196]5.5787,[197]5.5996,[198]5.6119,[199]5.6158,[200]5.6211,[201]5.6152,[202]5.6305,[203]5.6400,[204]5.6377,[205]5.6518,[206]5.6578,[207]5.6537,[208]5.6669,[209]5.6712,[210]5.6753,[211]5.6881,[212]5.6958,[213]5.7033,[214]5.7065,[215]5.7077,[216]5.7186,[217]5.7336,[218]5.7462,[219]5.7446,[220]5.7430,[221]5.7343,[222]5.7304,[223]5.7209,[224]5.7141,[225]5.7087,[226]5.7265,[227]5.7304,[228]5.7380,[229]5.7426,[230]5.7369,[231]5.7487,[232]5.7380,[233]5.7210,[234]5.7059,[235]5.6820,[236]5.6794,[237]5.6711,[238]5.6748,[239]5.6639,[240]5.6540,[241]5.6547,[242]5.6552,[243]5.6521,[244]5.6418,[245]5.6389,[246]5.6281,[247]5.6184,[248]5.6122,[249]5.6094,[250]5.6134,[251]5.6047,[252]5.6015,[253]5.5930,[254]5.5861,[255]5.5745,[256]5.5577,[257]5.5464,[258]5.5379,[259]5.5360,[260]5.5281,[261]5.5234,[262]5.5196,[263]5.5132,[264]5.4880,[265]5.4891,[266]5.4855,[267]5.4798,[268]5.4881,[269]5.4898,[270]5.4923,[271]5.5008,[272]5.5048,[273]5.5066,[274]5.5055,[275]5.5106,[276]5.5165,[277]5.5285,[278]5.5376,[279]5.5451,[280]5.5482,[281]5.5584,[282]5.5649,[283]5.5780,[284]5.5876,[285]5.5969,[286]5.6099,[287]5.6085,[288]5.6138,[289]5.6064,[290]5.5959,[291]5.5852,[292]5.5742,[293]5.5635,[294]5.5650,[295]5.5655,[296]5.5713,[297]5.5717,[298]5.5760,[299]5.5750,[300]5.5669,[301]5.5683,[302]5.5637,[303]5.5564,[304]5.5486,[305]5.5461,[306]5.5347,[307]5.5373,[308]5.5376,[309]5.5261,[310]5.5231,[311]5.5192,[312]5.5215,[313]5.5185,[314]5.5199,[315]5.5058,[316]5.5025,[317]5.4878,[318]5.4697,[319]5.4834,[320]5.4943,[321]5.4977,[322]5.4925,[323]5.4887,[324]5.4899,[325]5.5017,[326]5.5030,[327]5.5049,[328]5.5085,[329]5.5123,[330]5.5162,[331]5.5278,[332]5.5243,[333]5.5315,[334]5.5268,[335]5.5211,[336]5.5234,[337]5.5223,[338]5.5222,[339]5.5185,[340]5.5132,[341]5.5180,[342]5.5199,[343]5.5236,[344]5.5245,[345]5.5255,[346]5.5233,[347]5.5262,[348]5.5283,[349]5.5314,[350]5.5305,[351]5.5303,[352]5.5297,[353]5.5242,[354]5.5238,[355]5.5298,[356]5.5350,[357]5.5323,[358]5.5420,[359]5.5458,[360]5.5433,[361]5.5427,[362]5.5507,[363]5.5611,[364]5.5675,[365]5.5717,[366]5.5741,[367]5.5817,[368]5.5797,[369]5.5816,[370]5.5846,[371]5.5795,[372]5.5846,[373]5.5890,[374]5.5876,[375]5.5875,[376]5.5952,[377]5.5923,[378]5.5950,[379]5.5998,[380]5.5939,[381]5.5917,[382]5.5877,[383]5.5872,[384]5.5880,[385]5.5881,[386]5.5874,[387]5.5896,[388]5.5870,[389]5.5845,[390]5.5792,[391]5.5740,[392]5.5725,[393]5.5746,[394]5.5791,[395]5.5775,[396]5.5718,[397]5.5804,[398]5.5867,[399]5.5953,[400]5.5946,[401]5.5957,[402]5.5981,[403]5.6007,[404]5.6063,[405]5.6021,[406]5.6002,[407]5.6029,[408]5.6044,[409]5.6164,[410]5.6269,[411]5.6376,[412]5.6538,[413]5.6655,[414]5.6725,[415]5.6791,[416]5.6871,[417]5.6974,[418]5.7001,[419]5.7059,[420]5.7138,[421]5.7247,[422]5.7293,[423]5.7369,[424]5.7471,[425]5.7567,[426]5.7647,[427]5.7691,[428]5.7773,[429]5.7807,[430]5.7896,[431]5.8027,[432]5.8053,[433]5.8037,[434]5.8000,[435]5.8028,[436]5.8056,[437]5.8156,[438]5.8245,[439]5.8218,[440]5.8220,[441]5.8191,[442]5.8181,[443]5.8192,[444]5.8205,[445]5.8189,[446]5.8215,[447]5.8235,[448]5.8271,[449]5.8256,[450]5.8267,[451]5.8229,[452]5.8228,[453]5.8164,[454]5.8121,[455]5.8147,[456]5.8194,[457]5.8227,[458]5.8217,[459]5.8218,[460]5.8309,[461]5.8296,[462]5.8304,[463]5.8341,[464]5.8333,[465]5.8324,[466]5.8270,[467]5.8310,[468]5.8332,[469]5.8364,[470]5.8370,[471]5.8349,[472]5.8407,[473]5.8359,[474]5.8398,[475]5.8379,[476]5.8406,[477]5.8360,[478]5.8367,[479]5.8466,[480]5.8527,[481]5.8555,[482]5.8522,[483]5.8507,[484]5.8540,[485]5.8545,[486]5.8508,[487]5.8521,[488]5.8505,[489]5.8475,[490]5.8483,[491]5.8478,[492]5.8454,[493]5.8431,[494]5.8416,[495]5.8417,[496]5.8396,[497]5.8369,[498]5.8371,[499]5.8337,[500]5.8258,[501]5.8212,[502]5.8232,[503]5.8241,[504]5.8169,[505]5.8203,[506]5.8212,[507]5.8141,[508]5.8091,[509]5.8083,[510]5.8091,[511]5.8131,[512]5.8154,[513]5.8173,[514]5.8225,[515]5.8179,[516]5.8173,[517]5.8182,[518]5.8179,[519]5.8203,[520]5.8210,[521]5.8219,[522]5.8243,[523]5.8248,[524]5.8310,[525]5.8341,[526]5.8345,[527]5.8370,[528]5.8325,[529]5.8331,[530]5.8275,[531]5.8264,[532]5.8323,[533]5.8348,[534]5.8334,[535]5.8360,[536]5.8321,[537]5.8301,[538]5.8352,[539]5.8361,[540]5.8379,[541]5.8401,[542]5.8395,[543]5.8411,[544]5.8416,[545]5.8399,[546]5.8406,[547]5.8373,[548]5.8312,[549]5.8311,[550]5.8289,[551]5.8265,[552]5.8247,[553]5.8215,[554]5.8193,[555]5.8165,[556]5.8158,[557]5.8202,[558]5.8175,[559]5.8172,[560]5.8147,[561]5.8152,[562]5.8122,[563]5.8122,[564]5.8171,[565]5.8188,[566]5.8196,[567]5.8192,[568]5.8199,[569]5.8186,[570]5.8210,[571]5.8222,[572]5.8217,[573]5.8220,[574]5.8184,[575]5.8171,[576]5.8169,[577]5.8154,[578]5.8140,[579]5.8136,[580]5.8075,[581]5.8045,[582]5.8050,[583]5.8072,[584]5.8078,[585]5.7998,[586]5.7930,[587]5.7930,[588]5.7967,[589]5.8017,[590]5.8037,[591]5.8058,[592]5.8042,[593]5.8020,[594]5.8026,[595]5.8006,[596]5.8040,[597]5.8015,[598]5.7991,[599]5.8010,[600]5.8000,[601]5.7994,[602]5.8026,[603]5.8041,[604]5.8053,[605]5.8082,[606]5.8100,[607]5.8101,[608]5.8069,[609]5.8072,[610]5.8110,[611]5.8088,[612]5.8104,[613]5.8066,[614]5.8014,[615]5.7944,[616]5.7954,[617]5.7883,[618]5.7826,[619]5.7770,[620]5.7639,[621]5.7573,[622]5.7555,[623]5.7561,[624]5.7553,[625]5.7558,[626]5.7544,[627]5.7571,[628]5.7577,[629]5.7569,[630]5.7603,[631]5.7645,[632]5.7705,[633]5.7687,[634]5.7722,[635]5.7732,[636]5.7700,[637]5.7671,[638]5.7688,[639]5.7653,[640]5.7670,[641]5.7673,[642]5.7735,[643]5.7755,[644]5.7762,[645]5.7748,[646]5.7788,[647]5.7770,[648]5.7779,[649]5.7775,[650]5.7791,[651]5.7837,[652]5.7848,[653]5.7883,[654]5.7821,[655]5.7811,

llama_print_timings:        load time =  5546.65 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time = 649534.48 ms / 335360 tokens (    1.94 ms per token,   516.31 tokens per second)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings:       total time = 677274.58 ms
```
</details>

The correct value of `rope_freq_base` seems to be in `params.json` as `"rope_theta": 1000000`, but looks like `convert.py` doesn't export this value currently. Is there a metadata in gguf for this parameter?

**Comment by ggerganov** [comment]
We don't have one yet - we should introduce and add it to the spec: https://github.com/ggerganov/ggml/pull/302

Btw, the vocab now is 32016.
The K-quants require the Y dimension also to be divisible by 256. Why is this needed? Don't we need just the X dimension (i.e. `ne[0]`) to be divisible by 256?

https://github.com/ggerganov/llama.cpp/blob/ef955fbd230c571cc1cda0d19baaeec347523175/llama.cpp#L4533-L4541

**Comment by slaren** [comment]
> Btw, the vocab now is 32016.

Is this with all models? For 34b the sizes of the tensors suggest a `n_vocab` of 32000:

```
tok_embeddings.weight                            -> token_embd.weight                        | UnquantizedDataType(name='BF16') | [32000, 8192]
norm.weight                                      -> output_norm.weight                       | UnquantizedDataType(name='BF16') | [8192]
output.weight                                    -> output.weight                            | UnquantizedDataType(name='BF16') | [32000, 8192]
```

**Comment by ggerganov** [comment]
Here are some results on M2 Ultra:

| model                          | backend    | n_gpu_layers | test       |             t/s |
| ------------------------------ | ---------- | -----------: | ---------- | --------------: |
| codellama 7B mostly F16        | Metal      |          999 | pp 512     |   663.32 ± 1.10 |
| codellama 7B mostly Q8_0       | Metal      |          999 | pp 512     |   631.39 ± 0.30 |
| codellama 7B mostly Q6_K       | Metal      |          999 | pp 512     |   562.97 ± 0.54 |
| codellama 7B mostly Q5_K - Medium | Metal      |          999 | pp 512     |   562.58 ± 0.22 |
| codellama 7B mostly Q4_K - Medium | Metal      |          999 | pp 512     |   589.01 ± 0.09 |
| codellama 7B mostly Q4_1       | Metal      |          999 | pp 512     |   635.65 ± 0.30 |
| codellama 7B mostly Q4_0       | Metal      |          999 | pp 512     |   633.74 ± 0.30 |
| codellama 7B mostly Q3_K - Medium | Metal      |          999 | pp 512     |   582.17 ± 0.36 |
| codellama 7B mostly Q2_K       | Metal      |          999 | pp 512     |   581.32 ± 0.99 |
| codellama 7B mostly F16        | Metal      |          999 | tg 64      |    29.61 ± 0.05 |
| codellama 7B mostly Q8_0       | Metal      |          999 | tg 64      |    61.56 ± 0.14 |
| codellama 7B mostly Q6_K       | Metal      |          999 | tg 64      |    67.49 ± 0.03 |
| codellama 7B mostly Q5_K - Medium | Metal      |          999 | tg 64      |    68.46 ± 0.15 |
| codellama 7B mostly Q4_K - Medium | Metal      |          999 | tg 64      |    79.03 ± 0.03 |
| codellama 7B mostly Q4_1       | Metal      |          999 | tg 64      |    82.60 ± 0.12 |
| codellama 7B mostly Q4_0       | Metal      |          999 | tg 64      |    87.73 ± 0.30 |
| codellama 7B mostly Q3_K - Medium | Metal      |          999 | tg 64      |    75.79 ± 0.08 |
| codellama 7B mostly Q2_K       | Metal      |          999 | tg 64      |    74.56 ± 0.12 |

build: 01f2224 (1053)

Anyone working on adding the rope base to the meta data?
If not, I'll add it in about 15 mins

**Comment by slaren** [comment]
>Anyone working on adding the rope base to the meta data?

I am not working on it, I was waiting for some input since I don't know all the details of gguf.

**Comment by ggerganov** [comment]
You have to add the KV constant in the `gguf.py` and in `llama.cpp` similar to `LLM_KV_ROPE_SCALE_LINEAR`.
Just grep for all uses of `LLM_KV_ROPE_SCALE_LINEAR` and replicate as a new KV, for example `LLK_KV_ROPE_BASE`

**Comment by slaren** [comment]
> Does this affect all the new Code Llama models or only 34B? Something I'm ready elsewhere suggests all, is that right?

My plan is to only affect CodeLLama model, the rope freq base will be added as an optional metadata that will be omitted for the other models, so they won't change. But that may change after the review.

**Comment by ggerganov** [comment]
All new Code Llama are affacted - without this change one would need to provide the rope base manually, which is inconvenient

**Comment by slaren** [comment]
@TheBloke the change has been merged, it should be safe to convert the models now.

**Comment by ggerganov** [comment]
Just a heads up - I expect in the near future to tune the quantum mixtures to some extend.
For example, currently `Q4_0` does not use a high-bit `output` tensor (e.g. `Q6_K`) because the vocab has `ne[1]` not a multiple of 256. Not sure why we have this restriction, but probably we'll fix it and it would result in a new quantum model

**Comment by slaren** [comment]
Additionally, it might be a good idea to convert them with `--ctx 16384`, since the converter will default to 4096. Maybe we should change `convert.py` to use this value automatically if `theta_scale` is 1e6?

**Comment by slaren** [comment]
@TheBloke I tried your `codellama-7b-python.Q4_K_M.gguf` and it fails with this error:
```
error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected  4096, 32016, got  4096, 32000,     1,     1
```

I tried converting this model myself, and it works for me, so I am not sure what went wrong there. Maybe you used a different `tokenizer.model`?

**Comment by Jipok** [comment]
@slaren Q8 model works for me:
`./main -m ~/Downloads/codellama-7b-instruct.Q8_0.gguf -e -p "<s>[INST] How does hpa work in kubernetes?[/INST]" -s 0 --temp 0 --rope-freq-base 1e6`

**Comment by TheBloke** [comment]
Yeah I had a problem somewhere in my process, trying to fix now

**Comment by TheBloke** [comment]
I'm confused re rope_frequency_Base - I have it in my config.json but convert.py is not picking it up?

```
(pytorch2)  ubuntu@a10:/workspace/git/gguf-llama (master ✔) ᐅ grep rope_theta /workspace/models_codellama/7B/config.json
    "rope_theta": 1000000

(pytorch2)  ubuntu@a10:/workspace/git/gguf-llama (master ✔) ᐅ python3 ./convert.py --outtype f16 --outfile /workspace/process/codellama-7b/gguf/codellama-7b.fp16.gguf /workspace/models_codellama/7B
Loading model file /workspace/models_codellama/7B/model-00001-of-00002.safetensors
Loading model file /workspace/models_codellama/7B/model-00001-of-00002.safetensors
Loading model file /workspace/models_codellama/7B/model-00002-of-00002.safetensors
params = Params(n_vocab=32016, n_embd=4096, n_mult=5504, n_layer=32, n_ctx=16384, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-05, f_rope_freq_base=None, ftype=<GGMLFileType.MostlyF16: 1>, path_model=PosixPath('/workspace/models_codellama/7B'))
Loading vocab file '/workspace/models_codellama/7B/tokenizer.model', type 'spm'
```

`f_rope_freq_base=None` ?  And then when I do inference on this fp16
```
llm_load_print_meta: format         = GGUF V1 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 32016
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 16384
llm_load_print_meta: n_ctx          = 4096
llm_load_print_meta: n_embd         = 4096
llm_load_print_meta: n_head         = 32
llm_load_print_meta: n_head_kv      = 32
llm_load_print_meta: n_layer        = 32
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 1
llm_load_print_meta: f_norm_eps     = 1.0e-05
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 11008
llm_load_print_meta: freq_base      = 10000.0
llm_load_print_meta: freq_scale     = 1
llm_load_print_meta: model type     = 7B
llm_load_print_meta: model ftype    = mostly F16
llm_load_print_meta: model size     = 6.74 B
llm_load_print_meta: general.name   = LLaMA
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  = 12853.35 MB (+ 2048.00 MB per state)
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/35 layers to GPU
llm_load_tensors: VRAM used: 0 MB
```

freq_base is 10,000 still.

Am I doing something wrong? or misunderstanding something?

**Comment by TheBloke** [comment]
Oh I am misunderstanding - that's the section of convert.py that reads params.json, not config.json!

OK what am I meant to do when making a model from HF format, how do I set the correct rope_freq_base then?

**Comment by TheBloke** [comment]
Maybe I should just make the models from PTH, I feel like I'm making life much harder for myself trying to go PTH -> HF -> GGUF

**Comment by slaren** [comment]
It's not supported for HF models. If you can point me to an HF model, I can try to add it, assuming that the parameter is somewhere in `config.json` or `params.json`.

**Comment by slaren** [comment]
Yeah no problem, if everything goes well I'll open a PR in a short while.

**Comment by TheBloke** [comment]
Thanks so much!

And just to triple check I'm not screwing anything else up:
- 7B/13B/34B = vocab 32016
- *-Instruct = vocab 32016
- *-Python = vocab 32000

Is that right?  That seems to work fine just want to be extra sure

**Comment by slaren** [comment]
The 34B base model has a vocab of 32000, only 7B and 13B should have the extended vocab.

I am not sure about the instruct and python models yet, I can check, but it's going to take a while, I am running out of disk space

**Comment by TheBloke** [comment]
Ok thanks! I've not looked at 34B yet, will be shortly.

Don't worry it's fine, I was just wanting a sanity check if you already knew.  I've done some tests converting direct from PTH and it shows what I described above (at least for 7B and 13B) so I'm confident that must be correct

**Pull request merged**
