### PR TITLE
Server deps.sh unreadable xxd files to string literals.

### PR DESCRIPTION
**Pull request by jboero**

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by jboero** [comment]
Wow that was quick. Thanks!

**Comment by stduhpf** [comment]
This trows compiler `error C2026` when compiling `index.html.hpp` and `index.js.hpp `with Visual Studio. 
Spamming a bunch of `)LITERAL" R"LITERAL(` in the middle of the strings fixes it.

**Comment by ggerganov** [comment]
Ah, so we'll have to stick with the byte arrays then - that's unfortunate

**Comment by jboero** [comment]
Wait what? This should be a part of the C++11 standard which is how this is compiled. Is your Visual Studio env set to C++ version 11 or up?  Please verify as it's a shame to leave this because of an IDE misconfiguration.

**Comment by jboero** [comment]
That's a shame and odd because VS Code has no such issues.

I'd love to chunk it up with the `)LITERAL" R"LITERAL(` blocks somehow but not sure how to automate it in deps.sh.

**Comment by cebtenzzre** [comment]
> VS Code has no such issues

We're talking about MSVC here, it's a whole separate compiler developed by Microsoft.

> I'd love to chunk it up with the )LITERAL" R"LITERAL( blocks somehow but not sure how to automate it in deps.sh.

I could try to implement that if you'd like.

**Comment by jboero** [comment]
> We're talking about MSVC here, it's a whole separate compiler developed by Microsoft.

Yes I understand and it's a great IDE actually.

If you can find a quick way to do that then great yes. I was thinking of cutting the file up into blocks of 1K or so but that may be unpredictable depending on where the file ends. Open to suggestions.

**Pull request merged**
