### PR TITLE
llamafile : improve sgemm.cpp

### PR DESCRIPTION
**Pull request by jart**
- Re-enable by default
- Fix issue described in #6716
- Make code more abstract, elegant, and maintainable
- Faster handling of weirdly shaped `m` an `n` edge cases

### CODE REVIEW

**Review by ggerganov — COMMENTED** [review]
The build fails on Mac:

```bash
$ make -j
I llama.cpp build info: 
I UNAME_S:   Darwin
I UNAME_P:   arm
I UNAME_M:   arm64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -pthread -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion 
I CXXFLAGS:  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY 
I NVCCFLAGS: -std=c++11 -O3 
I LDFLAGS:   -framework Accelerate -framework Foundation -framework Metal -framework MetalKit 
I CC:        Apple clang version 15.0.0 (clang-1500.1.0.2.5)
I CXX:       Apple clang version 15.0.0 (clang-1500.1.0.2.5)

c++ -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread   -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi -I. -Icommon -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_LLAMAFILE -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY  -c sgemm.cpp -o sgemm.o
sgemm.cpp:515:13: error: unknown type name 'D'
            D Cv[RN][RM] = {};
            ^
sgemm.cpp:516:41: error: use of undeclared identifier 'KN'
            for (int l = 0; l < k; l += KN)
                                        ^
2 errors generated.
make: *** [sgemm.o] Error 1
```

Also, apply the following patch to enable LLAMAFILE with CMake builds:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f134a153..58a1805b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -43,17 +43,11 @@ else()
     set(LLAMA_METAL_DEFAULT OFF)
 endif()
 
-# TODO: fix this for Android CI
-#       https://github.com/ggerganov/llama.cpp/pull/6716#issuecomment-2061509191
-#if (CMAKE_SYSTEM_NAME MATCHES "ANDROID")
-#    set(LLAMA_LLAMAFILE_DEFAULT OFF)
-#else()
-#    set(LLAMA_LLAMAFILE_DEFAULT ON)
-#endif()
-
-# TODO: temporary disable until MoE is fixed
-#       https://github.com/ggerganov/llama.cpp/pull/6716
-set(LLAMA_LLAMAFILE_DEFAULT OFF)
+if (CMAKE_SYSTEM_NAME MATCHES "ANDROID")
+    set(LLAMA_LLAMAFILE_DEFAULT OFF)
+else()
+    set(LLAMA_LLAMAFILE_DEFAULT ON)
+endif()
 
 # general
 option(BUILD_SHARED_LIBS                "build shared libraries"                                OFF)
```

**Comment by jart** [comment]
@ggerganov Fixed. PTAL

Please give `Q8_0` a try (build it with `make -j32 LLAMA_NO_ACCELERATE=1 LLAMA_NO_METAL=1 main`) On my Mac Studio M2 Ultra, Mistral 7b Q8 prompt eval goes from 90 tok/sec to 140 tok/sec with this change. That's 16% faster than Apple Accelerate cblas_sgemm() which goes 120 tok/sec for me. The other quants I've tried (q40 and f16) seem to be equal to Accelerate in speed.

Do you know if there's a better way to fix the Android issue? IIUC it's due to an instruction not being available on 32-bit ARM. Is there a way we could solve that with an `#ifdef` instead? I don't own a 32-bit ARM system, so I have no way of doing this myself.

**Comment by jart** [comment]
@ggerganov Could you advise me on how I might bring the benefits of `llamafile_sgemm()` to `GGML_MUL_MAT_ID`? I know very little about mixture of expert architecture. It's not obvious to me how I might go about decomposing that operation into 2d matrix multiplications.

**Comment by ggerganov** [comment]
On `master` with `Accelerate` I get:

```bash
make clean && LLAMA_NO_METAL=1 make -j && ./llama-bench -m models/mistral-7b-v0.2/ggml-model-fp16.gguf -m models/mistral-7b-v0.2/ggml-model-q8_0.gguf -m models/mistral-7b-v0.2/ggml-model-q4_0.gguf -ngl 0 -n 0
```

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 8B F16                   |  13.49 GiB |     7.24 B | BLAS       |         16 | pp 512     |    152.87 ± 1.06 |
| llama 8B Q8_0                  |   7.17 GiB |     7.24 B | BLAS       |         16 | pp 512     |    147.44 ± 5.19 |
| llama 8B Q4_0                  |   3.83 GiB |     7.24 B | BLAS       |         16 | pp 512     |    149.98 ± 1.63 |

build: 8960fe86 (2713)

With this PR without `Accelerate`:

```bash
make clean && LLAMA_NO_ACCELERATE=1 LLAMA_NO_METAL=1 make -j && ./llama-bench -m models/mistral-7b-v0.2/ggml-model-fp16.gguf -m models/mistral-7b-v0.2/ggml-model-q8_0.gguf -m models/mistral-7b-v0.2/ggml-model-q4_0.gguf -ngl 0 -n 0
```

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B F16                   |  13.49 GiB |     7.24 B | CPU        |         16 | pp 512     |    172.84 ± 0.39 |
| llama 7B Q8_0                  |   7.17 GiB |     7.24 B | CPU        |         16 | pp 512     |    146.22 ± 0.44 |
| llama 7B Q4_0                  |   3.83 GiB |     7.24 B | CPU        |         16 | pp 512     |    123.81 ± 0.43 |

build: 6b220dca (2704)

So for me, F16 is faster now, Q8_0 is the same and Q4_0 is slower.

Btw, I've looked some more, and I think the proper call in `ggml.c` should be like this:

```diff
diff --git a/ggml.c b/ggml.c
index e3356bdb..086db96a 100644
--- a/ggml.c
+++ b/ggml.c
@@ -10878,15 +10878,13 @@ UseGgmlGemm1:;
     const size_t row_size = ggml_row_size(vec_dot_type, ne10);
 
 #if GGML_USE_LLAMAFILE
-    if (src1_cont) {
+    if (src1->type != vec_dot_type) {
         for (int64_t i13 = 0; i13 < ne13; i13++)
             for (int64_t i12 = 0; i12 < ne12; i12++)
                 if (!llamafile_sgemm(ne01, ne11, ne00/ggml_blck_size(src0->type),
                                      (const char *)src0->data + i12/r2*nb02 + i13/r3*nb03,
                                      nb01/ggml_type_size(src0->type),
-                                     (const char *)wdata + ggml_row_size(vec_dot_type,
-                                         nb12/ggml_type_size(src1->type)*i12 +
-                                         nb13/ggml_type_size(src1->type)*i13),
+                                     (const char *)wdata + (i12*ne11 + i13*ne12*ne11)*row_size,
                                      row_size/ggml_type_size(vec_dot_type),
                                      (char *)dst->data + i12*nb2 + i13*nb3,
                                      nb1/ggml_type_size(dst->type),
```

Regarding Android: in `ggml-quants.c` we do stuff like this to provide 32-bit ARM compatibility:

https://github.com/ggerganov/llama.cpp/blob/e931888d5024de814ce7119a18d6a959bfff3821/ggml-quants.c#L291-L307

We should not repeat the same implementation twice - we have to see if we can reuse it. I also don't have setup Android builds and it takes me some time to get the build running. So for now, let's focus on fixing the SGEMM and later we can think about improving Android support

Let me think some time about `GGML_MUL_MAT_ID` support

**Comment by jart** [comment]
Review comments addressed. PTAL. Agree on Android 32-bit.

> Let me think some time about `GGML_MUL_MAT_ID` support

I studied the code for hours and managed to figure it out. I've got a `llamafile_mixmul()` function working now that enables mixtral to go 2x faster on my machine for prompt processing.

**Review by ggerganov — APPROVED** [review]

**Comment by fairydreaming** [comment]
These changes cause failed assertions when running Cohere's Command R+ model:

```
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.
main: sgemm.cpp:827: bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int): Assertion `1ll * lda * m <= 0x7fffffff' failed.

Thread 22 "main" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fcf41ffb640 (LWP 108365)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140528142235200) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140528142235200) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140528142235200) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140528142235200, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7a99476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a7f7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7a7f71b in __assert_fail_base (fmt=0x7ffff7c34130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x555555811556 "1ll * lda * m <= 0x7fffffff", file=0x55555581150a "sgemm.cpp", line=827, 
    function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7a90e96 in __GI___assert_fail (assertion=0x555555811556 "1ll * lda * m <= 0x7fffffff", 
    file=0x55555581150a "sgemm.cpp", line=827, 
    function=0x555555811498 "bool llamafile_sgemm(int, int, int, const void*, int, const void*, int, void*, int, int, int, int, int, int, int)") at ./assert/assert.c:101
#7  0x000055555576c199 in llamafile_sgemm (m=256000, n=1, k=12288, A=0x7fcf9dd7b500, lda=12288, B=0x7fcf88918020, 
    ldb=12288, C=0x7fcf89518020, ldc=256000, ith=21, nth=32, task=0, Atype=1, Btype=0, Ctype=0) at sgemm.cpp:827
#8  0x0000555555588c78 in ggml_compute_forward_mul_mat (params=0x7fcf41ffae20, dst=0x55555bf087d0) at ggml.c:10831
#9  0x00005555555a1125 in ggml_compute_forward (params=0x7fcf41ffae20, tensor=0x55555bf087d0) at ggml.c:16254
#10 0x00005555555a75b0 in ggml_graph_compute_thread (data=0x7fffffffb660) at ggml.c:18398
#11 0x00007ffff7aebac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#12 0x00007ffff7b7d850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
When I reverted commit [192090b](https://github.com/ggerganov/llama.cpp/commit/192090bae47960f0d38d4967abe398a5d190057e) the problem disappeared. Log files attached.

[main-crash.log](https://github.com/ggerganov/llama.cpp/files/15106146/main-crash.log)
[main-working.log](https://github.com/ggerganov/llama.cpp/files/15106148/main-working.log)

**Comment by ggerganov** [comment]
Yes, this assert has to be avoided. The Command-R model has a very large output tensor and it's number of elements exceeds `int`. That's why in order to support it, we switched to `int64_t` in many places across the codebase: https://github.com/ggerganov/llama.cpp/pull/6491

This issue should be prioritized, @jart PTAL

**Comment by ggerganov** [comment]
Here are instruction to trigger this assert:

- clone https://huggingface.co/CohereForAI/c4ai-command-r-plus

```bash
# convert to GGUF
python3 convert-hf-to-gguf.py ~/Data/huggingface/c4ai-command-r-plus/ --outfile models/command-r-plus/ggml-model-f16.gguf --outtype f16

# quantize to Q8_0 + F16 token embeddings
make -j
./quantize --token-embedding-type f16 ./models/command-r-plus/ggml-model-f16.gguf ./models/command-r-plus/ggml-model-q8_0.gguf q8_0

# build in DEBUG and run
make clean
LLAMA_DEBUG=1 LLAMA_NO_METAL=1 LLAMA_NO_ACCELERATE=1 make -j
./main -m ./models/command-r-plus/ggml-model-q8_0.gguf
```

**Comment by fairydreaming** [comment]
I just tried a naive solution and replaced all ints in sgemm.cpp and sgemm.h with int64_t, and the resulting code works fine without any performance penalty (at least on my Epyc Genoa). Also there are no more crashes due to int overflow in pointer calculations when using Command R+.

By the way, @jart thank you for these changes, they improved the prompt eval time on my system by 65% on llama-3 70B Q8!

**Comment by jart** [comment]
Thanks for the inbox bump. Making this my top priority now. Expect a PR shortly.

**Pull request merged**
