### PR TITLE
`json`: better support for "type" unions (e.g. nullable arrays w/ typed items)

### PR DESCRIPTION
**Pull request by ochafik**
Adds support for the following nullable syntax I've seen in the wild (also checked properly by https://www.jsonschemavalidator.net/):

```json
{
  "type": ["array", "null"],
  "items": { "type": "string" }
}
```

Before this PR, the grammar above was treated like `{"anyOf": [{"type": "array"}, {"type": "null"}]}` (meaning it would accept to generate `[123]`).

With this PR, it ensures the array is typed, e.g. `["123"]` is possible but not `[123]`

### CODE REVIEW

**Comment by HanClinto** [comment]
Updating the integration tests with pass/fail cases for this one would help me understand better what's going on with this.

**Comment by ochafik** [comment]
> Updating the integration tests with pass/fail cases for this one would help me understand better what's going on with this.

I think we need https://github.com/ggerganov/llama.cpp/pull/7790 for that ;-) In the meantime added an example to the PR's description, sorry it was a bit cryptic :-D

**Comment by HanClinto** [comment]
> > Updating the integration tests with pass/fail cases for this one would help me understand better what's going on with this.
> 
> I think we need #7790 for that ;-) In the meantime added an example to the PR's description, sorry it was a bit cryptic :-D

haha, thanks. :) Noted -- I've been a bit slow on that one. It's finally updated and I think it's ready for review / merge.

**Comment by HanClinto** [comment]
Looks like one of the tests [is failing](https://github.com/ggerganov/llama.cpp/actions/runs/9627796636/job/26555301801?pr=7863#step:5:6567):

> Assertion failed: (false), function verify, file test-json-schema-to-grammar.cpp, line 38.

**Comment by ochafik** [comment]
> Looks like one of the tests [is failing](https://github.com/ggerganov/llama.cpp/actions/runs/9627796636/job/26555301801?pr=7863#step:5:6567):
> 
> > Assertion failed: (false), function verify, file test-json-schema-to-grammar.cpp, line 38.

Fixed, thanks!

**Review by HanClinto — APPROVED** [review]
Super, **super** clean. 

To test I reverted the change to `json-schema-to-grammar.cpp` and the integration test failed. Brought the changes in, and the integration test passed. 

The changes are small and discrete and self-contained. Love it! ❤️❤️❤️ Enthusiastic approval -- very well done!!

**Pull request merged**
