### PR TITLE
Make IQ1_M work for QK_K = 64

### PR DESCRIPTION
**Pull request by ikawrakow**
As with all other i-quants, AVX2, ARM_NEON, CPU scalar, Metal. CUDA will come later.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by ikawrakow** [comment]
@ggerganov Perhaps you should disable the nix build? I don't know about you, but for me a check running for 6 hours and eventually cancelled on every commit does not make much sense. If nothing else, lets have some merci with our planet.

**Comment by ggerganov** [comment]
@SomeoneSerge Is there something to be done to speed-up the builds? AFAICT, with the recent workflow concurrency changes (https://github.com/ggerganov/llama.cpp/pull/6243) all Nix builds are bound to be cancelled since the chance of committing something to `master` within 6h is quite large and this would cancel all running workflows

**Comment by SomeoneSerge** [comment]
@ggerganov thanks for the heads-up; I noticed a few cancelled builds but haven't got around to investigate this. I opened a tracking issue for now: https://github.com/ggerganov/llama.cpp/issues/6346

**Comment by mscheong01** [comment]
If we don't want nix builds to fail on `master`, we could exempt the `master` branch as stated in the #6243 description
>  But, if we don't want this to happen with our master branch workflows, we can make an exception. Here's how we could set it up:
```
concurrency: 
  group: ${{ github.ref == 'refs/heads/master' ? 'master-' + github.run_id : github.workflow + '-' + github.ref }}
  cancel-in-progress: true
```

**Pull request merged**
