### PR TITLE
readme : update gpt4all instructions

### LINKED ISSUE #975: GPT4All Instructions are missing both scripts: convert and migrate
Neither of these links works and the files aren't present anymore.

> You have to convert it to the new format using [./convert-gpt4all-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-gpt4all-to-ggml.py). You may also need to convert the model from the old format to the new format with [./migrate-ggml-2023-03-30-pr613.py](https://github.com/ggerganov/llama.cpp/blob/master/migrate-ggml-2023-03-30-pr613.py):

### LINKED ISSUE #1036: I want to use gpt4all, but there is no convert-gpt4all-to-ggml.py file.
I tried to convert the gpt4all binary to the file written in the README, but I couldn't run it because there was no executable file.
Maybe the name of that file has been changed? Or is there a separate location?

### PR DESCRIPTION
**Pull request by prusnak**
fixes https://github.com/ggerganov/llama.cpp/issues/975

### CODE REVIEW

**Comment by robbintt** [comment]
I am running into one issue with the bin:
```python convert.py models/gpt4all-lora-quantized.bin
Loading model file models/gpt4all-lora-quantized.bin
Traceback (most recent call last):
  File "convert.py", line 1145, in <module>
    main()
  File "convert.py", line 1133, in main
    vocab = load_vocab(vocab_dir)
  File "convert.py", line 1075, in load_vocab
    raise FileNotFoundError(f"Could not find tokenizer.model in {path} or its parent; if it's in another directory, pass the directory as --vocab-dir")
FileNotFoundError: Could not find tokenizer.model in models or its parent; if it's in another directory, pass the directory as --vocab-dir```

**Comment by prusnak** [comment]
As the error says, you don't have the `models/tokenizer.model` file. You need to obtain it from the same place you are obtaining your LLaMa weights.

**Comment by MillionthOdin16** [comment]
> I am running into one issue with the bin:

Also, based off the model and message, you probably should be using the migrate script, not the convert script. That model file is already ggml, it just needs to be migrated to current version.

**Comment by prusnak** [comment]
> migrate script, not the convert script

there is no migrate script anymore, just one complex one-does-it-all convert script

**Comment by MillionthOdin16** [comment]
There's not a `migrate-ggml-2023-03-30-pr613.py` script?

**Comment by prusnak** [comment]
> There's not a `migrate-ggml-2023-03-30-pr613.py` script?

No.

**Comment by MillionthOdin16** [comment]
Welp. Good to know. Unfortunate that it has the same exact name as a previous `convert.py` script that does a subset of tasks lol

**Comment by robbintt** [comment]
Anyways this PR is just for the readme. I have another error, will share in
20 min.

**Comment by robbintt** [comment]
Since this section is about Gpt4all, it might be helpful to enumerate the required files

**Comment by comex** [comment]
Thanks for cleaning up my oversight.

**Comment by prusnak** [comment]
Converting to draft since it seems that gpt4all conversion is broken, see https://github.com/ggerganov/llama.cpp/issues/984

**Comment by prusnak** [comment]
> Converting to draft since it seems that gpt4all conversion is broken, see #984

Fix for this error is in https://github.com/ggerganov/llama.cpp/pull/1031

GPT4All-J is not supported at the moment, which is reflected in the README

**Comment by prusnak** [comment]
Fixes https://github.com/ggerganov/llama.cpp/issues/1036

**Review by CRD716 — APPROVED** [review]

**Review by slaren — APPROVED** [review]

**Comment by hughobrien** [comment]
suggest adding the SHASUMS so people can validate their conversions

**Pull request merged**
