### PR TITLE
Server UI Improvement - New Try

### PR DESCRIPTION
**Pull request by mounta11n**
Hi, six months ago I already was in process of a pull request like this, but unfortunately due lack of time I couldnt work on it until a few days ago.

So I improved more things, fixed some bugs and cleaned up my code and here is my improved lightweight server webui with the simplicity of llama.cpp in mind.

the main features are:

**User Interface.**
Designed with CSS for a more appealing, clean and tidy appearance.

**Well Known Style.**
My initial styling inspiration was the OpenAI playground. A lot of people are already used to this design. But in the meantime I have made some more color themes.

**Dark and Light Themes.**
As mentioned, there are now some color themes to choose from.

**CSS outsourcing.**
The CSS has been moved to separate files to simplify maintenance and hacking.

**Dropdown-Menus.**
Convenient Drop-down menus for predefined prompt formats and system prompts have been added.

**Modular structure.**
Prompt formats and system prompts are stored in separate files, which makes editing very easy.

**More freedom.**
Prompt formats and system prompts are independent of each other and can therefore be combined as required.

**Added a lot of tooltips.**
With comprehensible explanations regarding each parameter.

You can finde more information here:

https://github.com/mounta11n/plusplus-camall/tree/plusplus

Here are some impressions:

ui-2_grammar
tooltips
prompt-formats
polarnight
mango-cpp

### CODE REVIEW

**Comment by mounta11n** [comment]
Note that the first picture is an old one. The most recent version has the apiKey Field in the top section of the UI, like in the other pictures.

**Review by mofosyne — APPROVED** [review]

**Review by ggerganov — APPROVED** [review]
Great! I like that the old UI is also available

Minor nit about the file names - prefer using kebab-case for consistency with the rest of the project:

- `promptFormats.js` -> `prompt-formats.js`
- `EN_systemPrompts.js` -> `EN_system-prompts.js`
- `DE_systemPrompts.js` -> `DE_system-prompts.js`

**Comment by mofosyne** [comment]
will merge once @mounta11n is happy with the PR and taken gg's suggestion into consideration

**Comment by mounta11n** [comment]
> Great! I like that the old UI is also available
> 
> Minor nit about the file names - prefer using kebab-case for consistency with the rest of the project:
> 
> * `promptFormats.js` -> `prompt-formats.js`
> * `EN_systemPrompts.js` -> `EN_system-prompts.js`
> * `DE_systemPrompts.js` -> `DE_system-prompts.js`

Alright, I have renamed the files.

I have noticed that if I want the "New UI" button and therefore the linking to the new ui and vice versa, linking back to old ui, I had to add the new files to server.cpp as static files too.
Otherwise we would have again the problem, that the user has to explicitly add the `--path` each time starting the server.

**Comment by mounta11n** [comment]
Please note that I have removed the german translation files and therefore the prefix "EN_" as well, since multilingual UI feature is in very early stage currently and has no relevance for now. There is a lot of work to do first.

@mofosyne that sounds great, thanks : )

some checks are in progress at this moment, I will look into it soon again.

@characharm that's a good point, but my initial idea was to work around the original old ui and keep its 'personality' (simplicity, lightweight), so without introducing new functionality if not necessary (like the prompt format handling, which I think is absolute necessary).
But I personally would be anyway totally okay with a minimalstic and subtile copy to clipboard button, if the main devs would give an okay as well. What are your thoughts @mofosyne @ggerganov?

**Review by ggerganov — APPROVED** [review]
> But I personally would be anyway totally okay with a minimalstic and subtile copy to clipboard button, if the main devs would give an okay as well.

That's right, as long as the new features are reasonably simple / cosmetic we can add them.

**Comment by ggerganov** [comment]
I think this is not related to the changes in this PR - seems like the JS library that we use has been updated upstream: https://github.com/ggerganov/llama.cpp/pull/7670

**Comment by mounta11n** [comment]
Ahh okay I see, so there is nothing else I can do right now but waiting, right?

**Comment by LoopControl** [comment]
Excited at seeing a UI overhaul.

I tend to fallback to using the UI so great to see a refresh.

**Comment by mounta11n** [comment]
Hey guys, I would just like to ask politely whether there has been any progress in the meantime or how we should proceed? @mofosyne @ggerganov

**Review by ggerganov — APPROVED** [review]

**Comment by LoopControl** [comment]
Tried this out and it looks great.

Unfortunately, it looks like the new UI doesn't seem to be respecting any new-lines in the output and crams all the text together. If I switch back to the original UI, line breaks render correctly.

**Comment by hanishkvc** [comment]
@LoopControl @mounta11n there is a simple minded simplechat webui added to lllama.cpp now (it is under examples/server/public_simplechat). You may want to give it a shot also.

**Comment by khimaros** [comment]
@mounta11n it seems like this new UI is not taking advantage of the KV cache at all. each subsequent message results in completely re-evaluating the history of that chat. is this expected? see also https://github.com/ggerganov/llama.cpp/issues/7185

**Pull request merged**
