### PR TITLE
[WIP] agent example (w/ sandboxable Tools!) & improved OAI compatibility layer (in Python)

### PR DESCRIPTION
**Pull request by ochafik**
**Superseded by https://github.com/ggerganov/llama.cpp/pull/9639**

Still very rough, but sharing a draft to get early feedback on the general direction.

This is an experiment in adding **grammar-constrained** tool support to llama.cpp, with a simple example of running agentic code on top, and support for **sandboxing unsafe tools** (e.g. Python interpreter).

Instead of bloating `server.cpp` any further, this slaps a Python layer in front of it to handle [tool calling](https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models) (partly because it's hard to do things well w/o proper jinja2 support - templates handle tool calling *peculiarly at best*, and partly because this could be a way to simplify the C++ server and focus it on performance and security rather than dealing with schemas and chat templates; WDYT?).

So this PR has a long way to go, but here's what can be done with it:

<details>
<summary>Show install instructions</summary>

- Note: To get conda, just install Miniforge (it's OSS): https://github.com/conda-forge/miniforge
- For Docker (to sandbox unsafe tools), consider [lima](https://github.com/lima-vm/lima) (containerd / OSS) or [Docker Desktop](https://docs.docker.com/desktop/)

```bash
git clone https://github.com/ochafik/llama.cpp --branch agent-example --single-branch llama.cpp-agent
cd llama.cpp-agent
conda create -n agent python=3.11
conda activate agent
pip install -r examples/agent/requirements.txt

make clean && make -j server
```

</details>

```bash
python -m examples.agent \
    --model mixtral-8x7b-instruct-v0.1.Q8_0.gguf \
    --tools examples/agent/tools/example_math_tools.py \
    --greedy \
    --goal "What is the sum of 2535 squared and 32222000403 then multiplied by one and a half. What's a third of the result?"
```

<details>
<summary>Show output</summary>

```bash
🛠️  add, divide, multiply, pow
💭 First, I will calculate the square of 2535, then add it to 32222000403. After that, I will multiply the result by 1.5 and finally, I will divide the result by 3.
⚙️  pow(value=2535, power=2) -> 6426225.0
💭 Now that I have calculated the square of 2535, I will calculate the sum of 6426225 and 32222000403.
⚙️  add(a=6426225, b=32222000403) -> 32228426628
💭 Now that I have calculated the sum, I will multiply it by 1.5.
⚙️  multiply(a=32228426628, b=1.5) -> 48342639942.0
💭 Now that I have calculated the product, I will divide it by 3.
⚙️  divide(a=48342639942.0, b=3) -> 16114213314.0
➡️  The result of the calculation is 16114213314.0.
```

```bash
python -c "print((2535**2 + 32222000403)*1.5 / 3)"
# 16114213314.0
```

</details>

```bash
python -m examples.agent \
    --tools examples/agent/tools/fake_weather_tools.py \
    --goal "What is the weather going to be like in San Francisco and Glasgow over the next 4 days." \
    --greedy
```

<details>
<summary>Show output</summary>

```bash
🛠️  get_current_weather, get_n_day_weather_forecast
💭 I will first get the current weather in San Francisco, then get the 4-day weather forecast for both San Francisco and Glasgow.
⚙️  get_current_weather(location=San Francisco, format=fahrenheit) -> ...
💭 I will first get the current weather in San Francisco, then get the 4-day weather forecast for both San Francisco and Glasgow.
⚙️  get_n_day_weather_forecast(location=San Francisco, format=fahrenheit, num_days=4) -> ...
💭 I will first get the current weather in San Francisco, then get the 4-day weather forecast for both San Francisco and Glasgow.
⚙️  get_n_day_weather_forecast(location=Glasgow, format=celsius, num_days=4) -> ...
The current weather in San Francisco is sunny and 87.8F. Here is the 4-day weather forecast:

For San Francisco:
- In 1 day: Cloudy, 60.8F
- In 2 days: Sunny, 73.4F
- In 3 days: Cloudy, 62.6F

For Glasgow:
- In 1 day: Cloudy, 16C
- In 2 days: Sunny, 23C
- In 3 days: Cloudy, 17C
```

</details>

```bash
python -m examples.agent --std-tools --goal "Say something nice in 1 minute."
```

<details>
<summary>Show output</summary>

```bash
🛠️  ask_user, say_out_loud, wait_for_date, wait_for_duration
💭 Thinking about what to say in the next minute.
⚙️  say_out_loud(something="In the next minute, I'll share a kind and uplifting message. Please wait...") -> None
💭 Waiting for the specified duration.
⚙️  wait_for_duration(duration={"seconds": 60}) -> None
💭 Thinking about what to say after the waiting period.
⚙️  say_out_loud(something="Thank you for your patience. Here's a nice message for you: 'A smile is the prettiest thing you can wear. So let your smile shine through.' - Dolly Parton") -> None
➡️ "The task of saying something nice in 1 minute is complete."
```

</details>

Add `--verbose` to see what's going on, and look at [examples/agent/README](https://github.com/ochafik/llama.cpp/blob/agent-example/examples/agent/README.md) & [examples/openai/README](https://github.com/ochafik/llama.cpp/blob/agent-example/examples/openai/README.md) for more details.

## Tool sandboxing

Since tools can quickly become unsafe (don't want a rogue AI poking at your files), I've added a simple script to sandbox tools. It wraps a Python module as a REST server inside a Docker container exposing its port, and since it's using FastAPI it gives a neat OpenAPI schema that can be consumed by the agent code.

Run this in a separate terminal to get a sandboxed python interpreter (`DATA_DIR` will contain any files created by Python programs):

```bash
# Note: with limactl, the default sandbox location ~/.llama.cpp/sandbox won't be writable
# (see https://github.com/lima-vm/lima/discussions/393)
# export DATA_DIR=/tmp/lima/llama.cpp/sandbox
PORT=9999 examples/agent/run_sandboxed_tools.sh \
        examples/agent/tools/unsafe_python_tools.py

# INFO: using DATA_DIR: /Users/ochafik/.llama.cpp/sandbox
# ...
# INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
```

Then tell the agent to discover tools at the new endpoint:

```bash
python -m examples.agent \
    --tools http://localhost:9999 \
    --goal "Whats cos(123) / 23 * 12.6 ?"
```

<details>
<summary>Show output</summary>

```
💭 To calculate the given mathematical expression, I will use the 'execute_python' tool.
⚙️  execute_python(source="import math\nresult = math.cos(123) / 23 * 12.6") -> {'result': -0.4864525314920599}
➡️ "-0.4864525314920599"
```

</details>

```bash
python -m examples.agent \
    --tools http://localhost:9999 \
    --goal "Create a file with 100k spaces"
```

<details>
<summary>Show output</summary>

```
💭 To accomplish the task of creating a file with 100k spaces, I need to consider how to generate and save this content. I will use the 'execute_python' tool to create a Python script that generates the spaces and writes them to a file.
⚙️  execute_python(source="with open('spaces_file.txt', 'w') as f:\n\tf.write(' ' * 100000)\n") -> {}
➡️ "File 'spaces_file.txt' has been created with 100,000 spaces."
```

```bash
wc -c ~/.llama.cpp/sandbox/spaces_file.txt
# 100000 ~/.llama.cpp/sandbox/spaces_file.txt
```

</details>

```bash
python -m examples.agent \
    --tools http://localhost:9999 \
    --goal "Write and run a program with a syntax error, then fix it"
```

<details>
<summary>Show output</summary>

```
💭 I need to create a Python program with a syntax error, run it, and then correct the error.
⚙️  execute_python(source="def hello:\\n    print('Hello, world')\\nheelo()") -> Error: expected '(' (<string>, line 1)
💭 I see that there is a syntax error in the code due to a typo. I need to correct the typo and run the code again.
⚙️  execute_python(source="def hello():\\n    print('Hello, world')\\nhello()") -> Error: unexpected character after line continuation character (<string>, line 1)
💭 It seems there is another syntax error in the corrected code. I need to investigate the issue and run the code again.
⚙️  execute_python(source="def hello():\n    print('Hello, world')\nhello()") -> {}
➡️ "Hello, world"
```

</details>

## Everybody gets tool calling support!

Some models have been explicitly fine-tuned for tool usage (e.g. [Functionary](https://github.com/MeetKai/functionary) with temptative support in https://github.com/ggerganov/llama.cpp/pull/5695, or [Hermes 2 Pro Mistral 7B](https://huggingface.co/NousResearch/Hermes-2-Pro-Mistral-7B) which has a [nice repo about it](https://github.com/NousResearch/Hermes-Function-Calling)).

Some other models don't officially have support, at least in their OSS models... (Mixtral 👀)

But since https://github.com/ggerganov/llama.cpp/pull/5978, all can be coerced into sticking to a specific JSON schema.

This example supports the following tool prompting strategies in [examples/openai/prompting.py](https://github.com/ochafik/llama.cpp/blob/agent-example/examples/openai/prompting.py) (see [dizzying combos of outputs](https://github.com/ochafik/llama.cpp/blob/agent-example/examples/openai/test_chat_handlers.md)):

- `--style=thoughtful_steps`: the default unless Functionary template is detected.

    Constrains the output to JSON with the following TypeScript signature (which it advertises as JSON schema), which fully constrains all of the function arguments:

    ```ts
      {
        thought_about_next_step_only: string,
        next_step: (
          {result: T} |
          {
            tool_calls: (
              {name: "function1", arguments: {"arg1": ..., "arg2":...}} |
              {name: "function1", arguments: {"arg1": ..., "arg2":...}} |
              ...
            )[]
          }
        )
      }
      // Where T is the output JSON schema from the --format flag, or 'any'
    ```

    It seems quite important to give the model some space to think before it even decides whether it has the final output or needs extra steps (`thought` might work just as well, YMMV). Note that by default only 1 tool call is allowed, but for models that support parallel tool calling, you can pass `--parallel-calls` (Functionary does this well, but Mixtral-instruct tends to hallucinate)

- `--style=functionary_v2`: besides using the proper template, this formats the signatures to TypeScript and deals with interesting edge cases (TODO: check whether this model has the only template that expects function call's arguments to be a json string, as opposed to a JSON object)

- `--style=short` / `long`: announces tools in a `<tool>...schemas...</tool>` system call, and uses less constrained output that allows mixing text and `<tool_call>{json}</tool_call>` inserts. 

  Since there is no negative lookahead (nor reluctant repetition modifier), I found it hard to write a grammar that allows "any text not containing `"<tool_call>"` then maybe `<tool_call>`. I settled for something a bit brittle (`content := [^<] | "<" [^t<] | "<t" [^o<]`), suggestions welcome!

- `--style=mixtral`: __OK now it gets weird__. Mixtral works well w/ `--style=thoughtful_steps` (I just had to collapse `system` and `tool` messages into `user` messages as its chat template is very restrictive), but when prompted w/ `You have these tools <tools>{json schemas}</tools>`, it spontaneously calls tools with the semi-standard syntax used by Hermes too... except it has spurious underscore escapes 🤔

    ```
    Imma tell you what i'm doin'
    <tool\_call>
    {"arguments": ..., "name": "my\_weirdly\_escaped\_function\_name"}
    </tool\_call>`
    ```

    So in the `mixtral` style I just unescape underscores and we get a tool-calling Mixtral (style is otherwise much like `long` / `short` and would also benefit from more grammar features)

## TODOs

* [x] Auto discover tools exposed by an OpenAPI endpoint
* [x] Fix / mitigate occasional "lost child process" issue
* [x] Add a Python code tool + made sandbox to work
* [ ] Turn Python tool to notebook / capture stdout / handle errors properly
* [ ] Wait for spawned servers to be healthy
* [ ] Add model URL / HF loading support
* [ ] Send separate PR w/ (cleaner) JSON number length cap (context: I was asking Mixtral to divide by 3 and it multiplied by... 0.33333333333333...) → https://github.com/ggerganov/llama.cpp/pull/6555
* [ ] Send separate PR w/ gguf utils (kv reading, lazy kv map, reader example update)
* [ ] Get some general approval & integrate feedback
* [ ] Measure token overhead of schemas & compress tool call syntax if possible (TS signatures borrowed from Functionary already help)
* [ ] Stream all the things
* [ ] Finish unit tests (wrap grammar parsing tester from python?)
* [ ] Open discussion re/ grammar features: reluctant modifier maybe? Is it actually needed?
* [ ] Server integration tests
* [ ] Prepare code for review (doc strings)

### CODE REVIEW

**Comment by phymbert** [comment]
Thanks for the effort to bring this nice feature :1st_place_medal: . Please mind to push commits on your fork first as it triggers lot of CI runs on the main repo.

**Comment by ochafik** [comment]
> Please mind to push commits on your fork first as it triggers lot of CI runs on the main repo.

@phymbert sorry for the CI noise again today, wanted to get the PR in good working order. Branch `agent-example-tmp` will get most of the updates going forward (I might also experiment with [skip-checks:true](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs)).

**Comment by phymbert** [comment]
> @phymbert sorry for the CI noise again today, wanted to get the PR in good working order. 

Please forgive my comment, firstly because I am sure you do your best, then I personally pushed 60+ commits last 4 days ;) and now the CI is canceling concurrent jobs. Goid luck!

**Comment by HanClinto** [comment]
This is a bit off-topic, but I noticed in your example call:

```
python -m examples.agent \
    --model mixtral-8x7b-instruct-v0.1.Q8_0.gguf \
    --tools examples/agent/tools/example_math_tools.py \
    --greedy \
    ```
    
Is there a particular reason you're using greedy sampling? If so, I think there is an opportunity for speedup when using grammars and greedy sampling, but I wasn't sure how frequently greedy sampling was used, so I haven't chased it down yet.

**Comment by skoulik** [comment]
Good day @ochafik ,
I know you are busy with important things, but still.
I've been experimenting with your agent-example branch in an attempt to pair llama.cpp with llamaindex agentic api.
It _almost_ works as expected. The only glitch I've found so far is that llamaindex barks at me, because it expects function arguments to be string (JSON escaped? and converted to string) while your agent returns them as pure JSON. Is it something that is supposed to be confugurable? Or is it just a WIP? An omission?

According to the official OpenAI API, they produce string, too, look here, for instance:
https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models

Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_ujD1NwPxzeOSCbgw2NOabOin', function=Function(**arguments='{\n  "location": "Glasgow, Scotland",\n  "format": "celsius",\n  "num_days": 5\n}'**, name='get_n_day_weather_forecast'), type='function')]), internal_metrics=[{'cached_prompt_tokens': 128, 'total_accepted_tokens': 0, 'total_batched_tokens': 273, 'total_predicted_tokens': 0, 'total_rejected_tokens': 0, 'total_tokens_in_completion': 274, 'cached_embeddings_bytes': 0, 'cached_embeddings_n': 0, 'uncached_embeddings_bytes': 0, 'uncached_embeddings_n': 0, 'fetched_embeddings_bytes': 0, 'fetched_embeddings_n': 0, 'n_evictions': 0, 'sampling_steps': 40, 'sampling_steps_with_predictions': 0, 'batcher_ttft': 0.035738229751586914, 'batcher_initial_queue_time': 0.0007979869842529297}])

**Comment by skoulik** [comment]
> Good day @ochafik , I know you are busy with important things, but still. I've been experimenting with your agent-example branch in an attempt to pair llama.cpp with llamaindex agentic api. It _almost_ works as expected. The only glitch I've found so far is that llamaindex barks at me, because it expects function arguments to be string (JSON escaped? and converted to string) while your agent returns them as pure JSON. Is it something that is supposed to be confugurable? Or is it just a WIP? An omission?
> 
> According to the official OpenAI API, they produce string, too, look here, for instance: https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models
> 
> Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_ujD1NwPxzeOSCbgw2NOabOin', function=Function(**arguments='{\n "location": "Glasgow, Scotland",\n "format": "celsius",\n "num_days": 5\n}'**, name='get_n_day_weather_forecast'), type='function')]), internal_metrics=[{'cached_prompt_tokens': 128, 'total_accepted_tokens': 0, 'total_batched_tokens': 273, 'total_predicted_tokens': 0, 'total_rejected_tokens': 0, 'total_tokens_in_completion': 274, 'cached_embeddings_bytes': 0, 'cached_embeddings_n': 0, 'uncached_embeddings_bytes': 0, 'uncached_embeddings_n': 0, 'fetched_embeddings_bytes': 0, 'fetched_embeddings_n': 0, 'n_evictions': 0, 'sampling_steps': 40, 'sampling_steps_with_predictions': 0, 'batcher_ttft': 0.035738229751586914, 'batcher_initial_queue_time': 0.0007979869842529297}])
> 
> Might be something to do with extra security/agents isolation.

Found expects_stringified_function_arguments ...

**Comment by ochafik** [comment]
@skoulik thanks so much for testing this out, and for reporting this stringification issue! The `expects_stringified_function_arguments` thing was me trying to work around some templates hard-coding that expectation of stringified args, but I hadn't dug enough to realize that's how things were actually meant to be 😅

Preparing a fix.

Also, I've been toying w/ moving some or all of that logic to C++, stay tuned :-D

**Comment by skoulik** [comment]
> 
> Preparing a fix.
> 
I've done a quick test and confirm that it works with Llamaingex example now.  Langchain will most likely work too.

> Also, I've been toying w/ moving some or all of that logic to C++, stay tuned :-D
> 
My five cents: I noticed that you've been experimenting with prompts throughout your commits history. I reckon it might be beneficial to have them customizable, too (in addition to the hard coded templates). People are going to use the server with plethora of different models, some of which might prefer another flavours of promts to work better.

> > Good day @ochafik , I know you are busy with important things
> 
> I mean, this is important to me too haha, but yeah I've been very side-tracked by real-life stuff / the Spring here 😎
No rush here, take your time and enjoy the life :)

**Pull request closed without merging**
