### PR TITLE
server : fix context shift

### PR DESCRIPTION
**Pull request by ggerganov**
This probably fixes the context shift functionality.

Also, continuation of #5104 - not sure if the `n_past_se` added there is really necessary, so I removed it. Needs testing.

### CODE REVIEW

**Comment by Green-Sky** [comment]
```
slot 0 is processing [task id: 283]
slot 0 : in cache: 264 tokens | to process: 0 tokens
slot 0 : kv cache rm - [264, end)
slot 0 : we have to evaluate at least 1 token to generate logits

print_timings: prompt eval time =      57.36 ms /     0 tokens (     inf ms per token,     0.00 tokens per second)
print_timings:        eval time =     106.73 ms /     5 runs   (   21.35 ms per token,    46.84 tokens per second)
print_timings:       total time =     164.10 ms
slot 0 released (269 tokens in cache)
{"timestamp":1706538015,"level":"INFO","function":"log_server_request","line":2356,"message":"request","remote_addr":"127.0.0.1","remote_port":53316,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 is processing [task id: 290]
slot 0 : in cache: 268 tokens | to process: 1 tokens
slot 0 : kv cache rm - [268, end)
slot 0: context shift - n_keep = 0, n_left = 511, n_discard = 255
slot 0: context shift - n_keep = 0, n_left = 511, n_discard = 255
slot 0: context shift - n_keep = 0, n_left = 511, n_discard = 255

print_timings: prompt eval time =      37.80 ms /     1 tokens (   37.80 ms per token,    26.45 tokens per second)
print_timings:        eval time =   19156.52 ms /  1000 runs   (   19.16 ms per token,    52.20 tokens per second)
print_timings:       total time =   19194.32 ms
slot 0 released (504 tokens in cache)
{"timestamp":1706538034,"level":"INFO","function":"log_server_request","line":2356,"message":"request","remote_addr":"127.0.0.1","remote_port":53326,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 is processing [task id: 1292]
slot 0 : in cache: 0 tokens | to process: 393 tokens
slot 0 : kv cache rm - [0, end)

print_timings: prompt eval time =     238.00 ms /   393 tokens (    0.61 ms per token,  1651.24 tokens per second)
print_timings:        eval time =     189.38 ms /     9 runs   (   21.04 ms per token,    47.52 tokens per second)
print_timings:       total time =     427.38 ms
slot 0 released (402 tokens in cache)
```
not sure its correct, will test more later.

**Review by Green-Sky — COMMENTED** [review]
style: not your fault, but it uses a mixture of `x--` and `x += 1`...

**Comment by Green-Sky** [comment]
while you are at it, pls add missing newlines to the help here https://github.com/ggerganov/llama.cpp/blob/5f62e231db3ec60320607ac6450ce9bf4dd43208/examples/server/server.cpp#L1825-L1826

**Comment by ggerganov** [comment]
There were some major issues still - I think I fixed those, but I'm still not sure if self-extend works now. Please let me know if you give it another try

**Comment by Green-Sky** [comment]
normal operation seems to be working now.
```
slot 0 is processing [task id: 12676]
slot 0 : in cache: 4093 tokens | to process: 0 tokens
slot 0 : kv cache rm - [4093, end)
slot 0 : we have to evaluate at least 1 token to generate logits
slot 0: context shift - n_keep = 0, n_left = 4094, n_discard = 2047
```

> There were some major issues still

**Comment by Green-Sky** [comment]
Self extend does not work. Either my settings are way off (not 100% on those values), or its just broken.
```
Available slots:
 -> Slot 0 - max context: 8192
 -> Slot 0 - self-extend: ga_n = 4, ga_w = 1024
{"timestamp":1706632770,"level":"INFO","function":"main","line":2541,"message":"model loaded"}
all slots are idle and system prompt is empty, clear the KV cache
{"timestamp":1706632840,"level":"INFO","function":"log_server_request","line":2354,"message":"request","remote_addr":"127.0.0.1","remote_port":55592,"status":200,"method":"GET","path":"/health","params":{}}
slot 0 is processing [task id: 0]
slot 0 : in cache: 0 tokens | to process: 4643 tokens
slot 0 : kv cache rm - [0, end)
slot 0 : applied self-extend to prompt: 0 tokens
Segmentation fault (core dumped)
```
@Maximilian-Winter

**Comment by Green-Sky** [comment]
update: running without selfextend now works properly, had my bot spam for hours with >20k server tasks and it was still fine. (beside the obv self deterioration when it keeps talking to itself)
```
...
InstructBot: (disappear)
InstructBot: (chuckles)
InstructBot: (voice) Goodbye and have a great day, everyone!
InstructBot: (disappear)
InstructBot: (chuckles)
InstructBot: (voice) If you need any assistance or have any questions, don't hesitate to ask InstructBot or myself.
InstructBot: (smiles)
InstructBot: (disappear)
InstructBot: (chuckles)
...
```

**Comment by Maximilian-Winter** [comment]
@Green-Sky Are you talking about my code or the code of this PR?

**Comment by Green-Sky** [comment]
> @Green-Sky Are you talking about my code or the code of this PR?

This pr with caching enabled. But since master with caching is broken too...

**Comment by Maximilian-Winter** [comment]
n_past_se was needed because otherwise the self extend won't work because all tokens of the prompt are added to the batch at once and the n_past is the total token count

**Comment by ggerganov** [comment]
I've reverted my changes on the self-extend for now, as it is difficult to test. But I think after we merge this PR in order to fix the context shift, we have to revisit and simplify the self-extend implementation. It's confusing to keep 2 values for `n_past`, so we should try improve this

**Comment by Maximilian-Winter** [comment]
@ggerganov I don't know if it is enough but calling it something like current_token_pos would maybe help?

**Comment by ggerganov** [comment]
That's one option, but I think there might be a way to do it with only `n_past`. Not sure though - need to look more into this. Let me know if you get any ideas

**Comment by Green-Sky** [comment]
btw, with both caching and self extend it does the log spam again:
```
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 256
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 128
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 64
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 32
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 16
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 8
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 4
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 2
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 1
update_slots : failed to decode the batch, n_batch = 1, ret = 1
```

but at least either seems to be working fine.

**Comment by Green-Sky** [comment]
It is still broken, but its way rarer now.

```
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 256
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 128
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 64
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 32
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 16
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 8
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 4
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 2
update_slots : failed to find free space in the KV cache, retrying with smaller n_batch = 1
update_slots : failed to decode the batch, n_batch = 1, ret = 1
```

**Comment by nelsonhurstdev** [comment]
Is there a new PR for this? I am getting the same spam messages for the KV cache. It seems to happen as soon as it reaches the context limit.  Unless I am using it wrong.

Is this the correct format?

/server.exe -ngl 99 --host localhost --port 5000 -c 8192 --grp-attn-n 4 --grp-attn-w 2048  -m D:/AI/LLM/Mixtral-8x7B-Instruct-v0.1.IQ3_XXS.gguf

**Comment by Green-Sky** [comment]
I saw https://github.com/ggerganov/llama.cpp/pull/5420, but did not test it yet. Or it is the one making it worse *shrug*

**Comment by ristew** [comment]
Possible it broke group attention, I was only testing without.

**Pull request merged**
