### PR TITLE
metal : parallel command buffer encoding

### PR DESCRIPTION
**Pull request by ggerganov**
Reading some Metal docs, this should be more efficient way to encode the Metal kernels:

- Use multiple command buffers
- Enqueue them at start
- Encode the commands in parallel on separate threads
- Each thread commits its buffer
- Wait for the last one to finish

On M1 Pro there is no difference in the measured inference time.

Still - interested to see if this is the same for other people.
Also might try this in combination with #1826 to see if this resolves the problems on some machines

### CODE REVIEW

**Comment by ikawrakow** [comment]
@ggerganov I see a 2.5% improvement on my 30-core M2 Max GPU at 7B (21.5 ms/token vs 22.0 ms/token on master). Difference becomes smaller at 13B: 38.4 ms on master vs 38.0 ms with this PR.

**Comment by johncronan** [comment]
Regarding your latter suggestion, I merged the two but I'm still getting gibberish.

**Comment by ymcui** [comment]
I didn't see noticeable speedup on M1 Max (32GB RAM) with our Chinese Alpaca-13B model.
Same as @johncronan , still get gibberish output for 33B model.

**Comment by djosh34** [comment]
<h1> Performance tests </h1>

<p>Based on what I've seen on my Macbook Pro (Apple M1 Pro 32GB 16 Core GPU), using this particular model with 13 billion parameters, I don't notice any major differences. It seems likely that any differences observed are due to random fluctuations in the data rather than any meaningful changes.</p>
<h3>Test metal-parallel-cb: 69bae5d</h3>


Test | Eval Time (ms)
-- | --
Test 1 | 94.55
Test 2 | 94.57
Test 3 | 94.66
Test 4 | 94.24
Test 5 | 94.34
Average | 94.472

<h3>Test master: 254a7a7</h3>


Test | Eval Time (ms)
-- | --
Test 1 | 94.80
Test 2 | 93.41
Test 3 | 95.13
Test 4 | 94.46
Test 5 | 95.35
Average | 94.63





<h1>Model</h1>
<pre><code class="language-rust">
llama.cpp: loading model from ./models/13B/Wizard-Vicuna-13B-Uncensored.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9031.70 MB (+ 1608.00 MB per state)
</code></pre>
<h1>Machine</h1>
<pre><code class="language-rust">Apple M1 Pro
RAM: 32 GB
GPU: 16 Cores
</code></pre>
<h1>Prompt</h1>
<pre><code class="language-rust">
Title: Crafting Compelling Stories: A Guide for AI Writers

Introduction:
Welcome, fellow AI writer! In this guide, we'll explore the art of crafting compelling stories that captivate readers. Let's dive in!

Chapter 1: Building Blocks

1.1 The Power of Plot:
Create a strong plot with engaging conflicts, well-paced narratives, and satisfying resolutions.

1.2 Breathing Life into Characters:
Develop relatable characters with desires, fears, and growth arcs. Craft authentic dialogue to reveal their personalities and build connections.

Chapter 2: Painting the Story World

2.1 Setting the Stage:
Craft vivid descriptions to transport readers to immersive settings. Strike a balance between detail and imagination.

2.2 Creating Atmosphere and Tone:
Set the mood with sensory details, word choices, and pacing. Create different tones to enhance the reader's experience.

Chapter 3: Unleashing Narrative Techniques

3.1 Points of View:
Choose the right perspective to engage readers and bring your story to life.

3.2 Mastering Dialogue:
Write natural and engaging dialogue that reveals emotions and advances the plot.

Chapter 4: Captivating Readers

4.1 Hooks and Introductions:
Grab readers' attention with intriguing openings that make them eager for more.

4.2 Weaving Tension and Conflict:
Build suspense, create conflicts, and escalate tension throughout your story.

Conclusion:
By applying these storytelling techniques, you'll craft compelling narratives that leave readers wanting more. Happy writing, fellow AI writer!

Write a long story about your passion of chickens:

Once upon a time
</code></pre>
<h1>Test metal-parallel-cb: 69bae5d</h1>
<h2>Test 1</h2>
<pre><code class="language-rust">llama_print_timings:        load time =  9303.34 ms
llama_print_timings:      sample time =   341.50 ms /   454 runs   (    0.75 ms per token)
llama_print_timings: prompt eval time = 16156.81 ms /   441 tokens (   36.64 ms per token)
llama_print_timings:        eval time = 42830.85 ms /   453 runs   (   94.55 ms per token)
llama_print_timings:       total time = 59377.74 ms
</code></pre>
<h2>Test 2</h2>
<pre><code class="language-rust">
llama_print_timings:        load time =  1252.56 ms
llama_print_timings:      sample time =   332.40 ms /   460 runs   (    0.72 ms per token)
llama_print_timings: prompt eval time = 15356.40 ms /   441 tokens (   34.82 ms per token)
llama_print_timings:        eval time = 43408.29 ms /   459 runs   (   94.57 ms per token)
llama_print_timings:       total time = 59144.38 ms
</code></pre>
<h2>Test 3</h2>
<pre><code class="language-rust">llama_print_timings:        load time =   725.83 ms
llama_print_timings:      sample time =   348.64 ms /   450 runs   (    0.77 ms per token)
llama_print_timings: prompt eval time = 15470.16 ms /   441 tokens (   35.08 ms per token)
llama_print_timings:        eval time = 42503.17 ms /   449 runs   (   94.66 ms per token)
llama_print_timings:       total time = 58370.33 ms
</code></pre>
<h2>Test 4</h2>
<pre><code class="language-rust">llama_print_timings:        load time =  1053.04 ms
llama_print_timings:      sample time =   300.58 ms /   427 runs   (    0.70 ms per token)
llama_print_timings: prompt eval time = 15350.88 ms /   441 tokens (   34.81 ms per token)
llama_print_timings:        eval time = 40146.60 ms /   426 runs   (   94.24 ms per token)
llama_print_timings:       total time = 55840.19 ms
</code></pre>
<h2>Test 5</h2>
<pre><code class="language-rust">
llama_print_timings:        load time =  1630.35 ms
llama_print_timings:      sample time =   257.03 ms /   355 runs   (    0.72 ms per token)
llama_print_timings: prompt eval time = 15549.40 ms /   441 tokens (   35.26 ms per token)
llama_print_timings:        eval time = 33395.23 ms /   354 runs   (   94.34 ms per token)
llama_print_timings:       total time = 49238.79 ms
</code></pre>
<h1>Test master: 254a7a7</h1>
<h2>Test 1</h2>
<pre><code class="language-rust">llama_print_timings:        load time =  2078.49 ms
llama_print_timings:      sample time =   367.06 ms /   511 runs   (    0.72 ms per token)
llama_print_timings: prompt eval time = 16798.91 ms /   441 tokens (   38.09 ms per token)
llama_print_timings:        eval time = 48347.26 ms /   510 runs   (   94.80 ms per token)
llama_print_timings:       total time = 65564.83 ms
</code></pre>
<h2>Test 2</h2>
<pre><code class="language-rust">llama_print_timings:        load time =   764.39 ms
llama_print_timings:      sample time =   256.24 ms /   349 runs   (    0.73 ms per token)
llama_print_timings: prompt eval time = 15358.24 ms /   441 tokens (   34.83 ms per token)
llama_print_timings:        eval time = 32507.36 ms /   348 runs   (   93.41 ms per token)
llama_print_timings:       total time = 48159.74 ms
</code></pre>
<h2>Test 3</h2>
<pre><code class="language-rust">llama_print_timings:        load time =   714.95 ms
llama_print_timings:      sample time =   354.14 ms /   496 runs   (    0.71 ms per token)
llama_print_timings: prompt eval time = 15518.18 ms /   441 tokens (   35.19 ms per token)
llama_print_timings:        eval time = 47089.92 ms /   495 runs   (   95.13 ms per token)
llama_print_timings:       total time = 63010.79 ms
</code></pre>
<h2>Test 4</h2>
<pre><code class="language-rust">llama_print_timings:        load time =   773.52 ms
llama_print_timings:      sample time =   308.98 ms /   428 runs   (    0.72 ms per token)
llama_print_timings: prompt eval time = 15435.33 ms /   441 tokens (   35.00 ms per token)
llama_print_timings:        eval time = 40332.40 ms /   427 runs   (   94.46 ms per token)
llama_print_timings:       total time = 56119.08 ms
</code></pre>
<h2>Test 5</h2>
<pre><code class="language-rust">llama_print_timings:        load time =   749.04 ms
llama_print_timings:      sample time =   415.89 ms /   586 runs   (    0.71 ms per token)
llama_print_timings: prompt eval time = 15637.79 ms /   441 tokens (   35.46 ms per token)
llama_print_timings:        eval time = 55781.94 ms /   585 runs   (   95.35 ms per token)
llama_print_timings:       total time = 71891.70 ms
</code></pre>

**Review by ggerganov — COMMENTED** [review]
Even though this does not bring any significant performance gains, I think it's better as it is the recommended way of populating the Metal kernels in the command queue

**Pull request merged**
