### PR TITLE
chore: Add hashsum for stablelm models

### PR DESCRIPTION
**Pull request by teleprint-me**
ref [#6920 (comment)](https://github.com/ggerganov/llama.cpp/pull/6920#issuecomment-2087827173)

### CODE REVIEW

**Comment by ggerganov** [comment]
You have to add the models in `chovert-hf-to-gguf-update.py` - read #6920

**Comment by arch-btw** [comment]
Related: https://github.com/ggerganov/llama.cpp/issues/7024

**Comment by teleprint-me** [comment]
@ggerganov I can do that, but I would recommend against it. It will couple the scripts, increase complexity, and is completely unneccessary for producing the output. Supppoting rationale for why would increase my confidence in this approach.

**Comment by slaren** [comment]
The function `get_vocab_base_pre` is generated by `convert-hf-to-gguf-update.py`, you are not supposed to edit it directly.

**Comment by teleprint-me** [comment]
@slaren Thanks, I'll need to review it again with fresh eyes. I must've missed it.

**Comment by teleprint-me** [comment]
Should I add the mi(s|x)tral BPE or SPM? I noticed that I can't convert the original models anymore with either script, but I can convert the safetensors.

**Comment by teleprint-me** [comment]
I really don't like this approach. This is gonna get really bad, really fast. I see the intent here to automate method though, not sure if it's any better than manually adding it. Still stand by my original stance with coupling and increased complexity. It's just extra steps to the same end goal.

**Comment by teleprint-me** [comment]
Don't merge this yet. I have some ideas.

**Pull request closed without merging**
