### PR TITLE
Update main's interactive mode to use the chat handshake templates support already available in llama.cpp (and currently only used by server,...)

### PR DESCRIPTION
**Pull request by hanishkvc**
Currently the interactive mode of main doesnt add any tags to identify system or user messages to the model, by default.

One will have to either
* use the seperate chatml mode to specifically work with chatml supported models.
* or pass in-prefix, in-suffix and reverse-prompt arguments as required to try and match the required chatting template.

This PR tries to add a generic chat mode to main, which can make use of any chat templates already added to llama_chat_apply_template_internal, which is currently used by server logic, but not main logic.

To help with the same a new chaton.hpp file is added to common, which contains
* llama_chat_apply_template_simple, which is a wrapper around llama_chat_apply_template(inturn internal) of lama.cpp
* llama_chat_reverse_prompt which helps add any needed reverse prompts for the requested template standard

To add new chat handshake templates remember to add needed logic to
* llama_chat_apply_template_internal (llama.cpp) and
* llama_chat_reverse_prompt (common/chaton.hpp)

To use this support pass -i and --chaton TEMPLATE_ID to main.
Currently supported templates is chatml and llama2, for other chat handshake template standards already support by chat_apply_template_internal, suitable reverse prompts need to be added to llama_chat_reverse_prompt.

### CODE REVIEW

**Comment by hanishkvc** [comment]
Adding the below patch to this PR, allows me to chat with llama3 also using main -i --chaton llama3

diff --git a/examples/server/utils.hpp b/examples/server/utils.hpp
index a8d43ac..21b224d 100644
--- a/examples/server/utils.hpp
+++ b/examples/server/utils.hpp
@@ -385,6 +385,7 @@ static json oaicompat_completion_params_parse(
     // We must add their end sequences to list of stop words
     llama_params["stop"].push_back("<|im_end|>"); // chatml
     llama_params["stop"].push_back("<end_of_turn>"); // gemma
+    llama_params["stop"].push_back("<|eot_id|>"); // llama3
 
     // Handle "response_format" field
     if (body.contains("response_format")) {
diff --git a/llama.cpp b/llama.cpp
index fa7c022..7be621f 100644
--- a/llama.cpp
+++ b/llama.cpp
@@ -119,6 +119,8 @@ static void llama_log_callback_default(ggml_log_level level, const char * text,
 #define LLAMA_LOG_INFO(...)  llama_log_internal(GGML_LOG_LEVEL_INFO , __VA_ARGS__)
 #define LLAMA_LOG_WARN(...)  llama_log_internal(GGML_LOG_LEVEL_WARN , __VA_ARGS__)
 #define LLAMA_LOG_ERROR(...) llama_log_internal(GGML_LOG_LEVEL_ERROR, __VA_ARGS__)
+#define LLAMA_LOG_DEBUG(...) llama_log_internal(GGML_LOG_LEVEL_DEBUG, __VA_ARGS__)
+
 
 //
 // helpers
@@ -17045,6 +17047,7 @@ static int32_t llama_chat_apply_template_internal(
     const std::string & tmpl,
     const std::vector<const llama_chat_message *> & chat,
     std::string & dest, bool add_ass) {
+    //LLAMA_LOG_DEBUG("DBUG:%s:%s\n", __func__, tmpl.c_str());
     // Taken from the research: https://github.com/ggerganov/llama.cpp/issues/5527
     std::stringstream ss;
     if (tmpl == "chatml" || tmpl.find("<|im_start|>") != std::string::npos) {
@@ -17090,6 +17093,22 @@ static int32_t llama_chat_apply_template_internal(
             }
         }
         // llama2 templates seem to not care about "add_generation_prompt"
+    } else if (tmpl == "llama3" || tmpl.find("<|start_header_id|>") != std::string::npos) {
+        for (auto message : chat) {
+            std::string content = message->content;
+            std::string role(message->role);
+            if (role == "system") {
+                ss << "<|start_header_id|>system<|end_header_id|>\n" << content << "\n<|eot_id|>\n\n";
+            } else if (role == "user") {
+                ss << "<|start_header_id|>user<|end_header_id|>\n" << content << "\n<|eot_id|>\n\n";
+            } else {
+                LLAMA_LOG_WARN("DBUG:%s:%s:%s\n", __func__, role.c_str(), content.c_str());
+                ss << "<|start_header_id|>" << role << "<|end_header_id|>\n" << content << "\n<|eot_id|>\n\n";
+            }
+        }
+        if (add_ass) {
+            ss << "<|start_header_id|>assistant<|end_header_id|>\n";
+        }
     } else if (tmpl == "zephyr" || tmpl.find("<|user|>") != std::string::npos) {
         // zephyr template
         for (auto message : chat) {

**Comment by DifferentialityDevelopment** [comment]
Did you add a flag for specifying the system roles message?

**Comment by ngxson** [comment]
I've made a detailed research on the same subject, so I strongly recommend you to refer to this issue: https://github.com/ggerganov/llama.cpp/issues/6391

Also, a new function named `llama_token_is_eog` will be introduced with llama3 in the other PR, so it's better to wait

**Comment by hanishkvc** [comment]
> This sounds like an excellent and much needed addition to main. Did you add a flag for specifying the system roles message?

In interactive mode (ie -i) any prompt file (-f) or prompt (-p) passed using the command line argument is treated as a system prompt and inturn this PR  formats it to match the system prompt template expected.

**Comment by arch-btw** [comment]
Here's the patch running with --verbose-prompt. I think there might be too many new lines?

```
main: prompt: '<|start_header_id|>system<|end_header_id|>
You are an assistant
<|eot_id|>

'
main: number of tokens in prompt = 11
128006 -> ''
  9125 -> 'system'
128007 -> ''
   198 -> '
'
  2675 -> 'You'
   527 -> ' are'
   459 -> ' an'
 18328 -> ' assistant'
   198 -> '
'
128009 -> ''
   271 -> '

'
main: static prompt based on n_keep: 'system
You are an assistant


'

main: interactive mode on.
Reverse prompt: '<|eot_id|>'
128009 -> ''

```

Without --verbose-prompt:


```
system
You are an assistant



> 
```

**Comment by hanishkvc** [comment]
There is a new PR, which is again a experiment which tries to use a simple minded json file to try and drive the logic, so that many aspects can be controlled by editing the json file, rather than needed to update the code.

https://github.com/ggerganov/llama.cpp/pull/6834

**Pull request closed without merging**
