### PR TITLE
cuda : rename build flag to LLAMA_CUDA

### PR DESCRIPTION
**Pull request by slaren**
`LLAMA_CUBLAS` still works for now to avoid breaking build scripts, but it prints a warning announcing that it will be removed in the future.

`GGML_USE_CUBLAS` is also renamed to `GGML_USE_CUDA`.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by slaren** [comment]
This also renames some targets in the RPM packages. cc @jboero

**Comment by jboero** [comment]
https://github.com/ggerganov/llama.cpp/pull/6304

**Comment by slaren** [comment]
Not sure why the nix CI is not completing, it seems to have timed out after 6 hours. The same things seems to be happening on master, so I don't think this PR is the cause.

**Comment by ikawrakow** [comment]
I think starting with this PR the nix CI is rebuilding ROCm each time (and timing out after 6 hours each time). In the previous merged PR #6298 and before nix ubuntu build was taking 22-23 minutes.

**Comment by slaren** [comment]
You can see the previous commit in master the nix run being cancelled after 5 hours (when this was merged).
https://github.com/ggerganov/llama.cpp/actions/runs/8424667760/job/23069080838

**Pull request merged**
