### PR TITLE
build : enable more non-default compiler warnings

### PR DESCRIPTION
**Pull request by cebtenzzre**
I compiled llama.cpp with clang's -Weverything option, and found some warning flags that I think we should use.

The new warnings are `-Wmissing-noreturn -Wextra-semi` for g++ and clang++, `-Wunreachable-code-break -Wunreachable-code-return` for clang and clang++, and `-Wrange-loop-bind-reference` for clang++.

I made a new `GGML_UNREACHABLE()` macro to cover some of the cases where it should be explicit that code is unreachable. It's basically `assert(false)`, but with the added benefit that it will compile to `__builtin_unreachable()` when assertions are disabled, both to enable compiler optimizations and to make sure no -Wreturn-type warnings appear because of the lack of a return statement at the end of a function.

Other included changes:
- Add missing 'static' specifiers
- Use -Werror=implicit-function-declaration for C
- Don't pass -Wdouble-promotion to old clang
- Build q8dot and benchmark-matmult in the Makefile by default

### CODE REVIEW

**Comment by Green-Sky** [comment]
did you check which version of the compilers support the flags?

**Comment by Cebtenzzre** [comment]
> did you check which version of the compilers support the flags?

It looks like -Wextra-semi was only added in GCC 7.1. master compiles fine with GCC 5. So I'll have to add some version checks to the build scripts.

**Review by ggerganov — APPROVED** [review]
Should merge after resolving conflicts

**Comment by ggerganov** [comment]
With CUDA builds, I think the `-Wpedantic` now spams the build with the following warning for every line:

```
...

In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/home/ubuntu/ggerganov/llama.cpp/ggml-cuda.cu:1295:3: warning: style of line directive is a GCC extension
 1295 | 
      |   ^
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/tmp/tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:5:3: warning: style of line directive is a GCC extension
    5 | #if !defined(__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__)
      |   ^~~~
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/home/ubuntu/ggerganov/llama.cpp/ggml-cuda.cu:1297:3: warning: style of line directive is a GCC extension
 1297 | 
      |   ^   
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/home/ubuntu/ggerganov/llama.cpp/ggml-cuda.cu:1297:3: warning: style of line directive is a GCC extension
 1297 | 
      |   ^   
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/home/ubuntu/ggerganov/llama.cpp/ggml-cuda.cu:1411:3: warning: style of line directive is a GCC extension
 1411 | 
      |   ^
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/tmp/tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:5:3: warning: style of line directive is a GCC extension
    5 | #if !defined(__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__)
      |   ^~~~
In file included from tmpxft_001370c3_00000000-7_ggml-cuda.cudafe1.stub.c:1:
/home/ubuntu/ggerganov/llama.cpp/ggml-cuda.cu:1413:3: warning: style of line directive is a GCC extension
 1413 | 

...
```

**Comment by slaren** [comment]
I also see that when building with cmake with CUDA enabled. The `Makefile` build disables `-Wpendatic` with nvcc to avoid this issue:
https://github.com/ggerganov/llama.cpp/blob/40e07a60f9ce06e79f3ccd4c903eba300fb31b5e/Makefile#L484

**Comment by Cebtenzzre** [comment]
I could try and change the structure of the flags to match the Makefile better. I wasn't really thinking about CUDA when I was porting my changes to CMake.

**Pull request merged**
