### PR TITLE
Publish gguf as a Pip package

### LINKED ISSUE #2702: Plans to publish `gguf` as a pip package?
Just wanted to ask if it is currently planned to distribute the `gguf.py` module as a pip package as it would enable consuming applications to easily read/write `gguf` files according to the defined spec.

### PR DESCRIPTION
**Pull request by monatis**
Closes #2702

This PR prepares GGUF as a Pip-installable package so that anyone can use it outside this repo as well.

https://pypi.org/project/gguf/

Developers should install it in editable mode with:

```sh
cd gguf-py
pip install --editable .
```

- I can add collaborators to the Pypi project upon request.
- My plan is gradually move conversion scripts to this package as command line entry points.
- In the future, it can be moved to its own repo with a collection of numerous conversion scripts, but it's currently fine to keep it in this repo for faster development.

### CODE REVIEW

**Comment by ggerganov** [comment]
Is there a way to make the convert scripts currently in the root of the repo to directly "see" the `gguf-py` code without having to install the pip dependency? Otherwise I think one would need to make a new version of the package for each change they would like to test. Or is this something that `pip install --editable .` fixes?

**Comment by monatis** [comment]
@ggerganov yes, with `pip install --editable .` any change in this repo will be instantly effective for conversion scripts as well --no need to re-install it during development.

**Review by ggerganov — APPROVED** [review]
Ok - let's merge when you think it is ready

**Comment by monatis** [comment]
Thanks --let's merge it as is --I'll add CI workflow for auto releases in an upcoming release

It'll require a secret in the repo, so I'll make sure that it's working before adding it.

**Comment by ggerganov** [comment]
Hm, something is not right. I get the following error:

```
 $ ▶ python3 convert.py 
Traceback (most recent call last):
  File "/Users/ggerganov/development/github/llama.cpp/convert.py", line 37, in <module>
    ARCH=gguf.MODEL_ARCH.LLAMA
         ^^^^^^^^^^^^^^^
AttributeError: module 'gguf' has no attribute 'MODEL_ARCH'
```

Maybe the package does not export the enums ?

**Comment by slaren** [comment]
Would it be possible to add a symlink to `gguf.py` in the root directory of the repository to avoid having to install the pip package?

**Pull request merged**
