### PR TITLE
Fallback to tokenizer.json if vocab.json does not exist

### LINKED ISSUE #5973: regression: convert.py Could not find any of ['vocab.json'] for deepseek-coder models (`--pad-vocab --vocab-type bpe`)
Regression commit 4d4d2366fc9c54d4a275065cfe9299c6cf7c5b78
```
python.exe convert.py --outtype f32 --pad-vocab --vocab-type bpe B:\deepseek-coder-7b-instruct-v1.5-qlora-amenokaku-code
...
Found vocab files: {'spm': None, 'bpe': None, 'hfft': WindowsPath('B:/deepseek-coder-7b-instruct-v1.5-qlora-amenokaku-code/tokenizer.json')}
Traceback (most recent call last):
  File "A:\gitproject\llama.cpp\convert.py", line 1479, in <module>
    main()
  File "A:\gitproject\llama.cpp\convert.py", line 1447, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type.split(","), model_parent_path)
  File "A:\gitproject\llama.cpp\convert.py", line 1323, in load_vocab
    vocab_type, path = self._select_file(vocab_types)
  File "A:\gitproject\llama.cpp\convert.py", line 1310, in _select_file
    raise FileNotFoundError(f"Could not find any of {[self._FILES[vt] for vt in vocab_types]}")
FileNotFoundError: Could not find any of ['vocab.json']
```
Same with the original deepseek-coder model.

git checkout aa2341298924ac89778252015efcb792f2df1e20 convert.py
OK

### LINKED ISSUE #6216: std::out_of_range: unordered_map::at: key not found while running deepseek-coder-33b-instruct
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

Macbook M1 pro max (64G Mem)
built llama with Release mode, using cmake.

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

reproduction steps:
```
git clone https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct
python ./convert.py --pad-vocab deepseek-coder-33b-instruct
./build/bin/quantize ./deepseek-coder-33b-instruct/ggml-model-f32.gguf ./deepseek-coder-33b-instruct/ggml-model-Q8_0 gguf Q8_0
```

execution log
```
Log start
main: build = 2483 (1943c019)
main: built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.3.0
main: seed  = 10281
llama_model_loader: loaded meta data with 26 key-value pairs and 561 tensors from ./deepseek-coder-33b-instruct/ggml-model-Q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = .
llama_model_loader: - kv   2:                           llama.vocab_size u32              = 32256
llama_model_loader: - kv   3:                       llama.context_length u32              = 16384
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 7168
llama_model_loader: - kv   5:                          llama.block_count u32              = 62
llama_model_loader: - kv   6:                  llama.feed_forward_length u32              = 19200
llama_model_loader: - kv   7:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   8:                 llama.attention.head_count u32              = 56
llama_model_loader: - kv   9:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  10:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  11:                       llama.rope.freq_base f32              = 100000.000000
llama_model_loader: - kv  12:                    llama.rope.scaling.type str              = linear
llama_model_loader: - kv  13:                  llama.rope.scaling.factor f32              = 4.000000
llama_model_loader: - kv  14:                          general.file_type u32              = 7
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,32256]   = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  17:                      tokenizer.ggml.scores arr[f32,32256]   = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,32256]   = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 32013
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 32021
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 32014
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  125 tensors
llama_model_loader: - type q8_0:  436 tensors
llm_load_vocab: SPM vocabulary, but newline token not found: unordered_map::at: key not found! Using special_pad_id instead.llm_load_vocab: mismatch in special tokens definition ( 243/32256 vs 256/32256 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32256
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 16384
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 62
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 19200
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 100000.0
llm_load_print_meta: freq_scale_train = 0.25
llm_load_print_meta: n_yarn_orig_ctx  = 16384
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 33.34 B
llm_load_print_meta: model size       = 33.00 GiB (8.50 BPW) 
llm_load_print_meta: general.name     = .
llm_load_print_meta: BOS token        = 32013 '<｜begin▁of▁sentence｜>'
llm_load_print_meta: EOS token        = 32021 '<|EOT|>'
llm_load_print_meta: UNK token        = 0 '!'
llm_load_print_meta: PAD token        = 32014 '<｜end▁of▁sentence｜>'
llm_load_tensors: ggml ctx size =    0.43 MiB
ggml_backend_metal_buffer_from_ptr: allocated buffer, size = 33554.00 MiB, (33554.06 / 49152.00)
llm_load_tensors: offloading 62 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 63/63 layers to GPU
llm_load_tensors:        CPU buffer size =   234.28 MiB
llm_load_tensors:      Metal buffer size = 33553.99 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 100000.0
llama_new_context_with_model: freq_scale = 0.25
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Max
ggml_metal_init: picking default device: Apple M1 Max
ggml_metal_init: loading '/Users/kangmo/src/llama.cpp/build/bin/default.metallib'
ggml_metal_init: GPU name:   Apple M1 Max
ggml_metal_init: GPU family: MTLGPUFamilyApple7  (1007)
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: simdgroup matrix mul. support = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 51539.61 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =   992.00 MiB, (34547.88 / 49152.00)
llama_kv_cache_init:      Metal KV buffer size =   992.00 MiB
llama_new_context_with_model: KV self size  =  992.00 MiB, K (f16):  496.00 MiB, V (f16):  496.00 MiB
llama_new_context_with_model:        CPU  output buffer size =   252.00 MiB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =   512.02 MiB, (35059.89 / 49152.00)
llama_new_context_with_model:      Metal compute buffer size =   512.00 MiB
llama_new_context_with_model:        CPU compute buffer size =    22.00 MiB
llama_new_context_with_model: graph nodes  = 2050
llama_new_context_with_model: graph splits = 2

system_info: n_threads = 10 / 10 | AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | 
libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
zsh: abort      ./build/bin/main -m ./deepseek-coder-33b-instruct/ggml-model-Q8_0.gguf --seed

```

### LINKED ISSUE #6238: #5821 breaks convert.py for models with additional vocabulary, resulting in garbage output
#5821 has changed the behaviour of how to convert models from HF with additional vocabulary, when the `--pad-vocab` option is needed, and the resulting conversion is unusable in llama.cpp and other clients such as LM Studio. I have tested it on multiple models, and others have reported the same. One example of such a model is [WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5](https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5). Here is the error output:

```
./llama.cpp/main -m WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5/ggml-model-f16.gguf -n 128
(...)
**Error**
libc++abi: terminating due to uncaught exception of type std::out_of_range: unordered_map::at: key not found
zsh: abort      ./llama.cpp/main -m WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5/ggml-model-f16.gguf -n 128
```

This happens both when only  `--pad-vocab` or `--pad-vocab --vocab-type hfft` are used during conversion. The other vocab types, `bpe` and `spm`, result in a failed conversion.

With `--pad-vocab --vocab-type bpe`:
```
Found vocab files: {'spm': None, 'bpe': None, 'hfft': PosixPath('WhiteRabbitNeo-33B-v1.5/tokenizer.json')}
Traceback (most recent call last):
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1479, in <module>
    main()
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1447, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type.split(","), model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1323, in load_vocab
    vocab_type, path = self._select_file(vocab_types)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1310, in _select_file
    raise FileNotFoundError(f"Could not find any of {[self._FILES[vt] for vt in vocab_types]}")
FileNotFoundError: Could not find any of ['vocab.json']
```

With `--pad-vocab --vocab-type spm`:
```
Found vocab files: {'spm': None, 'bpe': None, 'hfft': PosixPath('WhiteRabbitNeo-33B-v1.5/tokenizer.json')}
Traceback (most recent call last):
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1479, in <module>
    main()
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1447, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type.split(","), model_parent_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1323, in load_vocab
    vocab_type, path = self._select_file(vocab_types)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ssd/ai/llm-dev/llama.cpp/convert-4d4d236.py", line 1310, in _select_file
    raise FileNotFoundError(f"Could not find any of {[self._FILES[vt] for vt in vocab_types]}")
FileNotFoundError: Could not find any of ['tokenizer.model']
```

Previously, the required options were `--pad-vocab --vocab-type bpe`, and everything worked as expected. I have tested previous versions, and all the ones up to this one works. The last working version of convert.py is [aa23412](https://github.com/ggerganov/llama.cpp/tree/aa2341298924ac89778252015efcb792f2df1e20)

The changes that break it are in [4d4d236](https://github.com/ggerganov/llama.cpp/commit/4d4d2366fc9c54d4a275065cfe9299c6cf7c5b78)

### PR DESCRIPTION
**Pull request by CISC**
Fixes #6238
Fixes #6216
Fixes #5973

### CODE REVIEW

**Review by froggeric — APPROVED** [review]
Confirmed working. Tested with the previously mentioned WhiteRabbitNeo model. Conversion works fine with ` --pad-vocab --vocab-type bpe`. Without `--vocab-type`, it incorrectly identifies it at `hfft` and still produces a non-working file, which I think is back to the original behaviour.

**Review by froggeric — APPROVED** [review]
Reviewed code changes. Change from single item to list is ok, and adds missing fallback.

**Comment by cebtenzzre** [comment]
[deepseek-coder-33b-instruct](https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct/blob/61dc97b922b13995e7f83b7c8397701dbf9cfd4c/tokenizer_config.json#L33) and [WhiteRabbitNeo-33B-v1.5](https://huggingface.co/WhiteRabbitNeo/WhiteRabbitNeo-33B-v1.5/blob/97a5da2356633b1e49200ad21a9b0561a6c80134/tokenizer_config.json#L214) both specify LlamaTokenizer (SPM) as their tokenizer, but they obviously use a tokenizer.json compatible with BPE. This issue should be reported upstream, as it is the root cause of this issue - if they specified GPT2Tokenizer it would most likely work without any need for --vocab-type.

**Comment by CISC** [comment]
@cebtenzzre It should probably be reported upstream, but it's a little late now as there are plenty of DeepSeek derivatives, however I don't see how it would have any impact on convert.py as it would still not work without `--vocab-type` (BPE is not considered by default), even with existing vocab.json. This PR restores previous behaviour if vocab.json is missing.

@froggeric Thank you for reviewing. :)

**Comment by cebtenzzre** [comment]
> I don't see how it would have any impact on convert.py

The default vocab type as of my PR is `spm,hfft`. If it weren't for a) the bytes_to_unicode mapping being moved out of the conversion scripts in #3252, b) deepseek models claiming to use the Llama tokenizer, and c) tokenizer_model of HfVocab being fixed to `llama` instead of based on tokenizer_class, the `hfft` step would just work.

**Review by cebtenzzre — APPROVED** [review]

**Review by cebtenzzre — CHANGES_REQUESTED** [review]
Actually, could we also throw an exception in HfVocab if type(self.tokenizer) isn't one of:
```
LlamaTokenizer
LlamaTokenizerFast
CodeLlamaTokenizer
CodeLlamaTokenizerFast
GemmaTokenizer
GemmaTokenizerFast
```
?

**Comment by CISC** [comment]
> Actually, could we also throw an exception in HfVocab if type(self.tokenizer) isn't one of:
> ...

Well, two issues with that:
* Why add an artificial limitation (that would also need to be maintained for no apparent reason)?
* It's not relevant to this PR, should be a separate one IMO.

**Comment by cebtenzzre** [comment]
> * Why add an artificial limitation (that would also need to be maintained for no apparent reason)?

This issue manifests as a crash at runtime instead of an error at conversion time. This is because of two reasons:
- The model actually claims to have an spm vocab, even though it does not;
- HfVocab uses AutoTokenizer and *assumes* that the model has an spm vocab.

If that check is added, one will not waste time trying to convert e.g. [Aquila-7B](https://huggingface.co/BAAI/Aquila-7B/tree/main) with the default --vocab-type and then wondering why it crashes with an unclear error, which is a problem that didn't happen when hfft was opt-in. It would also help once the tokenizer_class in the deepseek models are fixed.

**Comment by CISC** [comment]
> This issue manifests as a crash at runtime instead of an error at conversion time. This is because of two reasons:
> 
> * The model actually claims to have an spm vocab, even though it does not;

Does it? The config sets it to [LlamaTokenizerFast](https://huggingface.co/docs/transformers/v4.39.1/en/model_doc/llama2#transformers.LlamaTokenizerFast) and that works fine for conversion (and running on transformers), it only fails when loading as SPM instead of BPE.

Either way I fear blocking conversion on unspecified tokenizer classes will become unmaintable.

> * HfVocab uses AutoTokenizer, yet it [_assumes_](https://github.com/ggerganov/llama.cpp/blob/b06c16ef9f81d84da520232c125d4d8a1d273736/convert.py#L462) that the model has an spm vocab.

I think perhaps this is a larger part of the issue, though I'm not sure how/where to fix that, is the vocab type assumed later on when setting/getting tokenizer_model in the GGUF?

> If that check is added, one will not waste time trying to convert e.g. [Aquila-7B](https://huggingface.co/BAAI/Aquila-7B/tree/main) with the default --vocab-type and then wondering why it crashes with an unclear error, which is a problem that didn't happen when hfft was opt-in. It would also help once the tokenizer_class in the deepseek models are fixed.

Only because spm,bpe was default then. :)

**Comment by cebtenzzre** [comment]
> Does it? The config sets it to [LlamaTokenizerFast](https://huggingface.co/docs/transformers/v4.39.1/en/model_doc/llama2#transformers.LlamaTokenizerFast) and that works fine for conversion (and running on transformers), it only fails when loading as SPM instead of BPE. I'm guessing transformers is more lenient than llama.cpp?

True, it does work in practice, even though it's the wrong class - you can tell from tokenizer.json that this is a GPT2-style BPE tokenizer, not a Llama-style BPE tokenizer. The better way is to inspect tokenizer.json to identify which kind of tokenizer it is - I'm working on a PR that does that, as well as some other refactoring.

> Only because spm,bpe was default then. :)

Was spm,bpe ever the default? Before my PR, spm was the default, so it would fail unless tokenizer.model was found:
https://github.com/ggerganov/llama.cpp/blob/c7a0ad8ec9ebb5ddb1c1c80c82f2ee041c525d47/convert.py#L1390
https://github.com/ggerganov/llama.cpp/blob/c7a0ad8ec9ebb5ddb1c1c80c82f2ee041c525d47/convert.py#L1335-L1338

**Comment by CISC** [comment]
> True, it does work in practice, even though it's the wrong class - you can tell from tokenizer.json that this is a GPT2-style BPE tokenizer, not a Llama-style BPE tokenizer. The better way is to inspect tokenizer.json to identify which kind of tokenizer it is - I'm working on a PR that does that, as well as some other refactoring.

That sounds like a much nicer solution, hope that works out.

> Was spm,bpe ever the default? Before my PR, spm was the default, so it would fail unless tokenizer.model was found:

No, sorry, I got mixed up.

**Pull request closed without merging**
