### PR TITLE
fix: add POSIX functionality for Linux compilation

### LINKED ISSUE #54: error: 'CLOCK_MONOTONIC' undeclared
The initial `make` fails with `CLOCK_MONOTONIC undeclared`
```
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:  
I CC:       cc (Alpine 12.2.1_git20220924-r9) 12.2.1 20220924
I CXX:      g++ (Alpine 12.2.1_git20220924-r9) 12.2.1 20220924

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3   -c ggml.c -o ggml.o
ggml.c: In function 'ggml_time_ms':
ggml.c:309:5: warning: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
  309 |     clock_gettime(CLOCK_MONOTONIC, &ts);
      |     ^~~~~~~~~~~~~
ggml.c:309:19: error: 'CLOCK_MONOTONIC' undeclared (first use in this function)
  309 |     clock_gettime(CLOCK_MONOTONIC, &ts);
      |                   ^~~~~~~~~~~~~~~
ggml.c:309:19: note: each undeclared identifier is reported only once for each function it appears in
ggml.c: In function 'ggml_time_us':
ggml.c:315:19: error: 'CLOCK_MONOTONIC' undeclared (first use in this function)
  315 |     clock_gettime(CLOCK_MONOTONIC, &ts);
      |                   ^~~~~~~~~~~~~~~
make: *** [Makefile:182: ggml.o] Error 1
``` 

This can be solved by adding `-D_POSIX_C_SOURCE=199309L` to the `C{,XX}FLAGS` in the Makefile. See this Stackoverflow question: https://stackoverflow.com/questions/29666937/error-clock-monotonic-undeclared-first-use-in-this-function

### PR DESCRIPTION
**Pull request by valentynbez**
Small fix to compile binaries properly on Linux: 
- defines `CLOCK_MONOTONIC` in `ggml.c`
- Closes #54

### CODE REVIEW

**Comment by prusnak** [comment]
Can you add a short comment why this is required? (I assume some functions are not recognized but not obvious which ones)

**Comment by valentynbez** [comment]
Sure!

**Comment by prusnak** [comment]
> Sure!

I meant into the source code.

Btw the issue mentions `_POSIX_C_SOURCE=199309L`; why did you chose newer standard and thus less compatibility?

**Comment by valentynbez** [comment]
CentOS7 with GCC 10.2.0

**Comment by ggerganov** [comment]
This flags has been discussed in `whisper.cpp` too and I still don't know when it should be added and when not.
Hopefully someone can clarify.

https://github.com/ggerganov/whisper.cpp/issues/37
https://github.com/ggerganov/whisper.cpp/pull/576

**Comment by prusnak** [comment]
Now thinking more about this, probably the cleanest option is to add compilation flags to the build system like suggested in 

```
CFLAGS += -D_POSIX_SOURCE -D_GNU_SOURCE
CXXFLAGS += -D_POSIX_SOURCE -D_GNU_SOURCE
```

We can probably set this for all compilers on all OSes, because either a compiler understands the flag and sets the value to the supported level or the flag is ignored.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
