### PR TITLE
Fixed painfully slow single process builds.

### PR DESCRIPTION
**Pull request by jboero**
I've noticed the container builds are painfully slow as they don't enable parallel compilation. I always add the `-j` for defaulting to the number of available threads in the box which dramatically speeds up building.  This would also be beneficial for the GitHub Actions and testing.  Suggest this gets merged for automation sanity.

### CODE REVIEW

**Comment by slaren** [comment]
Worth keeping in mind that `make -j` does not default to the number of threads, but rather it removes any limits. Likely not an issue in most cases, but it can be very bad for systems/VMs with a very low number of processors.

**Comment by jboero** [comment]
> Worth keeping in mind that `make -j` does not default to the number of threads
It's interesting because I've always heard that but in most Linux environments I've used lately it defaults to number of threads. Maybe it would be more helpful to

`make -j$(nprocs)` if the nprocs command is available?

**Comment by slaren** [comment]
I think that should work, but I don't know much about docker.

**Comment by giuseppe** [comment]
> I think that should work, but I don't know much about docker.

`nproc` is cpuset aware so it works well from a container (i.e. if you limit the number of cpu cores a container can use, `nproc` will report the correct number of cores)

**Review by slaren — APPROVED** [review]

**Pull request merged**
