### PR TITLE
llama : allow gguf RoPE keys to be overridden with defaults

### PR DESCRIPTION
**Pull request by cebtenzzre**
@klosax is this what you had in mind? It seems like the simplest way to resolve your TODO comment. I'd like to find a solution to this before I add more RoPE keys in PR #2268.

This way, the fallback value is hardcoded in llm_load_hparams and not exposed anywhere else. This shouldn't matter, because with GGUF the API user can't assume the value of these parameters before they've loaded the model.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by shibe2** [comment]
I have an older model [codellama-34b.Q6_K.gguf](https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/blob/0acd3eb318bd1d2b331d02e94d57bff274e7f2cc/codellama-34b.Q6_K.gguf), and it outputs garbage after commit a5661d7e71d15b8dfc81bc0510ba912ebe85dfa3. Why would that be?

**Comment by Cebtenzzre** [comment]
> I have an older model [codellama-34b.Q6_K.gguf](https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/blob/0acd3eb318bd1d2b331d02e94d57bff274e7f2cc/codellama-34b.Q6_K.gguf), and it outputs garbage after commit [a5661d7](https://github.com/ggerganov/llama.cpp/commit/a5661d7e71d15b8dfc81bc0510ba912ebe85dfa3).

Well, codellama-34b does use a different rope_freq_base, so maybe this commit did somehow break it. What is the sha256sum of your model file? There are [two versions](https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/commits/main/codellama-34b.Q6_K.gguf).

**Comment by shibe2** [comment]
1002ef07afb15d208819c844f9b0e28b98b3c0c8da3df54521e727c17b45917c

**Comment by Cebtenzzre** [comment]
I'm still looking into this, but there's something really odd about that model file - the strings for the keys all have an embedded NUL byte at the end, which is counted towards their length. I don't know of any version of the llama.cpp GGUF writer that did that.

**Comment by ggerganov** [comment]
@shibe2 Do you observe the issue with a newly created converted model with the latest version of the code?

**Comment by shibe2** [comment]
[LlongOrca-7B-16k](https://huggingface.co/Open-Orca/LlongOrca-7B-16k) works with default parameters on 569550df20c1ede59ff195a6b6e900957ad84d16. I converted it again just now. Output on a short prompt matches exactly the output of my previous conversion. Also, information retrieval from a long text works.

**Pull request merged**
