### PR TITLE
ggml : remove OpenCL

### PR DESCRIPTION
**Pull request by ggerganov**
Superseded by Vulkan

### CODE REVIEW

**Comment by MaggotHATE** [comment]
@ggerganov Fyi, Vulkan still suffers substantial memory allocation issue, especially with large context sizes (which are still within the model specifications), reported multiple times. Removing Clblast before this was fixed is a really bad move. It essentially locks users with 16GB RAM out of 7B models and larger.

Judging by this PR, the footprint of Clblast was minimal, so removing it doesn't make sense. As much as I want it, **current implementation of Vulkan does not supersede Clblast**.

Additionally, you didn't even announce this change as you did previously with similar ones. I understand, that technically it's not a breaking change, but it's an important feature, even if it was **partly** (MoE, mostly) broken for a long time.

**Comment by Sur3** [comment]
With CLBLAST I was able to run small models on my integrated Skylake GT2 [HD Graphics 520] with the full 8GB of RAM of my Laptop as VRAM. Will test Vulkan backend, hope it is no regression..

**Comment by Sur3** [comment]
Yeah no way Vulkan is an adequate replacement for OpenCL, with CLBLAS my model loads almost instantly and with Vulkan I am stuck at the loading screen..

**Comment by Sur3** [comment]
Also with Vulkan I run out of Memory with models that fully load fine with OpenCL:

```Vulkan takes endless time and then runs out of memory
ggml_vulkan: Found 1 Vulkan devices:
Vulkan0: Intel(R) HD Graphics 520 (SKL GT2) (Intel open-source Mesa driver) | uma: 1 | fp16: 1 | warp size: 32
llm_load_tensors: ggml ctx size =    0,32 MiB
ggml_vulkan: Device memory allocation of size 1516179456 failed.
ggml_vulkan: vk::Device::allocateMemory: ErrorOutOfDeviceMemory
llama_model_load: error loading model: unable to allocate backend buffer
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'dolphin-2.9.2-qwen2-7b-Q6_K.gguf'
main: error: unable to load model
```

```OpenCL loads fine instantly
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 7,62 B
llm_load_print_meta: model size       = 5,82 GiB (6,56 BPW) 
llm_load_print_meta: general.name     = dolphin-2.9.2-qwen2-7b
llm_load_print_meta: BOS token        = 11 ','
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
llm_load_tensors: ggml ctx size =    0,32 MiB
llm_load_tensors: offloading 28 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 29/29 layers to GPU
llm_load_tensors:        CPU buffer size =   426,36 MiB
llm_load_tensors:     OpenCL buffer size =  5532,43 MiB
```

Only upside of the Vulkan backend is maybe that if it finally loads on a model it will use ~90% of my GPU compared of ~80% with OpenCL, but I didn't measure yet if this also results in a speedup or only consumes more resources.

**Comment by jetro30087** [comment]
I tried Vulkan again after ignoring for a few months but the latest build crashes shortly after loading. OpenCL just worked no matter what hardware I through my installation on. I'm not sure how vulkan can supersede OpenCL when I just can't trust it to work on alot hardware. 

It would be better just to say there is no unified library and tell devs they are on their own for compatibility.

**Comment by Sur3** [comment]
Something is seriously wrong with the vulkan code, when using the vulkan code I get random output like `*(($"$&"$%***$` when without vulkan I get normal text with the same prompt.

**Comment by vt-alt** [comment]
CLBlast was versatile and supporting any OpenCL implementation including [nvidia, amd, and cpu](https://cnugteren.github.io/clblast/clblast.html) (for example via [PoCL](https://github.com/pocl/pocl?tab=readme-ov-file#gpu-support-on-different-architectures)) via OpenCL ICD loader. So it's a pity the support is removed.

**Comment by okias** [comment]
Seriously, Vulkan isn't replacement of OpenCL. Can we get this code back?

**Pull request merged**
