### PR TITLE
Add Smaug 70B support to conversion

### PR DESCRIPTION
**Pull request by bartowski1182**
Converted, quanted, and ran with no issue with these changes

https://huggingface.co/abacusai/Smaug-Llama-3-70B-Instruct

### CODE REVIEW

**Comment by bartowski1182** [comment]
Do I need to be at all concerned about the tests that got cancelled/skipped?

**Comment by ggerganov** [comment]
I noticed that the pre-tokenizer config of this model is slightly different from DBRX. The regex is the same, but the other config params differ. Should make sure that they are compatible by running more extensive tokenization tests

**Comment by ggerganov** [comment]
I usually create a vocab and then run tokenization on wikitext:

```bash
python3 convert-hf-to-gguf.py models/tokenizers/dbrx/ --outfile models/ggml-vocab-dbrx.gguf --vocab-only

./tests/test-tokenizer-0.sh dbrx ./build/wikitext-2-raw/wiki.train.raw
```

If all is good, it should output `Tokenization is correct!`

Though this test is not exhaustive and even if it passes it does not guarantee correctness. @jaime-m-p has been recently doing significant improvements to the tokenization tests, but I haven't studied in details yet #7375

**Comment by bartowski1182** [comment]
Okay I'll give that a look! 

Only reason I clumped it in with DBRX was because it seemed it only needed the regex support same as DBRX, hopefully tests will help show if that's true

**Comment by bartowski1182** [comment]
@ggerganov I'm hoping I did this correctly:

python3 ./tests/test-tokenizer-0.py /models/Smaug-Llama-3-70B-Instruct/ --fname-tok /training_data/wikitext-2-raw/wiki.train.raw

python3 convert-hf-to-gguf.py --outfile ./models/ggml-vocab-smaug-bpe.gguf --vocab-only /models/Smaug-Llama-3-70B-Instruct/

./test-tokenizer-0.sh smaug-bpe /training_data/wikitext-2-raw/wiki.train.raw

make: 'tests/test-tokenizer-0' is up to date.
Testing smaug-bpe on /training_data/wikitext-2-raw/wiki.train.raw ...
main : tokenized in 13682.403 ms (cpp)
Tokenization is correct!

**Comment by bartowski1182** [comment]
I ran it manually ahead of time because my models are in weird locations 

the first line I posted is me manually running the python tokenizer:

python3 ./tests/test-tokenizer-0.py /models/Smaug-Llama-3-70B-Instruct/ --fname-tok /training_data/wikitext-2-raw/wiki.train.raw

**Comment by bartowski1182** [comment]
the line in the test itself fails due to my weird model locations but the diff would also fail if the file didn't exist, so since I made it before hand it exists and matches

**Comment by ggerganov** [comment]
Ah yes, thats' correct. So this is good, but keep in mind there could be surprises with the tokenization in some edge cases

**Review by ggerganov — APPROVED** [review]

**Comment by bartowski1182** [comment]
@jaime-m-p any recommendations? is this okay to merge in the interim or should that issue be resolved?

**Comment by bartowski1182** [comment]
@ggerganov Think this is good to merge based on jaime's comment here: https://github.com/ggerganov/llama.cpp/pull/7530#issuecomment-2131499637

**Pull request merged**
