### PR TITLE
Cleanup/Minimalization of C++ Reflection patch

### PR DESCRIPTION
**Pull request by jmikedupont2**
Working now, is much cleaner

### CODE REVIEW

**Review by Galunid — CHANGES_REQUESTED** [review]
>Regarding turning ggml to C++ - definitely not an option.
But appreciate the effort in this PR and don't mind having it live as a separate branch.

https://github.com/ggerganov/llama.cpp/pull/4155#issuecomment-1822741861

**Comment by Galunid** [comment]
I'm not sure if we should create a separate branch in this repo and merge this PR there, or if we should just leave this PR open?

**Comment by jmikedupont2** [comment]
so I have added some more commits that dump out more data as example, I am working on a slow trace of all the tensors value in there now.

**Comment by jmikedupont2** [comment]
https://github.com/ggerganov/llama.cpp/pull/4228 I split out the viz stuff into its own branch and rebased this. it cleanly rebased off of master. I am very happy with it.

**Comment by jmikedupont2** [comment]
finally some feedback after spending weeks on these patches. not very nice

**Pull request closed without merging**
