### PR TITLE
ci: add debug build to sanitzier build matrix

### PR DESCRIPTION
**Pull request by Green-Sky**
discovered ggml.c does not compile in Debug right now.

### CODE REVIEW

**Comment by Green-Sky** [comment]
for some reason it compiles in ci in debug. looking at why.

**Comment by Green-Sky** [comment]
the ci results: https://github.com/Green-Sky/llama.cpp/actions/runs/4525140706

for reference, the compile error:
```
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5839:20: error: ‘ne13’ undeclared (first use in this function); did you mean ‘nb13’?
 5839 |     assert(ne03 == ne13);
      |                    ^~~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5840:12: error: ‘ne2’ undeclared (first use in this function); did you mean ‘nb2’?
 5840 |     assert(ne2  == ne12);
      |            ^~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5841:12: error: ‘ne3’ undeclared (first use in this function); did you mean ‘nb3’?
 5841 |     assert(ne3  == ne13);
      |            ^~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5844:12: error: ‘nb00’ undeclared (first use in this function); did you mean ‘nb0’?
 5844 |     assert(nb00 == sizeof(float));
      |            ^~~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5852:12: error: ‘ne0’ undeclared (first use in this function); did you mean ‘nb0’?
 5852 |     assert(ne0 == ne01);
      |            ^~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5853:12: error: ‘ne1’ undeclared (first use in this function); did you mean ‘nb1’?
 5853 |     assert(ne1 == ne11);
      |            ^~~
/home/runner/work/llama.cpp/llama.cpp/ggml.c:5809:15: warning: unused variable ‘ne10’ [-Wunused-variable]
 5809 |     const int ne10 = src1->ne[0];
      |               ^~~~
```

**Comment by Green-Sky** [comment]
> Why does it say "All checks have passed"?

you mean for this pr? that's because it does not build for non code changes in prs...

**Comment by Green-Sky** [comment]
> You could uncomment those lines and add #ifndef NDEBUG around it, I've already done that in a pending PR

make a pr and i will rebase :smile:

**Review by sw — APPROVED** [review]

**Comment by anzz1** [comment]
> Why does it say "All checks have passed"? It's not doing the CI checks?

The `pull_request` target does not have write permissions to the target repo (this repo) so that's why the workflows aren't set as triggers in PR's to avoid confusion of the changed workflow not working. The `pull_request_target` which isnt used here would have write permissions and should never be used in public repos, though many do not understanding the difference.

Workflow changes do trigger for pushes, so if the source repo has enabled actions (like @Green-Sky did) you can see the result of the changed workflow in the source repo where the commit was pushed. This is useful when you make a fork for a patch and want to play around with the actions in your own repo. There is also the `workflow_dispatch` trigger which simply means you can manually run the workflow for any branch in your own fork repo by going to "Actions -> CI -> Run workflow". I also added the "create new release" checkbox there so releases can be created from feature branches if you want to test making a release in ur fork before making a PR.

**Comment by anzz1** [comment]
To be honest, the "complete build" passing while the sanitizer builds fail can be a bit confusing, but it's necessary for now so that the whole build doesn't get canceled from the sanitizer errors.

It's just a temporary solution though, once we get rid of all the leaks and get all the sanitizer builds to pass, the `continue-on-error` flags should be removed so new leaks can't be introduced as they will fail the build.

**Comment by Green-Sky** [comment]
@anzz1 yea, we can tighten down the screws when stuff settles a bit.

**Pull request merged**
