### PR TITLE
Fix top k sampler in server example

### PR DESCRIPTION
**Pull request by ghost**
I noticed that the order in which the samplers were applied was different compared to the main example. I moved top k to be the first one.

### CODE REVIEW

**Comment by JohannesGaessler** [comment]
To the server devs: was there a conscious decision to order the sampling methods this way?

**Review by Green-Sky — APPROVED** [review]
looks like an oversight. assuming the one in main.cpp is correct LGTM

**Comment by digiwombat** [comment]
> To the server devs: was there a conscious decision to order the sampling methods this way?

There was not, I think it just got overlooked. I was considering implementing an array that could be passed with a request containing a sampler order so people could manually specify, a la KoboldAI, but never got around to it.

**Review by SlyEcho — APPROVED** [review]
We should pull out the sampling code into either llama.cpp or common.cpp or some other file...

**Review by JohannesGaessler — APPROVED** [review]
If I understand the source code correctly, only top_k sorts the candidates if they aren't already while tail_free, typical, and top_p require the candidates to be sorted already. So top_k first should be the correct way to do it.

**Pull request merged**
