### PR TITLE
Adding support for llama2.c models

### LINKED ISSUE #2379: llama : add support for llama2.c models
The new [llama2.c](https://github.com/karpathy/llama2.c) project provides means for training "baby" llama models stored in a custom binary format, with 15M and 44M models already available and more potentially coming out soon.

We should provide a simple conversion tool from `llama2.c` bin format to `ggml` format so we can run inference of the models in `llama.cpp`

Great task for people looking to get involved in the project

### LINKED ISSUE #2574: Segmentation fault in converting  my llama2c models to ggml.
hello ! 
I am try to convert my llama2c models to ggml.
but it looks like need a vocab file. so how can i get it ?

or How can i convert my tokenizer.model to a  GGML file?
i only have tokenizer.model  and tokenizer.bin now
```
$ ./bin/convert-llama2c-to-ggml --vocab-model ../../llama2.c.xs/tokenizer.model   --llama2c-model  ../../llama2.c.xs/out/model.bin   --llama2c-output-model ./xs
[malloc_weights:AK] Allocating [8000] x [288] = [2304000] float space for w->token_embedding_table
[malloc_weights:AK] Allocating [6] x [288] = [1728] float space for w->rms_att_weight
[malloc_weights:AK] Allocating [6] x [288] = [1728] float space for w->rms_ffn_weight
[malloc_weights:AK] Allocating [6] x [288] x [288] = [497664] float space for w->wq
[malloc_weights:AK] Allocating [6] x [288] x [288] = [497664] float space for w->wk
[malloc_weights:AK] Allocating [6] x [288] x [288] = [497664] float space for w->wv
[malloc_weights:AK] Allocating [6] x [288] x [288] = [497664] float space for w->wo
[malloc_weights:AK] Allocating [6] x [768] x [288] = [1327104] float space for w->w1
[malloc_weights:AK] Allocating [6] x [288] x [768] = [1327104] float space for w->w2
[malloc_weights:AK] Allocating [6] x [768] x [288] = [1327104] float space for w->w3
[malloc_weights:AK] Allocating [288] float space for w->rms_final_weight
llama.cpp: loading model from ../../llama2.c.xs/tokenizer.model
error loading model: unknown (magic, version) combination: 050a0e0a, 6b6e753c; is this really a GGML file?
llama_load_model_from_file: failed to load model
Segmentation fault (core dumped)

```

### PR DESCRIPTION
**Pull request by byte-6174**
As per [issue#2379](https://github.com/ggerganov/llama.cpp/issues/2379) this PR includes a script that reads the llama2.c models and saves them into ggml format. A readme is also included for ease of testing and use.

### CODE REVIEW

**Review by klosax — APPROVED** [review]

**Comment by klosax** [comment]
Looks good, but should be cleaned up according to failed checks.

**Review by SlyEcho — CHANGES_REQUESTED** [review]
Needs CMake lists.

**Review by SlyEcho — APPROVED** [review]

**Review by SlyEcho — CHANGES_REQUESTED** [review]
Could you look at issue #2574?

**Comment by klosax** [comment]
Similar https://github.com/ggerganov/llama.cpp/issues/2379#issuecomment-1672497582

I guess complete instructions on how to add the correct vocab is needed.

**Comment by klosax** [comment]
@byte-6174 Are the issues fixed?

**Comment by byte-6174** [comment]
yes.

**Comment by byte-6174** [comment]
note for custom-created tokenizers there is an issue in main, as repored by @jrudolph here:
https://github.com/ggerganov/llama.cpp/issues/2580

but this shouldn't affect if tokenizers from llama2.c or llama.cpp are used.

**Review by SlyEcho — APPROVED** [review]
I tested one of Karpathy's models and it seems to be working.

**Pull request merged**
