### PR TITLE
Server enhancements - grammar segfault and helper titles.

### PR DESCRIPTION
**Pull request by jboero**
I noticed the server example segfaults on a null context if the grammar can't be parsed. This is fixed.

I also added titles with helpful mouseover explanations in the UI to help people understand n_predict, top_k, etc:

image

### CODE REVIEW

**Comment by jboero** [comment]
Aaah smacked down by trailing whitespace. Reviewbot must be a python coder.

**Review by ggerganov — APPROVED** [review]
Nice!

Should we change the `deps.sh` script to output raw string literals?

**Comment by jboero** [comment]
Oh is that why they were written that way? Yes that would be great for
readability.

**Comment by ggerganov** [comment]
After rebasing and fixing the EditorConfig Checker we can merge

**Comment by jboero** [comment]
Thx. :+1: 
https://github.com/ggerganov/llama.cpp/pull/5221

**Comment by ggerganov** [comment]
I think this PR is quite outdated - probably not relevant anymore?

**Comment by jboero** [comment]
Good question. I'll take another look but I think the segfault fix on no grammar is still important. Unless another PR fixed it.

**Comment by mofosyne** [comment]
Is this bug still present? Just chasing up older PRs to make sure it's not obsolete

**Comment by jboero** [comment]
It looks like @ggerganov fixed this directly so no need anymore.
https://github.com/ggerganov/llama.cpp/blob/e2b065071c5fc8ac5697d12ca343551faee465cc/common/sampling.cpp#L17

**Pull request closed without merging**
