### PR TITLE
Documentation fix: Quantum -> Quantized.

### PR DESCRIPTION
**Pull request by Ujjawal-K-Panchal**
- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

## Description of changes
I just fixed a small spelling error at imatrix/readme and server/readme (specifically: quantum models -> quantized models). While it would be great to have support for Quantum Mechanics based language models in future [1](https://arxiv.org/abs/2008.09943), I am sure this refers to quantized models (models compressed by reducing precision of parameters).

## Why I bothered making such a small PR?

I refer to these documents (imatrix/readme, server/readme) very often. At first, I just ignored the spellchecks. After a while, it became irritating. So here I am.

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
Adding Quantum in your llm model name increases t/s by 20%.

**Comment by ggerganov** [comment]
Isn't "quantum" actually more appropriate than "quantized"? That's why we say "quantum physics" instead of "quantized physics".

**Comment by ngxson** [comment]
> Isn't "quantum" actually more appropriate than "quantized"? That's why we say "quantum physics" instead of "quantized physics".

Hmm not sure but I think "quantized" here meaning [quantization in signal processing](https://en.wikipedia.org/wiki/Quantization_(signal_processing)), not in physics (or I didn't get the joke? let me know if I should remove my comment)

**Comment by ggerganov** [comment]
Heh, I wasn't joking - I genuinely think that "quantum model" is correct. Yes, the process of converting continuous values into discrete values is "quantization". In a similar way, in _quantum_ mechanics, bound states are _quantized_ to discrete quantities [0]. I'm drawing the analogy that quantum mechanics is modelling nature, similar to how LLMs are modelling language and hence the same terminology should apply.

[0] - https://en.wikipedia.org/wiki/Quantum_mechanics

**Comment by ngxson** [comment]
Hmm ok that make sense. Thanks for the explanation.

But mixing naming quantum/quantized maybe a bit confused, so I think this PR is not really redundant (just my opinion)

**Comment by Ujjawal-K-Panchal** [comment]
Interesting! While the ML community in general seems to use the word "quantized" (search "quantized" at: [1](https://huggingface.co/docs/optimum/en/concept_guides/quantization), [2](https://pytorch.org/docs/stable/quantization.html), [3](https://arxiv.org/pdf/2402.18158)), I see the analogy @ggerganov is making. Thanks for the explanation!

Maybe one could add a short note somewhere in the two docs for the average user about your analogy for clarity. What do you think about that?

**Comment by JohannesGaessler** [comment]
>Isn't "quantum" actually more appropriate than "quantized"? That's why we say "quantum physics" instead of "quantized physics".

No, I disagree. In quantum physics things like discrete energy levels are inherent properties. Models that have been compressed from 16 bit floats to low-precision integers on the other hand have been actively changed from their original state. I personally don't like or use the term "quantum model" because it in my opinion just sounds like some marketing buzzword but I ultimately think which term is used is inconsequential; to me this is on the same level as whether or not the first letter of a code comment should be capitalized and use punctuation at the end of the line.

**Review by ggerganov — APPROVED** [review]
I agree it's better to be consistent, rather than which term we use specifically. So let's go with the established "quantized models"

**Pull request merged**
