### PR TITLE
SOTA 2-bit quants - part 2

### PR DESCRIPTION
**Pull request by ikawrakow**
This PR is a followup of #4773 and adds inference for 2.31 bits per weight (bpw) quantized models as `IQ2_XS`.

Why have so many 2-bit quantizations? The focus of this project is "Inference at the edge", where RAM/VRAM is limited, but one still wants to be able to use as large as it gets LLMs. For quantization below 4 bpw quantization error increases much more rapidly with decreasing model size than above 4 bits. Hence, for 2-bit quants, one basically wants to use the largest quantized model that would fit in available RAM/VRAM to get the best possible model performance. Case in point, Mixtral-8x7B does not fit in my 16 GB card when quantized with `Q2_K`, but it fits when using `IQ2_XXS` from PR #4773, or `IQ2_XS` from this PR. With `IQ2_XS` quantization error is quite a bit lower (perplexity 4.514 versus 4.948 for `IQ2_XXS`), but I can only use a context of up to 2048 tokens with the model fully loaded on the GPU, while with `IQ2_XXS` I can use a context of up to 10,000 tokens. So, depending on use case, `IQ2_XXS` or `IQ2_XS` will be more useful. 

To illustrate the rapid change in quantization error with model size (as measured by perplexity), the table gives a few examples of quantized model sizes along with their resulting perplexities (context length = 4096 tokens) for `IQ2_XXS` (2.06 bpw) and `IQ2_XS` (2.31 bpw).

| Model | File size 2.06 bpw (GiB) | PPL 2.06 bpw | File size 2.31 bpw (GiB) | PPL 2.31 bpw |
|---:|---:|---:|---:|---:|
|Mistral-7B   | 1.855 | 6.446 | 2.047 | 5.822 |
|LLaMA-v2-7B  | 1.728 | 7.067 | 1.895 | 6.308 |
|LLaMA-v2-13B | 3.295 | 5.728 | 3.624 | 5.288 |
|Mixtral-8x7B | 11.44 | 4.948 | 12.73 | 4.514 |
|LLaMA-v2-70B | 17.03 | 4.079 | 18.94 |  3.783  |   

The approach used is very similar to #4773 with the following differences:
* 512 instead of 256 E8-lattice points are used. This adds 1 bit per group of 8 weights, so 0.125 bpw
* Blocks of 16 instead of blocks of 32 weights are used. This adds 4 bits per block of 32 weights, so another 0.125 bpw.    

Because of these changes, bits need to be arranged differently compared to `IQ2_XXS`, and hence one needs separate kernels for vector and matrix multiplication. These are added by this PR for CUDA, Metal, and CPU inference (scalar, AVX2, ARM_NEON).

As with #4773 the quantization functionality is missing. I will be adding 2.31-bpw quantized models to [this repository on Huggingface](https://huggingface.co/ikawrakow/various-2bit-sota-gguf) for now.

### CODE REVIEW

**Comment by ikawrakow** [comment]
I have added the following quantized models to [this Huggingface repository](https://huggingface.co/ikawrakow/various-2bit-sota-gguf):

| Quantization | File name | Original model |
|:---|:---|:---|
|IQ2_XXS | llama-v2-7b-2.20bpw.gguf | LLaMA-v2-7B |
|                | llama-v2-13b-2.17bpw.gguf | LLaMA-v2-13B |
|                | llama-v2-70b-2.12bpw.gguf | LLaMA-v2-70B |
|                | mistral-7b-2.20bpw.gguf | Mistral-7B-v0.1 |
|                | nous-hermes-2-10.7b-2.18bpw.gguf | Nous-Hermes-2-SOLAR-10.7B |
|                | nous-hermes-2-34b-2.16bpw.gguf | Nous-Hermes-2-Yi-34B |
|                | mixtral-8x7b-2.10bpw.gguf | Mixtral-8x7B-v0.1 |
|                | mixtral-instruct-8x7b-2.10bpw.gguf | Mixtral-instruct-8x7B-v0.1 |
|                | rocket-3b-2.31bpw.gguf | Rocket-3B |
|IQ2_XS   | llama-v2-7b-2.42bpw.gguf | LLaMA-v2-7B |
|                | llama-v2-13b-2.39bpw.gguf | LLaMA-v2-13B |
|                | llama-v2-70b-2.36bpw.gguf | LLaMA-v2-70B |
|                | mistral-7b-2.43bpw.gguf | Mistral-7B-v0.1 |
|                | mistral-instruct-7b-2.43bpw.gguf | Mistral-Instruct-7B-v0.2 |
|                | nous-hermes-2-10.7b-2.41bpw.gguf | Nous-Hermes-2-SOLAR-10.7B |
|                | nous-hermes-2-34b-2.40bpw.gguf | Nous-Hermes-2-Yi-34B |
|                | mixtral-8x7b-2.34bpw.gguf | Mixtral-8x7B-v0.1 |
|                | mixtral-instruct-8x7b-2.34bpw.gguf | Mixtral-instruct-8x7B-v0.1 |
|Q2_K      | nous-hermes-2-10.7b-2.70bpw.gguf | Nous-Hermes-2-SOLAR-10.7B |
|               | nous-hermes-2-34b-2.69bpw.gguf | Nous-Hermes-2-Yi-34B |
|               | rocket-3b-2.76bpw.gguf | Rocket-3B |

**Comment by JianbangZ** [comment]
Thank you.
Would you mind releasing a couple of q2 for https://huggingface.co/Qwen/Qwen-14B-Chat? or maybe you can public your private repo so people can tryout different model quantizations.

**Comment by ikawrakow** [comment]
> Thank you.
> Would you mind releasing a couple of q2 for https://huggingface.co/Qwen/Qwen-14B-Chat? or maybe you can public your private repo so people can tryout different model quantizations.

It will be just a few more days that I need to add all necessary changes to `llama.cpp` for people to quantize their own models. Concerning Qwen: I have absolutely no idea how to compute an importance matrix for a Chinese language focussed model. What is a good training dataset that I can use? For mostly English models as I have been releasing, one needs to run through, say, ~50k tokens, and I use `wiki.train.raw`. Is there something similar for Chinese?

**Comment by pipixia244** [comment]
> Is there something similar for Chinese?

Maybe [this repo](https://huggingface.co/datasets/pleisto/wikipedia-cn-20230720-filtered) can help.
This Chinese dataset, like the English training dataset, is also a wiki dataset from Wikipedia. I think this could be an example for quantizing Chinese language model.

**Comment by JianbangZ** [comment]
> > Thank you.
> > Would you mind releasing a couple of q2 for https://huggingface.co/Qwen/Qwen-14B-Chat? or maybe you can public your private repo so people can tryout different model quantizations.
> 
> It will be just a few more days that I need to add all necessary changes to `llama.cpp` for people to quantize their own models. Concerning Qwen: I have absolutely no idea how to compute an importance matrix for a Chinese language focussed model. What is a good training dataset that I can use? For mostly English models as I have been releasing, one needs to run through, say, ~50k tokens, and I use `wiki.train.raw`. Is there something similar for Chinese?

Qwen-14B-Chat is a bilingual model, which has respectful English performance. I think for now it's OK to still use wiki to do important matrix calculation. Once you publish/upstream your code, people can playwith with quantization themselves. It's interesting to do some experiment on how to handle importantce matrix with multi-lingual model, maybe need to form a multilingual dataset or maybe english dataset would be enough.

**Comment by ikawrakow** [comment]
@JianbangZ 
> Qwen-14B-Chat is a bilingual model, which has respectful English performance. I think for now it's OK to still use wiki to do important matrix calculation. 

I did a quick test with Qwen14B. For `wiki.test.raw` and a context of 512 tokens I get
* `PPL(fp16) = 7.5941`
* `PPL(Q4_K_S) = 7.7758` without importance matrix, and `PPL(Q4_K_S) = 7.7171` with importance matrix from `wiki.train.raw`. So quantization error is 2.39% / 1.62% without/with importance matrix.
* `PPL(IQ2_XS) = 8.5681` (this PR), so quantization error is 12.8%.
* `PPL(IQ2_XXS) = 8.9891`, so quantization error is 18.4%.

Does this look of interest?

The issue with Qwen14B is that the number of columns in the `ffn_down` tensor is not a multiple of 256 (required by k-quants and the new `IQ2` quants), so these tensors quantize to `Q4_0`. As a result, the `IQ2_XXS`  quantized model ends up being 4.56 GiB (effectively 2.77 bpw), and `IQ2_XS` is 4.85 GiB (effectively 2.94 bpw).

**Comment by ggerganov** [comment]
Shall we add an enum value for that model file type?

https://github.com/ggerganov/llama.cpp/blob/a1610b05b2a8533e32fbb3f26d068c8d6d7bd526/llama.h#L105-L107

Without it, the log prints the model ftype as unknown, which is not fatal, but could be useful:

```
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 2.05 GiB (2.43 BPW) 
```

**Comment by ikawrakow** [comment]
> Shall we add an enum value for that model file type?

Yes, absolutely. I just forgot. Fixed with last commit.

**Comment by ikawrakow** [comment]
> These are pretty impressive numbers iMO, noticable improvement over master branch. I think 2.x bpw for a 14B model might be a bit stretch, ofc up for the realworld testing. 3.x bpw could be more interesting. Mind releasing couple 3.x bpw models for me to test?

OK, I'll do (but probably tomorrow European time). 

>  and look forward to quantize those myself.

Progress here is blocked on merging this PR and PR #4861

**Comment by ggerganov** [comment]
Will merge this PR soon - just need to resolve a problem with the Swift package since touching the enum in `ggml` breaks current builds (#4867). I think #4878 should resolve this and just need to confirm

For #4861, I think we should be able to easily add a more generic alternative to the proposed ggml callback, but want to first merge #4766 before that

**Comment by ikawrakow** [comment]
> For https://github.com/ggerganov/llama.cpp/pull/4861, I think we should be able to easily add a more generic alternative to the proposed ggml callback, but want to first merge https://github.com/ggerganov/llama.cpp/pull/4766 before that

There are two aspects of PR #4861:
1. Come up with the idea of using such activation statistics as importance matrix for quantization. This is novel, nobody has done something like that before.
2. Implement the idea in a given code base.

#4861 describes and document 1. so that, even if 2. is not perfect, it is still worth merging the PR to have this recorded in the repo history. One can always perfect the implementation after that, including adding support for CUDA/Metal.

**Review by ggerganov — APPROVED** [review]

**Comment by Nexesenex** [comment]
The new Q2_K quant confuses things with the old one, which is 1bpw bigger, and has been supplied for hundreds of models already.
It could have been useful to call it Q2_K_S in order to not use the same name for something quite different.

**Comment by Nexesenex** [comment]
The new Q2_K quant can confuse things with the old one, which is 1bpw bigger and has been supplied for hundreds of models already.
Would have it been possible to call it IQ2_S or, at worst, Q2_K_S, this in order to not use the same name for something quite different?

Aside that, superb work!

**Comment by ikawrakow** [comment]
@JianbangZ 

I have posted some quantized models for Qwen-14B-Chat [in this repo](https://huggingface.co/ikawrakow/qwen-14b-chat-gguf).

Strangely enough, `Q3_K_S` perplexity is better than `Q3_K_M` and as good as `Q4_K_S` on `wiki.test.raw`.

**Comment by Cran-May** [comment]
May you try this model?
https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v16.3-32k
offers muti-language supports

**Comment by ikawrakow** [comment]
> May you try this model?
> https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v16.3-32k
> offers muti-language supports

The multi-language is the problem. I have no experience with that (don't know what kind of training data to use, don't know how to verify the quality of the quantization, etc.). But I have now published my quantization method for 2-bit quantization (see PR #4897), and I'll follow up with another PR for all other quants in the next days. With that users will collect/report their experience, and hopefully we will learn what is the best way to quantize multi-language models, instruct tuned models, etc.

**Comment by JianbangZ** [comment]
> > May you try this model?
> > https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v16.3-32k
> > offers muti-language supports
> 
> The multi-language is the problem. I have no experience with that (don't know what kind of training data to use, don't know how to verify the quality of the quantization, etc.). But I have now published my quantization method for 2-bit quantization (see PR #4897), and I'll follow up with another PR for all other quants in the next days. With that users will collect/report their experience, and hopefully we will learn what is the best way to quantize multi-language models, instruct tuned models, etc.
> 
> I did post Qwen-14B as an experiment, but I need to first get feedback before quantizing other multi-language models.

I tried the iq2-xs and q3k-k-s, I think q3k performs much better, without seeing much degradation in Chinese language. Once I am allowed to quantize my self, I like to do 2 things (1) use a chinese dataset or a dual lingual dataset to calibrate (2) pick a 3.5 bpw quant method. what's the best options for 3.5 bpw ish?

**Comment by JianbangZ** [comment]
Tested the new Q2_K_S on https://github.com/ggerganov/llama.cpp/pull/4897
when tuned with wiki.train, PPL is 8.37
when tuned with a chinese wiki dataset people above suggested, PPL is 8.31

**Comment by Cran-May** [comment]
> > May you try this model?
> > https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v16.3-32k
> > offers muti-language supports
> 
> The multi-language is the problem. I have no experience with that (don't know what kind of training data to use, don't know how to verify the quality of the quantization, etc.). But I have now published my quantization method for 2-bit quantization (see PR #4897), and I'll follow up with another PR for all other quants in the next days. With that users will collect/report their experience, and hopefully we will learn what is the best way to quantize multi-language models, instruct tuned models, etc.
> 
> I did post Qwen-14B as an experiment, but I need to first get feedback before quantizing other multi-language models.

https://huggingface.co/OpenBuddy/openbuddy-zephyr-7b-v14.1
https://huggingface.co/openchat/openchat-3.5-0106
and
https://huggingface.co/CausalLM/7B-DPO-alpha
and
https://huggingface.co/CausalLM/14B-DPO-alpha
are SOTA muti-language models at 7B / 14B parameters
You can try use English materials.....

**Comment by Artefact2** [comment]
I can't get IQ2_XS inference to work on ROCm. The model just produces garbage tokens. Is this known?

~~~
./main -m ~/KoboldCpp/models/Mistral-7B-Instruct-v0.1-IQ2_XS.gguf -ngl 999 -p "The quick brown fox jumps over " -n 512

Log start
main: build = 1884 (0b2fca9)
main: built with cc (GCC) 13.2.1 20230801 for x86_64-pc-linux-gnu
main: seed  = 1705438728
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 ROCm devices:
  Device 0: AMD Radeon RX 6750 XT, compute capability 10.3, VMM: no
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from /home/romain/KoboldCpp/models/Mistral-7B-Instruct-v0.1-IQ2_XS.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = models
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 20
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q2_K:    5 tensors
llama_model_loader: - type q4_K:   32 tensors
llama_model_loader: - type q5_K:    1 tensors
llama_model_loader: - type iq2_xs:  188 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = IQ2_XS - 2.3125 bpw
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 2.05 GiB (2.43 BPW) 
llm_load_print_meta: general.name     = models
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.22 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size =  2054.70 MiB
llm_load_tensors:        CPU buffer size =    41.02 MiB
................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =    64.00 MiB
llama_new_context_with_model: KV self size  =   64.00 MiB, K (f16):   32.00 MiB, V (f16):   32.00 MiB
llama_new_context_with_model: graph splits (measure): 3
llama_new_context_with_model:      ROCm0 compute buffer size =    73.00 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =     9.00 MiB

system_info: n_threads = 8 / 16 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: 
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 512, n_batch = 512, n_predict = 512, n_keep = 0


 The quick brown fox jumps over 7###    #
                                         #      # 
▅# "# [end of text]

llama_print_timings:        load time =     577.81 ms
llama_print_timings:      sample time =       6.34 ms /    64 runs   (    0.10 ms per token, 10089.86 tokens per second)
llama_print_timings: prompt eval time =     180.74 ms /    10 tokens (   18.07 ms per token,    55.33 tokens per second)
llama_print_timings:        eval time =     923.83 ms /    63 runs   (   14.66 ms per token,    68.19 tokens per second)
llama_print_timings:       total time =    1123.28 ms /    73 tokens
Log end
~~~

**Comment by ikawrakow** [comment]
I don't have the ability to test with ROCm. Does `IQ2_XXS` work there?

**Comment by Artefact2** [comment]
As of 2b3a665d3917edf393761a24c4835447894df74a, I can reproduce:

~~~
make clean
make main
./main -m ~/KoboldCpp/models/Mistral-7B-Instruct-v0.1-IQ2_XXS.gguf -p "The meaning of life is " -n 128

system_info: n_threads = 8 / 16 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: 
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 The meaning of life is 42.
The answer to the ultimate question of life, the universe, and everything is 42. In this world-class bestseller, Douglas Adams revives the absurdity of the human condition with a hilarious blend of science fiction, satire, and philosophy. From the depths of space to the farthest reaches of the galaxy, Douglas Adams' interstellar tales are sure to leave you laughing and pondering life's ultimate question. [end of text]

llama_print_timings:        load time =     260.58 ms
llama_print_timings:      sample time =      12.74 ms /    98 runs   (    0.13 ms per token,  7694.12 tokens per second)
llama_print_timings: prompt eval time =     732.22 ms /     7 tokens (  104.60 ms per token,     9.56 tokens per second)
llama_print_timings:        eval time =   11042.81 ms /    97 runs   (  113.84 ms per token,     8.78 tokens per second)
llama_print_timings:       total time =   11809.46 ms /   104 tokens



make clean
make LLAMA_HIPBLAS=1 AMDGPU_TARGETS=gfx1030 main
./main -m ~/KoboldCpp/models/Mistral-7B-Instruct-v0.1-IQ2_XXS.gguf -p "The meaning of life is " -n 128 -ngl 999

sampling: 
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 512, n_batch = 512, n_predict = 128, n_keep = 0


 The meaning of life is 1#
"
$#▅
        #
#       #
          [end of text]

llama_print_timings:        load time =     529.69 ms
llama_print_timings:      sample time =       5.40 ms /    56 runs   (    0.10 ms per token, 10376.13 tokens per second)
llama_print_timings: prompt eval time =     175.51 ms /     7 tokens (   25.07 ms per token,    39.88 tokens per second)
llama_print_timings:        eval time =     754.51 ms /    55 runs   (   13.72 ms per token,    72.90 tokens per second)
llama_print_timings:       total time =     946.15 ms /    62 tokens
~~~

**Comment by ggerganov** [comment]
@Artefact2 On latest `master` run the following and show the failing tests:

```bash
make clean
make LLAMA_HIPBLAS=1 AMDGPU_TARGETS=gfx1030 -j tests
./tests/test-backend-ops
```

**Comment by Artefact2** [comment]
Here's a log @ggerganov, from 38566680cdfe982a495562332c25b9227de9cf8d.

[test-backend-ops.log](https://github.com/ggerganov/llama.cpp/files/13966321/test-backend-ops.log)

**Comment by ggerganov** [comment]
```
MUL_MAT(type_a=iq2_xxs,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1]): [MUL_MAT] NMSE = 0.999998137 > 0.000500000 FAIL
MUL_MAT(type_a=iq2_xs,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1]): [MUL_MAT] NMSE = 0.999998130 > 0.000500000 FAIL
```

From this it looks like the `mul_mat_vec_q` kernel is failing when HIPBLAS is enabled for IQ2 quants, but I don't see why. It works on the CUDA machines that I have access to, but I don't have AMD card to test with

**Comment by iddar** [comment]
How can I convert models to sota-2bits? Can I do it on models like Qwen?

**Comment by katlol** [comment]
Would it be possible to quantize something like https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v18.1-32k for multi language support?

**Comment by ikawrakow** [comment]
> Would it be possible to quantize something like https://huggingface.co/OpenBuddy/openbuddy-mixtral-7bx8-v18.1-32k for multi language support?

I have no experience with multi-lingual models. The one experiment I did for an English+French model indicated that it is likely necessary to include training data from all supported languages into the calibration dataset used to compute the importance matrix. But I don't know in what propositions, what are good training datasets for other languages, etc.

**Comment by sorasoras** [comment]
You need  wikitext with other languages.

**Pull request merged**
