### PR TITLE
Tokenizer WPM fixes for bert-bge and jina-v2-en

### PR DESCRIPTION
**Pull request by jaime-m-p**
Modifications to make WPM tokenizer match AutoTokenizer.

Tested with vocabs from models *bert-bge* and *jina-v2-en*.

### CODE REVIEW

**Comment by teleprint-me** [comment]
@jaime-m-p Can you try out applying the GPT-2 pre-tokenizer instead of the "default" value that's used? I think that might be part of the issue. It's a symptom I'm working on at the moment.

**Comment by iamlemec** [comment]
The usual value for `parse_special` is `False`. That's what gets used in the `embedding` example. In that case, the special tokens cache isn't used in tokenization. I actually think that the special tokens cache approach may not be desirable for the SPM model. Considering we're picking up ~7000 of them for most embedding models (versus 5 actual). This is also the reason the server embeddings don't seem to work correctly.

**Comment by teleprint-me** [comment]
Hm. Interesting. 🤔 

The original expression used for GPT-2 is the following:

```python
"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+"
```

https://github.com/openai/gpt-2/blob/master/src/encoder.py#L53

The `|\s+` might seem pointless, but this part of the regex decides whether to include spaces or not within segments based on the context.

The others should be omitted completely from pre-tok for testing purposes. This way, we at least have a control group.

**Review by ggerganov — APPROVED** [review]
> @ggerganov, Can't we just trust vocab.id_to_token[id].type?

I think so

**Pull request merged**
