### PR TITLE
vulkan: build fixes for 32b

### LINKED ISSUE #10923: Compile bug: macOS Vulkan build fails
### Git commit

eb5c3dc64bd967f2e23c87d9dec195f45468de60

### Operating systems

Mac

### GGML backends

Vulkan

### Problem description & steps to reproduce

The build process fails with errors in ggml_vk_host_get.

### First Bad Commit

_No response_

### Relevant log output

```shell
❯ cmake -B build -DGGML_METAL=OFF -DGGML_VULKAN=1
-- The C compiler identification is AppleClang 16.0.0.16000026
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/local/bin/git (found version "2.47.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Including CPU backend
-- Accelerate framework found
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
CMake Warning at ggml/src/ggml-cpu/CMakeLists.txt:53 (message):
  OpenMP not found
Call Stack (most recent call first):
  ggml/src/CMakeLists.txt:298 (ggml_add_cpu_backend_variant_impl)


-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Found BLAS: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/Accelerate.framework
-- BLAS found, Libraries: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/Accelerate.framework
-- BLAS found, Includes:
-- Including BLAS backend
-- Found Vulkan: /usr/local/lib/libvulkan.dylib (found version "1.4.303") found components: glslc glslangValidator
-- Vulkan found
-- GL_NV_cooperative_matrix2 supported by glslc
-- Including Vulkan backend
-- Configuring done (2.4s)
-- Generating done (0.7s)
-- Build files have been written to: /Users/soeren/Documents/Projects/llama.cpp/build


❯ cmake --build build --config Release
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  3%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  3%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  4%] Linking CXX shared library libggml-base.dylib
[  4%] Built target ggml-base
[  4%] Building CXX object ggml/src/ggml-vulkan/vulkan-shaders/CMakeFiles/vulkan-shaders-gen.dir/vulkan-shaders-gen.cpp.o
[  5%] Linking CXX executable ../../../../bin/vulkan-shaders-gen
[  5%] Built target vulkan-shaders-gen
[  6%] Generate vulkan shaders
ggml_vulkan: Generating and compiling shaders to SPIR-V
[  6%] Building CXX object ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:1368:2: warning: extra ';' outside of a function is incompatible with C++98 [-Wc++98-compat-extra-semi]
 1368 | };
      |  ^
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4777:9: error: no matching function for call to 'ggml_vk_host_get'
 4777 |         ggml_vk_host_get(ctx->device, q->data, d_Q, q_buf_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4778:9: error: no matching function for call to 'ggml_vk_host_get'
 4778 |         ggml_vk_host_get(ctx->device, k->data, d_K, q_buf_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4779:9: error: no matching function for call to 'ggml_vk_host_get'
 4779 |         ggml_vk_host_get(ctx->device, v->data, d_V, q_buf_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4780:9: error: no matching function for call to 'ggml_vk_host_get'
 4780 |         ggml_vk_host_get(ctx->device, dst->data, d_D, q_buf_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:4786:13: error: no matching function for call to 'ggml_vk_host_get'
 4786 |             ggml_vk_host_get(ctx->device, mask->data, d_M, q_buf_offset);
      |             ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5482:9: error: no matching function for call to 'ggml_vk_host_get'
 5482 |         ggml_vk_host_get(ctx->device, k->data, d_K, k_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5483:9: error: no matching function for call to 'ggml_vk_host_get'
 5483 |         ggml_vk_host_get(ctx->device, v->data, d_V, v_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5484:9: error: no matching function for call to 'ggml_vk_host_get'
 5484 |         ggml_vk_host_get(ctx->device, r->data, d_R, r_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5485:9: error: no matching function for call to 'ggml_vk_host_get'
 5485 |         ggml_vk_host_get(ctx->device, tf->data, d_TF, tf_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5486:9: error: no matching function for call to 'ggml_vk_host_get'
 5486 |         ggml_vk_host_get(ctx->device, td->data, d_TD, td_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5487:9: error: no matching function for call to 'ggml_vk_host_get'
 5487 |         ggml_vk_host_get(ctx->device, state->data, d_State, state_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:5488:9: error: no matching function for call to 'ggml_vk_host_get'
 5488 |         ggml_vk_host_get(ctx->device, dst->data, d_D, dst_offset);
      |         ^~~~~~~~~~~~~~~~
/Users/soeren/Documents/Projects/llama.cpp/ggml/src/ggml-vulkan/ggml-vulkan.cpp:3095:13: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 4th argument
 3095 | static void ggml_vk_host_get(vk_device& device, const void * ptr, vk_buffer& buf, size_t& buf_offset) {
      |             ^                                                                     ~~~~~~~~~~~~~~~~~~
1 warning and 12 errors generated.
make[2]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/ggml-vulkan.cpp.o] Error 1
make[1]: *** [ggml/src/ggml-vulkan/CMakeFiles/ggml-vulkan.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by jeffbolznv**
Should fix #10923

### CODE REVIEW

**Comment by ggerganov** [comment]
The `ggml-ci` has been reporting "maybe uninitialized" warnings for a while:

https://github.com/ggml-org/ci/blob/31168d7a582ded11a0dec489a62fb8bef74349a8/llama.cpp/a9/1a41364b25705dbb81ae996bc35c3440c63b35/ggml-6-x86-vulkan-t4/stdall#L538

Might want to fix these too.

**Comment by jeffbolznv** [comment]
Second commit ought to fix the uninitialized variables, though I couldn't reproduce the warnings/errors locally.

**Review by 0cc4m — APPROVED** [review]

**Comment by ggerganov** [comment]
Thanks. Also, I remember you discussed recently the segfaul upon program exit, but not sure which discussion was this. Do you have any ideas how this would be resolved? It's preventing the `ggml-ci` from running beyond the first test. (cc @netrunnereve)

**Comment by netrunnereve** [comment]
For what it's worth here's the thread discussing the segfault. It seems to be intermittent so if you restart the CI again you might be able to avoid it for now.

https://github.com/ggerganov/llama.cpp/issues/10528

**Comment by jeffbolznv** [comment]
Right, the discussion is in #10528. I don't currently have a linux system to repro that, but if @0cc4m isn't able to work on it soon then I might be able to set something up.

**Comment by ggerganov** [comment]
It's no longer segfault-ing after the restart. However, the CI appears to have revealed an issue when computing embeddings:

https://github.com/ggml-org/ci/tree/results/llama.cpp/eb/dee9478ca7ba65497b9b96f7457698c6ee5115/ggml-6-x86-vulkan-t4

**Comment by ggerganov** [comment]
This command is randomly segfault-ing upon exit:

```bash
./bin/llama-embedding --model ../models-mnt/rerank-tiny/ggml-model-f16.gguf -p "what is panda?</s></s>hi\nwhat is panda?</s></s>it's a bear\nwhat is panda?</s></s>The giant panda (Ailuropoda melanoleuca), sometimes called a panda bear or simply panda, is a bear species endemic to China." -ngl 99 -c 0 --pooling rank --embd-normalize -1 --verbose-prompt
```

I tried to get a stacktrace, but it's optimized out even in Debug for some reason:

```
batch_decode: n_tokens = 62, n_seq = 3

rerank score 0:    0.023
rerank score 1:    0.024
rerank score 2:    0.199

llama_perf_context_print:        load time =    1679.94 ms
llama_perf_context_print: prompt eval time =       7.25 ms /    62 tokens (    0.12 ms per token,  8556.44 tokens per second)
llama_perf_context_print:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:       total time =      11.52 ms /    63 tokens
[Thread 0x7fffe2a006c0 (LWP 78286) exited]
[Thread 0x7fffdea006c0 (LWP 78291) exited]
[Thread 0x7fffe20006c0 (LWP 78287) exited]

Thread 6 "[vkps] Update" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdf4006c0 (LWP 78290)]
0x00007fffe4801960 in ?? ()
(gdb) bt
#0  0x00007fffe4801960 in ?? ()
#1  0x0000000067685496 in ?? ()
#2  0x0000000036c9f0a0 in ?? ()
#3  0x0000000067685496 in ?? ()
#4  0x00000000000deb4c in ?? ()
#5  0x0000000000000007 in ?? ()
#6  0x00005555574cc838 in ?? ()
#7  0x181391d9e7cb40e8 in ?? ()
#8  0x00007fffe5c84320 in ?? ()
#9  0x0000555555a737d0 in ?? ()
#10 0x00007fffe4b392b4 in ?? ()
#11 0x00005555574cc958 in ?? ()
#12 0x181391d9f98f5968 in ?? ()
#13 0x181391d9e7af0a40 in ?? ()
#14 0x00005555574be3e0 in ?? ()
#15 0x203a6362696c6720 in ?? ()
#16 0x000055555768a3f0 in ?? ()
#17 0x00007fffe4803e20 in ?? ()
#18 0x00007fffdf4006c0 in ?? ()
#19 0xffffffffffffff60 in ?? ()
#20 0x0000000000000002 in ?? ()
#21 0x00007fffffffa3e0 in ?? ()
#22 0x00007fffe4804dfa in ?? ()
#23 0x00007fffdf4006c0 in ?? ()
#24 0x00007fffdf400cdc in ?? ()
#25 0x00007fffdf3ffef0 in ?? ()
#26 0x00007ffff669ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) q
```

**Comment by jeffbolznv** [comment]
Based on the thread name it's the same as https://github.com/ggerganov/llama.cpp/issues/10528. The stack is entirely in a driver thread, so I wouldn't expect to be able to get a useful stack trace.

**Pull request merged**
