### PR TITLE
cmake : enable warnings in llama

### PR DESCRIPTION
**Pull request by ggerganov**
Enable more compile warnings in CMake builds.

### CODE REVIEW

**Review by danbev — APPROVED** [review]
Could these blocks be moved to the parent CMakeLists.txt to avoid the duplication?

**Comment by ggerganov** [comment]
Probably we can refactor this in a function call and put it in the `cmake` folder to avoid duplication. But I think it's better to not call it in the root `CMakeLists.txt` since it will also apply to 3rd party sources (if any) and it's better to have the 3rd party sources decide their compile flags.

**Comment by slaren** [comment]
Agree, let's not duplicate this code. Either a function of storing C/C++ flags in a common variable should do it.

**Review by slaren — APPROVED** [review]
It might also make sense to rename `get_flags` to something like `ggml_get_flags` to make it clear where it comes from.

**Comment by ggerganov** [comment]
I didn't notice `get_flags` comes all the way from `ggml`. I added `llama_get_flags` to keep things separated. PTAnotherL

**Comment by slaren** [comment]
I think it would be ok to use `ggml_get_flags` in llama.cpp to avoid duplicating the code, keeping functions like this in sync is always a source of errors.

**Review by slaren — APPROVED** [review]

**Pull request merged**
