### PR TITLE
cleanup UI link list

### PR DESCRIPTION
**Pull request by slaren**
- Removed links that no longer work or that do not reference llama.cpp
- Removed the blurb in the few links that had it

### CODE REVIEW

**Review by JohannesGaessler — APPROVED** [review]
When I originally added the list my idea was to explicitly mark those projects that do not use permissive licenses since those are the cases where you can potentially get into legal trouble. But subsequently license declarations were added for permissive projects anyways wo maybe it would make sense to remove the sentence prior to the list and just list the license for each project?

**Comment by slaren** [comment]
Yes, I will try to add the missing licenses and remove the sentence.

**Comment by JohannesGaessler** [comment]
That's also fine I guess.

**Comment by ngxson** [comment]
Btw I'm also thinking about these ideas:
- Maybe move supported models, binding, UI, etc into a page called `showcase.md`
- Maybe also remove downstream project that haven't been updated for a long time (i.e. check their last commit)

**Review by ngxson — APPROVED** [review]

**Comment by slaren** [comment]
Agree, the lists are getting too big and they kind of detract from the more important information in the README.

**Review by ggerganov — APPROVED** [review]

**Pull request merged**
