### PR TITLE
Added Faraday to readme

### PR DESCRIPTION
**Pull request by biw**
I saw that there was an update to add a few more llamas.cpp based projects and Faraday was missing, so I added it 😄

### CODE REVIEW

**Comment by longregen** [comment]
I believe propietary projects should not be hidden between the rest of free, open source projects. Particularly, it feels like LMStudio is extremely closed-source, I believe it should not be listed; respectfully, I think this kind of PR could be seen as some sort of link farming.

**Comment by pacmanincarnate** [comment]
> I believe propietary projects should not be hidden between the rest of free, open source projects. Particularly, it feels like LMStudio is extremely closed-source, I believe it should not be listed; respectfully, I think this kind of PR could be seen as some sort of link farming.

They are two of a not huge number of interfaces for running llama.cpp. I'm not sure you can really call it link farming. It's not like this isn't a core part of both projects.

**Comment by ggerganov** [comment]
Adding proprietary projects using `llama.cpp` to that list is fine. But in this case, how do we know that it is using `llama.cpp`? For example, LMStudio clearly states it on their homepage

**Comment by JohannesGaessler** [comment]
They don't directly say it but they only support GGUF models and on their [website](https://docs.faraday.dev/models/choose-model#size-vs-perplexity-tradeoff) they have this image to guide quantization decisions:

quants

In this image they explicitly reference llama.cpp for the perplexity calculation. The other table information is also copied verbatim from llama.cpp. So my expectation very much is that Faraday internally uses llama.cpp for the model evaluation.

However, I also believe that the onus is not on the llama.cpp developers to investigate whether or not some other project makes use of the project. Ultimately this is all just conjecture. If the Faraday devs want to be listed they should make it clear whether or not they use llama.cpp.

**Comment by biw** [comment]
> Adding proprietary projects using `llama.cpp` to that list is fine. But in this case, how do we know that it is using `llama.cpp`? For example, LMStudio clearly states it on their homepage

This is a great point @ggerganov. I didn't notice till now that we didn't mention llama.cpp, that wasn't by design! I have added a callback to llama.cpp on our homepage 😄:
Screenshot 2024-02-06 at 1 29 33 PM

**Review by ggerganov — APPROVED** [review]

**Comment by cztomsik** [comment]
In that case, maybe you can also merge this one? :)
https://github.com/ggerganov/llama.cpp/pull/4362

**Pull request merged**
