### PR TITLE
Prompt lookup decoding

### PR DESCRIPTION
**Pull request by LeonEricsson**
ref #4226

This example implements the "Prompt Lookup Decoding" technique: 

https://github.com/apoorvumang/prompt-lookup-decoding

- This approach works best on input-grounded tasks such as summarization, document QA, code editing etc where there is a high overlap in input and output. 
- It replaces the draft model in speculative decoding with a simple ngram search of the input tokens. Similar to speculative decoding it has no impact on output.

TODO:

- [ ] Batched decoding by extracting multiple ngram lookup matches - currently picks the first match
- [ ] Improve lookup search technique
- [ ] Test varying `max_ngram_size` and `n_draft`

### CODE REVIEW

**Comment by LeonEricsson** [comment]
Looking for some assistance as I've run into a bug, hopefully this is the best way to do that (if not let me know please). I'm running into a bug where, after a couple of tokens, the target model starts spitting out a bunch of repeating tokens and nonsense. I've been testing on summarization input, below is an example.

Input:
` (cnn) -- can a movie actually convince you to support torture? Can a movie really persuade you that fracking -- a process used to drill for natural gas -- is a danger to the environment? Can a movie truly cause you to view certain minority groups in a negative light? Some scoff at the notion that movies do anything more than entertain. They are wrong. Sure, it's unlikely that one movie alone will change your views on issues of magnitude. But a movie (or tv show) can begin your education or miseducation on a topic. And for those already agreeing with the film's thesis, it can further entrench your views. Anyone who doubts the potential influence that movies can have on public opinion need to look no further than two films that are causing an uproar even before they have opened nationwide. They present hot button issues that manage to fire up people from the left and right. The first, zero dark thirty, is about the pursuit and killing of osama bin laden, which features scenes of torture. The second, promised land,  stars matt damon and explores how the use of fracking to drill for natural gas can pose health and environmental dangers. Critics of zero dark thirty fear that audiences will accept as true the film's story line that torture was effective in eliciting information to locate bin laden. They are rightfully concerned that the film will sway some to become more receptive or even supportive of the idea of torturing prisoners.Peter bergen: did torture really net bin laden? Summarize the text.`


Output:
`Citing specific paragraphs and quotes from the the text, summarize what it says. Did the tortureure of al suspect sus k prisoners one k prisoners os ab k a suspect an k the sus ab terror prisoners k os k terror k d k top " ab the the sus any prisoners prisoners  two os the those k k one k terror the a terror ab os bin ab the sus k suspect high ab al ab one  k a k these k ab captured ab one one prisoners one k os k sus a K a prisoners people an k a suspect k a prisoners a prisoners k os k ab k os k prisoners prisoners capt prisoners prisoners k d ab ab terror prisoners those the ab al ab a ab k any high al the k sus k prisoners ab prisoners k k k certain ab k suspect prisoners prisoners alleg " bin  k these suspect ab a k k a prisoners ali ab k suspect prisoners k k k one k k key ab K a k an prisoners the os the a sus sus ab bin`

**Comment by ggerganov** [comment]
You seem to be missing the logic for cleaning up the KV cache from the not-accepted draft tokens:

https://github.com/ggerganov/llama.cpp/blob/88ae8952b65cbf32eb1f5703681ea592e510e570/examples/lookahead/lookahead.cpp#L439-L443

Let's say your draft batch is this (4 tokens):

```
d0 d1 d2 d3
```

And you accept only `d0 d1`. You have to remove `d2 d3` from the cache with:

```c++
llama_kv_cache_seq_rm(ctx, 0, n_past, -1);
```

Where `n_past` has been updated to take into account that `d0 d1` have been accepted.

**Comment by LeonEricsson** [comment]
> You seem to be missing the logic for cleaning up the KV cache from the not-accepted draft tokens:
> 
> https://github.com/ggerganov/llama.cpp/blob/88ae8952b65cbf32eb1f5703681ea592e510e570/examples/lookahead/lookahead.cpp#L439-L443
> 
> Let's say your draft batch is this (4 tokens):
> 
> ```
> d0 d1 d2 d3
> ```
> 
> And you accept only `d0 d1`. You have to remove `d2 d3` from the cache with:
> 
> ```c++
> llama_kv_cache_seq_rm(ctx, 0, n_past, -1);
> ```
> 
> Where `n_past` has been updated to take into account that `d0 d1` have been accepted.

Fixed, thanks for the assistance.

**Comment by stduhpf** [comment]
> Looking for some assistance as I've run into a bug, hopefully this is the best way to do that (if not let me know please). I'm running into a bug where, after a couple of tokens, the target model starts spitting out a bunch of repeating tokens and nonsense. I've been testing on summarization input, below is an example.
> 
> Input: ` (cnn) -- can a movie actually convince you to support torture? Can a movie really persuade you that fracking -- a process used to drill for natural gas -- is a danger to the environment? Can a movie truly cause you to view certain minority groups in a negative light? Some scoff at the notion that movies do anything more than entertain. They are wrong. Sure, it's unlikely that one movie alone will change your views on issues of magnitude. But a movie (or tv show) can begin your education or miseducation on a topic. And for those already agreeing with the film's thesis, it can further entrench your views. Anyone who doubts the potential influence that movies can have on public opinion need to look no further than two films that are causing an uproar even before they have opened nationwide. They present hot button issues that manage to fire up people from the left and right. The first, zero dark thirty, is about the pursuit and killing of osama bin laden, which features scenes of torture. The second, promised land, stars matt damon and explores how the use of fracking to drill for natural gas can pose health and environmental dangers. Critics of zero dark thirty fear that audiences will accept as true the film's story line that torture was effective in eliciting information to locate bin laden. They are rightfully concerned that the film will sway some to become more receptive or even supportive of the idea of torturing prisoners.Peter bergen: did torture really net bin laden? Summarize the text.`
> 
> Output: `Citing specific paragraphs and quotes from the the text, summarize what it says. Did the tortureure of al suspect sus k prisoners one k prisoners os ab k a suspect an k the sus ab terror prisoners k os k terror k d k top " ab the the sus any prisoners prisoners two os the those k k one k terror the a terror ab os bin ab the sus k suspect high ab al ab one k a k these k ab captured ab one one prisoners one k os k sus a K a prisoners people an k a suspect k a prisoners a prisoners k os k ab k os k prisoners prisoners capt prisoners prisoners k d ab ab terror prisoners those the ab al ab a ab k any high al the k sus k prisoners ab prisoners k k k certain ab k suspect prisoners prisoners alleg " bin k these suspect ab a k k a prisoners ali ab k suspect prisoners k k k one k k key ab K a k an prisoners the os the a sus sus ab bin`

I ran into the same problem when I tried implementing it. Since I don't really know what I am doing, I couldn't find a way to fix it, so I gave up on this project. Ping me if you figure it out, I'm curious. 

ps: maybe you could add --color support so we can easily distinguish tokens taken from the promt and tokens generated by the model (like this for example: da5eaef1f34d0a1f584cd4a092e7691ea46a9d91)

**Comment by LeonEricsson** [comment]
> I ran into the same problem when I tried implementing it. Since I don't really know what I am doing, I couldn't find a way to fix it, so I gave up on this project. Ping me if you figure it out, I'm curious.
> 
> ps: maybe you could add --color support so we can easily distinguish tokens taken from the promt and tokens generated by the model (like this for example: [da5eaef](https://github.com/ggerganov/llama.cpp/commit/da5eaef1f34d0a1f584cd4a092e7691ea46a9d91))

Gerganov comment above was the solution in my case. I added KV management as such:

```
        // KV cache management
        // clean the cache of draft tokens that weren't accepted
        llama_kv_cache_seq_rm(ctx, 0, n_past, -1);
```

Color coding is a good idea, I will look into it this afternoon.

**Comment by ggerganov** [comment]
Seems to work OK

```bash
make -j && ./lookup -m models/mistral-instruct-7b-v0.2/ggml-model-f16.gguf -e -f build/task-summarize-0.txt --repeat_penalty 1.0 --color --temp 0.0 -c 4096 -b 4096 -n -1 --no-penalize-nl --verbose-prompt
```

image

**Review by ggerganov — APPROVED** [review]

**Comment by stduhpf** [comment]
Works flawlessly for me too!
 (even though it acually slows down generation on my current laptop, because prompt eval times are not that much lower than eval times for some reason)
 
image

**Comment by LeonEricsson** [comment]
> Works flawlessly for me too! (even though it acually slows down generation on my current laptop, because prompt eval times are not that much lower than eval times for some reason)
> 
>  Edit: Is the accept rate right? It looks suspiciously low here...

Nice, thanks for testing it out. I suspect it is correct, just from the last sentence `Is there anything else I can help` you get ~80 draft tokens from which none are accepted.

**Comment by ggerganov** [comment]
You can now control the draft size with `--draft N`:

```bash
./lookup \
    -m models/mistral-instruct-7b-v0.2/ggml-model-f16.gguf \
    -e -f build/task-repeat-0.txt --repeat_penalty 1.0 --color \
    --temp 0.0 -c 4096 -b 4096 -n -1 --no-penalize-nl --verbose-prompt --draft 5
```

image

**Comment by LeonEricsson** [comment]
> You can now control the draft size with `--draft N`:
> 
> ```shell
> ./lookup \
>     -m models/mistral-instruct-7b-v0.2/ggml-model-f16.gguf \
>     -e -f build/task-repeat-0.txt --repeat_penalty 1.0 --color \
>     --temp 0.0 -c 4096 -b 4096 -n -1 --no-penalize-nl --verbose-prompt --draft 5
> ```

thanks for all your help. I've been eager to contribute to the project but sort of nervous given its scope. You made things way easier and way less scary. Really appreciate it!

You have any thoughts regarding batching? Is it as straight forward as generating multiple candidates instead of picking the first match?

**Comment by stduhpf** [comment]
> > Works flawlessly for me too! (even though it acually slows down generation on my current laptop, because prompt eval times are not that much lower than eval times for some reason)
> > Edit: Is the accept rate right? It looks suspiciously low here...
> 
> Nice, thanks for testing it out! Which model are you running? Regarding the accept rate - I suspect it is correct, just from the last sentence `Is there anything else I can help` you get ~80 draft tokens from which none are accepted.

Oh, so even when there is no ngram matches, it still creates a draft token?

**Comment by ggerganov** [comment]
> You have any thoughts regarding batching? Is it as straight forward as generating multiple candidates instead of picking the first match?

The "batch of batches" speculation is implemented in the `speculative` example. It's even more advanced since it creates a tree of batches - i.e. common prefixes across the different batches are deduplicated. However, it could be a bit tricky to implement since you have to carefully prepare the `llama_batch` and then clean up correctly the kv cache. So it is possible to implement, but probably not straight forward. Also, the `lookahead` example can help with understanding how multiple batches work.

> Oh, so even when there is no ngram matches, it still creates a draft token?

No, in that example, for every `lazy dog` it matches `lazy dog'` from the prompt, while we generate `lazy dog.`. So for each dog we waste 10 drafted tokens since the `.` does not match the `'`

**Comment by stduhpf** [comment]
> No, in that example, for every lazy dog it matches lazy dog' from the prompt, while we generate lazy dog.. So for each dog we waste 10 drafted tokens since the . does not match the '

Oh I see, that makes a lot of sense.

**Comment by LeonEricsson** [comment]
> > No, in that example, for every lazy dog it matches lazy dog' from the prompt, while we generate lazy dog.. So for each dog we waste 10 drafted tokens since the . does not match the '
> 
> Oh I see, that makes a lot of sense.

Excuse my ignorance. I'm not sure what I was thinking obviously we don't generate draft tokens without a match 😴

**Comment by apoorvumang** [comment]
@LeonEricsson this is amazing! 

However I'm noticing some weird behaviour. One thing is, I'm seeing *slowdown* on my M2 Max 32GB on summarization task compared to just using `main` (prompt that took ~8 seconds takes 13 seconds). But there's a weirder issue:

- I noticed different output even with temp 0 when using `./main` vs `./lookup`
- This can be checked with just `./lookup` as well - set `--draft 0` and you get a different output. Set `draft` to anything else, you get something else.

Eg. with `--draft 0`, partial output:
```
Summarize the above text [/INST] Elon Musk attended the annual Atreju political meeting organized by Italian Prime Minister Giorgia Meloni's Brothers of Italy party in Rome. He urged the crowd to have more children to save Italy's culture due to the country's low birth rate. The venue was Castel Sant’Angelo, which was built as a mausoleum for Emperor Hadrian and is now a public museum. During his interview, Musk warned about the "woke mind virus" and its potential impact on Italy, expressed concerns over illegal immigration, and discussed the importance of colonizing Mars and the risks of artificial intelligence. He also criticized Disney for having the "woke mind virus."

encoded 1308 tokens in    3.779 seconds, speed:  384.268 t/s
decoded  144 tokens in    4.226 seconds, speed:   34.074 t/s

n_draft   = 0
n_predict = 144
n_drafted = 0
n_accept  = 0
accept    = nan%

target:

llama_print_timings:        load time =     451.71 ms
llama_print_timings:      sample time =      31.28 ms /   144 runs   (    0.22 ms per token,  4602.99 tokens per second)
llama_print_timings: prompt eval time =    3749.44 ms /  1307 tokens (    2.87 ms per token,   348.59 tokens per second)
llama_print_timings:        eval time =    4204.27 ms /   144 runs   (   29.20 ms per token,    34.25 tokens per second)
llama_print_timings:       total time =    8009.08 ms
ggml_metal_free: deallocating
```

With `--draft 10`
```
Summarize the above text [/INST] Elon Musk was the guest of honor at an annual conference organized by Italian Prime Minister Giorgia Meloni's Brothers of Italy party in Rome. He urged the crowd to have more children to save Italy's culture due to the country's low birth rate. The venue for the event was Castel Sant'Angelo, which was built as a mausoleum for Emperor Hadrian and is now a museum and public fortress connected to Vatican City. During his interview, Musk warned about the "woke mind virus" spreading from the US to Italy and criticized illegal immigration. He also discussed the importance of colonizing Mars and the potential risks of artificial intelligence. Previous headliners at the conference included Marine Le Pen, Viktor Orban, and Steve Bannon.

encoded 1308 tokens in    3.787 seconds, speed:  389.473 t/s
decoded  167 tokens in    9.749 seconds, speed:   17.130 t/s

n_draft   = 10
n_predict = 167
n_drafted = 780
n_accept  = 72
accept    = 9.231%

target:

llama_print_timings:        load time =     463.42 ms
llama_print_timings:      sample time =      27.97 ms /   167 runs   (    0.17 ms per token,  5970.04 tokens per second)
llama_print_timings: prompt eval time =   12990.67 ms /  2165 tokens (    6.00 ms per token,   166.66 tokens per second)
llama_print_timings:        eval time =     497.86 ms /    17 runs   (   29.29 ms per token,    34.15 tokens per second)
llama_print_timings:       total time =   13539.18 ms
ggml_metal_free: deallocating
```

Any idea why this might be happening @LeonEricsson @ggerganov ?

**Comment by ggerganov** [comment]
Which model are you using? Maybe copy paste the exact commands that you run. I did a quick test with F16 Mistral Instruct and couldn't reproduce.

**Comment by nittaya111** [comment]
😂😅💋💋💋💋💋💋💋💋💞❤️

เมื่อ พ. 20 ธ.ค. 2566 เวลา 14:41 Georgi Gerganov ***@***.***>
เขียนว่า:

**Comment by apoorvumang** [comment]
@ggerganov  command is
```
./lookup \
    -m models/7B/mistral-7b-instruct-v0.2.Q5_K_S.gguf \
    -f build/summary.txt --color \
    --temp 0.0 -c 4096 -b 4096 -n -1 --no-penalize-nl --verbose-prompt --draft 10
```

I downloaded model from here: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/blob/main/mistral-7b-instruct-v0.2.Q5_K_S.gguf

Prompt file:
[summary.txt](https://github.com/ggerganov/llama.cpp/files/13728160/summary.txt)

**Comment by apoorvumang** [comment]
Interestingly I'm not able to reproduce different outputs with `Q4_0` model (it works fine) - only `Q5_K_S` model is giving different outputs..

```
-----
command
./lookup \
    -m models/7B/mistral-7b-instruct-v0.2.Q4_0.gguf \
    -f build/summary.txt --color \
    --temp 0.0 -c 4096 -b 4096 --verbose-prompt --draft 0

output
Summarize the above text [/INST] Elon Musk attended the annual Atreju political meeting organized by Italian Prime Minister Giorgia Meloni's Brothers of Italy party in Rome. He urged the crowd to have more children to save Italy's culture due to its low birth rate. The venue was Castel Sant'Angelo, which was built as a mausoleum for Emperor Hadrian and is now a museum. During his interview, Musk warned about the "woke mind virus" and its potential impact on Italy, expressed concerns over illegal immigration, and discussed the importance of legal immigration and colonizing Mars. He also touched upon the dangers and opportunities of artificial intelligence and supported some regulatory control. Musk refused to engage in questions about his recent comments towards advertisers leaving Twitter and criticized Disney for having the "woke mind virus." Previous headliners at the conference included Marine Le Pen, Viktor Orban, and British Prime Minister Rishi Sunak.

encoded 1308 tokens in    3.050 seconds, speed:  493.370 t/s
decoded  197 tokens in    3.980 seconds, speed:   49.493 t/s

n_draft   = 0
n_predict = 197
n_drafted = 0
n_accept  = 0
accept    = nan%

target:

llama_print_timings:        load time =     416.38 ms
llama_print_timings:      sample time =      38.35 ms /   197 runs   (    0.19 ms per token,  5136.90 tokens per second)
llama_print_timings: prompt eval time =    3030.50 ms /  1307 tokens (    2.32 ms per token,   431.28 tokens per second)
llama_print_timings:        eval time =    3937.54 ms /   197 runs   (   19.99 ms per token,    50.03 tokens per second)
llama_print_timings:       total time =    7033.83 ms
ggml_metal_free: deallocating


----

command
./lookup \
    -m models/7B/mistral-7b-instruct-v0.2.Q4_0.gguf \
    -f build/summary.txt --color \
    --temp 0.0 -c 4096 -b 4096 --verbose-prompt --draft 1

output
Summarize the above text [/INST] Elon Musk attended the annual Atreju political meeting organized by Italian Prime Minister Giorgia Meloni's Brothers of Italy party in Rome. He urged the crowd to have more children to save Italy's culture due to its low birth rate. The venue was Castel Sant'Angelo, which was built as a mausoleum for Emperor Hadrian and is now a museum. During his interview, Musk warned about the "woke mind virus" and its potential impact on Italy, expressed concerns over illegal immigration, and discussed the importance of legal immigration and colonizing Mars. He also touched upon the dangers and opportunities of artificial intelligence and supported some regulatory control. Musk refused to engage in questions about his recent comments towards advertisers leaving Twitter and criticized Disney for having the "woke mind virus." Previous headliners at the conference included Marine Le Pen, Viktor Orban, and British Prime Minister Rishi Sunak.

encoded 1308 tokens in    3.052 seconds, speed:  493.148 t/s
decoded  197 tokens in   10.959 seconds, speed:   17.976 t/s

n_draft   = 1
n_predict = 197
n_drafted = 115
n_accept  = 56
accept    = 48.696%

target:

llama_print_timings:        load time =     606.35 ms
llama_print_timings:      sample time =      34.07 ms /   197 runs   (    0.17 ms per token,  5782.55 tokens per second)
llama_print_timings: prompt eval time =   13434.80 ms /  1537 tokens (    8.74 ms per token,   114.40 tokens per second)
llama_print_timings:        eval time =     518.72 ms /    26 runs   (   19.95 ms per token,    50.12 tokens per second)
llama_print_timings:       total time =   14015.14 ms
ggml_metal_free: deallocating

---
```

**Comment by apoorvumang** [comment]
@LeonEricsson @ggerganov  BTW the current implementation seems flawed to me. Please correct me if I'm wrong, but what's happening in current implementation is

- Certain tokens are drafted using lookup (correct and fast)
- For each draft token, an inner loop runs
  - *One by one* tokens are sampled from the LLM
  - If they match draft token, continue inner loop, otherwise break

The second step above is not what prompt lookup is - if you're sampling 1-by-1 and just checking whether they match draft token or not, there's no point in drafting (why even have draft?). The value with drafting is if in 1 step you can verify ALL draft tokens. This doesn't seem to be happening, and hence no speedup (in fact significant slowdown).

I will try to read up llama.cpp code from speculative, and I'll try to put my thoughts in code.

**Comment by LeonEricsson** [comment]
> @LeonEricsson @ggerganov BTW the current implementation seems flawed to me. Please correct me if I'm wrong, but what's happening in current implementation is
> 
> * Certain tokens are drafted using lookup (correct and fast)
> * For each draft token, an inner loop runs
>   
>   * _One by one_ tokens are sampled from the LLM
>   * If they match draft token, continue inner loop, otherwise break
> 
> The second step above is not what prompt lookup is - if you're sampling 1-by-1 and just checking whether they match draft token or not, there's no point in drafting (why even have draft?). The value with drafting is if in 1 step you can verify ALL draft tokens. This doesn't seem to be happening, and hence no speedup (in fact significant slowdown).
> 
> I will try to read up llama.cpp code from speculative, and I'll try to put my thoughts in code.

I was confused by this setup initially as well, if you look at the `speculative` example you'll see it runs the same. If you look at line [195](https://github.com/LeonEricsson/llama.cpp/blob/d8ed670c6ce276301c085bcc6a9f589ef0916502/examples/lookup/lookup.cpp#L195) you'll see that after prompt lookup we immediately perform the actual forward pass through the model using the entire draft. The sampling loop you are taking about isn't actually doing any heavy lifting. I haven't fully grasped why it's separated like this, perhaps the modularity allows for more flexibility in the sampling process?

**Comment by apoorvumang** [comment]
Hmm good point. I'm trying to reverse engineer `speculative`, lets see how far I can get.. I have a feeling this may get messy with KV cache.

Did you notice any speedups with the current lookup implementation @LeonEricsson ? I only got slowdown

**Comment by kalomaze** [comment]
> Hmm good point. I'm trying to reverse engineer `speculative`, lets see how far I can get.. I have a feeling this may get messy with KV cache.
> 
> Did you notice any speedups with the current lookup implementation @LeonEricsson ? I only got slowdown

I really think that the best way to do this, as opposed to how the PR is currently doing it, would be to just 'train' a basic n gram model, like an iPhone style autocomplete. So not based on current input, but in terms of **overall statistical likelihood** for the entire prompt.

Most of what speculative decoding seems to help with is for completing words that are made up of multiple tokens. For example, "treefrog" is 3 tokens:

image

I think a simple general-purpose n-gram model would be a better idea than simply ingesting the prompt.

**Comment by stduhpf** [comment]
> I really think that the best way to do this n-gram approach, as opposed to how the PR is currently doing it, would be to just 'train' a basic n gram model, like an iPhone style autocomplete. So not based on current input, but in terms of overall statistical likelihood for the entire generation irrespective of the prompt input.

Isn't that pretty much what the `speculative` example is currently doing? At least that's how I understand it

**Comment by kalomaze** [comment]
> > I really think that the best way to do this n-gram approach, as opposed to how the PR is currently doing it, would be to just 'train' a basic n gram model, like an iPhone style autocomplete. So not based on current input, but in terms of overall statistical likelihood for the entire generation irrespective of the prompt input.
> 
> Isn't that pretty much what the `speculative` example is currently doing? At least that's how I understand it

No, it's using an entire transformer neural network (the draft model) like TinyLlama

**Comment by ggerganov** [comment]
@LeonEricsson Do you plan more changes for this PR or should we merge it?

@apoorvumang The performance will vary based on the acceptance rate, `n_draft` and the batch decoding speed for that model. You can increase the acceptance rate by matching only larger n-grams. Probably no reason to go above 4-5 for `n_draft`

@kalomaze I think a great solution would be to design a local n-gram cache that will be dynamically updated based on the text being processed locally. For example, everybody can have their own cache which seamlessly accumulates n-grams as they use LLMs on their devices. The LLMs can then sample from that local n-gram cache and speculate with data that is specific to the user. I've thrown some ideas in this regard here: https://github.com/ggerganov/llama.cpp/discussions/4235

**Comment by stduhpf** [comment]
> > > I really think that the best way to do this n-gram approach, as opposed to how the PR is currently doing it, would be to just 'train' a basic n gram model, like an iPhone style autocomplete. So not based on current input, but in terms of overall statistical likelihood for the entire generation irrespective of the prompt input.
> > 
> > 
> > Isn't that pretty much what the `speculative` example is currently doing? At least that's how I understand it
> 
> No, it's using an entire transformer neural network (the draft model) like TinyLlama, not a simple n-gram, that's order of magnitudes slower

Excuse my stupidity, but a model that predicts the next n-gram given a sequence of token, isn't that just a language model?

**Comment by LeonEricsson** [comment]
> @LeonEricsson Do you plan more changes for this PR or should we merge it?

We can merge it! I may come back to look at batching and/or improved prompt search but don't have the time right now

**Comment by sorasoras** [comment]
Quick question： how does this work for llm translation between difference language？ I guess it should work great. how could i generate“ simple ngram search of the input tokens”？

**Comment by LeonEricsson** [comment]
> Quick question： how does this work for llm translation between difference language？ I guess it should work great. how could i generate“ simple ngram search of the input tokens”？

Translation is probably one of the worst applications of prompt lookup. Across languages you should see very few matches that expand longer than a token or two.

**Comment by x4080** [comment]
Hi, I tried with summarization and the result is better without using it ?
```
./lookup -ngl 1 -t 0 -m ./models/mistral.gguf --color --temp 0.3 -n -1 -f prompts/testprompt.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 4096 -b 2500 --draft 5
```
vs
```
./main -ngl 1 -t 0 -m ./models/mistral.gguf --color --temp 0.3 -n -1 -f prompts/testprompt.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 2500 --grp-attn-n 4 --grp-attn-w 1024 

```

**Comment by stduhpf** [comment]
> Hi, I tried with summarization and the result is better without using it ?

It depends on how fast is prompt processing vs token generation on your machine with your settings, and what is the accept rate. 
Overall, I found that regular speculative decoding using a very tiny model such as `SmolLlamix-8x101M` works much better, and it's also able to find patterns in the prompt, since these small models love to repeat the same thing over and over.

**Comment by apoorvumang** [comment]
> Hi, I tried with summarization and the result is better without using it ?
> 
> ```
> ./lookup -ngl 1 -t 0 -m ./models/mistral.gguf --color --temp 0.3 -n -1 -f prompts/testprompt.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 4096 -b 2500 --draft 5
> ```
> 
> vs
> 
> ```
> ./main -ngl 1 -t 0 -m ./models/mistral.gguf --color --temp 0.3 -n -1 -f prompts/testprompt.txt --min_p 0.1 --top_p 1 --top_k 50 --repeat_penalty 1.1 -c 2500 --grp-attn-n 4 --grp-attn-w 1024 
> ```
> 
> difference is small but better without prompt lookup

Yeah, I've found on;y a few cases where I'm getting speedup on M1 Mac. I think this has a lot to do with latency when doing a multi token decoding step - please check our #4624 for details

**Comment by x4080** [comment]
@apoorvumang Thanks

**Comment by x4080** [comment]
I tried it again using deepseek - and maybe it actually works, sometimes the cursor just jump because using the lookup ? It will display purple color instead of white

**Pull request merged**
