### PR TITLE
chore: Add model vocab support

### PR DESCRIPTION
**Pull request by teleprint-me**
ref [#6920 comment](https://github.com/ggerganov/llama.cpp/pull/6920#issuecomment-2087827173)

supersedes #7018

Adds the following models:

- phi
- stablelm
- ~~qwen~~ (qwen2 supersedes qwen)
- mistral
- mixtral

Adds the following extras:

- Adds the stablelm vocab
- Adds the generate-vocab.sh script
- Adds ability to generate the generate-vocab.sh script

### CODE REVIEW

**Review by Galunid — CHANGES_REQUESTED** [review]
Is this work in progress? It seems to miss implementation in `llama.cpp`. Those tokenizers won't be recognized leading to crash with runtime error.

**Comment by teleprint-me** [comment]
@Galunid Yes, it's still a work in progress. I was passing out while still implementing because I wanted to get it out of the way, so I decided to pause for a bit.

**Comment by teleprint-me** [comment]
Possible regression with llama-spm?

```sh
      Start 11: test-tokenizer-1-llama-spm
11/24 Test #11: test-tokenizer-1-llama-spm .......Subprocess aborted***Exception:   0.86 sec
```

**Comment by CISC** [comment]
@teleprint-me Should not `qwen` be removed since #7114 got merged? They are the same.

**Comment by teleprint-me** [comment]
@CISC 

I had already committed it and was waiting to be able to merge the PRs into this branch. I can remove it after some testing if it really isn't needed, but the pattern is useful to see the potential variety of implementations that we'll be dealing with. The original Qwen repos use BPE with tiktoken and a build script which is hooked into transformers tokenizer. While the vocab might be the same, the process for getting it is completely different. It's good to know about it, even if it isn't useful in this context.

**Comment by arch-btw** [comment]
The current output of Qwen after https://github.com/ggerganov/llama.cpp/pull/7114 is this:

>error loading model: error loading model vocabulary: unknown pre-tokenizer type: 'qwen2'

**Comment by teleprint-me** [comment]
Hm. I messed up the merge. That's no good.

**Comment by aahouzi** [comment]
@teleprint-me your PR is not working for stablelm models, why the pre-tokenizer is stablelm if I remember correctly it should be gpt-2 right ?

image

**Comment by teleprint-me** [comment]
@aahouzi Yes, you're correct. I think I know why this is happening.

I'm wondering if it's because of the `_set_vocab_gpt2` method.

```python
    def _set_vocab_gpt2(self) -> None:
        tokens, toktypes, tokpre = self.get_vocab_base()
        self.gguf_writer.add_tokenizer_model("gpt2")
        self.gguf_writer.add_tokenizer_pre(tokpre)
        self.gguf_writer.add_token_list(tokens)
        self.gguf_writer.add_token_types(toktypes)
```

`add_tokenizer_pre` is set, but `tokpre` is a variable that's passed to it. I fixed phi-2 by directly adding `self.gguf_writer.add_tokenizer_pre("gpt-2")` to it, unsure if this should be changed here though. Then override on a model-by-model basis as needed might be a better approach?

**Comment by teleprint-me** [comment]
Okay, I get it now. This verifies my initial intuition about how the mapping was setup in the update script. This needs to be refactored somehow. We can't rely on a name as an id for the models pre-tokenizer. The models vocab may be modified downstream and conversions will fail as a result even if the architecture is clearly supported. This is creating name conflicts. Turns out the phi-2 bug in #7219 and #7300 is a symptom of a more deeply rooted issue.

**Comment by teleprint-me** [comment]
I think I can fully automate this entire process and reduce the complexity. Not sure yet. Need to experiment.

**Comment by compilade** [comment]
> I fixed phi-2 by directly adding `self.gguf_writer.add_tokenizer_pre("gpt-2")` to it, unsure if this should be changed here though.

Phi-2 has this pre-tokenizer (from its `tokenizer.json`):

```json
  "pre_tokenizer": {
    "type": "ByteLevel",
    "add_prefix_space": false,
    "trim_offsets": true,
    "use_regex": true
  }
```
The `"use_regex"` here means to use the GPT-2 regex, so using the `gpt-2` is correct.

> Then override on a model-by-model basis as needed might be a better approach?

Hmm, no I don't think this will work for architectures which are used with different pre-tokenizers. For example, the `StableLMModel` uses at least 2 different pre-tokenizers:

- StableLM 3b uses GPT-2's regex:
  ```json
  "pre_tokenizer": {
    "type": "ByteLevel",
    "add_prefix_space": false,
    "trim_offsets": true,
    "use_regex": true
  }
  ```
- StableLM2 1.6B uses something else, which is similar (but not quite) the same as Llama 3:
  ```json
  "pre_tokenizer": {
    "type": "Sequence",
    "pretokenizers": [
      {
        "type": "Split",
        "pattern": {
          "Regex": "(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}| ?[^\\s\\p{L}\\p{N}]+[\r\n]*|\\s*[\r\n]+|\\s+(?!\\S)|\\s+"
        },
        "behavior": "Removed",
        "invert": true
      },
      {
        "type": "ByteLevel",
        "add_prefix_space": false,
        "trim_offsets": true,
        "use_regex": false
      }
    ]
  }
  ```

> I think I can fully automate this entire process and reduce the complexity. Not sure yet. Need to experiment.

Yes, this is definitely possible. A starting point would be to compare the `pre_tokenizer` field of all the `tokenizer.json` files fetched by `convert-hf-to-gguf-update.py`, then figure out which ones are the same, find a way to normalize the same-but-different ones (like `\r\n` vs `\\r\\n` in the regex).

The question probably is then: can pre-tokenizers entirely be identified by the `pre_tokenizer` field from `tokenizer.json`?

**Comment by aahouzi** [comment]
@compilade for StableLM3B, the picked hash is from olmo's pre-tokenizer

**Comment by teleprint-me** [comment]
> maybe this would be problematic with some models which use a custom tokenizer like in `_set_vocab_qwen` with `trust_remote_code=True`... In that case a pre-tokenizer could be hardcoded for these models, maybe.

@compilade Yeah, I tried this already, and it proved to be incredibly complicated. Many of us have already come to the conclusion that there is no reliable way to do this, so I'm thinking maybe we lean into that instead of veering away from it. A weakness can be utilized as a strength.

**Comment by compilade** [comment]
> @compilade for StableLM3B, the picked hash is from olmo's pre-tokenizer

@aahouzi Which seems appropriate, considering OLMo *also* uses GPT-2's regex for its pre-tokenizer:

From the `pre_tokenizer` field of OLMo in <https://huggingface.co/allenai/OLMo-7B-Instruct/raw/main/tokenizer.json>:

```json
"pre_tokenizer": {
  "type": "ByteLevel",
  "add_prefix_space": false,
  "trim_offsets": true,
  "use_regex": true
}
```

And OLMo uses GPT-2's regex in `llama.cpp`:

https://github.com/ggerganov/llama.cpp/blob/0fc1e820a9900a3dd08ddd3c6abe6604c53b689b/llama.cpp#L12351-L12356

**Comment by teleprint-me** [comment]
I think I figured out how to automate the tokenizer, model, checksum, and conversions all in one go. Will close this PR and open a new PR when I'm ready to post for huggingface related tasks.

**Comment by ggerganov** [comment]
> The question probably is then: can pre-tokenizers entirely be identified by the pre_tokenizer field from tokenizer.json?

There is also the `"normalizer"` section that I think plays some role in some tokenizers - seems to be mainly utilized for embeddings models.

**Comment by teleprint-me** [comment]
> There is also the "normalizer" section that I think plays some role in some tokenizers - seems to be mainly utilized for embeddings models.

The issue is determining what the `normalizer` is. Can we just assume it's NFD? It seems to have been working so far. Specify something else if it isn't?

The metadata for the `tokenizer.json` itself is inconsistent. It seems that the metadata in aggregate is more useful than it is individually, but even then, there are still missing pieces of information.

For example, the llama bpe normalizer is defined as `"normalizer": null,` and ends up not providing any useful information. The llama spm normalizer is not `null` and is defined as `"type": "Sequence"`.

Same for other types of related metadata such as added tokens, special tokens, model type, etc.

It seems that the `AutoTokenizer` will have most of the relevant information necessary already if it is available. The caveat is that this varies and is dependent upon a case-by-case basis.

**Comment by teleprint-me** [comment]
Hm.

```python
>>> tokenizer.backend_tokenizer.normalizer
>>> type(tokenizer.backend_tokenizer.normalizer)
<class 'NoneType'>
>>> from tokenizers import normalizers
>>> from tokenizers.normalizers import NFD, StripAccents
>>> normalizer = normalizers.Sequence([NFD(), StripAccents()])
>>> tokenizer.backend_tokenizer.normalizer = normalizer
>>> tokenizer.backend_tokenizer.normalizer
<tokenizers.normalizers.Sequence object at 0x76840738e1f0>
>>> tokenizer.backend_tokenizer.normalizer.normalize_str("Héllò hôw are ü?")
'Hello how are u?'
```

Not sure how reliable this would be? Plus, this is only really needed for the conversion? The vocab is already pre-existing, extracted, and then written to the model file. So, what's the plan here?

I guess it depends on what we're looking to do.

- Does the text need to be normalized, e.g. "cleaned".
- Does the text need to be pre-tokenized, e.g. "split upon boundries"
- Is the models integrity intact, e.g. "hashsum"
- Determine the models tokenizer type, e.g. "BPE"

These are just some off-the-cuff check boxes.

**Comment by teleprint-me** [comment]
Superseded by PR #7379

**Comment by flatsiedatsie** [comment]
Perhaps this should be implemented anyway, while the other project is still ongoing?

**Pull request closed without merging**
