### PR TITLE
Readme: add akx/ggify to tools

### PR DESCRIPTION
**Pull request by akx**
Figured I'd add a link to my tool. 

No worries if it's out of scope for the readme :)

### CODE REVIEW

**Comment by SlyEcho** [comment]
I was looking at how the files are stored on HF the other day. It's actually not infeasible to add support to convert.py to download the data on-the-fly using HTTP range requests, saving disk space. But it is also not trivial...

**Comment by alitariq4589** [comment]
Can one of the admins verify this patch?

**Comment by mofosyne** [comment]
Really appreciate your work in making it easier for people to port.

Just checking if this is still relevant now that people are moving to gguf

**Comment by akx** [comment]
@mofosyne It's still relevant. I just used (and updated) the tool for #7328 too...

**Review by mofosyne — APPROVED** [review]
Had a quick look at https://github.com/akx/ggify/blob/master/ggify.py for due diligence. Didn't check if it runs, but looks like it trying to do what it's trying to do at least. Approving and merging.

**Pull request merged**
