### PR TITLE
convert : refactor rope_freqs generation

### PR DESCRIPTION
**Pull request by compilade**
Follow-up from <https://github.com/ggerganov/llama.cpp/pull/9117#discussion_r1725292280>.

This isolates handling of generated tensors like `rope_freqs` for Llama3, Phi-3 and Exaone. This should also fix `--vocab-only` conversion for Phi-3-128k and Phi-3.5 (which previously generated invalid GGUF files because they included a non-zero tensor count while not including any tensor data).

Note that this will also be relevant for MiniCPM3 (#9322), which re-uses the misbehaving Phi-3 rope tensors insertion.

# TODO

- [x] Test Phi-3-mini-128k LoRA
  - Tested conversion and inference with <https://huggingface.co/UnderstandLing/Phi-3-mini-128k-instruct-nl> and noticed no problem
- [x] Test Phi-3-mini-128k vocab-only validity (with `llama-tokenize` too)
- [x] Test Phi-3-mini-128k conversion
- [x] Test MiniCPM3 conversion
- [x] Test MiniCPM3 vocab-only validity
- [ ] Test Llama-3.1 LoRA
- [x] Test Llama-3.1 conversion
  - includes `rope_freqs.weight`, and has the same checksum as a previous conversion I did a while ago with the same checkout of the upstream model
- [x] Test Llama-3.1 vocab-only (also with `llama-tokenize`) 
- [x] Run `tests/test-lora-conversion-inference.sh`
  - Doesn't really test `rope_freqs`, though.
- [x] Test Llama-3.2-1B-Instruct conversion
  - The resulting model file is exactly identical as when converting from `master`
  - The vocab-only file is also identical as what it was before

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low

### CODE REVIEW

**Review by ngxson — APPROVED** [review]
LGTM. Thanks for the implementation!

**Comment by ThiloteE** [comment]
Related to issue [Support for Phi-3 models #6849 ](https://github.com/ggerganov/llama.cpp/issues/6849)

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Should we merge this, or wait for the rest of the tests in OP to be confirmed?

**Comment by ngxson** [comment]
I ran the test locally and can confirm that it passes. Let's wait for final confirmation from @compilade to merge this.

**Comment by bioinformatist** [comment]
Hey bro, when I try to convert Minicpm3 to `.gguf` format, it says:

```
The repository for /models contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//models.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.
```

Will it be implemented by this PR? Thanks!

**Comment by compilade** [comment]
> @compilade Hey bro, when I try to convert Minicpm3 to `.gguf` format, it says:
> 
> ```
> The repository for /models contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//models.
> You can avoid this prompt in future by passing the argument `trust_remote_code=True`.
> ```
> 
> Will it be implemented by this PR? Thanks!

@bioinformatist 

Yes, actually, in <https://github.com/ggerganov/llama.cpp/commit/e83d2707d3edae76e2d00408b0e0cfa39468d509> I've changed how MiniCPM3's tokenizer is loaded to exactly avoid that custom code. It uses SentencePiece directly instead. I *think* it results in the same model files, but I didn't test that yet because I can't really run the custom tokenization code since it repends on `datamodel_code_generator` which is not in Nixpkgs.

That was a single line change in `set_vocab`.

**Comment by bioinformatist** [comment]
Got that, as we have been turning to NixOS (especially for production use) these days. Hope everything goes well! ❤️

**Pull request merged**
