### PR TITLE
Avoid using alloca

### PR DESCRIPTION
**Pull request by Rhialto**

### CODE REVIEW

**Comment by slaren** [comment]
MSVC doesn't seem to support VLA, at least it failed when I tried it in #820.

**Comment by Rhialto** [comment]
One thing with VLAs is that the length cannot be 0. That is annoying for the first case, but ok for the second, I guess.

But VLAs are weird in the C standard that they are only required in C99, and made optional in C11. So a compiler may rightfully not support them. I read that C23 requires support again...

**Comment by ggerganov** [comment]
Haven't looked in details what is the problem with `alloca` but adding this heap allocation is not desired. This has to be on the stack somehow

**Comment by Rhialto** [comment]
@ggerganov I described the problem with `alloca` in #881. In short: the Makefile claims strict standard compliance (`std=c11`) but using alloca conflicts with that. My proposal to change to `std=gnu11` was considered not good, so this is another way out.

**Pull request closed without merging**
